package com.kaymlyn.planeteater.simulation.celestial.planetconfig;

/**
 * Pre-configured patterns for creating realistic celestial bodies.
 *
 * Includes all planets in our solar system, major moons, and representative asteroids.
 * Layer radii are approximate and based on real astronomical data.
 *
 * Radius values are in meters (m).
 *
 * Generated by Claude (Sonnet 4.5)
 */
public enum PlanetPattern {

    // ==================== TERRESTRIAL PLANETS ====================

    MERCURY("IRON_NICKEL_CORE", 2.0e6,
            "MG_FE_SILICATE_MANTLE", 4.0e5,
            "ALUMINA_SILICA_CRUST", 3.9e4,
            "NONE", 0.0),

    VENUS("IRON_NICKEL_CORE", 3.0e6,
            "MG_FE_SILICATE_MANTLE", 2.84e6,
            "ALUMINA_SILICA_CRUST", 2.5e4,
            "GREENHOUSE_ATMOSPHERE", 2.50e5),

    EARTH("IRON_NICKEL_CORE", 3.476e6,
            "MG_FE_SILICATE_MANTLE", 2.885e6,
            "ALUMINA_SILICA_CRUST", 6.5e4,
            "NITROGEN_OXYGEN_ATMOSPHERE", 1.0e4),

    MARS("IRON_NICKEL_CORE", 1.7e6,
            "MG_FE_SILICATE_MANTLE", 1.69e6,
            "ALUMINA_SILICA_CRUST", 5.0e4,
            "LOW_CO2_ATMOSPHERE", 1.0e4),

    // ==================== GAS GIANTS ====================

    JUPITER("WET_SILICA_IRON", 7.0e7,           // Dense core
            "LIQUID_METALLIC_HYDROGEN", 1.5e7,   // Metallic hydrogen mantle
            "MOLECULAR_HYDROGEN", 1.5e6,         // Molecular hydrogen layer
            "HIGH_HYDROGEN_HELIUM", 1.0e6),      // Atmosphere

    SATURN("WET_SILICA_IRON", 5.8e7,
            "LIQUID_METALLIC_HYDROGEN", 8.0e6,
            "MOLECULAR_HYDROGEN", 1.0e6,
            "HIGH_HYDROGEN_HELIUM", 8.0e5),

    // ==================== ICE GIANTS ====================

    URANUS("DRY_SILICA_IRON", 2.53e7,
            "WET_AMMONIA_METHANE", 2.0e6,        // Ice mantle
            "MOLECULAR_HYDROGEN", 5.0e5,
            "LOW_HYDROGEN_HELIUM", 5.0e5),

    NEPTUNE("DRY_SILICA_IRON", 2.46e7,
            "WET_AMMONIA_METHANE", 1.8e6,
            "MOLECULAR_HYDROGEN", 5.0e5,
            "LOW_HYDROGEN_HELIUM", 5.0e5),

    // ==================== MAJOR MOONS - EARTH ====================

    LUNA("IRON_NICKEL_CORE", 3.5e5,             // Earth's Moon
            "MG_FE_SILICATE_MANTLE", 1.38e6,
            "ALUMINA_SILICA_CRUST", 5.0e4,
            "NONE", 0.0),

    // ==================== MAJOR MOONS - JUPITER ====================

    IO("IRON_NICKEL_CORE", 9.5e5,               // Volcanic moon
            "MG_FE_SILICATE_MANTLE", 9.0e5,
            "ALUMINA_SILICA_CRUST", 3.0e4,
            "SULFUR_ATMOSPHERE", 5.0e3),

    EUROPA("IRON_NICKEL_CORE", 6.0e5,           // Ice moon with subsurface ocean
            "MG_FE_SILICATE_MANTLE", 9.0e5,
            "OCEAN", 1.0e5,                      // Liquid water ocean
            "WATER_ICE_CRUST", 2.0e4),

    GANYMEDE("IRON_NICKEL_CORE", 7.0e5,         // Largest moon
            "MG_FE_SILICATE_MANTLE", 1.0e6,
            "OCEAN", 8.0e5,
            "WATER_ICE_CRUST", 1.5e5),

    CALLISTO("WET_SILICA_IRON", 6.0e5,          // Undifferentiated ice-rock mixture
            "WET_AMMONIA_METHANE", 1.2e6,
            "WATER_ICE_CRUST", 6.0e4,
            "NONE", 0.0),

    // ==================== MAJOR MOONS - SATURN ====================

    TITAN("WET_SILICA_IRON", 4.0e5,             // Only moon with thick atmosphere
            "WET_AMMONIA_METHANE", 1.8e6,
            "WATER_ICE_CRUST", 1.0e5,
            "NITROGEN_METHANE_ATMOSPHERE", 6.0e5),

    ENCELADUS("DRY_SILICA_IRON", 1.5e5,         // Active ice geysers
            "NONE", 0.0,
            "OCEAN", 5.0e4,
            "WATER_ICE_CRUST", 4.0e4),

    RHEA("DRY_SILICA_IRON", 1.0e5,
            "WATER_ICE_CRUST", 6.5e5,
            "NONE", 0.0,
            "NONE", 0.0),

    // ==================== ASTEROIDS - MAIN BELT ====================

    CERES("WET_SILICA_IRON", 2.2e5,             // Dwarf planet, largest asteroid
            "WET_AMMONIA_METHANE", 2.0e5,
            "WATER_ICE_CRUST", 4.0e4,
            "NONE", 0.0),

    VESTA("IRON_NICKEL_CORE", 1.1e5,            // Differentiated asteroid
            "MG_FE_SILICATE_MANTLE", 1.5e5,
            "ALUMINA_SILICA_CRUST", 8.0e3,
            "NONE", 0.0),

    PALLAS("WET_SILICA_IRON", 2.6e5,            // Undifferentiated
            "NONE", 0.0,
            "CARBONACEOUS_CRUST", 1.0e4,
            "NONE", 0.0),

    // ==================== ASTEROIDS - TYPES ====================

    C_TYPE_ASTEROID("CARBONACEOUS_CORE", 5.0e4, // Carbonaceous (most common)
            "NONE", 0.0,
            "CARBONACEOUS_CRUST", 2.0e4,
            "NONE", 0.0),

    S_TYPE_ASTEROID("WET_SILICA_IRON", 8.0e4,   // Silicaceous
            "NONE", 0.0,
            "ALUMINA_SILICA_CRUST", 1.5e4,
            "NONE", 0.0),

    M_TYPE_ASTEROID("IRON_NICKEL_CORE", 1.2e5,  // Metallic (iron-nickel)
            "NONE", 0.0,
            "NONE", 0.0,
            "NONE", 0.0),

    // ==================== COMETS ====================

    COMET("WET_SILICA_IRON", 2.0e3,             // Generic comet
            "NONE", 0.0,
            "WATER_ICE_CRUST", 3.0e3,
            "VOLATILE_COMA", 5.0e3),             // Active coma when near sun

    // ==================== KUIPER BELT OBJECTS ====================

    PLUTO("DRY_SILICA_IRON", 8.5e5,             // Dwarf planet
            "WATER_ICE_CRUST", 3.0e5,
            "NITROGEN_ICE_CRUST", 5.0e4,
            "NITROGEN_ATMOSPHERE", 1.5e5),

    ERIS("DRY_SILICA_IRON", 1.16e6,             // Most massive dwarf planet
            "WATER_ICE_CRUST", 2.0e5,
            "METHANE_ICE_CRUST", 1.0e4,
            "NONE", 0.0);

    final public String coreType;
    final public double coreRadius;
    final public String mantleType;
    final public double mantleRadius;
    final public String crustType;
    final public double crustRadius;
    final public String atmosphereType;
    final public double atmosphereRadius;

    /**
     * Create a planetary pattern with four layers.
     *
     * Radii are additive: each layer's radius adds to the previous layer.
     * - coreRadius: radius from center to edge of core
     * - mantleRadius: thickness of mantle layer (added to core)
     * - crustRadius: thickness of crust layer (added to mantle)
     * - atmosphereRadius: thickness of atmosphere (added to crust)
     *
     * Use "NONE" for missing layers (with radius 0.0).
     */
    PlanetPattern(String coreType, double coreRadius,
                  String mantleType, double mantleRadius,
                  String crustType, double crustRadius,
                  String atmosphereType, double atmosphereRadius) {
        this.coreType = coreType;
        this.coreRadius = coreRadius;
        this.mantleType = mantleType;
        this.mantleRadius = mantleRadius + this.coreRadius;
        this.crustType = crustType;
        this.crustRadius = crustRadius + this.mantleRadius;
        this.atmosphereType = atmosphereType;
        this.atmosphereRadius = atmosphereRadius + this.crustRadius;
    }
}