package com.kaymlyn.planeteater.celestial;

import com.kaymlyn.planeteater.resources.Composition;
import com.kaymlyn.planeteater.resources.Material;
import com.kaymlyn.planeteater.physics.PhysicsConstants;
import com.kaymlyn.planeteater.physics.Vector3D;

import lombok.Getter;

/**
 * Represents a star (central body in the system)
 * Can be mined using advanced stellar lifting technology
 * Uses mass-radius relationship for main sequence stars
 *
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Star extends CelestialBody {

    private Composition atmosphereComposition;  // Extractable materials from corona/photosphere
    private double surfaceTemperature;          // Kelvin
    private double massLossRate;                // Natural mass loss rate (kg/s)
    private double stellarRadius;               // Actual radius accounting for gravity/pressure (meters)

    /**
     * Create a star with default Sun-like properties
     */
    public static Star createSunLike(String id) {
        Composition comp = new Composition();
        // Stars are mostly hydrogen and helium
        comp.addMaterial(Material.HYDROGEN, PhysicsConstants.SOLAR_MASS * 0.73);
        comp.addMaterial(Material.HELIUM, PhysicsConstants.SOLAR_MASS * 0.25);
        comp.addMaterial(Material.OXYGEN_GAS, PhysicsConstants.SOLAR_MASS * 0.01);
        comp.addMaterial(Material.CARBON, PhysicsConstants.SOLAR_MASS * 0.003);
        comp.addMaterial(Material.IRON, PhysicsConstants.SOLAR_MASS * 0.001);

        Star star = new Star(id, Vector3D.ZERO, Vector3D.ZERO, comp);

        // Calculate actual stellar radius using mass-radius relationship
        star.stellarRadius = star.calculateMainSequenceRadius();

        // Set up extractable atmosphere (corona/photosphere)
        star.atmosphereComposition = new Composition();
        star.atmosphereComposition.addMaterial(Material.HYDROGEN, 1e20);  // 100 billion billion kg
        star.atmosphereComposition.addMaterial(Material.HELIUM, 3e19);
        star.atmosphereComposition.addMaterial(Material.OXYGEN_GAS, 1e18);

        star.surfaceTemperature = star.calculateMainSequenceTemperature();
        star.massLossRate = star.calculateMassLossRate();

        return star;
    }

    public Star(String id, Vector3D position, Vector3D velocity, Composition composition) {
        super(id, position, velocity, composition);
        this.atmosphereComposition = new Composition();
        this.stellarRadius = calculateMainSequenceRadius();
        this.surfaceTemperature = calculateMainSequenceTemperature();
        this.massLossRate = calculateMassLossRate();
    }

    /**
     * Calculate stellar radius using the main sequence mass-radius relationship
     * For main sequence stars:
     * - M < 1 M_sun: R scales as M^0.8
     * - M >= 1 M_sun: R scales as M^0.57
     *
     * This accounts for gravitational compression balanced by fusion pressure
     */
    private double calculateMainSequenceRadius() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8; // meters

        if (massRatio < 1.0) {
            // Low mass stars: stronger gravity compression relative to pressure
            return solarRadius * Math.pow(massRatio, 0.8);
        } else {
            // Higher mass stars: radiation pressure becomes more significant
            return solarRadius * Math.pow(massRatio, 0.57);
        }
    }

    /**
     * Calculate surface temperature using main sequence mass-luminosity-temperature relationship
     * L scales as M^3.5 for main sequence stars
     * L = 4πR²σT^4 (Stefan-Boltzmann)
     * Combining: T scales as (M^3.5 / R²)^0.25
     */
    private double calculateMainSequenceTemperature() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8;
        double solarTemp = 5778.0; // Kelvin

        // Luminosity scales as M^3.5
        double luminosityRatio = Math.pow(massRatio, 3.5);

        // Radius ratio
        double radiusRatio = stellarRadius / solarRadius;

        // Temperature from Stefan-Boltzmann: T^4 scales as L/R²
        double tempRatio = Math.pow(luminosityRatio / (radiusRatio * radiusRatio), 0.25);

        return solarTemp * tempRatio;
    }

    /**
     * Calculate mass loss rate (solar wind)
     * Scales roughly with luminosity and surface area
     * Higher mass stars lose mass faster
     */
    private double calculateMassLossRate() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarMassLoss = 2e9; // kg/s for Sun

        // Mass loss roughly scales with M^2 (combination of wind speed and density)
        return solarMassLoss * Math.pow(massRatio, 2.0);
    }

    /**
     * Calculate average density of the star
     * This accounts for compression - stars are much denser than their constituent materials
     */
    @Override
    public double getDensity() {
        double volume = (4.0 / 3.0) * Math.PI * Math.pow(stellarRadius, 3);
        return getMass() / volume;
    }

    /**
     * Override getRadius to return the calculated stellar radius
     * Not based on composition volume
     */
    @Override
    public double getRadius() {
        return stellarRadius;
    }

    /**
     * Extract material from the star's corona/photosphere
     * This represents stellar lifting or mass stream capture
     */
    public double extractStellarMaterial(Material material, double requestedMass,
                                         double extractionRate, double duration) {
        double maxByRate = extractionRate * duration;
        double toExtract = Math.min(requestedMass, maxByRate);

        double extracted = atmosphereComposition.removeMaterial(material, toExtract);
        replenishAtmosphere(duration);

        return extracted;
    }

    /**
     * Replenish the extractable atmosphere based on natural mass loss
     */
    private void replenishAtmosphere(double duration) {
        double massAdded = massLossRate * duration;

        atmosphereComposition.addMaterial(Material.HYDROGEN, massAdded * 0.73);
        atmosphereComposition.addMaterial(Material.HELIUM, massAdded * 0.25);
        atmosphereComposition.addMaterial(Material.OXYGEN_GAS, massAdded * 0.01);
    }

    /**
     * Check if star has a specific material available for extraction
     */
    public boolean hasExtractableMaterial(Material material) {
        return atmosphereComposition.contains(material);
    }

    /**
     * Get amount of extractable material
     */
    public double getExtractableAmount(Material material) {
        return atmosphereComposition.getMass(material);
    }

    /**
     * Calculate the minimum safe distance for mining operations
     * Corona extends to about 2-3 stellar radii
     */
    public double getMinimumMiningDistance() {
        return 3.0 * stellarRadius;
    }

    /**
     * Get the spectral class based on temperature
     * O > 30000K, B 10000-30000K, A 7500-10000K, F 6000-7500K,
     * G 5200-6000K, K 3700-5200K, M < 3700K
     */
    public String getSpectralClass() {
        if (surfaceTemperature > 30000) return "O";
        if (surfaceTemperature > 10000) return "B";
        if (surfaceTemperature > 7500) return "A";
        if (surfaceTemperature > 6000) return "F";
        if (surfaceTemperature > 5200) return "G";
        if (surfaceTemperature > 3700) return "K";
        return "M";
    }

    /**
     * Calculate luminosity relative to Sun
     * L scales as M^3.5 for main sequence stars
     */
    public double getLuminosity() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        return Math.pow(massRatio, 3.5);
    }

    /**
     * Stars are stationary at the center of the system
     */
    @Override
    public void update(Vector3D acceleration, double dt) {
        replenishAtmosphere(dt);
    }

    @Override
    public String toString() {
        return String.format("Star[id=%s, mass=%.3e kg (%.2f M☉), radius=%.3e m (%.2f R☉), " +
                        "temp=%.0f K, class=%s, density=%.1f kg/m³]",
                id, getMass(), getMass() / PhysicsConstants.SOLAR_MASS,
                stellarRadius, stellarRadius / 6.96e8,
                surfaceTemperature, getSpectralClass(), getDensity());
    }

    /**
     * Create a star with specific mass (in solar masses)
     */
    public static Star createMainSequenceStar(String id, double solarMasses) {
        Composition comp = new Composition();
        double totalMass = solarMasses * PhysicsConstants.SOLAR_MASS;

        comp.addMaterial(Material.HYDROGEN, totalMass * 0.73);
        comp.addMaterial(Material.HELIUM, totalMass * 0.25);
        comp.addMaterial(Material.OXYGEN_GAS, totalMass * 0.01);
        comp.addMaterial(Material.CARBON, totalMass * 0.003);
        comp.addMaterial(Material.IRON, totalMass * 0.001);

        Star star = new Star(id, Vector3D.ZERO, Vector3D.ZERO, comp);

        // Set up extractable atmosphere proportional to mass loss rate
        star.atmosphereComposition = new Composition();
        double atmosphereMass = star.massLossRate * 1e10; // ~100,000 seconds worth
        star.atmosphereComposition.addMaterial(Material.HYDROGEN, atmosphereMass * 0.73);
        star.atmosphereComposition.addMaterial(Material.HELIUM, atmosphereMass * 0.25);
        star.atmosphereComposition.addMaterial(Material.OXYGEN_GAS, atmosphereMass * 0.01);

        return star;
    }
}