package com.kaymlyn.planeteater.entities.artifice.actors;

import com.kaymlyn.planeteater.entities.artifice.OrbitalPlatform;
import com.kaymlyn.planeteater.entities.primordials.Asteroid;
import com.kaymlyn.planeteater.entities.primordials.OrbitalSystem;
import com.kaymlyn.planeteater.universals.Material;
import com.kaymlyn.planeteater.universals.TravelCalculator;
import com.kaymlyn.planeteater.universals.TravelCalculator.Trajectory;
import lombok.Getter;
import java.util.ArrayList;
import java.util.List;

/**
 * Manages a mining operation at an asteroid
 * Coordinates spacecraft, crew, and resource extraction
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class MiningOperation {
    
    public enum OperationStatus {
        PLANNING,       // Operation being set up
        TRAVELING,      // En route to asteroid
        ACTIVE,         // Currently mining
        RETURNING,      // Returning to platform
        COMPLETED       // Operation finished
    }
    
    private String id;
    private Spacecraft spacecraft;
    private Asteroid target;
    private List<MiningEntity> miners;
    private Material targetMaterial;
    private double targetAmount;        // Amount to mine (kg)
    private double minedAmount;         // Amount mined so far (kg)
    private OperationStatus status;
    
    private double startTime;           // When mining started (simulation time)
    private double elapsedMiningTime;   // Actual mining time (seconds)
    private Trajectory outboundTrajectory;
    private Trajectory returnTrajectory;
    
    public MiningOperation(String id, Spacecraft spacecraft, Asteroid target, 
                          Material targetMaterial, double targetAmount) {
        this.id = id;
        this.spacecraft = spacecraft;
        this.target = target;
        this.targetMaterial = targetMaterial;
        this.targetAmount = targetAmount;
        this.minedAmount = 0.0;
        this.miners = new ArrayList<>();
        this.status = OperationStatus.PLANNING;
        this.elapsedMiningTime = 0.0;
    }
    
    /**
     * Add a miner to the operation
     */
    public boolean addMiner(MiningEntity miner) {
        if (!spacecraft.boardEntity(miner)) {
            return false;
        }
        miners.add(miner);
        return true;
    }
    
    /**
     * Calculate total mining rate of all assigned miners
     */
    public double getTotalMiningRate() {
        return miners.stream()
            .mapToDouble(MiningEntity::getMiningRate)
            .sum();
    }
    
    /**
     * Calculate estimated time to complete mining
     */
    public double estimateMiningTime() {
        double rate = getTotalMiningRate();
        if (rate <= 0) return Double.POSITIVE_INFINITY;
        return (targetAmount - minedAmount) / rate;
    }
    
    /**
     * Plan the operation - calculate trajectories and check feasibility
     */
    public boolean planOperation(OrbitalPlatform platform, OrbitalSystem system) {
        if (status != OperationStatus.PLANNING) {
            return false;
        }
        
        // Check if asteroid has the target material
        if (!target.hasMaterial(targetMaterial)) {
            return false;
        }
        
        // Check if there's enough material
        if (target.getAvailableMaterial(targetMaterial) < targetAmount) {
            return false;
        }
        
        // Calculate outbound trajectory
        outboundTrajectory = TravelCalculator.calculateRendezvous(
            platform.getPosition(),
            platform.getVelocity(),
            target,
            system.getCurrentTime(),
            spacecraft,
            system
        );
        
        // Calculate return trajectory (will be from asteroid to platform)
        returnTrajectory = TravelCalculator.calculateDirectTransfer(
            target.getPosition(),
            platform.getPosition(),
            spacecraft
        );
        
        // Check if spacecraft has enough fuel for round trip
        double totalFuelNeeded = outboundTrajectory.fuelRequired + returnTrajectory.fuelRequired;
        if (spacecraft.getFuelMass() < totalFuelNeeded) {
            return false;
        }
        
        // Check if cargo space is sufficient
        if (spacecraft.getCargoCapacity() < targetAmount) {
            return false;
        }
        
        // Check crew capacity
        if (miners.size() > spacecraft.getMaxCrewCapacity()) {
            return false;
        }
        
        return true;
    }
    
    /**
     * Start the operation (launch from platform)
     */
    public boolean launch(double currentTime) {
        if (status != OperationStatus.PLANNING) {
            return false;
        }
        
        // Consume fuel for outbound journey
        spacecraft.consumeFuel(outboundTrajectory.fuelRequired);
        spacecraft.setState(Spacecraft.SpacecraftState.TRAVELING);
        status = OperationStatus.TRAVELING;
        startTime = currentTime;
        
        return true;
    }
    
    /**
     * Update the operation - progress mining, handle travel, etc.
     */
    public void update(double currentTime, double dt) {
        switch (status) {
            case TRAVELING:
                // Check if arrived at asteroid
                double travelElapsed = currentTime - startTime;
                if (travelElapsed >= outboundTrajectory.travelTime) {
                    arriveAtAsteroid(currentTime);
                }
                break;
                
            case ACTIVE:
                // Mine resources
                performMining(dt);
                break;
                
            case RETURNING:
                // Check if returned to platform
                double returnElapsed = currentTime - startTime;
                if (returnElapsed >= returnTrajectory.travelTime) {
                    completeOperation();
                }
                break;
        }
    }
    
    /**
     * Arrive at the asteroid and begin mining
     */
    private void arriveAtAsteroid(double currentTime) {
        spacecraft.setState(Spacecraft.SpacecraftState.AT_ASTEROID);
        status = OperationStatus.ACTIVE;
        startTime = currentTime;
        
        // Disembark miners
        for (MiningEntity miner : miners) {
            spacecraft.disembarkEntity(miner);
            miner.setState(MiningEntity.EntityState.MINING);
            miner.setCurrentLocation(target.getId());
        }
    }
    
    /**
     * Perform mining for a time step
     */
    private void performMining(double dt) {
        double rate = getTotalMiningRate();
        double toMine = Math.min(rate * dt, targetAmount - minedAmount);
        
        // Extract from asteroid
        double actualMined = target.mineMaterial(targetMaterial, toMine);
        
        // Load into spacecraft
        double loaded = spacecraft.loadCargo(targetMaterial, actualMined);
        minedAmount += loaded;
        elapsedMiningTime += dt;
        
        // Check if target reached
        if (minedAmount >= targetAmount || !target.hasMaterial(targetMaterial)) {
            beginReturn();
        }
    }
    
    /**
     * Begin return journey to platform
     */
    private void beginReturn() {
        // Re-board miners
        for (MiningEntity miner : miners) {
            spacecraft.boardEntity(miner);
            miner.setCurrentLocation(null);
        }
        
        // Consume fuel for return
        spacecraft.consumeFuel(returnTrajectory.fuelRequired);
        spacecraft.setState(Spacecraft.SpacecraftState.RETURNING);
        status = OperationStatus.RETURNING;
        startTime = System.currentTimeMillis() / 1000.0; // Use real time for simplicity
    }
    
    /**
     * Complete the operation
     */
    private void completeOperation() {
        spacecraft.setState(Spacecraft.SpacecraftState.DOCKED);
        status = OperationStatus.COMPLETED;
        
        // Disembark all crew
        for (MiningEntity miner : miners) {
            spacecraft.disembarkEntity(miner);
        }
    }
    
    /**
     * Calculate total operation time (travel + mining + return)
     */
    public double getTotalOperationTime() {
        if (outboundTrajectory == null || returnTrajectory == null) {
            return 0.0;
        }
        return outboundTrajectory.travelTime + estimateMiningTime() + returnTrajectory.travelTime;
    }
    
    /**
     * Calculate total fuel cost
     */
    public double getTotalFuelCost() {
        if (outboundTrajectory == null || returnTrajectory == null) {
            return 0.0;
        }
        return outboundTrajectory.fuelRequired + returnTrajectory.fuelRequired;
    }
    
    /**
     * Get operation efficiency (mined mass per fuel mass)
     */
    public double getEfficiency() {
        double fuelCost = getTotalFuelCost();
        if (fuelCost <= 0) return 0.0;
        return targetAmount / fuelCost;
    }
    
    @Override
    public String toString() {
        return String.format("com.kaymlyn.planeteater.entites.artifice.actors.MiningOperation[id=%s, target=%s, material=%s, " +
            "progress=%.1f/%.1f kg, status=%s, miners=%d]",
            id, target.getId(), targetMaterial.getSymbol(),
            minedAmount, targetAmount, status, miners.size());
    }
}