package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

/**
 * Flight plan storing maneuver chain.
 * Telemetry generated by sampling state predictions (no orbit storage).
 *
 * Generated by Claude (Sonnet 4.5) - Architecture Refactor
 */
@ToString
public class Itinerary {
    private final List<PiecewiseState> telemetry;

    @Getter
    private final double startTime;

    @Getter
    private ManeuverDetails initialManeuver;

    @Setter
    @Getter
    private Orbiter finalDestination;

    @Setter
    @Getter
    private Spacecraft.SpacecraftState finalSpacecraftState;

    @Getter
    private boolean feasible;

    @Getter
    private String infeasibilityReason;

    @Setter
    @Getter
    private double launchDeltaV;

    @Setter
    @Getter
    private double landingDeltaV;

    @Getter
    private double travelDeltaV;

    @Getter
    private double totalWaitTime;

    public Itinerary(double startTime) {
        this.startTime = startTime;
        this.telemetry = new ArrayList<>();
        this.feasible = true;
        this.infeasibilityReason = null;
        this.launchDeltaV = 0.0;
        this.landingDeltaV = 0.0;
        this.travelDeltaV = 0.0;
        this.totalWaitTime = 0.0;
    }

    public void setInitialManeuver(ManeuverDetails initialManeuver) {
        this.initialManeuver = initialManeuver;
        launchDeltaV = initialManeuver.getDeltaV();

        // Calculate total travel delta-V
        ManeuverDetails current = initialManeuver.getNext();
        travelDeltaV = 0.0;

        while (current != null && !current.isTerminus()) {
            travelDeltaV += current.getDeltaV();
            current = current.getNext();
        }

        if (current != null) {
            landingDeltaV = current.getDeltaV();
        }
    }

    public void setInfeasible(String reason) {
        this.feasible = false;
        this.infeasibilityReason = reason;
    }

    /**
     * Generate telemetry by sampling state predictions.
     * No orbit storage - uses ManeuverDetails.predictPositionAt().
     */
    public List<PiecewiseState> generateTelemetry(OrbitalSystem system) {
        if (!telemetry.isEmpty() || !feasible) {
            return telemetry;
        }

        ManeuverDetails current = initialManeuver;

        while (current != null) {
            String id = current.getId();

            // Determine maneuver type
            boolean isBurn = id.contains("Burn") ||
                    id.contains("Launch") ||
                    id.contains("Detach") ||
                    id.contains("Landing");

            if (isBurn) {
                // Burns: Single state at completion
                telemetry.add(new PiecewiseState(
                        current.getId(),
                        current.getEndingPosition(),
                        current.getEndingVelocity(),
                        current.getTimeToExecute(),
                        1.0
                ));
            } else {
                // Coast: Sample predicted trajectory
                int steps = (int) (current.getTimeToExecute() / system.getTimeStep());
                if (steps == 0) {
                    steps = 1;
                }

                for (int step = 0; step < steps; step++) {
                    double t = step * system.getTimeStep();
                    double time = current.getStartTime() + t;

                    // Use ManeuverDetails state prediction
                    Vector3D position = current.predictPositionAt(time);
                    Vector3D velocity = current.predictVelocityAt(time);

                    telemetry.add(new PiecewiseState(
                            current.getId() + " @t+" + t,
                            position,
                            velocity,
                            t,
                            t / current.getTimeToExecute()
                    ));
                }
            }

            current = current.getNext();
        }

        return telemetry;
    }

    public double getTotalFlightTime() {
        ManeuverDetails details = initialManeuver;
        double counter = 0.0;
        while (details != null) {
            counter += details.getTimeToExecute();
            details = details.getNext();
        }
        return counter;
    }

    public boolean validateAgainstSpacecraft(Spacecraft spacecraft) {
        if (!feasible) {
            return false;
        }

        double requiredDeltaV = travelDeltaV + launchDeltaV + landingDeltaV;
        double availableDeltaV = spacecraft.getAvailableDeltaV();

        if (availableDeltaV < requiredDeltaV) {
            setInfeasible(String.format(
                    "Insufficient delta-V: required %.1f m/s, available %.1f m/s",
                    requiredDeltaV, availableDeltaV
            ));
            return false;
        }

        double requiredFuel = spacecraft.fuelRequired(requiredDeltaV);
        if (requiredFuel > spacecraft.getFuelMass()) {
            setInfeasible(String.format(
                    "Insufficient fuel: required %.1f kg, available %.1f kg",
                    requiredFuel, spacecraft.getFuelMass()
            ));
            return false;
        }

        return true;
    }

    public String getSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== ITINERARY ===\n");
        sb.append(String.format("Start Time: %.2f days\n", startTime / PhysicsConstants.SECONDS_PER_DAY));
        sb.append(String.format("Feasible: %s\n", feasible ? "YES" : "NO - " + infeasibilityReason));

        if (feasible) {
            sb.append(String.format("Total Δv: %.1f m/s\n", travelDeltaV));
            sb.append(String.format("  Launch: %.1f m/s\n", launchDeltaV));
            sb.append(String.format("  Landing: %.1f m/s\n", landingDeltaV));
            sb.append(String.format("Total Time: %.2f days\n",
                    getTotalFlightTime() / PhysicsConstants.SECONDS_PER_DAY));

            if (totalWaitTime > 0) {
                sb.append(String.format("Wait Time: %.2f days\n",
                        totalWaitTime / PhysicsConstants.SECONDS_PER_DAY));
            }

            sb.append(String.format("Destination: %s (%s)\n",
                    finalDestination != null ? finalDestination.getId() : "None",
                    finalSpacecraftState != null ? finalSpacecraftState : "Unknown"));
        }

        return sb.toString();
    }
}