package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

/**
 * Enhanced flight plan for spacecraft orbital transfers
 *
 * Represents a complete sequence of maneuvers from origin to destination.
 * Tracks feasibility, delta-V requirements, and generates telemetry for rendering.
 *
 * Note: This class handles delta-V calculations only. Fuel requirements are
 * calculated by the Vehicle based on its specific characteristics (exhaust velocity, mass).
 *
 * Generated by Claude (Sonnet 4.5)
 */
@ToString
public class Itinerary {
    private final List<ManeuverDetails> maneuvers;
    private final List<PiecewiseState> telemetry;

    @Getter
    private final double startTime;

    @Setter
    @Getter
    private Orbiter finalDestination;

    @Setter
    @Getter
    private Spacecraft.SpacecraftState finalSpacecraftState;

    // Feasibility tracking
    @Getter
    private boolean feasible;

    @Getter
    private String infeasibilityReason;

    // Delta-V breakdown (not fuel - that's vehicle-specific)
    @Getter
    private double launchDeltaV;

    @Getter
    private double landingDeltaV;

    @Getter
    private double totalDeltaV;

    @Getter
    private double totalWaitTime;

    public Itinerary(double startTime) {
        this.startTime = startTime;
        this.telemetry = new ArrayList<>();
        this.maneuvers = new ArrayList<>();
        this.feasible = true;
        this.infeasibilityReason = null;
        this.launchDeltaV = 0.0;
        this.landingDeltaV = 0.0;
        this.totalDeltaV = 0.0;
        this.totalWaitTime = 0.0;
    }

    /**
     * Add a maneuver to the flight plan
     * Automatically updates total delta-V and wait time
     */
    public void addFlightPlan(ManeuverDetails maneuver) {
        maneuvers.add(maneuver);
        totalDeltaV += maneuver.getDeltaV();

        // Track wait time (coast phases with zero delta-V)
        if (maneuver.getDeltaV() < 1e-6) {
            totalWaitTime += maneuver.getTimeToExecute();
        }
    }

    /**
     * Set the launch delta-V requirement
     * This is the delta-V needed to escape the departure body's gravity well
     */
    public void setLaunchDeltaV(double deltaV) {
        this.launchDeltaV = deltaV;
    }

    /**
     * Set the landing delta-V requirement
     * This is the delta-V needed to land on the destination body
     */
    public void setLandingDeltaV(double deltaV) {
        this.landingDeltaV = deltaV;
    }

    /**
     * Mark this itinerary as infeasible
     */
    public void setInfeasible(String reason) {
        this.feasible = false;
        this.infeasibilityReason = reason;
    }

    /**
     * Generate telemetry for rendering
     * Creates position/velocity states for each timestep in the system
     *
     * Telemetry is cached - subsequent calls return the same list
     */
    public List<PiecewiseState> generateTelemetry(OrbitalSystem system) {
        if (telemetry.isEmpty() && feasible) {
            int totalSteps = 0;

            for (ManeuverDetails maneuver : maneuvers) {
                int stepsInManeuver = (int) (maneuver.getTimeToExecute() / system.getTimeStep());

                for (int step = 0; step < stepsInManeuver; step++) {
                    double elapsedTime = totalSteps * system.getTimeStep();
                    telemetry.add(RocketryCalculator.calculateTrajectoryState(
                            maneuver,
                            system.getCurrentTime() + startTime + elapsedTime
                    ));
                    totalSteps++;
                }
            }
        }
        return telemetry;
    }

    /**
     * Get total flight time (sum of all maneuver durations)
     */
    public double getTotalFlightTime() {
        return maneuvers.stream()
                .mapToDouble(ManeuverDetails::getTimeToExecute)
                .sum();
    }

    /**
     * Get the final maneuver in the sequence
     */
    public ManeuverDetails getFinalManeuver() {
        return maneuvers.isEmpty() ? null : maneuvers.get(maneuvers.size() - 1);
    }

    /**
     * Get number of maneuvers in this itinerary
     */
    public int getNumberOfManeuvers() {
        return maneuvers.size();
    }

    /**
     * Get read-only view of all maneuvers
     */
    public List<ManeuverDetails> getManeuvers() {
        return List.copyOf(maneuvers);
    }

    /**
     * Validate this itinerary against spacecraft capabilities
     *
     * @param spacecraft The spacecraft that will execute this itinerary
     * @return true if spacecraft can execute this plan, false otherwise
     */
    public boolean validateAgainstSpacecraft(Spacecraft spacecraft) {
        if (!feasible) {
            return false;
        }

        // Check if spacecraft has enough delta-V capability
        double requiredDeltaV = totalDeltaV + launchDeltaV + landingDeltaV;
        double availableDeltaV = spacecraft.getAvailableDeltaV();

        if (availableDeltaV < requiredDeltaV) {
            setInfeasible(String.format(
                "Insufficient delta-V: required %.1f m/s, available %.1f m/s",
                requiredDeltaV, availableDeltaV
            ));
            return false;
        }

        // Check fuel requirements
        double requiredFuel = spacecraft.fuelRequired(requiredDeltaV);
        if (requiredFuel > spacecraft.getFuelMass()) {
            setInfeasible(String.format(
                "Insufficient fuel: required %.1f kg, available %.1f kg",
                requiredFuel, spacecraft.getFuelMass()
            ));
            return false;
        }

        return true;
    }

    /**
     * Create a summary string of this itinerary
     */
    public String getSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== ITINERARY ===\n");
        sb.append(String.format("Start Time: %.2f days\n", startTime / PhysicsConstants.SECONDS_PER_DAY));
        sb.append(String.format("Feasible: %s\n", feasible ? "YES" : "NO - " + infeasibilityReason));

        if (feasible) {
            sb.append(String.format("Maneuvers: %d\n", maneuvers.size()));
            sb.append(String.format("Total Δv: %.1f m/s\n", totalDeltaV));
            sb.append(String.format("  Launch: %.1f m/s\n", launchDeltaV));
            sb.append(String.format("  Landing: %.1f m/s\n", landingDeltaV));
            sb.append(String.format("Total Time: %.2f days\n",
                getTotalFlightTime() / PhysicsConstants.SECONDS_PER_DAY));

            if (totalWaitTime > 0) {
                sb.append(String.format("Wait Time: %.2f days\n",
                    totalWaitTime / PhysicsConstants.SECONDS_PER_DAY));
            }

            sb.append(String.format("Destination: %s (%s)\n",
                finalDestination != null ? finalDestination.getId() : "None",
                finalSpacecraftState != null ? finalSpacecraftState : "Unknown"));
        }

        return sb.toString();
    }
}
