package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Simplified flight plan as a sequence of scheduled velocity changes.
 *
 * This replaces the complex ManeuverDetails chain with a simple list
 * of burns. Position tracking is handled by the n-body simulation,
 * not pre-calculated trajectories.
 *
 * Benefits:
 * - No reference frame complexity (all burns in global frame)
 * - No trajectory prediction (simulation handles position)
 * - No NaN bugs from coordinate conversions
 * - Simpler and more maintainable
 * - More accurate (includes n-body perturbations)
 *
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Itinerary {
    private final List<ScheduledBurn> burns;
    private final double startTime;

    @Setter
    private Orbiter destination;

    @Setter
    private Spacecraft.SpacecraftState finalState;

    private boolean feasible;
    private String infeasibilityReason;

    public Itinerary(double startTime) {
        this.burns = new ArrayList<>();
        this.startTime = startTime;
        this.feasible = true;
    }

    /**
     * Add a burn to the schedule.
     * Burns are automatically sorted by execution time.
     */
    public void addBurn(ScheduledBurn burn) {
        burns.add(burn);
        Collections.sort(burns);
    }

    /**
     * Get all burns in chronological order.
     */
    public List<ScheduledBurn> getBurns() {
        return Collections.unmodifiableList(burns);
    }

    /**
     * Get the next burn that should execute.
     *
     * @param currentTime Current simulation time
     * @return Next burn, or null if all burns completed
     */
    public ScheduledBurn getNextBurn(double currentTime) {
        for (ScheduledBurn burn : burns) {
            if (burn.executionTime() >= currentTime) {
                return burn;
            }
        }
        return null;
    }

    /**
     * Remove a burn from the schedule (after execution).
     */
    public void removeBurn(ScheduledBurn burn) {
        burns.remove(burn);
    }

    /**
     * Check if all burns have been executed.
     */
    public boolean isComplete(double currentTime) {
        return burns.isEmpty() ||
                burns.getLast().executionTime() < currentTime;
    }

    /**
     * Calculate total delta-V budget required.
     */
    public double getTotalDeltaV() {
        return burns.stream()
                .mapToDouble(ScheduledBurn::deltaVMagnitude)
                .sum();
    }

    /**
     * Get estimated completion time (time of last burn).
     */
    public double getEstimatedCompletionTime() {
        if (burns.isEmpty()) {
            return startTime;
        }
        return burns.get(burns.size() - 1).executionTime();
    }

    /**
     * Get estimated total mission duration.
     */
    public double getEstimatedDuration() {
        return getEstimatedCompletionTime() - startTime;
    }

    /**
     * Mark this itinerary as infeasible with a reason.
     */
    public void setInfeasible(String reason) {
        this.feasible = false;
        this.infeasibilityReason = reason;
    }

    /**
     * Validate that spacecraft has sufficient resources.
     *
     * @param spacecraft The spacecraft to validate
     * @return true if spacecraft can execute this itinerary
     */
    public boolean validateAgainstSpacecraft(Spacecraft spacecraft) {
        if (!feasible) {
            return false;
        }

        double requiredDeltaV = getTotalDeltaV();
        double availableDeltaV = spacecraft.getAvailableDeltaV();

        if (availableDeltaV < requiredDeltaV) {
            setInfeasible(String.format(
                    "Insufficient delta-V: required %.1f m/s, available %.1f m/s",
                    requiredDeltaV, availableDeltaV));
            return false;
        }

        // Calculate total fuel required
        double currentMass = spacecraft.getTotalMass();
        double totalFuel = 0.0;

        for (ScheduledBurn burn : burns) {
            double fuelNeeded = burn.fuelRequired(currentMass, spacecraft.getExhaustVelocity());
            totalFuel += fuelNeeded;
            currentMass -= fuelNeeded;
        }

        if (totalFuel > spacecraft.getFuelMass()) {
            setInfeasible(String.format(
                    "Insufficient fuel: required %.1f kg, available %.1f kg",
                    totalFuel, spacecraft.getFuelMass()));
            return false;
        }

        return true;
    }

    /**
     * Merge burns that fall within the given time resolution of each other.
     *
     * Two burns scheduled within timeResolution seconds of each other are treated
     * as coincident: their delta-V vectors are summed and a single combined burn
     * replaces them, scheduled at the earlier of the two times.
     *
     * This reduces fuel consumption because one burn of magnitude |dv1 + dv2|
     * costs less than two sequential burns via Tsiolkovsky: the spacecraft carries
     * less mass after the first burn, making the second slightly more expensive.
     *
     * Safety constraint: only call this on burns that are genuinely coincident
     * due to planning precision. Burns intentionally spaced at different orbital
     * positions (bi-elliptic apoapsis burns, plane changes) must not be merged.
     *
     * @param timeResolution Maximum gap in seconds between burns to consider coincident
     * @return Number of burns removed by consolidation
     */
    public int consolidate(double timeResolution) {
        if (burns.size() < 2) {
            return 0;
        }

        int removedCount = 0;
        int index = 0;

        while (index < burns.size() - 1) {
            ScheduledBurn current = burns.get(index);
            ScheduledBurn next = burns.get(index + 1);

            double timeDelta = next.executionTime() - current.executionTime();

            if (timeDelta <= timeResolution) {
                // Combine: sum delta-V vectors, use earlier execution time
                Vector3D combinedDeltaV = current.deltaVelocity().add(next.deltaVelocity());
                String combinedDescription = current.description() + " + " + next.description();

                ScheduledBurn merged = new ScheduledBurn(
                        current.id() + "_merged",
                        current.executionTime(),
                        combinedDeltaV,
                        combinedDescription
                );

                burns.remove(index + 1);
                burns.remove(index);
                burns.add(index, merged);
                removedCount++;
                // Do not advance index - check if merged burn is also close to the next one
            } else {
                index++;
            }
        }

        return removedCount;
    }

    /**
     * Get human-readable summary of this itinerary.
     */
    public String getSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== ITINERARY ===\n");
        sb.append(String.format("Start Time: %.2f days (T=%.1f s)\n",
                startTime / PhysicsConstants.SECONDS_PER_DAY, startTime));
        sb.append(String.format("Estimated Completion: %.2f days (T=%.1f s)\n",
                getEstimatedCompletionTime() / PhysicsConstants.SECONDS_PER_DAY,
                getEstimatedCompletionTime()));
        sb.append(String.format("Feasible: %s\n",
                feasible ? "YES" : "NO - " + infeasibilityReason));

        if (feasible) {
            sb.append(String.format("Total Δv: %.1f m/s\n", getTotalDeltaV()));
            sb.append(String.format("Number of Burns: %d\n", burns.size()));

            if (destination != null) {
                sb.append(String.format("Destination: %s (%s)\n",
                        destination.getId(),
                        finalState != null ? finalState : "Unknown"));
            }

            sb.append("\nBurn Schedule:\n");
            for (int i = 0; i < burns.size(); i++) {
                ScheduledBurn burn = burns.get(i);
                sb.append(String.format("  %d. T+%.1f s: %s (Δv=%.1f m/s)\n",
                        i + 1,
                        burn.executionTime() - startTime,
                        burn.description(),
                        burn.deltaVMagnitude()));
            }
        }

        return sb.toString();
    }

    @Override
    public String toString() {
        return String.format("Itinerary[burns=%d, Δv=%.1f m/s, feasible=%s]",
                burns.size(), getTotalDeltaV(), feasible);
    }
}