package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.vehicles.Satellite;
import lombok.Getter;
import lombok.ToString;

import java.util.UUID;

/**
 * A class representing Spaceship behaviors. Spaceships can do one of two things in flight: burn and coast.
 * New maneuvers are created FROM existing maneuvers using builder methods,
 * which automatically use the ending state of the previous maneuver as the
 * starting state of the new maneuver.
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
@ToString(exclude = {"previous", "next"})  // Avoid circular reference in toString
public class ManeuverDetails {
    private final String id;
    private final Vector3D startingPosition;
    private final Vector3D startingVelocity;
    private final Vector3D endingPosition;
    private final Vector3D endingVelocity;
    private final double deltaV;
    private final Orbit orbit;
    private final double timeToExecute;
    private final double startTime;

    // Chain references
    private final ManeuverDetails previous;
    private ManeuverDetails next;

    private boolean terminus;

    /**
     * Private constructor - use static factory or builder methods instead
     */
    private ManeuverDetails(
            String id,
            Vector3D startingPosition,
            Vector3D startingVelocity,
            Vector3D endingPosition,
            Vector3D endingVelocity,
            double deltaV,
            Orbit orbitState,
            double timeToExecute,
            double startTime,
            ManeuverDetails previous) {

        this(
                id,
                startingPosition,
                startingVelocity,
                endingPosition,
                endingVelocity,
                deltaV,
                orbitState,
                timeToExecute,
                startTime,
                previous,
                false);

    }
    private ManeuverDetails(
            String id,
            Vector3D startingPosition,
            Vector3D startingVelocity,
            Vector3D endingPosition,
            Vector3D endingVelocity,
            double deltaV,
            Orbit orbitState,
            double timeToExecute,
            double startTime,
            ManeuverDetails previous,
            boolean terminus) {

        this.id = id;
        this.startingPosition = startingPosition;
        this.startingVelocity = startingVelocity;
        this.endingPosition = endingPosition;
        this.endingVelocity = endingVelocity;
        this.deltaV = deltaV;
        this.orbit = orbitState;
        this.timeToExecute = timeToExecute;
        this.startTime = startTime;
        this.previous = previous;
        this.next = null;
        this.terminus = terminus;

        // Link back from previous
        if (previous != null) {
            previous.next = this;
        }
    }

    /**
     * Get the time when this maneuver ends
     */
    public double getEndTime() {
        return startTime + timeToExecute;
    }

    /**
     * STATIC FACTORY: Create the first maneuver in a chain from an initial state
     * This is the ONLY way to start a maneuver chain.
     *
     * @param initialPosition Starting position
     * @param initialVelocity Starting velocity
     * @param startTime Time when this maneuver begins
     * @return First maneuver in the chain
     */
    public static ManeuverDetails createInitial(
            String id,
            Vector3D initialPosition,
            Vector3D initialVelocity,
            Gravitational centerBody,
            double startTime) {

        Orbit orbit = Orbit.calculateOrbit(
                centerBody,  // Will be set by caller if needed
                initialPosition,
                initialVelocity,startTime);

        return new ManeuverDetails(
                id != null ? id : "Initial-" + UUID.randomUUID(),
                initialPosition,
                initialVelocity,
                initialPosition,  // No movement
                initialVelocity,  // No velocity change
                0.0,
                orbit,
                0.0,
                startTime,
                null);  // No previous maneuver
    }

    public static ManeuverDetails takeOff(
            Gravitational launchBody,
            double startTime) {

        double rOrbit = launchBody.getStandardOrbitalRadius();

        Vector3D orbitalVelocity = launchBody.getStandardCircularOrbitVector();
        Vector3D orbitalPosition = launchBody.getStandardCircularOrbitPosition( Vector3D.ZERO);
        Orbit orbit = Orbit.calculateOrbit(launchBody,orbitalPosition,orbitalVelocity,startTime);

        return new ManeuverDetails("Take off to Standard Orbit (" + launchBody.getStandardOrbitalRadius()+ "m) from " + launchBody.getId(),
                launchBody.getPosition(),
                launchBody.getVelocity(), // when/if we handle spinning bodies. add scalar of the planet's tangential rotation.
                orbitalPosition,
                orbitalVelocity,
                launchBody.getEscapeVelocityFromRadius(rOrbit) + (launchBody.getOrbitalVelocity(rOrbit) - Math.sqrt(launchBody.getGravitationalParameter() / rOrbit)),
                orbit,
                //distance divided by half orbital velocity
                launchBody.getStandardOrbitalAltitude()*2/orbitalVelocity.magnitude(),
                startTime,
                null
        );
    }

    public static ManeuverDetails detach(Satellite satellite, double startTime) {
// Detach from satellite/station (negligible delta-V)
        return new ManeuverDetails(
                "Detach from " + satellite.getId(),
                satellite.getPosition(),
                satellite.getVelocity(),
                satellite.getPosition(),
                satellite.getVelocity(),
                0.0001,
                Orbit.calculateOrbitFor(satellite,startTime),
                0.0,
                startTime,
                null);
    }

    /**
     * FIXED: Land on a gravitational body at its FUTURE position
     *
     * Changes from original:
     * 1. Calculate where the planet will be when we arrive
     * 2. Use proper time calculation for descent
     * 3. Correct delta-V calculation
     *
     * Generated by Claude (Sonnet 4.5) - Bug Fix
     */
    public ManeuverDetails finallyLand(Gravitational landingTarget) {
        if(landingTarget instanceof Star) {
            // Cannot land on a star
            this.terminus = true;
            return this;
        }

        if(!(landingTarget instanceof Orbiter destinationOrbiter)) {
            // Landing target must be an orbiter to predict position
            throw new IllegalArgumentException(
                    "Landing target must be an Orbiter to calculate future position");
        }


        // Time when we arrive at planet (end of previous maneuver)
        double arrivalTime = this.getEndTime();
        // Calculate where the planet will be when we arrive
        Orbit planetOrbit = destinationOrbiter.calculateCurrentOrbit().withTime(arrivalTime);

        // Predict planet's position at arrival
        OrbitalState futureDestination = planetOrbit.calculateOrbitAfterT0(
                arrivalTime - planetOrbit.epoch());

        // Calculate landing time (rough estimate: deorbit + descent)
        // Assume average velocity during descent is half escape velocity
        double altitudeToCover = landingTarget.getStandardOrbitalAltitude();
        double averageDescentSpeed = landingTarget.getSurfaceEscapeVelocity() / 2.0;
        double descentTime = altitudeToCover / averageDescentSpeed;

        // Add time for deorbit burn (assume 1/4 orbital period at standard altitude)
        double deorbitTime = Math.PI * 0.5 * Math.sqrt(
                Math.pow(landingTarget.getStandardOrbitalRadius(), 3) /
                        landingTarget.getGravitationalParameter());

        double totalLandingTime = deorbitTime + descentTime;

        // Calculate delta-V for landing (escape velocity from standard orbit)
        double landingDeltaV = landingTarget.getEscapeVelocityFromRadius(
                landingTarget.getStandardOrbitalRadius());

        return new ManeuverDetails(
                "Landing-" + ((OrbitingBody)landingTarget).getId(),
                this.endingPosition,           // Start where previous maneuver ended
                this.endingVelocity,           // With previous ending velocity
                futureDestination.position(),  // End at planet's FUTURE position
                futureDestination.velocity(),  // Match planet's FUTURE velocity
                landingDeltaV,                 // Delta-V for landing
                null,                          // No orbit after landing
                totalLandingTime,              // Actual time for landing sequence
                this.getEndTime(),             // Start when previous maneuver ends
                this,
                true);                         // This is a terminus
    }

    /**
     * BUILDER: Create an impulsive burn maneuver (instant velocity change)
     * Automatically uses this maneuver's ending state as starting state.
     *
     * @param newVelocity Velocity after burn
     * @param description Description of the burn
     * @return New maneuver chained to this one
     */
    public ManeuverDetails thenBurn(Vector3D newVelocity, String description) {
        return new ManeuverDetails(
                description != null ? description : "Burn-" + UUID.randomUUID(),
                this.endingPosition,      // Burn at current position
                this.endingVelocity,      // Starting velocity
                this.endingPosition,      // No position change (instant)
                newVelocity,              // New velocity
                newVelocity.subtract(this.endingVelocity).magnitude(),
                Orbit.calculateOrbit(this.orbit.centerBody(), this),                 // New orbit after burn
                0.0,                      // Instant maneuver
                getEndTime(),
                this);
    }

    /**
     * BUILDER: Create a coast maneuver (follow transfer orbit)
     * Automatically uses this maneuver's ending state as starting state.
     *
     * @param coastTime Duration of coast (seconds)
     * @return New maneuver chained to this one
     */
    public ManeuverDetails thenCoast(double coastTime) {
        if(coastTime <= 0.0) {
            throw new IllegalArgumentException("Non-Positive Coast Times not allowed.");
        }

        double timeFromOrbitEpoch = getEndTime() - orbit.epoch();
        double finalTimeFromOrbitEpoch = timeFromOrbitEpoch + coastTime;

        OrbitalState endState = orbit.calculateOrbitAfterT0(finalTimeFromOrbitEpoch);

        return new ManeuverDetails(
                "Coast-" + UUID.randomUUID(),
                this.endingPosition,      // Start where previous ended
                this.endingVelocity,      // With previous ending velocity
                endState.position(),      // End at propagated position
                endState.velocity(),      // With propagated velocity
                0.0,                      // No delta-V for coasting
                orbit,                    // ✓ FIXED: Use original orbit, don't modify epoch!
                coastTime,
                getEndTime(),
                this);
    }

    /**
     * Get the first maneuver in this chain
     */
    public ManeuverDetails getFirst() {
        ManeuverDetails current = this;
        while (current.previous != null) {
            current = current.previous;
        }
        return current;
    }

    // Legacy constructor for backward compatibility - DEPRECATED
    @Deprecated
    public ManeuverDetails(
            String id,
            Vector3D startingPosition,
            Vector3D startingVelocity,
            Vector3D endingPosition,
            Vector3D endingVelocity,
            double deltaV,
            Orbit orbitState,
            double timeToExecute,
            double epoch0) {

        this(id, startingPosition, startingVelocity, endingPosition, endingVelocity,
                deltaV, orbitState, timeToExecute, epoch0, null);

        System.err.println("WARNING: Using deprecated ManeuverDetails constructor. " +
                "Consider using builder methods instead.");
    }
}