package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.vehicles.Satellite;
import lombok.Getter;
import lombok.ToString;

import java.util.UUID;

/**
 * REFACTORED: Maneuver as state chain
 *
 * Represents a single maneuver (burn or coast) in a flight plan.
 * Stores position/velocity states, NOT orbits.
 *
 * Orbits are calculated on demand for trajectory prediction during coasts,
 * but are not stored as persistent state.
 *
 * Generated by Claude (Sonnet 4.5) - Architecture Refactor
 */
@Getter
@ToString(exclude = {"previous", "next"})
public class ManeuverDetails {
    private final String id;
    private final Vector3D startingPosition;
    private final Vector3D startingVelocity;
    private final Vector3D endingPosition;
    private final Vector3D endingVelocity;
    private final double deltaV;
    private final Gravitational referenceBody;  // For trajectory calculations
    private final double timeToExecute;
    private final double startTime;

    // Chain references
    private final ManeuverDetails previous;
    private ManeuverDetails next;

    private boolean terminus;

    private ManeuverDetails(
            String id,
            Vector3D startingPosition,
            Vector3D startingVelocity,
            Vector3D endingPosition,
            Vector3D endingVelocity,
            double deltaV,
            Gravitational referenceBody,
            double timeToExecute,
            double startTime,
            ManeuverDetails previous,
            boolean terminus) {

        this.id = id;
        this.startingPosition = startingPosition;
        this.startingVelocity = startingVelocity;
        this.endingPosition = endingPosition;
        this.endingVelocity = endingVelocity;
        this.deltaV = deltaV;
        this.referenceBody = referenceBody;
        this.timeToExecute = timeToExecute;
        this.startTime = startTime;
        this.previous = previous;
        this.next = null;
        this.terminus = terminus;

        if (previous != null) {
            previous.next = this;
        }
    }

    public double getEndTime() {
        return startTime + timeToExecute;
    }

    // ==================== STATIC FACTORY METHODS ====================

    /**
     * Create the first maneuver in a chain from initial state.
     */
    public static ManeuverDetails createInitial(
            String id,
            Vector3D initialPosition,
            Vector3D initialVelocity,
            Gravitational referenceBody,
            double startTime) {

        return new ManeuverDetails(
                id != null ? id : "Initial-" + UUID.randomUUID(),
                initialPosition,
                initialVelocity,
                initialPosition,
                initialVelocity,
                0.0,
                referenceBody,
                0.0,
                startTime,
                null,
                false);
    }

    public static ManeuverDetails takeOff(
            Gravitational launchBody,
            double startTime) {

        double rOrbit = launchBody.getStandardOrbitalRadius();

        Vector3D orbitalVelocity = launchBody.getStandardCircularOrbitVector();
        Vector3D orbitalPosition = launchBody.getStandardCircularOrbitPosition(Vector3D.ZERO);

        double launchDeltaV = launchBody.getEscapeVelocityFromRadius(rOrbit) +
                (launchBody.getOrbitalVelocity(rOrbit) -
                        Math.sqrt(launchBody.getGravitationalParameter() / rOrbit));

        double launchTime = launchBody.getStandardOrbitalAltitude() * 2 / orbitalVelocity.magnitude();

        return new ManeuverDetails(
                "Take off to Standard Orbit (" + launchBody.getStandardOrbitalRadius() + "m) from " + launchBody.getId(),
                launchBody.getPosition(),
                launchBody.getVelocity(),
                orbitalPosition,
                orbitalVelocity,
                launchDeltaV,
                launchBody,
                launchTime,
                startTime,
                null,
                false);
    }

    public static ManeuverDetails detach(Satellite satellite, double startTime) {
        return new ManeuverDetails(
                "Detach from " + satellite.getId(),
                satellite.getPosition(),
                satellite.getVelocity(),
                satellite.getPosition(),
                satellite.getVelocity(),
                0.0001,
                satellite.getParentBody(),
                0.0,
                startTime,
                null,
                false);
    }

    // ==================== BUILDER METHODS ====================

    /**
     * Create an impulsive burn (instant velocity change).
     */
    public ManeuverDetails thenBurn(Vector3D newVelocity, String description) {
        return new ManeuverDetails(
                description != null ? description : "Burn-" + UUID.randomUUID(),
                this.endingPosition,
                this.endingVelocity,
                this.endingPosition,
                newVelocity,
                newVelocity.subtract(this.endingVelocity).magnitude(),
                this.referenceBody,
                0.0,
                getEndTime(),
                this,
                false);
    }

    /**
     * Create a coast maneuver (follow ballistic trajectory).
     *
     * Uses 2-body approximation to predict ending position/velocity.
     * Orbit is calculated as needed, not stored.
     */
    public ManeuverDetails thenCoast(double coastTime) {
        if (coastTime <= 0.0) {
            throw new IllegalArgumentException("Non-positive coast times not allowed.");
        }

        // Calculate trajectory for prediction
        Orbit trajectory = Orbit.fromState(referenceBody, endingPosition, endingVelocity);
        OrbitalState endState = trajectory.propagate(coastTime);

        return new ManeuverDetails(
                "Coast-" + UUID.randomUUID(),
                this.endingPosition,
                this.endingVelocity,
                endState.position(),
                endState.velocity(),
                0.0,
                this.referenceBody,
                coastTime,
                getEndTime(),
                this,
                false);
    }

    /**
     * Land on a gravitational body.
     */
    public ManeuverDetails finallyLand(Gravitational landingTarget) {
        if (landingTarget instanceof Star) {
            this.terminus = true;
            return this;
        }

        if (!(landingTarget instanceof Orbiter destinationOrbiter)) {
            throw new IllegalArgumentException(
                    "Landing target must be an Orbiter to calculate future position");
        }

        double arrivalTime = this.getEndTime();

        // Predict where planet will be at arrival
        Orbit planetTrajectory = Orbit.fromState(
                destinationOrbiter.getParentBody(),
                destinationOrbiter.getPosition(),
                destinationOrbiter.getVelocity()
        );

        OrbitalState futureDestination = planetTrajectory.propagate(arrivalTime - destinationOrbiter.getParentBody().getSystem().getCurrentTime());

        // Calculate landing time
        double altitudeToCover = landingTarget.getStandardOrbitalAltitude();
        double averageDescentSpeed = landingTarget.getSurfaceEscapeVelocity() / 2.0;
        double descentTime = altitudeToCover / averageDescentSpeed;

        double deorbitTime = Math.PI * 0.5 * Math.sqrt(
                Math.pow(landingTarget.getStandardOrbitalRadius(), 3) /
                        landingTarget.getGravitationalParameter());

        double totalLandingTime = deorbitTime + descentTime;
        double landingDeltaV = landingTarget.getEscapeVelocityFromRadius(
                landingTarget.getStandardOrbitalRadius());

        return new ManeuverDetails(
                "Landing-" + ((OrbitingBody) landingTarget).getId(),
                this.endingPosition,
                this.endingVelocity,
                futureDestination.position(),
                futureDestination.velocity(),
                landingDeltaV,
                landingTarget,
                totalLandingTime,
                this.getEndTime(),
                this,
                true);
    }

    // ==================== TRAJECTORY PREDICTION ====================

    /**
     * Predict position at a specific time during this maneuver.
     * For coasts, uses 2-body approximation.
     * For burns, returns ending position (instantaneous).
     */
    public Vector3D predictPositionAt(double time) {
        if (time < startTime || time > getEndTime()) {
            throw new IllegalArgumentException(
                    "Time " + time + " outside maneuver range [" + startTime + ", " + getEndTime() + "]");
        }

        if (timeToExecute == 0.0) {
            // Burn - instantaneous
            return endingPosition;
        }

        // Coast - calculate trajectory
        double elapsed = time - startTime;
        Orbit trajectory = Orbit.fromState(referenceBody, startingPosition, startingVelocity);
        return trajectory.propagate(elapsed).position();
    }

    /**
     * Predict velocity at a specific time during this maneuver.
     */
    public Vector3D predictVelocityAt(double time) {
        if (time < startTime || time > getEndTime()) {
            throw new IllegalArgumentException(
                    "Time " + time + " outside maneuver range [" + startTime + ", " + getEndTime() + "]");
        }

        if (timeToExecute == 0.0) {
            return endingVelocity;
        }

        double elapsed = time - startTime;
        Orbit trajectory = Orbit.fromState(referenceBody, startingPosition, startingVelocity);
        return trajectory.propagate(elapsed).velocity();
    }

    /**
     * Get the first maneuver in this chain.
     */
    public ManeuverDetails getFirst() {
        ManeuverDetails current = this;
        while (current.previous != null) {
            current = current.previous;
        }
        return current;
    }
}