package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Asteroid;
import com.kaymlyn.planeteater.simulation.celestial.CelestialBody;
import com.kaymlyn.planeteater.simulation.celestial.Planet;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import lombok.Getter;
import lombok.Setter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

/**
 * Manages all celestial bodies and handles orbital mechanics simulation
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
@Setter
public class OrbitalSystem {
    private Star centralStar;
    private List<CelestialBody> bodies;
    private Map<String, CelestialBody> bodyMap;
    private double currentTime; // seconds since epoch
    private double timeStep; // simulation time step in seconds
    
    public OrbitalSystem(Star centralStar, double timeStep) {
        this.centralStar = centralStar;
        this.bodies = new ArrayList<>();
        this.bodyMap = new HashMap<>();
        this.currentTime = 0.0;
        this.timeStep = timeStep;
        
        // Add the star to the system
        addBody(centralStar);
    }
    
    /**
     * Add a celestial body to the system
     */
    public void addBody(CelestialBody body) {
        bodies.add(body);
        bodyMap.put(body.getId(), body);
    }
    
    /**
     * Remove a celestial body from the system
     */
    public boolean removeBody(String id) {
        CelestialBody body = bodyMap.remove(id);
        if (body != null) {
            bodies.remove(body);
            return true;
        }
        return false;
    }
    
    /**
     * Get a body by ID
     * @return CelestialBody identified by id
     */
    public CelestialBody getBody(String id) {
        return bodyMap.get(id);
    }
    
    /**
     * Get all bodies except the star
     * @return List containing all the non-star bodies in the System
     */
    public List<CelestialBody> getOrbitingBodies() {
        List<CelestialBody> orbiting = new ArrayList<>(bodies);
        orbiting.remove(centralStar);
        return orbiting;
    }

    /**
     * Get all stars in the system
     * @return List containing all the stars in the system
     */
    public List<Star> getStars() {
        List<Star> centralStars = new ArrayList<>();
        centralStars.add(centralStar);
        return centralStars;
    }
    
    /**
     * Step the simulation forward by one time step using simple Euler integration
     */
    public void stepEuler() {
        // Calculate accelerations for all bodies
        Map<CelestialBody, Vector3D> accelerations = new HashMap<>();
        for (CelestialBody body : bodies) {
            accelerations.put(body, calculateAcceleration(body));
        }
        
        // Update all bodies
        for (CelestialBody body : bodies) {
            body.update(accelerations.get(body), timeStep);
        }
        
        currentTime += timeStep;
    }
    
    /**
     * Step the simulation forward using Velocity Verlet integration (more accurate)
     * x(t+dt) = x(t) + v(t)*dt + 0.5*a(t)*dt²
     * v(t+dt) = v(t) + 0.5*(a(t) + a(t+dt))*dt
     */
    public double stepVerlet() {
        Date start = new Date();
        // Calculate current accelerations
        Map<CelestialBody, Vector3D> accelerations = new HashMap<>();
        for (CelestialBody body : bodies) {
            accelerations.put(body, calculateAcceleration(body));
        }
        
        // Update positions
        for (CelestialBody body : bodies) {
            Vector3D accel = accelerations.get(body);
            Vector3D newPos = body.getPosition()
                .add(body.getVelocity().multiply(timeStep))
                .add(accel.multiply(0.5 * timeStep * timeStep));
            body.setPosition(newPos);
        }
        
        // Calculate new accelerations at new positions
        Map<CelestialBody, Vector3D> newAccelerations = new HashMap<>();
        for (CelestialBody body : bodies) {
            newAccelerations.put(body, calculateAcceleration(body));
        }
        
        // Update velocities using average of old and new accelerations
        for (CelestialBody body : bodies) {
            Vector3D oldAccel = accelerations.get(body);
            Vector3D newAccel = newAccelerations.get(body);
            Vector3D avgAccel = oldAccel.add(newAccel).multiply(0.5);
            Vector3D newVel = body.getVelocity().add(avgAccel.multiply(timeStep));
            body.setVelocity(newVel);
        }
        
        currentTime += timeStep;
        System.out.println("Verlet simulation took " + (new Date().getTime() - start.getTime()) + " milliseconds");
        return currentTime;
    }
    
    /**
     * Step the simulation forward by a specified amount of time
     */
    public void advance(double duration) {
        double targetTime = currentTime + duration;
        while (currentTime < targetTime) {
            stepVerlet();
        }
    }
    
    /**
     * Calculate orbital velocity for a circular orbit at given radius
     * v = sqrt(G * M / r)
     */
    public double circularOrbitVelocity(double radius) {
        return Math.sqrt(PhysicsConstants.G * centralStar.getMass() / radius);
    }
    
    /**
     * Calculate orbital period for a circular orbit at given radius
     * T = 2π * sqrt(r³ / (G * M))
     */
    public double orbitalPeriod(double radius) {
        return 2.0 * Math.PI * Math.sqrt(Math.pow(radius, 3) / 
            (PhysicsConstants.G * centralStar.getMass()));
    }
    
    /**
     * Place a body in a circular orbit at specified radius and angle
     * @param body The body to place in orbit
     * @param radius Distance from star in meters
     * @param angle Angle in radians (0 = +X axis)
     */
    public void placeInCircularOrbit(CelestialBody body, double radius, double angle) {
        placeInEllipticalOrbit(
                body,
                radius,
                0.0,
                0.0,
                0.0,
                0.0,
                angle
        );
    }

    /**
     * Place a body in a circular orbit at specified radius and angle
     *
     * @param body The body to place in orbit
     * @param radius Distance from star in meters
     * @param angle Angle in radians (0 = +X axis)
     * @param inclination Inclination in radians (0 = +Z axis)
     */
    public void placeInCircularOrbit(CelestialBody body, double radius, double angle, double inclination) {
        placeInEllipticalOrbit(
                body,
                radius,
                0.0,
                inclination,
                0.0,
                0.0,
                angle
        );
    }

    public void placeAllInCircularOrbits(List<? extends CelestialBody> bodies, double minimumAURadius, double maximumAURadius) {
        Random random = new Random(0L);
        bodies.forEach(body -> placeInCircularOrbit(body,
                random.nextDouble(minimumAURadius,maximumAURadius)*PhysicsConstants.AU,
                random.nextDouble()*2*Math.PI));
    }

    /**
     * Place all provided bodies in an elliptical orbit at random distances and angles to the parent star.
     * All undefined values will be set to a value between 0 and 2π
     *
     * @param bodies The bodies to place in orbit around the system's star
     * @param minimumAURadius Minimum distance from the star measured in AU
     * @param maximumAURadius Maximum distance from the star measured in AU
     * @param maxInclination Maximum angle of inclination measured in radians
     * @param maximumEccentricity Maximum eccentricity
     */
    public void placeAllInEllipticalOrbits(List<? extends CelestialBody> bodies,
                                           double minimumAURadius,
                                           double maximumAURadius,
                                           double maxInclination,
                                           double maximumEccentricity) {
        Random random = new Random(0L);
        bodies.forEach(body -> placeInEllipticalOrbit(body,
                random.nextDouble(minimumAURadius,maximumAURadius)*PhysicsConstants.AU,
                random.nextDouble(0,maximumEccentricity),
                random.nextDouble(0,maxInclination),
                random.nextDouble()*2*Math.PI,
                random.nextDouble()*2*Math.PI,
                random.nextDouble()*2*Math.PI));
    }

    /**
     * Place a body in an elliptical orbit using orbital elements
     *
     * @param body The body to place in orbit
     * @param semiMajorAxis Semi-major axis (a) in meters
     * @param eccentricity Eccentricity (e), 0 = circular, 0-1 = ellipse
     * @param inclination Inclination (i) from ecliptic plane in radians
     * @param longitudeOfAscendingNode Longitude of ascending node (Ω) in radians
     * @param argumentOfPeriapsis Argument of periapsis (ω) in radians
     * @param trueAnomaly True anomaly (ν) - position in orbit in radians
     */
    @SuppressWarnings("DuplicateExpressions")
    public void placeInEllipticalOrbit(CelestialBody body,
                                       double semiMajorAxis,
                                       double eccentricity,
                                       double inclination,
                                       double longitudeOfAscendingNode,
                                       double argumentOfPeriapsis,
                                       double trueAnomaly) {

        // Validate inputs
        if (eccentricity < 0.0 || eccentricity >= 1.0) {
            throw new IllegalArgumentException("Eccentricity must be in range [0, 1)");
        }
        if (semiMajorAxis <= 0.0) {
            throw new IllegalArgumentException("Semi-major axis must be positive");
        }

        // Calculate distance from focus at true anomaly
        double r = semiMajorAxis * (1.0 - eccentricity * eccentricity) /
                (1.0 + eccentricity * Math.cos(trueAnomaly));

        // Position in orbital plane (2D)
        double xOrbital = r * Math.cos(trueAnomaly);
        double yOrbital = r * Math.sin(trueAnomaly);

        // Velocity in orbital plane
        // Vis-viva equation: v = sqrt(μ(2/r - 1/a))
        double mu = PhysicsConstants.G * centralStar.getMass();
        double vMagnitude = Math.sqrt(mu * (2.0 / r - 1.0 / semiMajorAxis));

        // Velocity direction (perpendicular to radius vector)
        // Flight path angle: tan(φ) = e*sin(ν) / (1 + e*cos(ν))
        double flightPathAngle = Math.atan2(eccentricity * Math.sin(trueAnomaly),
                1.0 + eccentricity * Math.cos(trueAnomaly));

        // Velocity components in orbital plane
        double vxOrbital = vMagnitude * Math.cos(trueAnomaly + Math.PI/2 + flightPathAngle);
        double vyOrbital = vMagnitude * Math.sin(trueAnomaly + Math.PI/2 + flightPathAngle);

        // Rotate from orbital plane to 3D space using Euler angles
        // Apply rotations: Ω (longitude of ascending node), i (inclination), ω (argument of periapsis)

        // Combined rotation matrix elements
        double cosO = Math.cos(longitudeOfAscendingNode);
        double sinO = Math.sin(longitudeOfAscendingNode);
        double cosi = Math.cos(inclination);
        double sini = Math.sin(inclination);
        double cosw = Math.cos(argumentOfPeriapsis);
        double sinw = Math.sin(argumentOfPeriapsis);

        // Position transformation
        double x = xOrbital * (cosO * cosw - sinO * sinw * cosi) -
                yOrbital * (cosO * sinw + sinO * cosw * cosi);
        double y = xOrbital * (sinO * cosw + cosO * sinw * cosi) -
                yOrbital * (sinO * sinw - cosO * cosw * cosi);
        double z = xOrbital * (sinw * sini) + yOrbital * (cosw * sini);

        // Velocity transformation
        double vx = vxOrbital * (cosO * cosw - sinO * sinw * cosi) -
                vyOrbital * (cosO * sinw + sinO * cosw * cosi);
        double vy = vxOrbital * (sinO * cosw + cosO * sinw * cosi) -
                vyOrbital * (sinO * sinw - cosO * cosw * cosi);
        double vz = vxOrbital * (sinw * sini) + vyOrbital * (cosw * sini);

        body.setPosition(new Vector3D(x, y, z));
        body.setVelocity(new Vector3D(vx, vy, vz));

        addBody(body);
    }
    
    /**
     * Get all asteroids in the system
     */
    public List<Asteroid> getAsteroids() {
        List<Asteroid> asteroids = new ArrayList<>();
        for (CelestialBody body : bodies) {
            if (body instanceof Asteroid) {
                asteroids.add((Asteroid) body);
            }
        }
        return asteroids;
    }
    
    /**
     * Get all planets in the system
     */
    public List<Planet> getPlanets() {
        List<Planet> planets = new ArrayList<>();
        for (CelestialBody body : bodies) {
            if (body instanceof Planet) {
                planets.add((Planet) body);
            }
        }
        return planets;
    }

    /**
     * Calculate orbital elements from current position and velocity
     * Useful for analyzing orbits
     *
     * @return Map containing: "a" (semi-major axis), "e" (eccentricity),
     *         "i" (inclination), "Ω" (longitude of ascending node),
     *         "ω" (argument of periapsis), "ν" (true anomaly)
     */
    public static Map<String, Double> calculateOrbitalElements(Star centralStar, CelestialBody body) {
        Map<String, Double> elements = new HashMap<>();

        Vector3D r = body.getPosition();
        Vector3D v = body.getVelocity();
        double mu = PhysicsConstants.G * centralStar.getMass();

        // Specific orbital energy
        double energy = v.magnitudeSquared() / 2.0 - mu / r.magnitude();

        // Semi-major axis
        double a = -mu / (2.0 * energy);
        elements.put("a", a);

        // Angular momentum vector
        Vector3D h = r.cross(v);
        double hMag = h.magnitude();

        // Eccentricity vector
        Vector3D eVec = v.cross(h).divide(mu).subtract(r.normalize());
        double e = eVec.magnitude();
        elements.put("e", e);

        // Inclination
        double i = Math.acos(h.getZ() / hMag);
        elements.put("i", i);

        // Node vector (points to ascending node)
        Vector3D n = Vector3D.UNIT_Z.cross(h);
        double nMag = n.magnitude();

        // Longitude of ascending node
        double omega;
        if (nMag > 1e-10) {
            omega = Math.acos(n.getX() / nMag);
            if (n.getY() < 0) omega = 2 * Math.PI - omega;
        } else {
            omega = 0.0; // Undefined for non-inclined orbits
        }
        elements.put("Omega", omega);

        // Argument of periapsis
        double w;
        if (nMag > 1e-10 && e > 1e-10) {
            w = Math.acos(n.dot(eVec) / (nMag * e));
            if (eVec.getZ() < 0) w = 2 * Math.PI - w;
        } else {
            w = 0.0; // Undefined for circular or non-inclined orbits
        }
        elements.put("omega", w);

        // True anomaly
        double nu;
        if (e > 1e-10) {
            nu = Math.acos(eVec.dot(r) / (e * r.magnitude()));
            if (r.dot(v) < 0) nu = 2 * Math.PI - nu;
        } else {
            // For circular orbits, measure from ascending node
            if (nMag > 1e-10) {
                nu = Math.acos(n.dot(r) / (nMag * r.magnitude()));
                if (r.getZ() < 0) nu = 2 * Math.PI - nu;
            } else {
                nu = Math.atan2(r.getY(), r.getX());
            }
        }
        elements.put("nu", nu);

        return elements;
    }
    
    @Override
    public String toString() {
        return String.format("OrbitalSystem[bodies=%d, time=%.2f days]",
            bodies.size(), currentTime / PhysicsConstants.SECONDS_PER_DAY);
    }

    /**
     * Calculate gravitational acceleration on a body from all other bodies
     */
    private Vector3D calculateAcceleration(CelestialBody body) {
        Vector3D totalAcceleration = Vector3D.ZERO;

        for (CelestialBody other : bodies) {
            if (other == body) continue;

            Vector3D force = other.gravitationalForceOn(body);
            // a = F / m
            Vector3D acceleration = force.divide(body.getMass());
            totalAcceleration = totalAcceleration.add(acceleration);
        }

        return totalAcceleration;
    }
}