package com.kaymlyn.planeteater.simulation.physics;

/**
 * Represents the kinematic state of an object at a point in time.
 * This is the ground truth - position and velocity are what actually exist.
 * Orbital elements are derived properties that can be calculated from this state.
 *
 * Generated by Claude (Sonnet 4.5) - Architecture Refactor
 */
public record OrbitalState(
        Vector3D position,
        Vector3D velocity
) {

    /**
     * Calculate angular momentum magnitude.
     */
    public double angularMomentum() {
        return position.cross(velocity).magnitude();
    }

    /**
     * Calculate orbital elements from this state.
     * Result is only valid at this instant.
     */
    public Orbit toOrbit(com.kaymlyn.planeteater.simulation.celestial.Gravitational centerBody) {
        return Orbit.fromState(centerBody, position, velocity);
    }
}
