package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.NonNull;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Transfer planning using Lambert-based trajectory solving.
 *
 * Lambert's problem finds the velocity vectors required to travel between two
 * position vectors in a given time. This correctly accounts for the actual
 * positions of origin and destination bodies at departure and arrival,
 * which orbit-radius-only approaches (Hohmann) cannot do.
 *
 * Hohmann and bi-elliptic transfers are orbit-to-orbit maneuvers that require
 * precise phase alignment between the two bodies. Lambert subsumes Hohmann:
 * when transfer angle is 180 degrees, orbits are circular and coplanar, and
 * time of flight equals the Hohmann period, Lambert produces the identical
 * burn vectors. Lambert is therefore retained as the sole interplanetary
 * transfer strategy.
 *
 * Bi-elliptic transfers are fundamentally three-burn, two-arc maneuvers and
 * cannot be expressed as a single Lambert arc. They are more efficient than
 * Hohmann only when the radius ratio exceeds approximately 11.94 (relevant
 * for outer planet transfers). Reserved for future implementation.
 *
 * Transfer strategies offered:
 *   LAMBERT_FAST      - 1.0x minimum transfer time; fastest, highest delta-V
 *   LAMBERT_BALANCED  - 1.5x minimum transfer time; moderate tradeoff
 *   LAMBERT_EFFICIENT - 2.5x minimum transfer time; slower, lower delta-V
 *   LAMBERT_MAX_DELTAV - uses full available spacecraft delta-V budget;
 *                        arrives as soon as physically possible given fuel
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class TransferPlanner {

    /**
     * Upper bound for transfer time search as a multiple of the minimum
     * transfer time (Hohmann half-period). The max delta-V search will not
     * consider trajectories longer than this limit.
     *
     * Default is 5.0. Set higher for missions to fast inner bodies or slow
     * outer planets where longer transfer windows may be acceptable.
     * Example: TransferPlanner.maxTransferTimeMultiplier = 100.0;
     */
    public static double maxTransferTimeMultiplier = 5.0;

    /**
     * Number of iterations for the Brent root-find used in the max delta-V
     * transfer time search. Higher values improve accuracy at the cost of
     * additional Lambert solves. 64 iterations gives sub-second precision
     * for typical solar system transfer times.
     */
    private static final int MAX_DELTAV_SEARCH_ITERATIONS = 64;

    public enum TransferStrategy {
        LAMBERT_FAST,
        LAMBERT_BALANCED,
        LAMBERT_EFFICIENT,
        LAMBERT_MAX_DELTAV
    }

    public enum OptimizationGoal {
        MINIMUM_TIME,
        MINIMUM_DELTAV,
        BALANCED
    }

    @Getter
    public static class TransferOption {
        private final TransferStrategy strategy;
        private final Itinerary itinerary;
        private final double efficiencyScore;

        public TransferOption(TransferStrategy strategy, @NonNull Itinerary itinerary) {
            this.strategy = strategy;
            this.itinerary = itinerary;

            if(itinerary != null) {
                double totalDeltaV = itinerary.getTotalDeltaV();
                this.efficiencyScore = totalDeltaV > 0 ?
                        itinerary.getEstimatedDuration() / totalDeltaV :
                        Double.POSITIVE_INFINITY;
            } else {
                this.efficiencyScore = Double.POSITIVE_INFINITY;
            }
        }
    }

    // ==================== TRANSFER OPTION GENERATION ====================
    /**
     * Generate all transfer options between two orbiting bodies.
     *
     * Four Lambert transfers are attempted:
     *
     *   LAMBERT_FAST        1.0x minimum transfer time
     *   LAMBERT_BALANCED    1.5x minimum transfer time
     *   LAMBERT_EFFICIENT   2.5x minimum transfer time
     *   LAMBERT_MAX_DELTAV  shortest transfer time achievable within the
     *                       spacecraft's full available delta-V budget,
     *                       searched up to maxTransferTimeMultiplier * minimum
     *
     * The minimum transfer time is the Hohmann half-period. The 1.0x Lambert
     * solution converges to the Hohmann solution when planetary phase conditions
     * are met.
     *
     * All feasible options are returned sorted by efficiency score (duration /
     * delta-V). The optimizer then selects from this combined pool, so a fixed
     * multiplier option that happens to be superior to the max delta-V solution
     * for the current geometry will be preferred automatically.
     *
     * @param spacecraft    the spacecraft making the transfer
     * @param origin        starting body
     * @param destination   target body
     * @param land          true to dock at destination, false to orbit
     * @param departureTime absolute simulation time to begin transfer
     * @return list of feasible transfer options, sorted by efficiency score
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static List<TransferOption> generateTransferOptions(
            Spacecraft spacecraft,
            Orbiter origin,
            Orbiter destination,
            boolean land,
            double departureTime) {
        return generateTransferOptions(spacecraft,origin,destination,land, departureTime, true);
    }
    /**
     * Generate feasible transfer options between two orbiting bodies.
     *
     * Four Lambert transfers are attempted:
     *
     *   LAMBERT_FAST        1.0x minimum transfer time
     *   LAMBERT_BALANCED    1.5x minimum transfer time
     *   LAMBERT_EFFICIENT   2.5x minimum transfer time
     *   LAMBERT_MAX_DELTAV  shortest transfer time achievable within the
     *                       spacecraft's full available delta-V budget,
     *                       searched up to maxTransferTimeMultiplier * minimum
     *
     * The minimum transfer time is the Hohmann half-period. The 1.0x Lambert
     * solution converges to the Hohmann solution when planetary phase conditions
     * are met.
     *
     * All feasible options are returned sorted by efficiency score (duration /
     * delta-V). The optimizer then selects from this combined pool, so a fixed
     * multiplier option that happens to be superior to the max delta-V solution
     * for the current geometry will be preferred automatically.
     *
     * @param spacecraft    the spacecraft making the transfer
     * @param origin        starting body
     * @param destination   target body
     * @param land          true to dock at destination, false to orbit
     * @param departureTime absolute simulation time to begin transfer
     * @return list of feasible transfer options, sorted by efficiency score
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static List<TransferOption> generateTransferOptions(
            Spacecraft spacecraft,
            Orbiter origin,
            Orbiter destination,
            boolean land,
            double departureTime,
            boolean includeInfeasible) {

        List<TransferOption> options = new ArrayList<>();

        Orbit originOrbit = origin.snapshotOrbit();
        Orbit targetOrbit = destination.snapshotOrbit();

        double minTransferTime = calculateMinimumTransferTime(originOrbit, targetOrbit);

        // Fixed time-of-flight options
        double[] multipliers = {1.0, 1.5, 2.5};
        TransferStrategy[] fixedStrategies = {
                TransferStrategy.LAMBERT_FAST,
                TransferStrategy.LAMBERT_BALANCED,
                TransferStrategy.LAMBERT_EFFICIENT
        };

        for (int i = 0; i < multipliers.length; i++) {
            double transferTime = minTransferTime * multipliers[i];
            Itinerary lambert = buildLambertTransfer(
                    spacecraft, targetOrbit, destination,
                    land, departureTime, transferTime);

            if (lambert.isFeasible()) {
                options.add(new TransferOption(fixedStrategies[i], lambert));
            }
        }

        // Max delta-V option: find shortest transfer time within fuel budget
        double maxTransferTime = minTransferTime * maxTransferTimeMultiplier;
        Itinerary maxDeltaVTransfer = buildMaxDeltaVTransfer(
                spacecraft, targetOrbit, destination,
                land, departureTime, minTransferTime, maxTransferTime);
        if ((includeInfeasible && maxDeltaVTransfer != null) || ( maxDeltaVTransfer != null && maxDeltaVTransfer.isFeasible())) {
            options.add(new TransferOption(TransferStrategy.LAMBERT_MAX_DELTAV, maxDeltaVTransfer));
        }

        options.sort(Comparator.comparingDouble(TransferOption::getEfficiencyScore));
        return options;
    }

    // ==================== TRANSFER BUILDERS ====================

    /**
     * Build a Lambert transfer with the specified time of flight.
     * <p>
     * The departure burn changes velocity from the current spacecraft velocity
     * to the Lambert solution velocity. The arrival burn has two components:
     * <p>
     * 1. Heliocentric match: decelerate from Lambert arrival velocity to
     * match the destination body's heliocentric velocity.
     * 2. Orbit insertion: decelerate from hyperbolic approach speed into
     * a circular orbit at destination.getStandardOrbitalRadius().
     * Only applied when destinationBody is Gravitational.
     * <p>
     * The hyperbolic excess velocity (v_infinity) is the magnitude of the
     * relative approach velocity between the spacecraft and destination at
     * the moment of arrival. Capture requires:
     * <p>
     * v_hyperbolic = sqrt(v_infinity^2 + 2 * mu_dest / r_capture)
     * v_circular   = sqrt(mu_dest / r_capture)
     * delta_v_capture = v_hyperbolic - v_circular
     *
     * @param spacecraft      the spacecraft making the transfer
     * @param target          target orbit (heliocentric)
     * @param destinationBody destination orbiter
     * @param land            true to dock, false to orbit
     * @param departureTime   absolute simulation time of departure burn
     * @param transferTime    duration of transfer in seconds
     * @return itinerary with departure and arrival burns
     * <p>
     * Generated by Claude (Sonnet 4.5)
     */
    public static Itinerary buildLambertTransfer(
            Spacecraft spacecraft,
            Orbit target,
            Orbiter destinationBody,
            boolean land,
            double departureTime,
            double transferTime) {

        Itinerary itinerary = new Itinerary(departureTime);
        itinerary.setDestination(destinationBody);
        itinerary.setFinalState(land ?
                Spacecraft.SpacecraftState.DOCKED :
                Spacecraft.SpacecraftState.ORBITING);

        try {
            double arrivalTime = departureTime + transferTime;
            double currentTime = spacecraft.getSystem().getCurrentTime();
            OrbitalState futureTarget = target.stateAt(arrivalTime, currentTime);

            Vector3D departurePosition = spacecraft.getPosition();
            Vector3D arrivalPosition = futureTarget.position();
            double mu = target.centerBody().getGravitationalParameter();

            LambertSolution solution = solveLambert(
                    departurePosition, arrivalPosition, transferTime, mu);

            if (solution == null) {
                itinerary.setInfeasible(
                        "Lambert solver did not converge for this geometry " +
                                "(transfer angle near 0 or 180 degrees)");
                return itinerary;
            }

            Vector3D departureDeltaV = solution.departureVelocity().subtract(spacecraft.getVelocity());

            itinerary.addBurn(new ScheduledBurn(
                    "lambert-departure",
                    departureTime,
                    departureDeltaV,
                    "Lambert Transfer Departure"
            ));

            // True heliocentric capture: difference between destination velocity
            // and Lambert arrival velocity (not an approximation)
            Vector3D heliocentricCaptureDeltaV = futureTarget.velocity()
                    .subtract(solution.arrivalVelocity());

            if (destinationBody instanceof Gravitational gravitationalDest) {
                double approachSpeed = solution.arrivalVelocity()
                        .subtract(futureTarget.velocity()).magnitude();
                double insertionDeltaV = calculateOrbitInsertionDeltaV(
                        gravitationalDest, approachSpeed);
                double totalArrivalMagnitude =
                        heliocentricCaptureDeltaV.magnitude() + insertionDeltaV;

                Vector3D arrivalDirection = heliocentricCaptureDeltaV.magnitude() > 1e-10
                        ? heliocentricCaptureDeltaV.normalize()
                        : Vector3D.UNIT_X;

                itinerary.addBurn(new ScheduledBurn(
                        "lambert-arrival",
                        arrivalTime,
                        arrivalDirection.multiply(totalArrivalMagnitude),
                        "Lambert Transfer Arrival"
                ));
            } else {
                itinerary.addBurn(new ScheduledBurn(
                        "lambert-arrival",
                        arrivalTime,
                        heliocentricCaptureDeltaV,
                        "Lambert Transfer Arrival"
                ));
            }

            if (land && destinationBody instanceof Gravitational gravitationalDest) {
                addLandingBurn(itinerary, gravitationalDest, arrivalTime);
            }

            itinerary.validateAgainstSpacecraft(spacecraft);

        } catch (Exception e) {
            itinerary.setInfeasible("Lambert transfer calculation failed: " + e.getMessage());
        }

        return itinerary;
    }

    /**
     * Find the shortest transfer time within the spacecraft's full delta-V budget.
     * <p>
     * Performs a binary search over transfer times between minTransferTime and
     * maxTransferTime. At each candidate time, the required delta-V is computed
     * via Lambert. The search finds the shortest transfer time at which the
     * required delta-V does not exceed the spacecraft's available delta-V.
     * <p>
     * Because delta-V vs transfer time is not monotonic (it has a minimum
     * somewhere in the search range), the search works as follows:
     * <p>
     * 1. Sample the range at SEARCH_SAMPLES points to find the minimum
     * delta-V region and the two boundary regions where delta-V exceeds
     * the budget.
     * 2. Binary search on the short-time boundary (left of the minimum)
     * to find the shortest feasible time.
     * <p>
     * Returns null if no feasible transfer exists within the search range.
     *
     * @param spacecraft      the spacecraft making the transfer
     * @param targetOrbit     target orbit snapshot
     * @param destinationBody destination orbiter
     * @param land            true to dock, false to orbit
     * @param departureTime   absolute simulation time of departure
     * @param minTransferTime lower bound for search (seconds)
     * @param maxTransferTime upper bound for search (seconds)
     * @return feasible itinerary using full delta-V budget, or null if none found
     * <p>
     * Generated by Claude (Sonnet 4.5)
     */
    private static Itinerary buildMaxDeltaVTransfer(
            Spacecraft spacecraft,
            Orbit targetOrbit,
            Orbiter destinationBody,
            boolean land,
            double departureTime,
            double minTransferTime,
            double maxTransferTime) {

        double availableDeltaV = spacecraft.getAvailableDeltaV();

        // Sample the range to locate the minimum delta-V region and feasibility boundaries
        final int SEARCH_SAMPLES = 20;
        double[] sampleTimes = new double[SEARCH_SAMPLES];
        double[] sampleDeltaVs = new double[SEARCH_SAMPLES];
        double timeStep = (maxTransferTime - minTransferTime) / (SEARCH_SAMPLES - 1);

        for (int i = 0; i < SEARCH_SAMPLES; i++) {
            sampleTimes[i] = minTransferTime + i * timeStep;
            Itinerary candidate = buildLambertTransfer(
                    spacecraft, targetOrbit, destinationBody,
                    land, departureTime, sampleTimes[i]);
            sampleDeltaVs[i] = candidate.getTotalDeltaV();
        }

        // Find the shortest time at which delta-V is within budget.
        // Scan left-to-right; the first sample at or below availableDeltaV
        // gives the right boundary for a short-time binary search.
        double searchLow = -1.0;
        double searchHigh = -1.0;

        for (int i = 0; i < SEARCH_SAMPLES - 1; i++) {
            boolean currentFeasible = sampleDeltaVs[i] <= availableDeltaV;
            boolean nextFeasible = sampleDeltaVs[i + 1] <= availableDeltaV;

            if (!currentFeasible && nextFeasible) {
                // Feasibility boundary found: delta-V crosses into budget here
                searchLow = sampleTimes[i];
                searchHigh = sampleTimes[i + 1];
                break;
            }
            if (currentFeasible) {
                // Already feasible at the start of the range
                searchLow = minTransferTime;
                searchHigh = sampleTimes[i];
                break;
            }
        }

        if (searchLow < 0) {
            // No feasible transfer found in the sampled range
            return null;
        }

        // Binary search to refine the shortest feasible transfer time
        for (int iteration = 0; iteration < MAX_DELTAV_SEARCH_ITERATIONS; iteration++) {
            double midTransferTime = (searchLow + searchHigh) / 2.0;
            Itinerary candidate = buildLambertTransfer(
                    spacecraft, targetOrbit, destinationBody,
                    land, departureTime, midTransferTime);

            if (candidate.getTotalDeltaV() <= availableDeltaV) {
                searchHigh = midTransferTime;
            } else {
                searchLow = midTransferTime;
            }
        }

        // Build and return the final itinerary at the converged transfer time
        return buildLambertTransfer(
                spacecraft, targetOrbit, destinationBody,
                land, departureTime, searchHigh);
    }

    // ==================== SELECTION ====================

    /**
     * Select the best transfer option based on the optimization goal.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static TransferOption selectBestTransfer(
            List<TransferOption> options,
            OptimizationGoal goal) {

        if (options.isEmpty()) {
            return null;
        }

        return switch (goal) {
            case MINIMUM_TIME -> options.stream()
                    .min(Comparator.comparingDouble(opt ->
                            opt.getItinerary().getEstimatedDuration()))
                    .orElse(null);

            case MINIMUM_DELTAV -> options.stream()
                    .min(Comparator.comparingDouble(opt ->
                            opt.getItinerary().getTotalDeltaV()))
                    .orElse(null);

            case BALANCED -> options.stream()
                    .min(Comparator.comparingDouble(TransferOption::getEfficiencyScore))
                    .orElse(null);
        };
    }

    // ==================== PRIVATE HELPERS ====================

    /**
     * Calculate the delta-V required to capture from a hyperbolic approach into
     * a standard circular orbit around the destination body.
     *
     * The spacecraft arrives with hyperbolic excess velocity v_infinity relative
     * to the destination. At periapsis of the hyperbolic approach (set to the
     * standard orbital radius):
     *
     *   v_hyperbolic = sqrt(v_infinity^2 + 2 * mu_dest / r_capture)
     *   v_circular   = sqrt(mu_dest / r_capture)
     *   delta_v      = v_hyperbolic - v_circular  (retrograde deceleration)
     *
     * @param destination  destination gravitational body
     * @param v_infinity   hyperbolic excess speed at arrival (m/s)
     * @return delta-V magnitude required for capture (m/s), always positive
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static double calculateOrbitInsertionDeltaV(
            Gravitational destination,
            double v_infinity) {

        double muDestination = destination.getGravitationalParameter();
        double captureRadius = destination.getStandardOrbitalRadius();

        double v_hyperbolic_periapsis = Math.sqrt(
                v_infinity * v_infinity + 2.0 * muDestination / captureRadius);
        double v_circular_capture = Math.sqrt(muDestination / captureRadius);

        return v_hyperbolic_periapsis - v_circular_capture;
    }

    /**
     * Add a landing burn to the itinerary after arrival at a gravitational body.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static void addLandingBurn(
            Itinerary itinerary,
            Gravitational destination,
            double arrivalTime) {

        double orbitalRadius = destination.getStandardOrbitalRadius();
        double landingDeltaV = destination.getEscapeVelocityFromRadius(orbitalRadius);

        double descentTime = destination.getStandardOrbitalAltitude() * 2.0 /
                destination.getSurfaceEscapeVelocity();

        itinerary.addBurn(new ScheduledBurn(
                "landing",
                arrivalTime + descentTime,
                Vector3D.ZERO.subtract(
                        destination.getStandardCircularOrbitVector()
                                .subtract(destination.getVelocity())
                ).multiply(landingDeltaV /
                        destination.getStandardCircularOrbitVector().magnitude()),
                "Landing at " + destination.getId()
        ));
    }

    /**
     * Solve Lambert's problem using the universal variable method.
     *
     * Finds the departure and arrival velocity vectors for a conic arc
     * connecting position r1 to position r2 in the given time of flight.
     * Handles all transfer geometries including near-0 and near-180 degree
     * transfer angles.
     *
     * Algorithm: universal variable iteration (Bate, Mueller, White formulation)
     * with Stumpff c2/c3 functions for numerical stability across conic types.
     *
     * @param r1           departure position vector (m)
     * @param r2           arrival position vector (m)
     * @param transferTime time of flight (s), must be positive
     * @param mu           gravitational parameter of central body (m^3/s^2)
     * @return LambertSolution containing departure and arrival velocity vectors,
     *         or null if no solution converged within tolerance
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static LambertSolution solveLambert(
            Vector3D r1,
            Vector3D r2,
            double transferTime,
            double mu) {

        double r1Magnitude = r1.magnitude();
        double r2Magnitude = r2.magnitude();

        // Determine transfer angle (0 to 2*pi)
        double cosTransferAngle = r1.dot(r2) / (r1Magnitude * r2Magnitude);
        cosTransferAngle = Math.max(-1.0, Math.min(1.0, cosTransferAngle));

        // Use cross product z-component to determine orbit direction
        double crossZ = r1.getX() * r2.getY() - r1.getY() * r2.getX();
        double transferAngle = crossZ >= 0.0
                ? Math.acos(cosTransferAngle)
                : 2.0 * Math.PI - Math.acos(cosTransferAngle);

        if (transferAngle < 1e-10 || Math.abs(transferAngle - Math.PI) < 1e-10) {
            // Degenerate geometry: collinear vectors, indeterminate plane
            return null;
        }

        // A parameter (positive for prograde transfers)
        double sqrtArg = r1Magnitude * r2Magnitude * (1.0 + cosTransferAngle);
        if (sqrtArg < 1e-20) {
            return null;
        }
        double universalA = Math.signum(Math.sin(transferAngle)) * Math.sqrt(sqrtArg);

        // Universal variable iteration: find z such that time-of-flight matches
        double zLow = -4.0 * Math.PI * Math.PI;
        double zHigh = 4.0 * Math.PI * Math.PI;
        double universalZ = 0.0;

        final int MAX_ITERATIONS = 200;
        final double CONVERGENCE_TOLERANCE = 1e-6;

        for (int iteration = 0; iteration < MAX_ITERATIONS; iteration++) {
            double zMid = (zLow + zHigh) / 2.0;

            double[] stumpff = stumpffFunctions(zMid);
            double c2 = stumpff[0];
            double c3 = stumpff[1];

            double sqrtY = r1Magnitude + r2Magnitude
                    + universalA * (zMid * c3 - 1.0) / Math.sqrt(c2);
            if (universalA > 0.0 && sqrtY < 0.0) {
                zLow = zMid;
                continue;
            }

            double universalY = Math.max(sqrtY, 0.0);
            double universalX = Math.sqrt(universalY / c2);
            double computedTime = (Math.pow(universalX, 3) * c3
                    + universalA * Math.sqrt(universalY)) / Math.sqrt(mu);

            if (Math.abs(computedTime - transferTime) < CONVERGENCE_TOLERANCE) {
                universalZ = zMid;
                break;
            }

            if (computedTime < transferTime) {
                zLow = zMid;
            } else {
                zHigh = zMid;
            }
            universalZ = zMid;
        }

        // Recover Lagrange f and g coefficients
        double[] stumpff = stumpffFunctions(universalZ);
        double c2 = stumpff[0];
        double c3 = stumpff[1];

        double universalY = r1Magnitude + r2Magnitude
                + universalA * (universalZ * c3 - 1.0) / Math.sqrt(c2);
        if (universalY < 0.0) {
            return null;
        }

        double universalX = Math.sqrt(universalY / c2);

        double lagrangeF = 1.0 - universalY / r1Magnitude;
        double lagrangeG = universalA * Math.sqrt(universalY / mu);
        double lagrangeGDot = 1.0 - universalY / r2Magnitude;

        if (Math.abs(lagrangeG) < 1e-20) {
            return null;
        }

        // Departure and arrival velocities from Lagrange coefficients
        // v1 = (r2 - f*r1) / g
        // v2 = (gDot*r2 - r1) / g    [rearranged from r2 = f*r1 + g*v1]
        Vector3D departureVelocity = r2.subtract(r1.multiply(lagrangeF)).divide(lagrangeG);
        Vector3D arrivalVelocity = r2.multiply(lagrangeGDot).subtract(r1).divide(lagrangeG);

        return new LambertSolution(departureVelocity, arrivalVelocity);
    }

    /**
     * Stumpff functions c2 and c3 used in the universal variable Lambert solver.
     *
     * c2(z) and c3(z) are entire functions that provide numerical stability
     * across elliptic (z > 0), parabolic (z = 0), and hyperbolic (z < 0) trajectories.
     *
     * For z > 0 (elliptic):
     *   c2 = (1 - cos(sqrt(z))) / z
     *   c3 = (sqrt(z) - sin(sqrt(z))) / sqrt(z^3)
     *
     * For z < 0 (hyperbolic):
     *   c2 = (1 - cosh(sqrt(-z))) / z
     *   c3 = (sinh(sqrt(-z)) - sqrt(-z)) / sqrt((-z)^3)
     *
     * For z near 0 (parabolic): series expansion
     *   c2 = 1/2 - z/24 + z^2/720 - ...
     *   c3 = 1/6 - z/120 + z^2/5040 - ...
     *
     * @param z universal variable squared
     * @return double[]{c2, c3}
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static double[] stumpffFunctions(double z) {
        if (z > 1e-6) {
            double sqrtZ = Math.sqrt(z);
            double c2 = (1.0 - Math.cos(sqrtZ)) / z;
            double c3 = (sqrtZ - Math.sin(sqrtZ)) / (sqrtZ * z);
            return new double[]{c2, c3};
        } else if (z < -1e-6) {
            double sqrtNegZ = Math.sqrt(-z);
            double c2 = (1.0 - Math.cosh(sqrtNegZ)) / z;
            double c3 = (Math.sinh(sqrtNegZ) - sqrtNegZ) / (sqrtNegZ * (-z));
            return new double[]{c2, c3};
        } else {
            // Series expansion near z = 0
            double c2 = 0.5 - z / 24.0 + z * z / 720.0;
            double c3 = 1.0 / 6.0 - z / 120.0 + z * z / 5040.0;
            return new double[]{c2, c3};
        }
    }

    /**
     * Departure and arrival velocity vectors from a Lambert solution.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private record LambertSolution(Vector3D departureVelocity, Vector3D arrivalVelocity) {}


    /**
     * Calculate minimum transfer time between two orbits.
     *
     * Returns the Hohmann half-period, which is the theoretical minimum
     * time for a two-burn transfer between circular coplanar orbits.
     * Used as the baseline time-of-flight for Lambert multiplier selection
     * and as the lower bound for the max delta-V search.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static double calculateMinimumTransferTime(Orbit origin, Orbit target) {
        double transferSemiMajorAxis = (origin.semiMajorAxis() + target.semiMajorAxis()) / 2.0;
        double mu = origin.centerBody().getGravitationalParameter();
        return Math.PI * Math.sqrt(Math.pow(transferSemiMajorAxis, 3) / mu);
    }
}