package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.NonNull;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Transfer planning using Lambert-based trajectory solving.
 *
 * Lambert's problem finds the velocity vectors required to travel between two
 * position vectors in a given time. This correctly accounts for the actual
 * positions of origin and destination bodies at departure and arrival,
 * which orbit-radius-only approaches (Hohmann) cannot do.
 *
 * Hohmann and bi-elliptic transfers are orbit-to-orbit maneuvers that require
 * precise phase alignment between the two bodies. Lambert subsumes Hohmann:
 * when transfer angle is 180 degrees, orbits are circular and coplanar, and
 * time of flight equals the Hohmann period, Lambert produces the identical
 * burn vectors. Lambert is therefore retained as the sole interplanetary
 * transfer strategy.
 *
 * Bi-elliptic transfers are fundamentally three-burn, two-arc maneuvers and
 * cannot be expressed as a single Lambert arc. They are more efficient than
 * Hohmann only when the radius ratio exceeds approximately 11.94 (relevant
 * for outer planet transfers). Reserved for future implementation.
 *
 * Transfer strategies offered:
 *   LAMBERT_FAST      - 1.0x minimum transfer time; fastest, highest delta-V
 *   LAMBERT_BALANCED  - 1.5x minimum transfer time; moderate tradeoff
 *   LAMBERT_EFFICIENT - 2.5x minimum transfer time; slower, lower delta-V
 *   LAMBERT_MAX_DELTAV - uses full available spacecraft delta-V budget;
 *                        arrives as soon as physically possible given fuel
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class TransferPlanner {

    /**
     * Upper bound for transfer time search as a multiple of the minimum
     * transfer time (Hohmann half-period). The max delta-V search will not
     * consider trajectories longer than this limit.
     *
     * Default is 5.0. Set higher for missions to fast inner bodies or slow
     * outer planets where longer transfer windows may be acceptable.
     * Example: TransferPlanner.maxTransferTimeMultiplier = 100.0;
     */
    public static double maxTransferTimeMultiplier = 5.0;

    /**
     * Number of iterations for the binary search used in the max delta-V
     * transfer time search. Higher values improve accuracy at the cost of
     * additional Lambert solves. 64 iterations gives sub-second precision
     * for typical solar system transfer times.
     */
    private static final int MAX_DELTAV_SEARCH_ITERATIONS = 64;

    public enum TransferStrategy {
        LAMBERT_FAST,
        LAMBERT_BALANCED,
        LAMBERT_EFFICIENT,
        LAMBERT_MAX_DELTAV
    }

    public enum OptimizationGoal {
        MINIMUM_TIME,
        MINIMUM_DELTAV,
        BALANCED
    }

    @Getter
    public static class TransferOption {
        private final TransferStrategy strategy;
        private final Itinerary itinerary;
        private final double efficiencyScore;

        public TransferOption(TransferStrategy strategy, @NonNull Itinerary itinerary) {
            this.strategy = strategy;
            this.itinerary = itinerary;

            double totalDeltaV = itinerary.getTotalDeltaV();
            this.efficiencyScore = totalDeltaV > 0
                    ? itinerary.getEstimatedDuration() / totalDeltaV
                    : Double.POSITIVE_INFINITY;
        }
    }

    // ==================== TRANSFER OPTION GENERATION ====================

    /**
     * Generate all feasible transfer options between two orbiting bodies.
     *
     * Four Lambert transfers are attempted:
     *
     *   LAMBERT_FAST        1.0x minimum transfer time
     *   LAMBERT_BALANCED    1.5x minimum transfer time
     *   LAMBERT_EFFICIENT   2.5x minimum transfer time
     *   LAMBERT_MAX_DELTAV  shortest transfer time achievable within the
     *                       spacecraft's full available delta-V budget,
     *                       searched up to maxTransferTimeMultiplier * minimum
     *
     * The minimum transfer time is the Hohmann half-period. The 1.0x Lambert
     * solution converges to the Hohmann solution when planetary phase conditions
     * are met.
     *
     * All feasible options are returned sorted by efficiency score (duration /
     * delta-V). The optimizer then selects from this combined pool, so a fixed
     * multiplier option that happens to be superior to the max delta-V solution
     * for the current geometry will be preferred automatically.
     *
     * @param spacecraft    the spacecraft making the transfer
     * @param origin        starting body
     * @param destination   target body
     * @param land          true to dock at destination, false to orbit
     * @param departureTime absolute simulation time to begin transfer
     * @return list of feasible transfer options, sorted by efficiency score
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static List<TransferOption> generateTransferOptions(
            Spacecraft spacecraft,
            Dockable origin,
            Orbiter destination,
            boolean land,
            double departureTime) {

        List<TransferOption> options = new ArrayList<>();

        Orbit originOrbit = origin.snapshotOrbit();
        Orbit targetOrbit = destination.snapshotOrbit();

        double minTransferTime = calculateMinimumTransferTime(originOrbit, targetOrbit);

        // Fixed time-of-flight options
        double[] multipliers = {1.0, 1.5, 2.5};
        TransferStrategy[] fixedStrategies = {
                TransferStrategy.LAMBERT_FAST,
                TransferStrategy.LAMBERT_BALANCED,
                TransferStrategy.LAMBERT_EFFICIENT
        };

        for (int i = 0; i < multipliers.length; i++) {
            double transferTime = minTransferTime * multipliers[i];
            Itinerary lambert = buildLambertTransfer(
                    spacecraft, targetOrbit, destination,
                    land, departureTime, transferTime);

            if (lambert.isFeasible()) {
                options.add(new TransferOption(fixedStrategies[i], lambert));
            }
        }

        // Max delta-V option: find shortest transfer time within fuel budget
        double maxTransferTime = minTransferTime * maxTransferTimeMultiplier;
        Itinerary maxDeltaVTransfer = buildMaxDeltaVTransfer(
                spacecraft, targetOrbit, destination,
                land, departureTime, minTransferTime, maxTransferTime);
        if (maxDeltaVTransfer != null && maxDeltaVTransfer.isFeasible()) {
            options.add(new TransferOption(TransferStrategy.LAMBERT_MAX_DELTAV, maxDeltaVTransfer));
        }

        options.sort(Comparator.comparingDouble(TransferOption::getEfficiencyScore));
        return options;
    }

    // ==================== TRANSFER BUILDERS ====================

    /**
     * Build a Lambert transfer with the specified time of flight.
     *
     * The departure burn changes velocity from the current spacecraft velocity
     * to the Lambert solution departure velocity. The arrival burn has two
     * components:
     *
     * 1. For non-Gravitational destinations: match the destination's heliocentric
     *    velocity (heliocentric capture only).
     * 2. For Gravitational destinations: compute orbit insertion delta-V using
     *    the hyperbolic excess speed at arrival, then apply in the direction that
     *    opposes the approach velocity. This fully accounts for heliocentric
     *    capture and planetary orbit insertion in a single burn.
     *
     * The orbit insertion formula:
     *   v_infinity    = |Lambert arrival velocity - destination heliocentric velocity|
     *   v_hyperbolic  = sqrt(v_infinity^2 + 2 * mu_dest / r_capture)
     *   v_circular    = sqrt(mu_dest / r_capture)
     *   delta_v_total = v_hyperbolic - v_circular  (deceleration at periapsis)
     *
     * @param spacecraft      the spacecraft making the transfer
     * @param target          target orbit (heliocentric)
     * @param destinationBody destination orbiter
     * @param land            true to dock, false to orbit
     * @param departureTime   absolute simulation time of departure burn
     * @param transferTime    duration of transfer in seconds
     * @return itinerary with departure and arrival burns, feasibility validated
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static Itinerary buildLambertTransfer(
            Spacecraft spacecraft,
            Orbit target,
            Orbiter destinationBody,
            boolean land,
            double departureTime,
            double transferTime) {

        Itinerary itinerary = new Itinerary(departureTime);
        itinerary.setDestination(destinationBody);
        itinerary.setFinalState(land
                ? Spacecraft.SpacecraftState.DOCKED
                : Spacecraft.SpacecraftState.ORBITING);

        try {
            double arrivalTime = departureTime + transferTime;
            double currentTime = spacecraft.getSystem().getCurrentTime();
            OrbitalState futureTarget = target.stateAt(arrivalTime, currentTime);

            Vector3D departurePosition = spacecraft.getPosition();
            Vector3D arrivalPosition = futureTarget.position();
            double mu = target.centerBody().getGravitationalParameter();

            LambertUtility.LambertSolution solution = LambertUtility.solveLambert(
                    departurePosition, arrivalPosition, transferTime, mu);

            if (solution == null) {
                itinerary.setInfeasible(
                        "Lambert solver did not converge for this geometry " +
                                "(transfer angle near 0 or 180 degrees)");
                return itinerary;
            }

            // Departure burn: accelerate from current velocity to Lambert departure velocity
            Vector3D departureDeltaV = solution.departureVelocity()
                    .subtract(spacecraft.getVelocity());

            itinerary.addBurn(new ScheduledBurn(
                    "lambert-departure",
                    departureTime,
                    departureDeltaV,
                    "Lambert Transfer Departure"
            ));

            if (destinationBody instanceof Gravitational gravitationalDest) {
                // Arrival burn: single retrograde deceleration that captures into
                // the destination's standard circular orbit.
                //
                // v_infinity is the hyperbolic excess speed relative to the destination.
                // calculateOrbitInsertionDeltaV computes the full periapsis burn needed
                // to go from hyperbolic approach to circular orbit. This is the only
                // arrival burn needed - it subsumes the heliocentric capture.
                //
                // Direction: oppose the approach velocity (retrograde).
                double v_infinity = solution.arrivalVelocity()
                        .subtract(futureTarget.velocity()).magnitude();
                double insertionDeltaV = calculateOrbitInsertionDeltaV(
                        gravitationalDest, v_infinity);

                // Approach direction: Lambert arrival velocity minus destination velocity
                Vector3D approachDirection = solution.arrivalVelocity()
                        .subtract(futureTarget.velocity());
                Vector3D arrivalBurnDirection = approachDirection.magnitude() > 1e-10
                        ? approachDirection.normalize().multiply(-1.0)
                        : Vector3D.UNIT_X.multiply(-1.0);

                itinerary.addBurn(new ScheduledBurn(
                        "lambert-arrival",
                        arrivalTime,
                        arrivalBurnDirection.multiply(insertionDeltaV),
                        "Lambert Transfer Arrival (orbit insertion)"
                ));

                if (land) {
                    addLandingBurn(itinerary, gravitationalDest, arrivalTime);
                }
            } else {
                // Non-gravitational destination: match heliocentric velocity only
                Vector3D heliocentricCaptureDeltaV = futureTarget.velocity()
                        .subtract(solution.arrivalVelocity());

                itinerary.addBurn(new ScheduledBurn(
                        "lambert-arrival",
                        arrivalTime,
                        heliocentricCaptureDeltaV,
                        "Lambert Transfer Arrival"
                ));
            }

            itinerary.validateAgainstSpacecraft(spacecraft);

        } catch (Exception e) {
            itinerary.setInfeasible("Lambert transfer calculation failed: " + e.getMessage());
        }

        return itinerary;
    }

    /**
     * Find the shortest transfer time within the spacecraft's full delta-V budget.
     *
     * Performs a binary search over transfer times between minTransferTime and
     * maxTransferTime. At each candidate time, the required delta-V is computed
     * via Lambert. The search finds the shortest transfer time at which the
     * required delta-V does not exceed the spacecraft's available delta-V.
     *
     * Because delta-V vs transfer time is not monotonic (it has a minimum
     * somewhere in the search range), the search works as follows:
     *
     * 1. Sample the range at SEARCH_SAMPLES points to find the minimum
     *    delta-V region and the two boundary regions where delta-V exceeds
     *    the budget.
     * 2. Binary search on the short-time boundary (left of the minimum)
     *    to find the shortest feasible time.
     *
     * Returns null if no feasible transfer exists within the search range.
     *
     * @param spacecraft      the spacecraft making the transfer
     * @param targetOrbit     target orbit snapshot
     * @param destinationBody destination orbiter
     * @param land            true to dock, false to orbit
     * @param departureTime   absolute simulation time of departure
     * @param minTransferTime lower bound for search (seconds)
     * @param maxTransferTime upper bound for search (seconds)
     * @return feasible itinerary using full delta-V budget, or null if none found
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static Itinerary buildMaxDeltaVTransfer(
            Spacecraft spacecraft,
            Orbit targetOrbit,
            Orbiter destinationBody,
            boolean land,
            double departureTime,
            double minTransferTime,
            double maxTransferTime) {

        double availableDeltaV = spacecraft.getAvailableDeltaV();

        // Sample the range to locate the minimum delta-V region and feasibility boundaries
        final int SEARCH_SAMPLES = 20;
        double[] sampleTimes = new double[SEARCH_SAMPLES];
        double[] sampleDeltaVs = new double[SEARCH_SAMPLES];
        double timeStep = (maxTransferTime - minTransferTime) / (SEARCH_SAMPLES - 1);

        for (int i = 0; i < SEARCH_SAMPLES; i++) {
            sampleTimes[i] = minTransferTime + i * timeStep;
            Itinerary candidate = buildLambertTransfer(
                    spacecraft, targetOrbit, destinationBody,
                    land, departureTime, sampleTimes[i]);
            sampleDeltaVs[i] = candidate.getTotalDeltaV();
        }

        // Find the shortest time at which delta-V is within budget.
        // Scan left-to-right; the first sample at or below availableDeltaV
        // gives the right boundary for a short-time binary search.
        double searchLow = -1.0;
        double searchHigh = -1.0;

        for (int i = 0; i < SEARCH_SAMPLES - 1; i++) {
            boolean currentFeasible = sampleDeltaVs[i] <= availableDeltaV;
            boolean nextFeasible = sampleDeltaVs[i + 1] <= availableDeltaV;

            if (!currentFeasible && nextFeasible) {
                // Feasibility boundary found: delta-V crosses into budget here
                searchLow = sampleTimes[i];
                searchHigh = sampleTimes[i + 1];
                break;
            }
            if (currentFeasible) {
                // Already feasible at the start of the range
                searchLow = minTransferTime;
                searchHigh = sampleTimes[i];
                break;
            }
        }

        if (searchLow < 0) {
            // No feasible transfer found in the sampled range
            return null;
        }

        // Binary search to refine the shortest feasible transfer time
        for (int iteration = 0; iteration < MAX_DELTAV_SEARCH_ITERATIONS; iteration++) {
            double midTransferTime = (searchLow + searchHigh) / 2.0;
            Itinerary candidate = buildLambertTransfer(
                    spacecraft, targetOrbit, destinationBody,
                    land, departureTime, midTransferTime);

            if (candidate.getTotalDeltaV() <= availableDeltaV) {
                searchHigh = midTransferTime;
            } else {
                searchLow = midTransferTime;
            }
        }

        // Build and return the final itinerary at the converged transfer time
        return buildLambertTransfer(
                spacecraft, targetOrbit, destinationBody,
                land, departureTime, searchHigh);
    }

    // ==================== SELECTION ====================

    /**
     * Select the best transfer option based on the optimization goal.
     *
     * MINIMUM_TIME:  shortest estimated duration
     * MINIMUM_DELTAV: lowest total delta-V requirement
     * BALANCED:      lowest efficiency score (duration / delta-V)
     *
     * Returns null if the options list is empty.
     *
     * @param options list of feasible transfer options
     * @param goal    optimization criterion
     * @return best matching option, or null if list is empty
     *
     * Generated by Claude (Sonnet 4.5)
     */
    public static TransferOption selectBestTransfer(
            List<TransferOption> options,
            OptimizationGoal goal) {

        if (options.isEmpty()) {
            return null;
        }

        return switch (goal) {
            case MINIMUM_TIME -> options.stream()
                    .min(Comparator.comparingDouble(opt ->
                            opt.getItinerary().getEstimatedDuration()))
                    .orElse(null);

            case MINIMUM_DELTAV -> options.stream()
                    .min(Comparator.comparingDouble(opt ->
                            opt.getItinerary().getTotalDeltaV()))
                    .orElse(null);

            case BALANCED -> options.stream()
                    .min(Comparator.comparingDouble(TransferOption::getEfficiencyScore))
                    .orElse(null);
        };
    }

    // ==================== PRIVATE HELPERS ====================

    /**
     * Calculate the delta-V required to capture from a hyperbolic approach into
     * a standard circular orbit around the destination body.
     *
     * The spacecraft arrives with hyperbolic excess velocity v_infinity relative
     * to the destination. At periapsis of the hyperbolic approach (set to the
     * standard orbital radius):
     *
     *   v_hyperbolic = sqrt(v_infinity^2 + 2 * mu_dest / r_capture)
     *   v_circular   = sqrt(mu_dest / r_capture)
     *   delta_v      = v_hyperbolic - v_circular  (retrograde deceleration)
     *
     * This single burn fully accounts for both heliocentric capture and
     * insertion into the destination's standard circular orbit. Do not add
     * a separate heliocentric match delta-V on top of this value.
     *
     * @param destination  destination gravitational body
     * @param v_infinity   hyperbolic excess speed at arrival (m/s)
     * @return delta-V magnitude required for capture (m/s), always positive
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static double calculateOrbitInsertionDeltaV(
            Gravitational destination,
            double v_infinity) {

        double muDestination = destination.getGravitationalParameter();
        double captureRadius = destination.getStandardOrbitalRadius();

        double v_hyperbolic_periapsis = Math.sqrt(
                v_infinity * v_infinity + 2.0 * muDestination / captureRadius);
        double v_circular_capture = Math.sqrt(muDestination / captureRadius);

        return v_hyperbolic_periapsis - v_circular_capture;
    }

    /**
     * Add a landing burn to the itinerary after arrival at a gravitational body.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static void addLandingBurn(
            Itinerary itinerary,
            Gravitational destination,
            double arrivalTime) {

        double orbitalRadius = destination.getStandardOrbitalRadius();
        double landingDeltaV = destination.getEscapeVelocityFromRadius(orbitalRadius);

        double descentTime = destination.getStandardOrbitalAltitude() * 2.0
                / destination.getSurfaceEscapeVelocity();

        itinerary.addBurn(new ScheduledBurn(
                "landing",
                arrivalTime + descentTime,
                Vector3D.ZERO.subtract(
                        destination.getStandardCircularOrbitVector()
                                .subtract(destination.getVelocity())
                ).multiply(landingDeltaV
                        / destination.getStandardCircularOrbitVector().magnitude()),
                "Landing at " + destination.getId()
        ));
    }

    /**
     * Calculate minimum transfer time between two orbits.
     *
     * Returns the Hohmann half-period, which is the theoretical minimum
     * time for a two-burn transfer between circular coplanar orbits.
     * Used as the baseline time-of-flight for Lambert multiplier selection
     * and as the lower bound for the max delta-V search.
     *
     * Generated by Claude (Sonnet 4.5)
     */
    private static double calculateMinimumTransferTime(Orbit origin, Orbit target) {
        double transferSemiMajorAxis = (origin.semiMajorAxis() + target.semiMajorAxis()) / 2.0;
        double mu = origin.centerBody().getGravitationalParameter();
        return Math.PI * Math.sqrt(Math.pow(transferSemiMajorAxis, 3) / mu);
    }
}