package com.kaymlyn.planeteater.simulation.celestial;

import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.PlanetPattern;
import com.kaymlyn.planeteater.simulation.vehicles.CentralMind;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import com.kaymlyn.planeteater.simulation.vehicles.VehicleFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for OrbitalSystem.
 *
 * Tests cover:
 * - Construction and initial state
 * - Body registration (addBody, removeBody, getBody, getOrbiter)
 * - Spacecraft registration and deregistration
 * - Orbit placement (circular and elliptical) with physics validation
 * - Simulation stepping (stepVerlet, advance)
 * - Gravitational acceleration direction and magnitude
 * - Time tracking
 *
 * Physics reference:
 *   Circular orbit speed:   v = sqrt(GM / r)
 *   Gravitational accel:    g = GM / r^2
 *   Verlet position update: x(t+dt) = x(t) + v(t)*dt + 0.5*a(t)*dt^2
 *
 * OrbitalSystem is tested with real integration (not mocked), per the design
 * decision recorded in BACKLOG.md (resolved 2026-02-17).
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("OrbitalSystem Tests")
public class OrbitalSystemTest {

    private static final double TIME_STEP_S         = 3600.0;      // 1 hour in seconds
    private static final double ONE_AU_M            = PhysicsConstants.AU;

    // Tolerances
    // Position tolerance for single-step tests: generous relative to orbital scale
    private static final double POSITION_TOLERANCE_M  = 1e6;       // 1000 km
    // Velocity tolerance: generous relative to typical orbital speeds (~30 km/s at 1 AU)
    private static final double VELOCITY_TOLERANCE_MS  = 100.0;    // 100 m/s
    // Acceleration tolerance: relative
    private static final double ACCEL_RELATIVE_TOLERANCE = 1e-3;
    // Time tolerance: sub-second (floating point accumulation only)
    private static final double TIME_TOLERANCE_S      = 1e-6;

    private CelestialBodyFactory factory;
    private OrbitalSystem system;
    private Star centralStar;

    @BeforeEach
    void setUp() {
        centralStar = CelestialBodyFactory.createMainSequenceStar("TestStar", 1.0);
        factory = new CelestialBodyFactory(centralStar, TIME_STEP_S);
        system = factory.getSystem();
    }

    // ==================== CONSTRUCTION ====================

    @Test
    @DisplayName("construction: central star is in bodyMap after initialization")
    void testCentralStarIsInBodyMap() {
        CelestialBody retrieved = system.getBody(system.getCentralStar().getId());

        assertNotNull(retrieved,
                "Central star must be present in bodyMap after OrbitalSystem construction");
    }

    @Test
    @DisplayName("construction: initial currentTime is zero")
    void testInitialCurrentTimeIsZero() {
        assertEquals(0.0, system.getCurrentTime(), TIME_TOLERANCE_S,
                "currentTime must be zero immediately after construction");
    }

    @Test
    @DisplayName("construction: initial timeStep matches the value supplied at construction")
    void testTimeStepMatchesConstructionParameter() {
        assertEquals(TIME_STEP_S, system.getTimeStep(), TIME_TOLERANCE_S,
                "timeStep must match the value supplied to CelestialBodyFactory");
    }

    @Test
    @DisplayName("construction: physicsObjects is non-empty (star is a CelestialBody and registered)")
    void testPhysicsObjectsNotEmptyAfterConstruction() {
        assertFalse(system.getBodyMap().isEmpty(),
                "physicsObjects must contain at least the central star after construction");
    }

    // ==================== BODY REGISTRATION ====================

    @Test
    @DisplayName("addBody (via createPlanetFromPattern): planet appears in bodyMap")
    void testAddedPlanetIsInBodyMap() {
        Planet earth = factory.createPlanetFromPattern(
                "Earth", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        assertNotNull(system.getBody("Earth"),
                "Planet must be retrievable from bodyMap by id after creation");
    }

    @Test
    @DisplayName("addBody (via createPlanetFromPattern): planet appears in orbiters map")
    void testAddedPlanetIsInOrbiters() {
        Planet earth = factory.createPlanetFromPattern(
                "Earth", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        assertNotNull(system.getOrbiter("Earth"),
                "Planet (which is an Orbiter) must be in orbiters map after creation");
    }

    @Test
    @DisplayName("addBody (via createPlanetFromPattern): planet appears in physicsObjects")
    void testAddedPlanetIsInPhysicsObjects() {
        Planet earth = factory.createPlanetFromPattern(
                "Earth", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        assertTrue(system.getPhysicsObjects().containsKey("Earth"),
                "Planet must be in physicsObjects (subject to Verlet integration) after creation");
    }

    @Test
    @DisplayName("getBody: returns null for unknown id")
    void testGetBodyReturnsNullForUnknownId() {
        assertNull(system.getBody("does-not-exist"),
                "getBody must return null for an id that has not been registered");
    }

    @Test
    @DisplayName("getOrbiter: returns null for unknown id")
    void testGetOrbiterReturnsNullForUnknownId() {
        assertNull(system.getOrbiter("does-not-exist"),
                "getOrbiter must return null for an id that has not been registered");
    }

    // ==================== SPACECRAFT REGISTRATION ====================

    @Test
    @DisplayName("registerSpacecraft: spacecraft appears in physicsObjects")
    void testRegisterSpacecraftAddsToPhysicsObjects() {
        CentralMind platform = factory.createCentralMind(ONE_AU_M);
        Spacecraft probe = VehicleFactory.createCubeSat("probe-reg-1", platform);

        system.registerSpacecraft(probe);

        assertTrue(system.getPhysicsObjects().containsKey("probe-reg-1"),
                "Spacecraft must be in physicsObjects after registerSpacecraft()");
    }

    @Test
    @DisplayName("registerSpacecraft: spacecraft appears in spacecraftInTransit")
    void testRegisterSpacecraftAddsToTransitMap() {
        CentralMind platform = factory.createCentralMind(ONE_AU_M);
        Spacecraft probe = VehicleFactory.createCubeSat("probe-reg-2", platform);

        system.registerSpacecraft(probe);

        assertTrue(system.getSpacecraftInTransit().containsKey("probe-reg-2"),
                "Spacecraft must be in spacecraftInTransit after registerSpacecraft()");
    }

    @Test
    @DisplayName("unregister: spacecraft remains in physicsObjects after transit removal")
    void testUnregisterKeepsSpacecraftInPhysicsObjects() {
        CentralMind platform = factory.createCentralMind(ONE_AU_M);
        Spacecraft probe = VehicleFactory.createCubeSat("probe-unreg-1", platform);

        system.registerSpacecraft(probe);
        system.unregister(probe);

        assertTrue(system.getPhysicsObjects().containsKey("probe-unreg-1"),
                "Spacecraft must remain in physicsObjects after unregister() (Verlet continues)");
    }

    @Test
    @DisplayName("unregister: spacecraft removed from spacecraftInTransit")
    void testUnregisterRemovesFromTransitMap() {
        CentralMind platform = factory.createCentralMind(ONE_AU_M);
        Spacecraft probe = VehicleFactory.createCubeSat("probe-unreg-2", platform);

        system.registerSpacecraft(probe);
        system.unregister(probe);

        assertFalse(system.getSpacecraftInTransit().containsKey("probe-unreg-2"),
                "Spacecraft must not be in spacecraftInTransit after unregister()");
    }

    @Test
    @DisplayName("unregisterAndRemoveFromPhysics: spacecraft removed from both maps")
    void testUnregisterAndRemoveFromPhysicsRemovesFromBothMaps() {
        CentralMind platform = factory.createCentralMind(ONE_AU_M);
        Spacecraft probe = VehicleFactory.createCubeSat("probe-full-unreg", platform);

        system.registerSpacecraft(probe);
        system.unregisterAndRemoveFromPhysics(probe);

        assertAll("full deregistration",
                () -> assertFalse(system.getPhysicsObjects().containsKey("probe-full-unreg"),
                        "Spacecraft must not be in physicsObjects after unregisterAndRemoveFromPhysics()"),
                () -> assertFalse(system.getSpacecraftInTransit().containsKey("probe-full-unreg"),
                        "Spacecraft must not be in spacecraftInTransit after unregisterAndRemoveFromPhysics()")
        );
    }

    // ==================== ORBIT PLACEMENT ====================

    @Test
    @DisplayName("placeInCircularOrbit: body position is at the requested radius from origin")
    void testCircularOrbitPositionIsAtRequestedRadius() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthRadius", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        double actualRadius = earth.getPosition().magnitude();

        assertEquals(ONE_AU_M, actualRadius, POSITION_TOLERANCE_M,
                "Planet placed at 1 AU must have a position magnitude of 1 AU");
    }

    @Test
    @DisplayName("placeInCircularOrbit: orbital speed equals sqrt(GM/r)")
    void testCircularOrbitSpeedMatchesKeplerian() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthSpeed", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        // v_circular = sqrt(G * M_star / r)
        double gravitationalParameter = PhysicsConstants.G * centralStar.getMass();
        double expectedSpeed = Math.sqrt(gravitationalParameter / ONE_AU_M);
        double actualSpeed   = earth.getVelocity().magnitude();

        assertEquals(expectedSpeed, actualSpeed, VELOCITY_TOLERANCE_MS,
                "Orbital speed at 1 AU must equal sqrt(GM/r) = " + expectedSpeed + " m/s");
    }

    @Test
    @DisplayName("placeInCircularOrbit: velocity is perpendicular to position vector")
    void testCircularOrbitVelocityIsPerpendicularToPosition() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthPerp", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        // For a circular orbit in the ecliptic, position dot velocity must be zero
        double dotProduct = earth.getPosition().dot(earth.getVelocity());

        assertEquals(0.0, dotProduct, ONE_AU_M * VELOCITY_TOLERANCE_MS,
                "Position and velocity must be perpendicular for a circular orbit (dot product = 0)");
    }

    @Test
    @DisplayName("placeInEllipticalOrbit: body at non-zero eccentricity is placed at periapsis distance")
    void testEllipticalOrbitPeriapsisDistance() {
        double semiMajorAxis = ONE_AU_M;
        double eccentricity  = 0.2;
        // At trueAnomaly = 0 (periapsis): r = a * (1 - e)
        double expectedPeriapsisDistance = semiMajorAxis * (1.0 - eccentricity);

        Planet eccentric = factory.createPlanetFromPattern(
                "Eccentric", centralStar,
                new Orbit(semiMajorAxis, eccentricity, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.MARS, 1.0);

        double actualRadius = eccentric.getPosition().magnitude();

        assertEquals(expectedPeriapsisDistance, actualRadius, POSITION_TOLERANCE_M,
                "Body placed at trueAnomaly=0 with e=0.2 must be at periapsis r = a*(1-e)");
    }

    // ==================== SIMULATION STEPPING ====================

    @Test
    @DisplayName("stepVerlet: currentTime advances by exactly one timeStep")
    void testStepVerletAdvancesTimeByOneTimeStep() {
        double timeBeforeStep = system.getCurrentTime();

        system.stepVerlet();

        assertEquals(timeBeforeStep + TIME_STEP_S, system.getCurrentTime(), TIME_TOLERANCE_S,
                "stepVerlet must increment currentTime by exactly one timeStep");
    }

    @Test
    @DisplayName("stepVerlet: returns updated currentTime")
    void testStepVerletReturnsUpdatedTime() {
        double returnedTime = system.stepVerlet();

        assertEquals(system.getCurrentTime(), returnedTime, TIME_TOLERANCE_S,
                "stepVerlet must return the updated currentTime");
    }

    @Test
    @DisplayName("advance: currentTime increases by the requested duration")
    void testAdvanceIncrementsTimeByRequestedDuration() {
        double duration = TIME_STEP_S * 10.0;

        system.advance(duration);

        assertEquals(duration, system.getCurrentTime(), TIME_TOLERANCE_S,
                "advance(duration) must result in currentTime == duration when starting from zero");
    }

    @Test
    @DisplayName("stepVerlet: planet position changes after one step")
    void testPlanetPositionChangesAfterOneStep() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthMotion", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        Vector3D positionBeforeStep = earth.getPosition();
        system.stepVerlet();
        Vector3D positionAfterStep = earth.getPosition();

        // Planet orbital speed at 1 AU is ~29,780 m/s; in one hour it moves ~107 Mm
        double displacement = positionAfterStep.subtract(positionBeforeStep).magnitude();
        assertTrue(displacement > 1e6,
                "Planet position must change meaningfully after one Verlet step; displacement was "
                        + displacement + " m");
    }

    // ==================== GRAVITATIONAL ACCELERATION ====================

    @Test
    @DisplayName("gravitational acceleration at 1 AU: magnitude matches GM/r^2")
    void testGravitationalAccelerationMagnitudeAtOneAU() {
        // A planet placed at 1 AU from a solar mass star must experience
        // g = GM / r^2 = 5.93e-3 m/s^2
        Planet earth = factory.createPlanetFromPattern(
                "EarthGrav", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        Vector3D positionBeforeStep = earth.getPosition();
        Vector3D velocityBeforeStep = earth.getVelocity();
        system.stepVerlet();
        Vector3D positionAfterStep = earth.getPosition();
        Vector3D velocityAfterStep = earth.getVelocity();

        // From Verlet: delta_v ≈ a * dt (first-order approximation for one step)
        double deltaVelocity = velocityAfterStep.subtract(velocityBeforeStep).magnitude();
        double observedAcceleration = deltaVelocity / TIME_STEP_S;

        // Expected: g = G * M_star / r^2
        double gravitationalParameter = PhysicsConstants.G * centralStar.getMass();
        double expectedAcceleration = centralStar.getGravitationalParameter() / (ONE_AU_M * ONE_AU_M);

        assertEquals(expectedAcceleration, observedAcceleration,
                expectedAcceleration * ACCEL_RELATIVE_TOLERANCE,
                "Gravitational acceleration at 1 AU must equal GM/r^2 = "
                        + expectedAcceleration + " m/s^2");
    }

    @Test
    @DisplayName("gravitational acceleration: directed toward the central star")
    void testGravitationalAccelerationDirectedTowardStar() {
        // Place planet along the +X axis; acceleration must point toward -X (toward star)
        Planet earth = factory.createPlanetFromPattern(
                "EarthDir", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        Vector3D velocityBeforeStep = earth.getVelocity();
        system.stepVerlet();
        Vector3D velocityAfterStep = earth.getVelocity();

        // Velocity change direction should point toward the star (origin)
        Vector3D deltaVelocity = velocityAfterStep.subtract(velocityBeforeStep);
        Vector3D towardStar    = earth.getPosition().normalize().multiply(-1.0);

        // The component of delta-velocity along the toward-star direction must be positive
        double radialComponent = deltaVelocity.normalize().dot(towardStar);
        assertTrue(radialComponent > 0.9,
                "Gravitational acceleration must be directed toward the central star; "
                        + "radial component of unit delta-velocity was " + radialComponent);
    }

    // ==================== MULTIPLE BODIES ====================

    @Test
    @DisplayName("two planets: both appear in physicsObjects independently")
    void testTwoPlanetsAreTrackedIndependently() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthTwo", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        Planet mars = factory.createPlanetFromPattern(
                "MarsTwo", centralStar,
                new Orbit(ONE_AU_M * 1.524, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.MARS, 1.0);

        assertAll("both planets tracked in physicsObjects",
                () -> assertTrue(system.getPhysicsObjects().containsKey("EarthTwo"),
                        "Earth must be in physicsObjects"),
                () -> assertTrue(system.getPhysicsObjects().containsKey("MarsTwo"),
                        "Mars must be in physicsObjects")
        );
    }

    @Test
    @DisplayName("two planets: positions diverge after simulation advances")
    void testTwoPlanetsAtDifferentRadiiDivergeInPosition() {
        Planet earth = factory.createPlanetFromPattern(
                "EarthDiv", centralStar,
                new Orbit(ONE_AU_M, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.EARTH, 1.0);

        Planet mars = factory.createPlanetFromPattern(
                "MarsDiv", centralStar,
                new Orbit(ONE_AU_M * 1.524, 0.0, 0.0, 0.0, 0.0, 0.0, centralStar),
                PlanetPattern.MARS, 1.0);

        // Their initial angular positions differ (same trueAnomaly=0, different a),
        // so positions are already different. After stepping they must remain different.
        double startingSeparation = earth.getPosition().distanceTo(mars.getPosition());
        system.advance(TIME_STEP_S * 100.0);
        double separation = earth.getPosition().distanceTo(mars.getPosition());
        assertNotEquals(startingSeparation, separation,
                "Earth and Mars at different orbital radii must have distinct positions after advancing");
    }
}