package com.kaymlyn.planeteater.operations;

import com.kaymlyn.planeteater.vehicles.Spacecraft;
import com.kaymlyn.planeteater.celestial.CelestialBody;
import com.kaymlyn.planeteater.physics.OrbitalSystem;
import com.kaymlyn.planeteater.physics.PhysicsConstants;
import com.kaymlyn.planeteater.physics.Vector3D;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Handles trajectory planning and fuel calculations for spacecraft travel
 * 
 * Generated by Claude (Sonnet 4.5)
 */
public class TravelCalculator {
    
    /**
     * Represents a planned trajectory between two positions
     */
    @Getter
    @AllArgsConstructor
    public static class Trajectory {
        public Vector3D startPosition;
        public Vector3D endPosition;
        public double deltaV;           // Required delta-v (m/s)
        public double travelTime;       // Travel duration (seconds)
        public double fuelRequired;     // Fuel needed (kg)
        
        @Override
        public String toString() {
            return String.format("Trajectory[distance=%.3e m, deltaV=%.1f m/s, " +
                "time=%.2f days, fuel=%.1f kg]",
                startPosition.distanceTo(endPosition),
                deltaV, travelTime / PhysicsConstants.SECONDS_PER_DAY, fuelRequired);
        }
    }
    
    /**
     * Calculate a simple direct transfer trajectory
     * This is a simplified model - assumes instant acceleration and straight-line travel
     * For more realism, we'd implement Hohmann transfers
     */
    public static Trajectory calculateDirectTransfer(Vector3D start, Vector3D end, 
                                                     Spacecraft spacecraft) {
        double distance = start.distanceTo(end);
        
        // Simple model: accelerate to midpoint, decelerate to arrival
        // Assumes constant thrust at midpoint
        // Total deltaV = 2 * sqrt(2 * a * d/2) where a*t²/2 = d/2
        // Simplified: deltaV proportional to sqrt(distance)
        
        // More realistic approach: assume we want to arrive in reasonable time
        // Using vis-viva equation approximation for orbital transfers
        double deltaV = estimateDeltaVForDistance(distance);
        
        // Travel time based on distance and available deltaV
        // Simplified: time = distance / (average velocity)
        // Average velocity ~ deltaV / 2 (accelerate then decelerate)
        double averageVelocity = deltaV / 2.0;
        double travelTime = distance / averageVelocity;
        
        // Calculate fuel required using Tsiolkovsky equation
        double fuelRequired = spacecraft.getFuelRequiredForDeltaV(deltaV);
        
        return new Trajectory(start, end, deltaV, travelTime, fuelRequired);
    }
    
    /**
     * Calculate Hohmann transfer between circular orbits
     * More realistic for orbital mechanics
     */
    public static Trajectory calculateHohmannTransfer(double r1, double r2,
                                                      double centralMass,
                                                      Spacecraft spacecraft) {
        // Semi-major axis of transfer ellipse
        double a = (r1 + r2) / 2.0;
        
        // Orbital velocities
        double v1 = Math.sqrt(PhysicsConstants.G * centralMass / r1);
        double v2 = Math.sqrt(PhysicsConstants.G * centralMass / r2);
        
        // Velocities at periapsis and apoapsis of transfer orbit
        double vp = Math.sqrt(PhysicsConstants.G * centralMass * (2.0/r1 - 1.0/a));
        double va = Math.sqrt(PhysicsConstants.G * centralMass * (2.0/r2 - 1.0/a));
        
        // Delta-v requirements
        double deltaV1 = Math.abs(vp - v1);  // Injection burn
        double deltaV2 = Math.abs(v2 - va);  // Circularization burn
        double totalDeltaV = deltaV1 + deltaV2;
        
        // Transfer time (half orbital period of transfer ellipse)
        double transferTime = Math.PI * Math.sqrt(Math.pow(a, 3) / 
            (PhysicsConstants.G * centralMass));
        
        // Fuel required
        double fuelRequired = spacecraft.getFuelRequiredForDeltaV(totalDeltaV);
        
        Vector3D start = new Vector3D(r1, 0, 0);
        Vector3D end = new Vector3D(r2, 0, 0);
        
        return new Trajectory(start, end, totalDeltaV, transferTime, fuelRequired);
    }
    
    /**
     * Estimate delta-v needed based on distance
     * This is a simplified heuristic
     */
    private static double estimateDeltaVForDistance(double distance) {
        // Rough heuristic: more distance requires more deltaV
        // Scale with square root of distance (similar to orbital mechanics)
        // Base assumption: 1 AU distance ≈ 30 km/s deltaV (rough Earth-Mars)
        
        double baseDistance = PhysicsConstants.AU;
        double baseDeltaV = 30000.0; // m/s
        
        return baseDeltaV * Math.sqrt(distance / baseDistance);
    }
    
    /**
     * Check if a spacecraft can complete a trajectory
     */
    public static boolean canCompleteTrajectory(Spacecraft spacecraft, Trajectory trajectory) {
        // Check fuel availability
        if (spacecraft.getFuelMass() < trajectory.fuelRequired) {
            return false;
        }
        
        // Check if deltaV is achievable
        if (spacecraft.getAvailableDeltaV() < trajectory.deltaV) {
            return false;
        }
        
        return true;
    }
    
    /**
     * Calculate rendezvous trajectory accounting for orbital motion
     * This predicts where the target will be when the spacecraft arrives
     */
    public static Trajectory calculateRendezvous(Vector3D startPos, Vector3D startVel,
                                                 CelestialBody target,
                                                 double currentTime,
                                                 Spacecraft spacecraft,
                                                 OrbitalSystem system) {
        // First estimate: how long will it take to get there?
        Vector3D currentTargetPos = target.getPosition();
        double distance = startPos.distanceTo(currentTargetPos);
        double estimatedDeltaV = estimateDeltaVForDistance(distance);
        double estimatedTime = distance / (estimatedDeltaV / 2.0);
        
        // Predict where target will be after travel time
        // Simple prediction: assume circular orbit
        Vector3D targetVel = target.getVelocity();
        double orbitalRadius = currentTargetPos.magnitude();
        double angularVelocity = targetVel.magnitude() / orbitalRadius;
        double angleChange = angularVelocity * estimatedTime;
        
        // Rotate target position by predicted angle
        double currentAngle = Math.atan2(currentTargetPos.getY(), currentTargetPos.getX());
        double futureAngle = currentAngle + angleChange;
        Vector3D predictedTargetPos = new Vector3D(
            orbitalRadius * Math.cos(futureAngle),
            orbitalRadius * Math.sin(futureAngle),
            0
        );
        
        // Now calculate trajectory to predicted position
        return calculateDirectTransfer(startPos, predictedTargetPos, spacecraft);
    }
    
    /**
     * Calculate the relative velocity needed to match orbits with a target
     */
    public static double calculateMatchVelocity(Vector3D currentVel, Vector3D targetVel) {
        return currentVel.subtract(targetVel).magnitude();
    }
}