package com.kaymlyn.planeteater;

import com.kaymlyn.planeteater.entities.artifice.actors.Spacecraft;
import com.kaymlyn.planeteater.entities.primordials.Asteroid;
import com.kaymlyn.planeteater.entities.primordials.Composition;
import com.kaymlyn.planeteater.entities.artifice.actors.MiningEntity;
import com.kaymlyn.planeteater.entities.artifice.actors.MiningOperation;
import com.kaymlyn.planeteater.entities.artifice.OrbitalPlatform;
import com.kaymlyn.planeteater.entities.primordials.OrbitalSystem;
import com.kaymlyn.planeteater.entities.primordials.Star;
import com.kaymlyn.planeteater.universals.Material;
import com.kaymlyn.planeteater.universals.PhysicsConstants;
import com.kaymlyn.planeteater.universals.TravelCalculator;
import com.kaymlyn.planeteater.universals.Vector3D;

/**
 * Demonstrates the asteroid mining simulation
 * Shows how all components work together
 * 
 * Generated by Claude (Sonnet 4.5)
 */
public class SimulationDemo {
    
    public static void main(String[] args) {
        System.out.println("=== ASTEROID MINING SIMULATION ===\n");
        
        // 1. Create the orbital system with a Sun-like star
        System.out.println("1. Initializing orbital system...");
        Star sun = Star.createSunLike("Sun");
        double timeStep = 3600.0; // 1 hour time steps
        OrbitalSystem system = new OrbitalSystem(sun, timeStep);
        System.out.println("   " + sun);
        System.out.println();
        
        // 2. Set up the orbital platform at 1 AU
        System.out.println("2. Setting up orbital platform...");
        OrbitalPlatform platform = new OrbitalPlatform("Platform-Alpha", PhysicsConstants.AU);
        platform.initializeOrbit(system);
        System.out.println("   " + platform);
        System.out.println("   Orbit period: " + 
            (system.orbitalPeriod(platform.getOrbitRadius()) / PhysicsConstants.SECONDS_PER_DAY) + 
            " days");
        System.out.println();
        
        // 3. Create some asteroids in the system
        System.out.println("3. Placing asteroids in the system...");
        
        // Small M-type asteroid at 1.5 AU (metal-rich)
        Asteroid asteroid1 = Asteroid.createMType("Asteroid-M1",
            Vector3D.ZERO, Vector3D.ZERO, 100.0); // 100m radius
        system.placeInCircularOrbit(asteroid1, 1.5 * PhysicsConstants.AU, Math.PI / 4);
        System.out.println("   " + asteroid1);
        System.out.println("   Available Iron: " + 
            String.format("%.3e kg", asteroid1.getAvailableMaterial(Material.IRON)));
        
        // Small C-type asteroid at 2.0 AU (water-rich)
        Asteroid asteroid2 = Asteroid.createCType("Asteroid-C1",
            Vector3D.ZERO, Vector3D.ZERO, 80.0); // 80m radius
        system.placeInCircularOrbit(asteroid2, 2.0 * PhysicsConstants.AU, Math.PI);
        System.out.println("   " + asteroid2);
        System.out.println("   Available Water Ice: " + 
            String.format("%.3e kg", asteroid2.getAvailableMaterial(Material.WATER_ICE)));
        System.out.println();
        
        // 4. Create mining entities
        System.out.println("4. Creating mining crew...");
        MiningEntity human1 = MiningEntity.createHuman("Miner-1");
        MiningEntity robot1 = MiningEntity.createBasicRobot("Robot-1");
        MiningEntity robot2 = MiningEntity.createAdvancedRobot("Robot-2");
        System.out.println("   " + human1);
        System.out.println("   " + robot1);
        System.out.println("   " + robot2);
        System.out.println();
        
        // 5. Create a mining vessel
        System.out.println("5. Constructing mining vessel...");
        Spacecraft vessel = Spacecraft.createMiningVessel("Vessel-1");
        System.out.println("   " + vessel);
        System.out.println("   Construction materials:");
        for (var entry : vessel.getConstruction().getMaterials().entrySet()) {
            System.out.println("      " + entry.getKey() + ": " + 
                String.format("%.1f kg", entry.getValue()));
        }
        System.out.println();
        
        // 6. Plan a mining operation to asteroid1
        System.out.println("6. Planning mining operation to " + asteroid1.getId() + "...");
        double targetAmount = 50000.0; // Mine 50 tons of iron
        MiningOperation operation = new MiningOperation(
            "Op-001", vessel, asteroid1, Material.IRON, targetAmount);
        
        // Add crew
        operation.addMiner(human1);
        operation.addMiner(robot1);
        operation.addMiner(robot2);
        System.out.println("   Total mining rate: " + 
            String.format("%.2f kg/s", operation.getTotalMiningRate()));
        
        // Plan the operation
        boolean canProceed = operation.planOperation(platform, system);
        System.out.println("   Operation feasible: " + canProceed);
        
        if (canProceed) {
            System.out.println("   Estimated mining time: " + 
                String.format("%.2f hours", operation.estimateMiningTime() / 3600.0));
            System.out.println("   Total operation time: " + 
                String.format("%.2f days", operation.getTotalOperationTime() / PhysicsConstants.SECONDS_PER_DAY));
            System.out.println("   Fuel required: " + 
                String.format("%.1f kg", operation.getTotalFuelCost()));
            System.out.println("   Efficiency: " + 
                String.format("%.2f kg mined per kg fuel", operation.getEfficiency()));
        }
        System.out.println();
        
        // 7. Demonstrate trajectory calculation
        System.out.println("7. Calculating trajectory details...");
        TravelCalculator.Trajectory trajectory = TravelCalculator.calculateDirectTransfer(
            platform.getPosition(), asteroid1.getPosition(), vessel);
        System.out.println("   " + trajectory);
        System.out.println();
        
        // 8. Run a short simulation
        System.out.println("8. Running simulation for 10 days...");
        double simulationDays = 10.0;
        int steps = (int)(simulationDays * PhysicsConstants.SECONDS_PER_DAY / timeStep);
        
        System.out.println("   Initial positions:");
        System.out.println("      Platform: " + platform.getPosition());
        System.out.println("      Asteroid M1: " + asteroid1.getPosition());
        System.out.println("      Asteroid C1: " + asteroid2.getPosition());
        
        for (int i = 0; i < steps; i++) {
            system.stepVerlet();
            platform.update(timeStep, system);
        }
        
        System.out.println("   After " + simulationDays + " days:");
        System.out.println("      Platform: " + platform.getPosition());
        System.out.println("      Asteroid M1: " + asteroid1.getPosition());
        System.out.println("      Asteroid C1: " + asteroid2.getPosition());
        System.out.println("   Simulation time: " + 
            (system.getCurrentTime() / PhysicsConstants.SECONDS_PER_DAY) + " days");
        System.out.println();
        
        // 9. Demonstrate resource extraction
        System.out.println("9. Simulating resource extraction...");
        double ironBefore = asteroid1.getAvailableMaterial(Material.IRON);
        double extracted = asteroid1.mineMaterial(Material.IRON, 1000.0);
        double ironAfter = asteroid1.getAvailableMaterial(Material.IRON);
        
        System.out.println("   Iron before: " + String.format("%.3e kg", ironBefore));
        System.out.println("   Extracted: " + String.format("%.1f kg", extracted));
        System.out.println("   Iron after: " + String.format("%.3e kg", ironAfter));
        System.out.println();
        
        // 10. Demonstrate platform inventory
        System.out.println("10. Adding resources to platform inventory...");
        platform.addResource(Material.IRON, extracted);
        platform.addResource(Material.WATER_ICE, 500.0);
        platform.addResource(Material.ALUMINUM, 200.0);
        System.out.println(platform.getInventoryReport());
        
        // 11. Demonstrate spacecraft recycling
        System.out.println("11. Recycling spacecraft...");
        Spacecraft cargoShuttle = Spacecraft.createCargoShuttle("Shuttle-1");
        System.out.println("   Created: " + cargoShuttle.getId());
        System.out.println("   Dry mass: " + cargoShuttle.getDryMass() + " kg");
        
        Composition recycled = cargoShuttle.recycle();
        System.out.println("   Recycled materials:");
        for (var entry : recycled.getMaterials().entrySet()) {
            System.out.println("      " + entry.getKey() + ": " + 
                String.format("%.1f kg", entry.getValue()));
        }
        System.out.println();
        
        // 12. Show system summary
        System.out.println("12. System summary:");
        System.out.println("   Total bodies: " + system.getOrbitingBodies().size());
        System.out.println("   Asteroids: " + system.getAsteroids().size());
        System.out.println("   Planets: " + system.getPlanets().size());
        System.out.println("   Platform inventory: " + 
            String.format("%.3e kg", platform.getTotalInventoryMass()));
        System.out.println();
        
        System.out.println("=== SIMULATION COMPLETE ===");
    }
}