package com.kaymlyn.planeteater.entities.primordials;

import com.kaymlyn.planeteater.universals.PhysicsConstants;
import com.kaymlyn.planeteater.universals.Vector3D;
import lombok.Getter;
import lombok.Setter;

/**
 * Abstract base class for all celestial bodies in the simulation
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
@Setter
public abstract class CelestialBody {
    protected String id;
    protected Vector3D position; // meters
    protected Vector3D velocity; // m/s
    protected Composition composition;
    
    public CelestialBody(String id, Vector3D position, Vector3D velocity, Composition composition) {
        this.id = id;
        this.position = position;
        this.velocity = velocity;
        this.composition = composition;
    }
    
    /**
     * Get the total mass of this body in kg
     */
    public double getMass() {
        return composition.getTotalMass();
    }
    
    /**
     * Calculate radius assuming spherical body
     * r = (3V / 4π)^(1/3)
     */
    public double getRadius() {
        double volume = composition.getTotalVolume();
        return Math.cbrt((3.0 * volume) / (4.0 * Math.PI));
    }
    
    /**
     * Get the bulk density of this body
     */
    public double getDensity() {
        return composition.getBulkDensity();
    }
    
    /**
     * Calculate gravitational force this body exerts on another body
     * F = G * m1 * m2 / r²
     * Returns force vector pointing from other body toward this body
     */
    public Vector3D gravitationalForceOn(CelestialBody other) {
        Vector3D displacement = this.position.subtract(other.position);
        double distanceSquared = displacement.magnitudeSquared();
        
        if (distanceSquared < 1e-10) {
            return Vector3D.ZERO;
        }
        
        double forceMagnitude = PhysicsConstants.G * this.getMass() * other.getMass() / distanceSquared;
        return displacement.normalize().multiply(forceMagnitude);
    }
    
    /**
     * Update position and velocity based on acceleration over time step
     * Uses simple Euler integration for now
     */
    public void update(Vector3D acceleration, double dt) {
        // v = v + a * dt
        velocity = velocity.add(acceleration.multiply(dt));
        // p = p + v * dt
        position = position.add(velocity.multiply(dt));
    }
    
    @Override
    public String toString() {
        return String.format("%s[id=%s, pos=%s, vel=%s, mass=%.3e kg, radius=%.3e m]",
            getClass().getSimpleName(), id, position, velocity, getMass(), getRadius());
    }
}