package com.kaymlyn.planeteater.entities.primordials;

import com.kaymlyn.planeteater.universals.Material;
import com.kaymlyn.planeteater.universals.PhysicsConstants;
import com.kaymlyn.planeteater.universals.Vector3D;

/**
 * Represents a star (central body in the system)
 * 
 * Generated by Claude (Sonnet 4.5)
 */
public class Star extends CelestialBody {
    
    /**
     * Create a star with default Sun-like properties
     */
    public static Star createSunLike(String id) {
        Composition comp = new Composition();
        // Simplified - stars are mostly hydrogen and helium, but we'll use a placeholder
        // Since we're not modeling stellar material extraction, we just need the mass
        comp.addMaterial(Material.IRON, PhysicsConstants.SOLAR_MASS);
        
        return new Star(id, Vector3D.ZERO, Vector3D.ZERO, comp);
    }
    
    public Star(String id, Vector3D position, Vector3D velocity, Composition composition) {
        super(id, position, velocity, composition);
    }
    
    /**
     * Stars are typically stationary at the center of the system
     * Override to prevent accidental movement
     */
    @Override
    public void update(Vector3D acceleration, double dt) {
        // Stars don't move in our simplified model
        // If we want to model binary stars later, we can change this
    }
}