package com.kaymlyn.planeteater.simulation.resources;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Enhanced comprehensive test suite for Composition class.
 * CRITICAL DISTINCTION:
 * - Composition stores MASS (kg) for physics calculations
 * - Cargo holds constrain by VOLUME (m³) for physical space
 * - This test suite validates both mass and volume tracking
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("Composition Tests - Enhanced with Volume Tracking")
public class OldCompositionTest {

    private static final double TOLERANCE = 1e-6;

    private double standardMass;
    private double standardVolume;
    private Composition composition;

    @BeforeEach
    void setUp() {
        standardMass = 100.0;
        standardVolume = 100.0;
        composition = new Composition();
    }

    // ==================== ORIGINAL TESTS (PRESERVED) ====================

    @Test
    @DisplayName("Simple composition addition and removal")
    void validateSimpleCompositionAdditionAndRemoval() {
        composition.addMaterialAsRawMass(Material.IRON, standardMass)
                .addMaterialAsVolume(Material.IRON_OXIDE, standardVolume);

        double initialTotalMass = composition.getTotalMass();
        double initialMassFe = composition.getMass(Material.IRON);
        double initialMassFeO = composition.getMass(Material.IRON_OXIDE);
        double densityFeO = Material.IRON_OXIDE.getDensity();

        composition.addMaterialAsRawMass(Material.IRON, standardMass);
        double totalMassWithAddition = composition.getTotalMass();
        double massWithAdditionFe = composition.getMass(Material.IRON);
        double massWithAdditionFeO = composition.getMass(Material.IRON_OXIDE);

        double removedFeO = composition.removeMaterial(Material.IRON_OXIDE, standardMass);
        double totalMassWithRemoval = composition.getTotalMass();
        double massWithRemovalFe = composition.getMass(Material.IRON);
        double massWithRemovalFeO = composition.getMass(Material.IRON_OXIDE);

        boolean presenceH = composition.contains(Material.HYDROGEN);
        double removedH = composition.removeMaterial(Material.HYDROGEN, standardMass);

        boolean presenceBeforeRemoval = composition.contains(Material.IRON);
        double removedFE = composition.removeMaterial(Material.IRON, standardMass * 3);
        boolean presenceAfterRemoval = composition.contains(Material.IRON);

        Assertions.assertAll(
                () -> assertEquals(densityFeO*standardVolume + standardMass, initialTotalMass, TOLERANCE,
                        "Total Mass should be 100m^3 of FeO plus 100kg of Fe"),
                () -> assertEquals(standardMass, initialMassFe, TOLERANCE,
                        "Fe Mass should be equal to standard Mass"),
                () -> assertEquals(standardMass * densityFeO, initialMassFeO, TOLERANCE,
                        "FeO Mass should relate to its density"),
                () -> assertEquals(densityFeO*standardVolume + 2*standardMass, totalMassWithAddition, TOLERANCE,
                        "Total Mass should be 100m^3 of FeO plus 200kg of Fe"),
                () -> assertEquals(standardMass*2, massWithAdditionFe, TOLERANCE,
                        "Fe Mass should be double standard mass"),
                () -> assertEquals(initialMassFeO, massWithAdditionFeO, TOLERANCE,
                        "FeO Mass should remain unchanged after addition of other resources"),
                () -> assertEquals(standardMass, removedFeO, TOLERANCE,
                        "Return of removed mass should equal mass requested if available"),
                () -> assertEquals(densityFeO*standardVolume + standardMass, totalMassWithRemoval, TOLERANCE,
                        "Total Mass after removal"),
                () -> assertEquals(massWithAdditionFe, massWithRemovalFe, TOLERANCE,
                        "Fe Mass unchanged after removal of other resources"),
                () -> assertEquals(densityFeO*standardVolume - standardMass, massWithRemovalFeO, TOLERANCE,
                        "FeO Mass should be 100kg less"),
                () -> assertFalse(presenceH, "Hydrogen not present"),
                () -> assertEquals(0.0, removedH, TOLERANCE, "Cannot remove non-existent material"),
                () -> assertTrue(presenceBeforeRemoval, "Materials present when in list"),
                () -> assertEquals(standardMass * 2, removedFE, TOLERANCE,
                        "Remove all available when requesting more"),
                () -> assertFalse(presenceAfterRemoval, "Material removed when exhausted")
        );
    }

    @Test
    @DisplayName("Error checking for invalid inputs")
    void validateErrorChecking() {
        Composition testComp = new Composition();

        Assertions.assertAll(
                () -> assertEquals(0.0, testComp.removeMaterial(Material.IRON, -3), TOLERANCE,
                        "Cannot remove negative mass"),
                () -> assertFalse(testComp.addMaterialAsRawMass(Material.IRON, -3).contains(Material.IRON),
                        "Cannot add negative mass"),
                () -> assertFalse(testComp.addMaterialAsVolume(Material.IRON, -3).contains(Material.IRON),
                        "Cannot add negative volume"),
                () -> assertEquals(0.0, testComp.removeMaterial(null, 10), TOLERANCE,
                        "Null material returns 0"),
                () -> assertEquals(0.0, testComp.addMaterialAsRawMass(null, 10).getTotalMass(), TOLERANCE,
                        "Null material not added (mass)"),
                () -> assertEquals(0.0, testComp.addMaterialAsVolume(null, 10).getTotalMass(), TOLERANCE,
                        "Null material not added (volume)")
        );
    }

    @Test
    @DisplayName("Metrics calculations")
    void validateMetrics() {
        composition.addMaterialAsVolume(Material.IRON, standardVolume);
        double ironDensity = composition.getBulkDensity();

        composition.addMaterialAsVolume(Material.IRON_OXIDE, standardVolume);
        double ironMixDensity = composition.getBulkDensity();
        double mixedDensity = (Material.IRON.getDensity() + Material.IRON_OXIDE.getDensity())/2;

        Assertions.assertAll(
                () -> assertEquals(Material.IRON.getDensity(), ironDensity, TOLERANCE,
                        "Pure material density"),
                () -> assertEquals(mixedDensity, ironMixDensity, TOLERANCE,
                        "Mixed density is average for equal volumes"),
                () -> assertEquals("Composition[Fe: 7.87e+05 kg, FeO: 5.24e+05 kg]", composition.toString()),
                () -> assertEquals("Composition[]", new Composition().toString())
        );
    }

    @Test
    @DisplayName("Extraction with targeting")
    void validateExtraction(){
        composition.addMaterialAsRawMass(Material.IRON,1e4)
                .addMaterialAsRawMass(Material.IRON_OXIDE, 2e4)
                .addMaterialAsRawMass(Material.SILICA, 1e5);

        Composition extracted1 = composition.extract(200,1.0);
        Composition extracted2 = composition.extract(200,2.0,Material.IRON);
        Composition extracted3 = composition.extract(200, 2.0, Material.IRON, Material.IRON_OXIDE);

        Assertions.assertAll(
                () -> assertEquals(200, (int)extracted1.getTotalMass()),
                () -> assertEquals(1538, (int)(extracted1.getMass(Material.IRON)*100)),
                () -> assertEquals(3076, (int)(extracted1.getMass(Material.IRON_OXIDE)*100)),
                () -> assertEquals(15384, (int)(extracted1.getMass(Material.SILICA)*100)),
                () -> assertEquals(3714, (int)(extracted2.getTotalMass()*100)),
                () -> assertEquals(2857, (int)(extracted2.getMass(Material.IRON)*100)),
                () -> assertEquals(142, (int)(extracted2.getMass(Material.IRON_OXIDE)*100)),
                () -> assertEquals(714, (int)(extracted2.getMass(Material.SILICA)*100)),
                () -> assertEquals(8120, (int)(extracted3.getTotalMass()*100)),
                () -> assertEquals(2493, (int)(extracted3.getMass(Material.IRON)*100)),
                () -> assertEquals(5001, (int)(extracted3.getMass(Material.IRON_OXIDE)*100)),
                () -> assertEquals(625, (int)(extracted3.getMass(Material.SILICA)*100))
        );
    }

    // ==================== NEW: VOLUME TRACKING TESTS ====================

    @Test
    @DisplayName("Get volume of specific material")
    void testGetMaterialVolume() {
        composition.addMaterialAsVolume(Material.IRON, 2.5);
        composition.addMaterialAsVolume(Material.ALUMINUM, 1.5);

        assertAll("Material volumes",
                () -> assertEquals(2.5, composition.getVolume(Material.IRON), TOLERANCE),
                () -> assertEquals(1.5, composition.getVolume(Material.ALUMINUM), TOLERANCE)
        );
    }

    @Test
    @DisplayName("Volume of non-existent material is zero")
    void testVolumeNonExistent() {
        assertEquals(0.0, composition.getVolume(Material.HYDROGEN), TOLERANCE);
    }

    @Test
    @DisplayName("Total volume calculation")
    void testTotalVolume() {
        composition.addMaterialAsRawMass(Material.IRON, 1000.0);
        composition.addMaterialAsRawMass(Material.ALUMINUM, 500.0);

        double expected = 1000.0 / Material.IRON.getDensity() +
                500.0 / Material.ALUMINUM.getDensity();

        assertEquals(expected, composition.getTotalVolume(), TOLERANCE);
    }

    @Test
    @DisplayName("Add by volume calculates mass")
    void testAddByVolume() {
        composition.addMaterialAsVolume(Material.IRON, 1.0);

        assertAll("Add by volume",
                () -> assertEquals(Material.IRON.getDensity(), composition.getMass(Material.IRON), TOLERANCE),
                () -> assertEquals(1.0, composition.getTotalVolume(), TOLERANCE)
        );
    }

    @Test
    @DisplayName("Volume consistency: mass vs volume methods")
    void testVolumeConsistency() {
        Composition byMass = new Composition();
        Composition byVol = new Composition();

        byMass.addMaterialAsRawMass(Material.IRON, 7874.0);
        byVol.addMaterialAsVolume(Material.IRON, 1.0);

        assertAll("Consistency",
                () -> assertEquals(byMass.getTotalMass(), byVol.getTotalMass(), TOLERANCE),
                () -> assertEquals(byMass.getTotalVolume(), byVol.getTotalVolume(), TOLERANCE),
                () -> assertEquals(1.0, byMass.getTotalVolume(), TOLERANCE),
                () -> assertEquals(7874.0, byVol.getTotalMass(), TOLERANCE)
        );
    }

    @Test
    @DisplayName("Removal updates volume")
    void testRemovalUpdatesVolume() {
        composition.addMaterialAsVolume(Material.IRON, 5.0);

        double massToRemove = Material.IRON.getDensity() * 2.0;
        composition.removeMaterial(Material.IRON, massToRemove);

        assertEquals(3.0, composition.getTotalVolume(), TOLERANCE);
    }

    // ==================== CARGO VOLUME SCENARIOS ====================

    @Test
    @DisplayName("Dense materials: less volume for same mass")
    void testDenseMaterials() {
        Composition iron = new Composition();
        Composition aluminum = new Composition();

        iron.addMaterialAsRawMass(Material.IRON, 1000.0);
        aluminum.addMaterialAsRawMass(Material.ALUMINUM, 1000.0);

        assertTrue(iron.getTotalVolume() < aluminum.getTotalVolume(),
                "Denser iron takes less volume");
    }

    @Test
    @DisplayName("Light materials: more volume for same mass")
    void testLightMaterials() {
        Composition waterIce = new Composition();
        Composition iron = new Composition();

        waterIce.addMaterialAsRawMass(Material.WATER_ICE, 100.0);
        iron.addMaterialAsRawMass(Material.IRON, 100.0);

        assertTrue(waterIce.getTotalVolume() > iron.getTotalVolume(),
                "Light water ice takes more volume");
    }

    @Test
    @DisplayName("Cargo hold volume constraint")
    void testCargoVolumeConstraint() {
        double cargoHoldVolume = 50.0; // m³
        Composition cargo = new Composition();

        cargo.addMaterialAsVolume(Material.IRON, 20.0);
        cargo.addMaterialAsVolume(Material.ALUMINUM, 15.0);
        cargo.addMaterialAsVolume(Material.SILICA, 10.0);

        double used = cargo.getTotalVolume();
        double remaining = cargoHoldVolume - used;

        assertAll("Cargo tracking",
                () -> assertEquals(45.0, used, TOLERANCE),
                () -> assertEquals(5.0, remaining, TOLERANCE),
                () -> assertTrue(used <= cargoHoldVolume)
        );
    }

    @Test
    @DisplayName("Same volume, different masses")
    void testSameVolumeDifferentMass() {
        Composition iron = new Composition();
        Composition aluminum = new Composition();

        iron.addMaterialAsVolume(Material.IRON, 10.0);
        aluminum.addMaterialAsVolume(Material.ALUMINUM, 10.0);

        assertAll("Same volume comparison",
                () -> assertEquals(10.0, iron.getTotalVolume(), TOLERANCE),
                () -> assertEquals(10.0, aluminum.getTotalVolume(), TOLERANCE),
                () -> assertTrue(iron.getTotalMass() > aluminum.getTotalMass())
        );
    }

    @Test
    @DisplayName("Realistic cargo manifest")
    void testRealisticManifest() {
        Composition cargo = new Composition();

        cargo.addMaterialAsVolume(Material.IRON, 2.0);
        cargo.addMaterialAsVolume(Material.ALUMINUM, 3.0);
        cargo.addMaterialAsVolume(Material.WATER_ICE, 5.0);

        double expectedMass = 2.0 * Material.IRON.getDensity() +
                3.0 * Material.ALUMINUM.getDensity() +
                5.0 * Material.WATER_ICE.getDensity();

        assertAll("Cargo manifest",
                () -> assertEquals(10.0, cargo.getTotalVolume(), TOLERANCE),
                () -> assertEquals(expectedMass, cargo.getTotalMass(), TOLERANCE),
                () -> assertEquals(2.0, cargo.getVolume(Material.IRON), TOLERANCE),
                () -> assertEquals(3.0, cargo.getVolume(Material.ALUMINUM), TOLERANCE),
                () -> assertEquals(5.0, cargo.getVolume(Material.WATER_ICE), TOLERANCE)
        );
    }
}