package com.kaymlyn.planeteater.simulation.vehicles;

import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.entities.Automaton;
import com.kaymlyn.planeteater.simulation.operations.TravelCalculator;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;
import java.util.Map;

/**
 * Represents a spacecraft for traveling between celestial bodies
 * Can carry cargo and mining entities
 * Recyclable - can be dismantled for materials
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@EqualsAndHashCode(callSuper = false)
@Data
public class Spacecraft extends Vehicle {
    
    public enum SpacecraftState {
        DOCKED,         // At platform
        TRAVELING,      // In transit
        STRANDED
    }
    private Composition construction;   // Materials used to build the spacecraft
    private Composition cargo;
    private List<Automaton> crew;

    private SpacecraftState state;
    private Orbiter location;
    
    public Spacecraft(String id,
                      double dryMass,
                      double maxFuelCapacity,
                      double cargoCapacity,
                      double exhaustVelocity,
                      boolean hasLifeSupport,
                      int maxCrewCapacity,
                      int minCrewRequirement) {
        super(id, dryMass, maxFuelCapacity, cargoCapacity, exhaustVelocity, hasLifeSupport, maxCrewCapacity, minCrewRequirement);
        this.id = id;

        this.construction = new Composition();
        this.state = SpacecraftState.DOCKED;
    }

    public double planRoute(Orbiter destination, boolean dock) {
        double fuelRequired = 0.0;
        if(location != null) {

            if(location instanceof Planet) {
                double originRadius = ((Planet) location).getRadius();
                fuelRequired += TravelCalculator.calculateTakeoffDeltaV(location.getMass(),originRadius,originRadius*1.1, this);
                fuelRequired += TravelCalculator.calculateRendezvous(TravelCalculator.randomUnitVector().multiply(originRadius*1.1).add(location.getPosition()),destination,this).fuelRequired;
            }
            else {
                fuelRequired += TravelCalculator.calculateRendezvous(location.getPosition(),destination,this).fuelRequired;
            }
        }

        if(dock) {
            if(destination instanceof Planet) {
                fuelRequired += TravelCalculator.calculateLanding(
                        ((Planet) destination).getRadius() * 1.1,
                        destination.getMass(),
                        ((Planet) destination).getRadius(),
                        this);
            } else {
                fuelRequired += TravelCalculator.calculateLanding(500, destination.getMass(), 0, this);
            }
        }
        return fuelRequired;
    }

    /**
     * Recycle the spacecraft, returning all construction materials
     */
    public Composition recycle() {
        Composition materials = new Composition();
        
        // Return all construction materials
        for (Map.Entry<Material, Double> entry : construction.getMaterials().entrySet()) {
            materials.addMaterialAsVolume(entry.getKey(), entry.getValue());
        }
        
        // Return any remaining fuel (assuming it's a recyclable type)
        // In practice, fuel might be hydrogen or similar
        return materials;
    }
    
    @Override
    public String toString() {
        return String.format("com.kaymlyn.planeteater.vehicles.Spacecraft[id=%s, state=%s, mass=%.1f kg, fuel=%.1f/%.1f kg, " +
            "cargo=%.1f/%.1f kg, crew=%d/%d, deltaV=%.1f m/s]",
            id, state, getTotalMass(), fuelMass, maxFuelCapacity,
            cargo.getTotalMass(), cargoCapacity, crew.size(), maxCrewCapacity,
            getAvailableDeltaV());
    }
}