package com.kaymlyn.planeteater.simulation.vehicles;

import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.Orbit;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.entities.Automaton;
import com.kaymlyn.planeteater.simulation.physics.Itinerary;
import com.kaymlyn.planeteater.simulation.physics.ManeuverDetails;
import com.kaymlyn.planeteater.simulation.physics.OrbitalState;
import com.kaymlyn.planeteater.simulation.physics.PiecewiseState;
import com.kaymlyn.planeteater.simulation.physics.RocketryCalculator;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Represents a spacecraft for traveling between celestial bodies
 * Can carry cargo and mining entities
 * Recyclable - can be dismantled for materials
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@EqualsAndHashCode(callSuper = false)
@Data
public class Spacecraft extends Vehicle {

    public enum SpacecraftState {
        DOCKED,         // At platform
        TRAVELING,      // In transit
        ORBITING,
        STRANDED
    }

    private Composition construction;   // Materials used to build the spacecraft
    private Composition cargo;
    private List<Automaton> crew;

    private SpacecraftState state;
    private Orbiter orbiting;
    private Itinerary itinerary;
    private List<PiecewiseState> telemetry;
    private int currentTravelCycle;
    private double transitTime;

    private OrbitalSystem system;

    public Spacecraft(String id,
                      double dryMass,
                      double maxFuelCapacity,
                      double cargoCapacity,
                      double exhaustVelocity,
                      boolean hasLifeSupport,
                      int maxCrewCapacity,
                      int minCrewRequirement,
                      Orbiter shipyard) {
        super(id, dryMass, maxFuelCapacity, cargoCapacity, exhaustVelocity, hasLifeSupport, maxCrewCapacity, minCrewRequirement);

        this.construction = new Composition();
        this.state = SpacecraftState.DOCKED;
        this.itinerary = null;
        this.telemetry = null;
        this.orbiting = shipyard;
        this.system = shipyard.getParentBody().getSystem();
        this.position = shipyard.getPosition();
        this.currentTravelCycle = 0;
        this.cargo = new Composition();
        this.crew = new ArrayList<>();

    }

    public Gravitational getLocation() {
        if(orbiting == null || !(orbiting instanceof Gravitational)) {
            return system.getCentralStar();
        } else {
            return ((Gravitational) orbiting);
        }
    }

    public void programItinerary(Itinerary itinerary){
        this.itinerary = itinerary;
        currentTravelCycle = 0;
    }

    public void completeTravel() {

        consumeFuel(itinerary.getLandingFuel());
        telemetry = null;
        System.out.println("Final Destination : " + orbiting);
        if(itinerary.getFinalSpacecraftState() == SpacecraftState.DOCKED) {
            if(orbiting instanceof Dockable) {
                setState(SpacecraftState.DOCKED);
                system.unregister(this);
            } else if (orbiting instanceof Gravitational) {
                setState(SpacecraftState.ORBITING);
            } else {
                setState(SpacecraftState.STRANDED);
            }
        } else if (itinerary.getFinalSpacecraftState() == SpacecraftState.ORBITING){
            if(orbiting instanceof Gravitational) {
                setState(SpacecraftState.ORBITING);
            } else if (orbiting instanceof Dockable) {
                system.unregister(this);
                setState(SpacecraftState.DOCKED);
            } else {
                setState(SpacecraftState.STRANDED);
            }
        } else {
            setState(SpacecraftState.STRANDED);
        }

        itinerary = null;
    }

    public void simulateTravel() {
        if(itinerary != null) {
            if(telemetry == null) {
                telemetry = itinerary.generateTelemetry(system.getTimeStep());
            }
            if(telemetry == null) {
                return;
            }

            //Launch to Orbit
            if(currentTravelCycle == 0) {
                consumeFuel(itinerary.getLaunchFuel());
                this.state = SpacecraftState.ORBITING;
                itinerary.setStartTime(system.getCurrentTime());
                system.register(this);
            }

            //Step through Telemetry based on
            if(telemetry.size() > currentTravelCycle) {
                position = telemetry.get(currentTravelCycle).position;
                if(!Double.isNaN(position.getZ())) {
                    this.state = SpacecraftState.TRAVELING;
                }
                currentTravelCycle++;
            } else {
                //Arrive at destination
                Vector3D finalPosition = null;
                if(itinerary.getFinalDestination() != null) {
                    this.orbiting = itinerary.getFinalDestination();
                    if(itinerary.getFinalSpacecraftState() == SpacecraftState.DOCKED) {
                        finalPosition = this.orbiting.getPosition();
                    } else {
                        finalPosition = telemetry.getLast().position;
                    }
                }

                if(finalPosition == null && !telemetry.isEmpty()) {
                    finalPosition = telemetry.getLast().position;
                } else {
                    finalPosition = position;
                }
                position = finalPosition;
                completeTravel();
            }
        }
    }

    //Calculate a dry run of the route
    public Itinerary planRoute(@NonNull Orbiter destination, boolean land) {

        Itinerary route = new Itinerary();

        Orbit destinationOrbit = destination.calculateCurrentOrbit();
        route.setFinalDestination(destination);
        ManeuverDetails active = null;
        double totalDeltaV = 0;
        System.out.println("Fuel Spend : " + totalDeltaV);
        //takeoff
        if (orbiting != null) {
            //launch if not in orbit
            if(state == SpacecraftState.DOCKED) {
                // launch out of a gravitational well
                // otherwise undocking from a space station negligible deltav for undocking. this can definitely change
                // in the future for large stations.
                if (orbiting instanceof Gravitational) {
                    ManeuverDetails takeoff = RocketryCalculator.calculateTakeoffToStandardOrbit(((Planet) orbiting), this);
                    totalDeltaV += takeoff.getDeltaV();
                    route.setLaunchFuel(fuelRequired(takeoff.getDeltaV()));
                    System.out.println("Fuel Spend - launch : " + totalDeltaV);
                    route.addFlightPlan(takeoff);
                    active = takeoff;
                    //get into orbit around parent gravitational body, unless star. Can't escape the star.
                    if(orbiting instanceof Planet) {
                        ManeuverDetails escape = RocketryCalculator.calculateEscapeOrbit(
                            takeoff.getOrbitState(),
                                orbiting);
                        totalDeltaV += escape.getDeltaV();
                        System.out.println("Fuel Spend - escape : " + totalDeltaV);
                        route.addFlightPlan(escape);
                        active = escape;
                    }

                } else { //You're on a satellite harry
                    ManeuverDetails detach = new ManeuverDetails(Orbit.calculateOrbit(orbiting.getParentBody(),this.position, this.orbiting.getVelocity()));
                    totalDeltaV += detach.getDeltaV();
                    System.out.println("Fuel Spend - detach : " + totalDeltaV);
                    route.addFlightPlan(detach);
                    active = detach;
                }
            } else if (state == SpacecraftState.ORBITING) { //Ship already in orbit. let's escape
                //unless it's a star
                if (orbiting instanceof Planet) {
                    active = RocketryCalculator.calculateEscapeOrbit(
                            Orbit.calculateOrbit((Gravitational) orbiting, position, velocity),
                            orbiting);
                    totalDeltaV += active.getDeltaV();
                    System.out.println("Fuel Spend - escape : " + totalDeltaV);
                    route.addFlightPlan(active);
                }
            }
        }

        ManeuverDetails coplanarBurn;
        //get into coplanar orbit with the destination
        if(active == null) {//You've been orbiting a star or on a satellite.

            coplanarBurn = RocketryCalculator.adjustToCoplanar(
                    Orbit.calculateOrbit(destinationOrbit.centerBody(), position, velocity), // <-- velocity is zero.
                    destinationOrbit
            );
        } else { //get coplanar
            coplanarBurn = RocketryCalculator.adjustToCoplanar(
                    Orbit.calculateOrbit(destinationOrbit.centerBody(), active.getEndingPosition(), active.getEndingVelocity()),
                    destinationOrbit
            );
        }

        totalDeltaV += coplanarBurn.getDeltaV();
        System.out.println("Fuel Spend - coplanar : " + totalDeltaV);
        route.addFlightPlan(coplanarBurn);
        active = coplanarBurn;

        //time to wait for Hohmann Transfer
        ManeuverDetails wait = new ManeuverDetails(
                active.getOrbitState(),
                RocketryCalculator.calculateNextLaunchWindowWaitTime(active.getOrbitState(), destinationOrbit)
        );
        route.addFlightPlan(wait);

        //Hohmann Transfer. should be fine for most orbital transfers at this stage.
        // TODO: add a switch to different transfers in the future fuel and time optimizations can be made depending on what maneuvers are chosen
        ManeuverDetails transfer = RocketryCalculator.calculateHohmannTransferBetweenOrbits(wait.getOrbitState(),destinationOrbit);
        totalDeltaV += transfer.getDeltaV();
        System.out.println("Fuel Spend - Hohmann : " + totalDeltaV);
        route.addFlightPlan(transfer);
        active = transfer;

        //finalizing travel
        if(destination instanceof Gravitational) {
            //get into orbit
            ManeuverDetails capture = RocketryCalculator.calculateOrbitalInsertionDeltaV(
                    active.getOrbitState(),
                    (Gravitational) destination,
                    destination,
                    ((Gravitational) destination).getStandardOrbitalAltitude());
            totalDeltaV += capture.getDeltaV();
            System.out.println("Fuel Spend - capture : " + totalDeltaV);
            route.addFlightPlan(capture);
            if(land) {
                //landing
                ManeuverDetails landing = RocketryCalculator.calculateLandingOnGravitational((Gravitational) destination,this);
                route.addFlightPlan(landing);
                active = landing;
                double landingFuel = active.getDeltaV();
                totalDeltaV += landingFuel;
                System.out.println("Fuel Spend - land : " + totalDeltaV);
                route.setLandingFuel(fuelRequired(landingFuel));
                route.setFinalSpacecraftState(SpacecraftState.DOCKED);
            } else {
                //orbiting
                route.setFinalSpacecraftState(SpacecraftState.ORBITING);
                route.setLandingFuel(0.0);
            }
        } else {
            //slow down or catch up with the space station
            System.out.println("Match Velocity" + RocketryCalculator.calculateMatchVelocity(
                    active.getEndingVelocity(),
                    destinationOrbit.calculateOrbitAfterT0(route.getTotalFlightTime()).velocity()));
            OrbitalState futureState = destinationOrbit.calculateOrbitAfterT0(route.getTotalFlightTime());
            ManeuverDetails match = new ManeuverDetails(
                    active.getEndingPosition(),
                    active.getEndingVelocity(),
                    futureState.position(),
                    futureState.velocity(),
                    RocketryCalculator.calculateMatchVelocity(
                    active.getEndingVelocity(),
                    destinationOrbit.calculateOrbitAfterT0(route.getTotalFlightTime()).velocity()),
                    futureState.orbitalElements(),
                    0.0);
            totalDeltaV += match.getDeltaV();
            System.out.println("Fuel Spend - match : " + totalDeltaV);
            route.addFlightPlan(match);

            route.setLandingFuel(0.0);
            route.setFinalSpacecraftState(SpacecraftState.DOCKED);
        }
//        route.setTotalFuelCost(totalDeltaV);
        System.out.println("Total DeltaV Required : " + totalDeltaV + " Total DeltaV Available : " + getAvailableDeltaV());
        return route;
    }

    /**
     * Recycle the spacecraft, returning all construction materials
     */
    public Composition recycle() {
        Composition materials = new Composition();
        
        // Return all construction materials
        for (Map.Entry<Material, Double> entry : construction.getMaterials().entrySet()) {
            materials.addMaterialAsVolume(entry.getKey(), entry.getValue());
        }
        
        // Return any remaining fuel (assuming it's a recyclable type)
        // In practice, fuel might be hydrogen or similar
        system.unregister(this);
        return materials;
    }
    
    @Override
    public String toString() {
        return String.format("com.kaymlyn.planeteater.vehicles.Spacecraft[id=%s, state=%s, mass=%.1f kg, fuel=%.1f/%.1f kg, " +
            "cargo=%.1f/%.1f kg, crew=%d/%d, deltaV=%.1f m/s]",
            id, state, getTotalMass(), fuelMass, maxFuelCapacity,
            cargo.getTotalMass(), cargoCapacity, crew.size(), maxCrewCapacity,
            getAvailableDeltaV());
    }
}