package com.kaymlyn.planeteater.simulation.vehicles;

import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.PhysicsBody;
import com.kaymlyn.planeteater.simulation.physics.Itinerary;
import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.physics.ScheduledBurn;
import com.kaymlyn.planeteater.simulation.physics.TransferPlanner;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NonNull;

import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;

/**
 * A crewable, thruster-equipped vehicle capable of significant orbital maneuvers.
 *
 * Spacecraft extends Vehicle (crewable construct with inventory) and implements
 * PhysicsBody (participates in gravitational integration). It does NOT implement
 * Orbiter: spacecraft are not primarily defined by a gravitational parent body.
 * Their position is owned by the physics simulation when in flight, and by their
 * docking platform when docked.
 *
 * State machine:
 *   DOCKED    - position and velocity delegated to the docking platform.
 *               Not in physics simulation.
 *   TRAVELING - active itinerary, burns executing on schedule.
 *               In physics simulation (physicsBody map + spacecraftInTransit).
 *   ORBITING  - no active itinerary, physics owns trajectory.
 *               In physics simulation (physicsBody map only).
 *               Covers both intentional orbit and out-of-fuel drift.
 *               Check getFuelMass() > 0 to determine if maneuvering is possible.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@EqualsAndHashCode(callSuper = false)
@Data
public class Spacecraft extends Vehicle implements PhysicsBody {

    public enum SpacecraftState {
        DOCKED,
        TRAVELING,
        ORBITING
    }

    private SpacecraftState state;
    private Orbiter orbiting;
    private Itinerary itinerary;

    // Position and velocity owned by Spacecraft (not inherited from Vehicle)
    private Vector3D position;
    private Vector3D velocity;

    private OrbitalSystem system;

    public Spacecraft(String id,
                      Composition construction,
                      double maxFuelCapacity,
                      double cargoCapacity,
                      double exhaustVelocity,
                      boolean hasLifeSupport,
                      int maxCrewCapacity,
                      int minCrewRequirement,
                      Orbiter shipyard) {
        super(id, construction, maxFuelCapacity, cargoCapacity, exhaustVelocity,
                hasLifeSupport, maxCrewCapacity, minCrewRequirement);

        this.state = SpacecraftState.DOCKED;
        this.itinerary = null;
        this.orbiting = shipyard;
        this.system = shipyard.getParentBody().getSystem();
        this.position = shipyard.getPosition();
        this.velocity = shipyard.getVelocity();
    }

    // ==================== PHYSICSBODY ====================

    /**
     * Current position in meters.
     * When DOCKED, delegates to the docking platform.
     * When TRAVELING or ORBITING, returns the spacecraft's own integrated position.
     */
    @Override
    public Vector3D getPosition() {
        if (state == SpacecraftState.DOCKED && orbiting != null) {
            return orbiting.getPosition();
        }
        return position;
    }

    /**
     * Calculate orbital elements from current position and velocity.
     *
     * The result is only valid at this instant. In an n-body system, the actual
     * trajectory will diverge immediately due to perturbations from other bodies.
     * Use this for analysis and trajectory planning, not for position tracking.
     *
     * @return orbital elements at this instant
     */
    @Override
    public Orbit snapshotOrbit() {
        if(orbiting instanceof Gravitational grav) {
            return Orbit.fromState(grav, getPosition(), getVelocity());
        } else {
            return Orbit.fromState(system.getCentralStar(), getPosition(), getVelocity());
        }
    }

    /**
     * Current velocity in m/s.
     * When DOCKED, delegates to the docking platform.
     * When TRAVELING or ORBITING, returns the spacecraft's own integrated velocity.
     */
    @Override
    public Vector3D getVelocity() {
        if (state == SpacecraftState.DOCKED && orbiting != null) {
            return orbiting.getVelocity();
        }
        return velocity;
    }

    /**
     * Apply a gravitational acceleration for one time step.
     * The Verlet integrator calls setPosition/setVelocity directly; this method
     * is provided for callers that need a single-call update.
     */
    @Override
    public void update(Vector3D acceleration, double timeStep) {
        velocity = velocity.add(acceleration.multiply(timeStep));
        position = position.add(velocity.multiply(timeStep));
    }

    // ==================== NAVIGATION ====================

    /**
     * The gravitational body this spacecraft is primarily associated with.
     * Falls back to the central star when not associated with a gravitational body.
     *
     * @return associated gravitational body, never null
     */
    public Gravitational getLocation() {
        if (orbiting instanceof Gravitational gravitational) {
            return gravitational;
        }
        return system.getCentralStar();
    }

    public double getMass() {
        return super.getTotalMass();
    }

    /**
     * Program an itinerary for the next launch.
     *
     * @param itinerary planned sequence of burns
     */
    public void programItinerary(Itinerary itinerary) {
        this.itinerary = itinerary;
    }

    /**
     * Plan a route to a destination using the transfer planner.
     *
     * @param destination   target body
     * @param land          true to dock at destination, false to orbit
     * @param departureTime absolute simulation time to depart
     * @param priority      optimization goal
     * @return a feasible itinerary, or null if no valid transfer exists
     */
    public Itinerary planRoute(
            @NonNull Orbiter destination,
            boolean land,
            double departureTime,
            TransferPlanner.OptimizationGoal priority) {

        List<TransferPlanner.TransferOption> options =
                TransferPlanner.generateTransferOptions(
                        this,
                        this.orbiting,
                        destination,
                        land,
                        departureTime
                );

        TransferPlanner.TransferOption bestOption =
                TransferPlanner.selectBestTransfer(
                        options,
                        Objects.requireNonNullElse(priority,
                                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV)
                );

        return bestOption != null ? bestOption.getItinerary() : null;
    }

    // ==================== SIMULATION ====================

    /**
     * Execute any scheduled burns whose time has been reached, then check for
     * itinerary completion. Called each step by OrbitalSystem for all spacecraft
     * in spacecraftInTransit.
     */
    public void simulateTravel() {
        if (itinerary == null) {
            return;
        }

        double currentTime = system.getCurrentTime();

        ScheduledBurn nextBurn = itinerary.getNextBurn(currentTime);
        while (nextBurn != null && nextBurn.shouldExecute(currentTime)) {

            Vector3D preBurnVelocity = velocity;

            velocity = velocity.add(nextBurn.deltaVelocity());

            double fuelNeeded = nextBurn.fuelRequired(getTotalMass(), exhaustVelocity);
            double fuelConsumed = consumeFuel(fuelNeeded);

            if (fuelConsumed < fuelNeeded * 0.99) {
                // Out of fuel: transition to ORBITING. Physics continues; transit ends.
                System.err.printf(
                        "WARNING: %s ran out of fuel during burn %s. Drifting.%n",
                        id, nextBurn.id());
                setState(SpacecraftState.ORBITING);
                system.unregister(this);
                itinerary = null;
                return;
            }

            itinerary.removeBurn(nextBurn);

            System.out.printf(
                    "[T=%.1f] %s executed %s: dv=%.1f m/s, fuel=%.1f kg, v: %s -> %s%n",
                    currentTime, id, nextBurn.description(),
                    nextBurn.deltaVelocity().magnitude(), fuelConsumed,
                    preBurnVelocity, velocity
            );

            if (state == SpacecraftState.DOCKED) {
                state = SpacecraftState.TRAVELING;
            }

            nextBurn = itinerary.getNextBurn(currentTime);
        }

        if (itinerary.isComplete(currentTime)) {
            try {
                consumeFuel(itinerary.getBurns().getLast().fuelRequired(getTotalMass(), exhaustVelocity));
            } catch (NoSuchElementException ignore) {
                System.out.println("No burns to spend fuel on.");
            }
            completeTravel();
        }
    }

    /**
     * Transition to the final state specified by the completed itinerary.
     *
     * DOCKED:   dock with destination platform; platform manages position forward.
     *           Removed from physics simulation entirely.
     * ORBITING: associate with destination; physics owns trajectory.
     *           Removed from transit management only.
     */
    private void completeTravel() {
        if (itinerary == null) {
            return;
        }

        System.out.printf(
                "[T=%.1f] %s completed itinerary to %s%n",
                system.getCurrentTime(), id,
                itinerary.getDestination() != null
                        ? itinerary.getDestination().getId()
                        : "destination"
        );

        Orbiter destination = itinerary.getDestination();
        SpacecraftState targetState = itinerary.getFinalState();
        itinerary = null;

        if (targetState == SpacecraftState.DOCKED && destination instanceof Dockable dockable) {
            dockable.dock(this);
            setState(SpacecraftState.DOCKED);
            orbiting = destination;
            system.unregisterAndRemoveFromPhysics(this);
            return;
        }

        // ORBITING - or DOCKED fallback when destination is not Dockable
        orbiting = destination;
        setState(SpacecraftState.ORBITING);
        system.unregister(this);
    }

    // ==================== LAUNCH ====================

    /**
     * Launch this spacecraft.
     *
     * Validates the itinerary and fuel, captures position and velocity from the
     * docking platform, undocks, then registers with OrbitalSystem for Verlet
     * integration and burn execution.
     *
     * @param timeStep simulation time step, used to consolidate near-coincident burns
     * @return true if launch succeeded
     */
    public boolean launch(double timeStep) {
        if (itinerary == null) {
            System.err.println("Cannot launch: no itinerary programmed");
            return false;
        }
        if (!itinerary.isFeasible()) {
            System.err.println("Cannot launch: " + itinerary.getInfeasibilityReason());
            return false;
        }
        if (state != SpacecraftState.DOCKED) {
            System.err.println("Cannot launch: not docked");
            return false;
        }

        double totalDeltaV = itinerary.getTotalDeltaV();
        double burnsRemoved = itinerary.consolidate(timeStep);
        double deltaDeltaV = totalDeltaV - itinerary.getTotalDeltaV();
        System.out.printf("%d burns consolidated for %.2f less delta-V.%n",
                (int) burnsRemoved, deltaDeltaV);

        double requiredFuel = 0.0;
        double runningMass = getTotalMass();
        for (ScheduledBurn burn : itinerary.getBurns()) {
            double fuelNeeded = burn.fuelRequired(runningMass, exhaustVelocity);
            requiredFuel += fuelNeeded;
            runningMass -= fuelNeeded;
        }

        if (requiredFuel > fuelMass) {
            System.err.printf(
                    "Cannot launch: insufficient fuel (need %.1f kg, have %.1f kg)%n",
                    requiredFuel, fuelMass);
            return false;
        }

        this.position = orbiting.getPosition();
        this.velocity = orbiting.getVelocity();

        if (orbiting instanceof Dockable dockable) {
            dockable.getHanger().remove(this.id);
        }

        setState(SpacecraftState.TRAVELING);
        system.registerSpacecraft(this);

        System.out.printf(
                "[T=%.1f] %s launched from %s with %d scheduled burns%n",
                system.getCurrentTime(), id, orbiting.getId(),
                itinerary.getBurns().size()
        );

        return true;
    }

    // ==================== LIFECYCLE ====================

    /**
     * Disassemble this spacecraft and return its construction materials.
     * Removes from both transit tracking and physics integration.
     *
     * @return Composition of construction materials
     */
    @Override
    public Composition recycle() {
        Composition materials = super.recycle();
        system.unregisterAndRemoveFromPhysics(this);
        return materials;
    }

    @Override
    public String toString() {
        return String.format(
                "Spacecraft[id=%s, state=%s, mass=%.1f kg, fuel=%.1f/%.1f kg, " +
                        "cargo=%.1f/%.1f m^3, crew=%d/%d, deltaV=%.1f m/s]",
                id, state, getTotalMass(), fuelMass, maxFuelCapacity,
                cargo.getTotalVolume(), cargoCapacity,
                crew.size(), maxCrewCapacity,
                getAvailableDeltaV());
    }
}