package com.kaymlyn.planeteater.simulation.vehicles;

import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;

/**
 * Factory for pre-configured spacecraft archetypes.
 *
 * All vehicles are sized against the Tsiolkovsky rocket equation:
 *
 *   delta-V = v_exhaust * ln(mass_initial / mass_final)
 *
 * where mass_initial = dry_mass + fuel_mass and mass_final = dry_mass.
 *
 * =====================================================================
 * DELTA-V EFFICIENCY REFERENCE
 * =====================================================================
 *
 * Efficiency is determined by two independent factors:
 *
 * 1. EXHAUST VELOCITY (v_exhaust = Isp * 9.81 m/s)
 *    The speed at which propellant exits the engine. Higher exhaust
 *    velocity produces more delta-V per kilogram of propellant burned.
 *    This is the primary efficiency metric - doubling exhaust velocity
 *    doubles delta-V for the same propellant mass fraction.
 *
 *    Propulsion type          Exhaust velocity (m/s)   Thrust
 *    Cold gas (N2, CO2)       400  -  700              Very low
 *    Monopropellant hydrazine 1,600 - 2,300             Low
 *    Bipropellant chemical    2,900 - 4,500             High
 *    Nuclear thermal          8,000 - 9,000             Medium-high
 *    Ion drive (xenon)        20,000 - 80,000           Very low
 *    Solar sail               Effectively infinite      Negligible
 *
 * 2. MASS RATIO (mass_initial / mass_final)
 *    The ratio of total launch mass to dry mass. A vehicle that is 90%
 *    propellant by mass has mass_ratio = 10 and achieves
 *    delta-V = v_exhaust * ln(10) = 2.30 * v_exhaust.
 *    A 50% propellant fraction achieves only 0.69 * v_exhaust.
 *
 *    Structural efficiency (lighter dry mass for the same payload) and
 *    propellant density (denser propellants pack more mass into the same
 *    tank volume) both improve the achievable mass ratio.
 *
 * PRACTICAL DELTA-V REQUIREMENTS (approximate):
 *    Inner asteroid belt transfer (nearby):     100 -   500 m/s
 *    Inner asteroid belt transfer (distant):    500 - 2,000 m/s
 *    Earth to Mars (departure only):                 ~2,945 m/s
 *    Mars orbit insertion (capture):                 ~2,085 m/s
 *    Earth to Mars round trip (total):              ~10,000 m/s
 *
 * NOTE ON ION DRIVES:
 *    The current simulation uses impulsive burn modeling (instantaneous
 *    delta-V). Ion drives produce thrust over days or weeks and require
 *    continuous-burn trajectory integration. This is a planned future
 *    extension: a ContinuousBurn record type and a LowThrustPlanner.
 *    The Verlet integrator already supports continuous forces; the main
 *    work is in trajectory planning, not physics simulation.
 * =====================================================================
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class VehicleFactory {

    /**
     * Create a small unmanned cargo probe for early-game asteroid transfers.
     *
     * Sized at Cube Sat scale. Monopropellant hydrazine propulsion.
     * Sufficient for inner asteroid belt hops of 100-1000 m/s delta-V.
     * Not suitable for planetary transfers.
     *
     * Dry mass:  ~7.2 kg (aluminum + titanium frame)
     * Fuel mass: 5.0 kg hydrazine
     * Exhaust velocity: 2,200 m/s (monopropellant)
     * Available delta-V: ~1,150 m/s
     */
    public static Spacecraft createCubeSat(String id, Dockable shipyard) {
        Composition construction = new Composition();
        construction.addMaterialAsVolume(Material.ALUMINUM, 0.001);
        construction.addMaterialAsVolume(Material.TITANIUM, 0.001);

        Spacecraft ship = new Spacecraft(
                id,
                construction,
                5.0,      // fuel mass kg - hydrazine monopropellant
                0.5,      // cargo capacity m^3
                2200.0,   // exhaust velocity m/s - monopropellant hydrazine
                false,    // no life support
                0,        // no crew capacity
                0,        // no crew requirement
                shipyard
        );
        shipyard.dock(ship);
        return ship;
    }

    /**
     * Create a crewed interplanetary mining vessel for mid-game operations.
     *
     * Bipropellant chemical propulsion. Suitable for asteroid belt to
     * inner planet transfers. Carries a small crew with life support.
     *
     * Dry mass:  ~5,000 kg
     * Fuel mass: 15,000 kg bipropellant
     * Exhaust velocity: 4,000 m/s (bipropellant chemical)
     * Available delta-V: ~4,394 m/s
     */
    public static Spacecraft createMiningVessel(String id, Orbiter shipyard) {
        Composition construction = new Composition();
        construction.addMaterialAsRawMass(Material.ALUMINUM, 2500.0);
        construction.addMaterialAsRawMass(Material.TITANIUM, 1500.0);
        construction.addMaterialAsRawMass(Material.SILICA, 500.0);
        construction.addMaterialAsRawMass(Material.WATER_ICE, 500.0);

        return new Spacecraft(
                id,
                construction,
                15000.0,  // fuel mass kg
                15.0,     // cargo capacity m^3
                4000.0,   // exhaust velocity m/s - bipropellant
                true,     // life support for crew
                2,        // max crew
                1,        // min crew
                shipyard
        );
    }

    /**
     * Create a heavy unmanned cargo hauler for bulk resource transport.
     *
     * High thrust bipropellant. Large cargo volume for late-game logistics.
     *
     * Dry mass:  ~10,000 kg
     * Fuel mass: 20,000 kg
     * Exhaust velocity: 4,500 m/s (high-performance bipropellant)
     * Available delta-V: ~2,877 m/s
     */
    public static Spacecraft createHeavyHauler(String id, Orbiter shipyard) {
        Composition construction = new Composition();
        construction.addMaterialAsRawMass(Material.IRON, 5000.0);
        construction.addMaterialAsRawMass(Material.ALUMINUM, 3000.0);
        construction.addMaterialAsRawMass(Material.TITANIUM, 2000.0);

        return new Spacecraft(
                id,
                construction,
                20000.0,  // fuel mass kg
                200.0,    // cargo capacity m^3 - large hold
                4500.0,   // exhaust velocity m/s
                false,    // no life support
                0,        // unmanned
                0,
                shipyard
        );
    }

    /**
     * Create a purpose-built interplanetary transfer vehicle.
     *
     * High mass ratio bipropellant design capable of Earth-Mars transfers
     * including orbit insertion. Not intended for cargo operations.
     *
     * Dry mass:  ~1,000 kg
     * Fuel mass: 8,000 kg
     * Exhaust velocity: 4,500 m/s (high-performance bipropellant)
     * Available delta-V: ~9,592 m/s - sufficient for Earth-Mars round trip
     */
    public static Spacecraft createInterplanetaryProbe(String id, Dockable shipyard) {
        Composition construction = new Composition();
        construction.addMaterialAsRawMass(Material.TITANIUM, 600.0);
        construction.addMaterialAsRawMass(Material.ALUMINUM, 400.0);

        Spacecraft ship = new Spacecraft(
                id,
                construction,
                8000.0,   // fuel mass kg
                2.0,      // minimal cargo capacity m^3
                4500.0,   // exhaust velocity m/s
                false,    // unmanned
                0,
                0,
                shipyard
        );
        shipyard.dock(ship);
        return ship;
    }
}