package com.kaymlyn.planeteater.simulation.vehicles;

import com.kaymlyn.planeteater.simulation.entities.Automaton;
import com.kaymlyn.planeteater.simulation.entities.EntityType;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Abstract base class for all crewable constructs with an inventory.
 *
 * Vehicle models the common capabilities shared by any construct that can carry
 * crew and resources: fuel management, cargo loading, crew boarding, and
 * propulsion budget calculations via the Tsiolkovsky rocket equation.
 *
 * Vehicle deliberately does NOT own position or velocity. Those are PhysicsBody
 * concerns and belong to the implementation that participates in the physics
 * simulation (Orbiter for stations and celestial bodies, Spacecraft for
 * thruster-equipped vehicles).
 *
 * Vehicle does NOT have an abstract getLocation() method. Location is a
 * Spacecraft-level concept tied to the simulation state machine. Planetside
 * vehicles, stations, and future constructs have their own location semantics.
 *
 * Cargo capacity is VOLUME-based (m^3), not mass-based (kg). Physical space
 * is the limiting resource; dense materials pack more mass into the same volume.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@EqualsAndHashCode
@ToString
@Data
@NoArgsConstructor
public abstract class Vehicle {

    protected String id;
    private Composition construction;   // kg - mass of vehicle without fuel or cargo
    protected double fuelMass;          // kg - current fuel load
    protected double maxFuelCapacity;   // kg - maximum fuel the vehicle can carry
    protected double cargoCapacity;     // m^3 - maximum cargo volume
    protected double exhaustVelocity;   // m/s - effective exhaust velocity (Isp * g0)
    protected boolean hasLifeSupport;   // whether organic crew can be carried
    protected int maxCrewCapacity;      // maximum number of crew entities
    protected int minCrewRequirement;   // minimum crew needed to operate
    protected Composition cargo;        // current cargo (tracks mass and volume internally)
    protected List<Automaton> crew;     // current crew

    public Vehicle(String id,
                   Composition construction,
                   double maxFuelCapacity,
                   double cargoCapacity,
                   double exhaustVelocity,
                   boolean hasLifeSupport,
                   int maxCrewCapacity,
                   int minCrewRequirement) {

        this.id = id;
        this.construction = construction;
        this.fuelMass = maxFuelCapacity; // start fully fueled
        this.maxFuelCapacity = maxFuelCapacity;
        this.cargoCapacity = cargoCapacity;
        this.exhaustVelocity = exhaustVelocity;
        this.hasLifeSupport = hasLifeSupport;
        this.maxCrewCapacity = maxCrewCapacity;
        this.minCrewRequirement = minCrewRequirement;
        this.cargo = new Composition();
        this.crew = new ArrayList<>();
    }

    /**
     * Total current mass: dry mass plus fuel, cargo, and crew.
     *
     * @return total mass in kg
     */
    public double getTotalMass() {
        double crewMass = crew.stream().mapToDouble(Automaton::getMass).sum();
        return construction.getTotalMass() + fuelMass + cargo.getTotalMass() + crewMass;
    }

    public double getDryMass() {
        return construction.getTotalMass();
    }

    /**
     * Available cargo space in m^3.
     *
     * @return remaining volume in m^3
     */
    public double getAvailableCargoSpace() {
        return cargoCapacity - cargo.getTotalVolume();
    }

    /**
     * Available crew slots.
     *
     * @return number of additional crew that can board
     */
    public int getAvailableCrewSlots() {
        return maxCrewCapacity - crew.size();
    }

    /**
     * Add fuel up to capacity.
     *
     * @param amount kg to add
     * @return actual amount added
     */
    public double addFuel(double amount) {
        double space = maxFuelCapacity - fuelMass;
        double toAdd = Math.min(amount, space);
        fuelMass += toAdd;
        return toAdd;
    }

    /**
     * Consume fuel for propulsion.
     *
     * @param amount kg to consume
     * @return actual amount consumed (may be less if tank is low)
     */
    public double consumeFuel(double amount) {
        double toConsume = Math.min(amount, fuelMass);
        fuelMass -= toConsume;
        return toConsume;
    }

    /**
     * Load cargo by volume.
     *
     * @param material the material to load
     * @param volume   volume in m^3
     * @return actual volume loaded (limited by available space)
     */
    public double loadCargo(Material material, double volume) {
        double available = getAvailableCargoSpace();
        double toLoad = Math.min(volume, available);
        if (toLoad > 0) {
            cargo.addMaterialAsVolume(material, toLoad);
        }
        return toLoad;
    }

    /**
     * Unload cargo by volume.
     *
     * @param material the material to unload
     * @param volume   volume in m^3 to unload
     * @return actual volume unloaded
     */
    public double unloadCargo(Material material, double volume) {
        if (volume <= 0 || material == null) {
            return 0.0;
        }
        double massToRemove = material.massForVolume(volume);
        double actualMassRemoved = cargo.removeMaterial(material, massToRemove);
        return material.volumeForMass(actualMassRemoved);
    }

    /**
     * Board a crew member or robot.
     *
     * Inorganic automatons (robots) can board any vehicle.
     * Organic automatons (humans) require life support.
     *
     * @param entity the automaton to board
     * @return true if boarding succeeded
     */
    public boolean boardAutomaton(Automaton entity) {
        if (crew.size() >= maxCrewCapacity) {
            return false;
        }
        if (entity.getType() == EntityType.INORGANIC) {
            crew.add(entity);
            return true;
        }
        if (entity.getType() == EntityType.ORGANIC && !hasLifeSupport) {
            return false;
        }
        crew.add(entity);
        return true;
    }

    /**
     * Disembark a crew member.
     *
     * @param entity the automaton to disembark
     * @return the entity if found and removed, null otherwise
     */
    public Automaton disembarkCrew(Automaton entity) {
        if (crew.remove(entity)) {
            return entity;
        }
        return null;
    }

    /**
     * Delta-V available with current fuel load.
     * Tsiolkovsky: delta-V = v_exhaust * ln(m_initial / m_final)
     *
     * @return available delta-V in m/s
     */
    public double getAvailableDeltaV() {
        double initialMass = getTotalMass();
        double finalMass = initialMass - fuelMass;
        if (finalMass <= 0 || initialMass <= 0) {
            return 0.0;
        }
        return exhaustVelocity * Math.log(initialMass / finalMass);
    }

    /**
     * Fuel mass required to achieve the given delta-V from the current total mass.
     * Inverse Tsiolkovsky: m_fuel = m_total * (1 - e^(-delta_V / v_exhaust))
     *
     * @param deltaV delta-V to achieve in m/s
     * @return required fuel mass in kg
     */
    public double fuelRequired(double deltaV) {
        return getTotalMass() - getTotalMass() / Math.exp(deltaV / exhaustVelocity);
    }

    /**
     * Disassemble this spacecraft and return its construction materials.
     * Removes from both transit tracking and physics integration.
     *
     * @return Composition of construction materials
     */
    public Composition recycle() {
        Composition materials = new Composition();
        for (Map.Entry<Material, Double> entry : construction.getMaterials().entrySet()) {
            materials.addMaterialAsRawMass(entry.getKey(), entry.getValue());
        }
        return materials;
    }
}