package com.kaymlyn.planeteater.simulation.entities;

import lombok.Getter;
import lombok.Setter;

/**
 * Represents a mining worker - can be human or robot
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
@Setter
public class MiningEntity {

    private String id;
    private EntityType type;
    private EntityLocomotion motion;
    private double mass; // kg
    private double miningRate; // kg of type per second
    private boolean requiresLifeSupport;
    private boolean providesLifeSupport;
    private boolean crewable;
    private double productivity;
    private EntityState state;
    private String currentLocation; // ID of current location (platform or asteroid)
    
    public enum EntityState {
        IDLE,           // At platform, not assigned
        TRAVELING,      // En route to destination
        MINING,         // Actively mining
        RETURNING       // Returning to platform
    }
    
    public MiningEntity(String id, EntityType type, EntityLocomotion motion, double productivity, double mass, double miningRate) {
        this.id = id;
        this.type = type;
        this.motion = motion;
        this.mass = mass;
        this.miningRate = miningRate;
        this.requiresLifeSupport = (type == EntityType.ORGANIC);
        this.state = EntityState.IDLE;
        this.currentLocation = null;
        this.crewable = false;
        this.providesLifeSupport = false;
    }
    
    /**
     * Calculate amount of type this entity can mine in given time
     */
    public double calculateMiningYield(double timeSeconds) {
        return miningRate * productivity * timeSeconds;
    }

    public boolean requiresLifeSupport() {
        switch (this.type) {
            case ORGANIC, SEMIORGANIC -> { return true; }
            case INORGANIC -> { return false; }
        }
        return false;
    }

    @Override
    public String toString() {
        return String.format("com.kaymlyn.planeteater.entities.MiningEntity[id=%s, type=%s, mass=%.1f kg, rate=%.2f kg/s, state=%s]",
            id, type, mass, miningRate, state);
    }
}