package com.kaymlyn.planeteater.simulation.resources;

import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

/**
 * Represents the material composition of a celestial body
 * 
 * Generated by Claude (Sonnet 4.5)
 */
public class Composition {
    private final Map<Material, Double> materials; //Material -> mass in kg
    
    public Composition() {
        this.materials = new HashMap<>();
    }

    public void addBulkMaterial(Composition composition) {
        materials.putAll(composition.getMaterials());
    }

    /**
     * Add a material that will fill the given volume
     * @param material The type of material to add to the Composition
     * @param volume The volume in cubic meters
     */
    public void addMaterialAsVolume(Material material, double volume) {
        if (volume < 0) {
            throw new IllegalArgumentException("Volume cannot be negative");
        }
        addMaterialAsRawMass(material,material.massForVolume(volume));
    }

    /**
     * Add a material with a given mass
     * @param material The type of material to add to the Composition
     * @param mass The mass in kg
     */
    public void addMaterialAsRawMass(Material material, double mass) {
        if (mass < 0) {
            throw new IllegalArgumentException("Mass cannot be negative");
        }
        materials.merge(material, mass, Double::sum);
    }
    
    /**
     * Remove a specific amount of a material
     * Returns the actual amount removed (amount may be less if insufficient quantity)
     */
    public double removeMaterial(Material material, double mass) {
        if (mass < 0) {
            throw new IllegalArgumentException("Mass cannot be negative");
        }
        
        double currentMass = materials.getOrDefault(material, 0.0);
        double toRemove = Math.min(mass, currentMass);
        
        if (toRemove > 0) {
            double remaining = currentMass - toRemove;
            if (remaining < 1e-10) {
                materials.remove(material);
            } else {
                materials.put(material, remaining);
            }
        }
        
        return toRemove;
    }
    
    /**
     * Get the mass of a specific material
     */
    public double getMass(Material material) {
        return materials.getOrDefault(material, 0.0);
    }
    
    /**
     * Get total mass of all materials
     */
    public double getTotalMass() {
        return materials.values().stream().mapToDouble(Double::doubleValue).sum();
    }
    
    /**
     * Calculate the bulk density based on composition
     * This assumes materials are uniformly mixed
     */
    public double getBulkDensity() {
        double totalMass = getTotalMass();
        if (totalMass < 1e-10) {
            return 0.0;
        }
        
        double totalVolume = materials.entrySet().stream()
            .mapToDouble(e -> e.getKey().volumeForMass(e.getValue()))
            .sum();
        
        return totalMass / totalVolume;
    }
    
    /**
     * Calculate total volume based on composition
     */
    public double getTotalVolume() {
        return materials.entrySet().stream()
            .mapToDouble(e -> e.getKey().volumeForMass(e.getValue()))
            .sum();
    }
    
    /**
     * Get an unmodifiable view of the materials map
     */
    public Map<Material, Double> getMaterials() {
        return Collections.unmodifiableMap(materials);
    }
    
    /**
     * Check if composition contains a specific material
     */
    public boolean contains(Material material) {
        return materials.containsKey(material) && materials.get(material) > 0;
    }
    
    /**
     * Get the fraction of total mass for a specific material
     */
    public double getFraction(Material material) {
        double totalMass = getTotalMass();
        if (totalMass < 1e-10) {
            return 0.0;
        }
        return getMass(material) / totalMass;
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Composition[");
        materials.forEach((mat, mass) -> 
            sb.append(String.format("%s: %.2e kg, ", mat.getSymbol(), mass)));
        if (!materials.isEmpty()) {
            sb.setLength(sb.length() - 2); // Remove trailing ", "
        }
        sb.append("]");
        return sb.toString();
    }
}