package com.kaymlyn.planeteater.simulation.resources;

import lombok.Getter;

/**
 * Represents different materials found in celestial bodies
 * with their physical properties
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public enum Material {
    // Metals
    IRON(7874.0, "Fe"),
    NICKEL(8908.0, "Ni"),
    ALUMINUM(2700.0, "Al"),
    MAGNESIUM(1738.0, "Mg"),
    TITANIUM(4506.0, "Ti"),
    
    // Rock-forming minerals and oxides
    SILICA(2648.0, "SiO₂"),           // Silicon dioxide
    TITANIUM_OXIDE(4230.0, "TiO₂"),
    MAGNESIUM_OXIDE(3580.0, "MgO"),
    ALUMINUM_OXIDE(3950.0, "Al₂O₃"),
    CALCIUM_OXIDE(3340.0, "CaO"),
    IRON_OXIDE(5240.0, "FeO"),
    
    // Silicates (complex minerals)
    OLIVINE(3320.0, "(Mg,Fe)₂SiO₄"),   // Magnesium-iron silicate
    PYROXENE(3300.0, "(Mg,Fe)SiO₃"),   // Chain silicate
    FELDSPAR(2650.0, "NaAlSi₃O₈"),     // Aluminum silicate
    
    // Volatiles and ices
    WATER_ICE(917.0, "H₂O"),
    CO2_ICE(1562.0, "CO₂"),            // Dry ice
    METHANE_ICE(494.0, "CH₄"),
    AMMONIA_ICE(817.0, "NH₃"),
    NITROGEN_ICE(1027.0, "N₂"),
    
    // Gases (at standard conditions - we'll use liquid/solid densities for storage)
    HYDROGEN(70.8, "H₂"),              // Liquid hydrogen density
    HELIUM(125.0, "He"),               // Liquid helium density
    OXYGEN_GAS(1141.0, "O₂"),          // Liquid oxygen density
    NITROGEN_GAS(808.0, "N₂"),         // Liquid nitrogen density
    
    // Sulfur compounds
    SULFUR(2070.0, "S"),
    IRON_SULFIDE(4840.0, "FeS"),       // Troilite
    
    // Carbonaceous materials
    CARBON(2267.0, "C"),               // Graphite density
    ORGANIC_COMPOUNDS(1200.0, "C,H,O"), // Average for organic materials
    
    // Other significant elements
    CALCIUM(1550.0, "Ca"),
    SODIUM(971.0, "Na"),
    POTASSIUM(862.0, "K"),
    CHROMIUM(7190.0, "Cr"),
    PHOSPHORUS(1820.0, "P"),

    //Bucket for every other element not outlined above (Precious Metals, Rare metals and gases)
    TRACE_ELEMENTS(19300.0, "TE");
    
    private final double density; // kg/m³
    private final String symbol;
    
    Material(double density, String symbol) {
        this.density = density;
        this.symbol = symbol;
    }
    
    /**
     * Calculate volume for a given mass of this type
     */
    public double volumeForMass(double mass) {
        return mass / density;
    }
    
    /**
     * Calculate mass for a given volume of this type
     */
    public double massForVolume(double volume) {
        return volume * density;
    }
    
    /**
     * Check if this is a volatile/ice type
     */
    public boolean isVolatile() {
        return this == WATER_ICE || this == CO2_ICE || this == METHANE_ICE || 
               this == AMMONIA_ICE || this == NITROGEN_ICE;
    }
    
    /**
     * Check if this is a gas (stored as liquid/solid)
     */
    public boolean isGas() {
        return this == HYDROGEN || this == HELIUM || this == OXYGEN_GAS || 
               this == NITROGEN_GAS;
    }
    
    /**
     * Check if this is a metal
     */
    public boolean isMetal() {
        return this == IRON || this == NICKEL || this == ALUMINUM || 
               this == MAGNESIUM || this == TITANIUM || this == CALCIUM ||
               this == SODIUM || this == POTASSIUM || this == CHROMIUM;
    }

    public String toString() {
        return this.name();
    }
}