package com.kaymlyn.planeteater.simulation.integration;

import com.kaymlyn.planeteater.simulation.celestial.CelestialBodyFactory;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.PlanetPattern;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.physics.Itinerary;
import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.TransferPlanner;
import com.kaymlyn.planeteater.simulation.vehicles.CentralMind;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import com.kaymlyn.planeteater.simulation.vehicles.VehicleFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * End-to-End Mission Integration Test
 *
 * Tests the complete workflow of a spacecraft mission from creation to completion:
 * 1. System setup (solar system with planets)
 * 2. Spacecraft creation at orbital platform
 * 3. Route planning to destination
 * 4. Launch sequence
 * 5. Mission execution (simulated over time)
 * 6. Arrival validation
 * 7. Fuel consumption verification
 *
 * This integration test validates that all components (OrbitalSystem, TransferPlanner,
 * Spacecraft, Itinerary, ScheduledBurn) work together correctly as a cohesive system.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("End-to-End Mission Integration Tests")
public class EndToEndMissionTest {

    private static final double POSITION_TOLERANCE = 1e6;  // 1000 km tolerance for arrival
    private static final double FUEL_TOLERANCE = 100.0;     // 100 kg fuel tolerance
    private static final double TIME_STEP = 3600.0;         // 1 hour time steps

    private CelestialBodyFactory factory;
    private OrbitalSystem system;
    private Star sun;
    private Planet earth;
    private Planet mars;
    private CentralMind platform;

    @BeforeEach
    void setUp() {
        // Create solar system
        sun = CelestialBodyFactory.createMainSequenceStar("Sol", 1.0);
        factory = new CelestialBodyFactory(sun, TIME_STEP);
        system = factory.getSystem();

        // Create Earth
        earth = factory.createPlanetFromPattern(
                "Earth",
                sun,
                new Orbit(PhysicsConstants.AU, 0.0, 0.0, 0.0, 0.0, 0.0, sun),
                PlanetPattern.EARTH,
                1.0
        );

        // Create Mars
        mars = factory.createPlanetFromPattern(
                "Mars",
                sun,
                new Orbit(PhysicsConstants.AU * 1.524, 0.0, 0.0, 0.0, 0.0, 0.0, sun),
                PlanetPattern.MARS,
                1.0
        );

        // Create orbital platform at Earth
        platform = factory.createCentralMind(PhysicsConstants.AU);
    }

    // ==================== SIMPLE MISSION TESTS ====================

    @Test
    @DisplayName("Complete Earth to Mars mission")
    void testEarthToMarsMission() {
        // Step 1: Create spacecraft at platform
        Spacecraft shuttle = VehicleFactory.createCargoShuttle("Explorer-1", platform);

        assertAll("Initial spacecraft state",
                () -> assertEquals(Spacecraft.SpacecraftState.DOCKED, shuttle.getState()),
                () -> assertEquals(platform, shuttle.getOrbiting()),
                () -> assertTrue(shuttle.getFuelMass() > 0, "Should have fuel")
        );

        // Step 2: Plan route to Mars
        double departureTime = system.getCurrentTime() + 86400.0; // Depart in 1 day
        Itinerary route = shuttle.planRoute(
                mars,
                false,  // Orbit Mars, don't land
                departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV
        );

        assertNotNull(route, "Should generate a route to Mars");
        assertTrue(route.isFeasible(), "Route should be feasible");
        assertTrue(route.getBurns().size() >= 2, "Should have at least departure and arrival burns");

        // Step 3: Program itinerary and launch
        shuttle.programItinerary(route);
        double initialFuel = shuttle.getFuelMass();
        boolean launched = shuttle.launch(system.getTimeStep());

        assertAll("Launch sequence",
                () -> assertTrue(launched, "Launch should succeed"),
                () -> assertEquals(Spacecraft.SpacecraftState.TRAVELING, shuttle.getState()),
                () -> assertFalse(platform.getHanger().containsKey("Explorer-1"), "Should leave platform")
        );

        // Step 4: Simulate mission
        int maxSteps = 50000; // Prevent infinite loops (about 5.7 years at 1 hour steps)
        int steps = 0;

        while (!route.isComplete(system.getCurrentTime()) && steps < maxSteps) {
            system.stepVerlet();
            steps++;
        }

        assertTrue(steps < maxSteps, "Mission should complete before timeout");

        // Step 5: Validate arrival
        double distanceToMars = shuttle.getPosition().subtract(mars.getPosition()).magnitude();
        double marsOrbitRadius = mars.getStandardOrbitalRadius();

        assertAll("Mission completion",
                () -> assertTrue(route.isComplete(system.getCurrentTime()), "Itinerary should be complete"),
                () -> assertEquals(Spacecraft.SpacecraftState.ORBITING, shuttle.getState()),
                () -> assertEquals(mars, shuttle.getOrbiting()),
                () -> assertTrue(distanceToMars < marsOrbitRadius * 2.0,
                        String.format("Distance to Mars %.0f km should be within tolerance", distanceToMars / 1000.0))
        );

        // Step 6: Verify fuel consumption
        double fuelConsumed = initialFuel - shuttle.getFuelMass();
        double expectedDeltaV = route.getTotalDeltaV();

        assertAll("Fuel consumption",
                () -> assertTrue(fuelConsumed > 0, "Should have consumed fuel"),
                () -> assertTrue(fuelConsumed < initialFuel, "Should have fuel remaining"),
                () -> assertTrue(expectedDeltaV > 0, "Should have required delta-V")
        );

        System.out.println(String.format(
                "Mission completed in %d steps (%.1f days). Fuel consumed: %.1f kg. Final distance to Mars: %.0f km",
                steps, steps * TIME_STEP / 86400.0, fuelConsumed, distanceToMars / 1000.0
        ));
    }

    @Test
    @DisplayName("Mission with insufficient fuel fails at launch")
    void testInsufficientFuelMission() {
        // Create spacecraft with very limited fuel
        Spacecraft tinyShuttle = new Spacecraft(
                "Tiny-1",
                5000.0,
                100.0,  // Only 100 kg fuel
                20.0,
                3000.0,
                false,
                0,
                0,
                platform
        );

        // Try to plan route to Mars
        double departureTime = system.getCurrentTime() + 86400.0;
        Itinerary route = tinyShuttle.planRoute(
                mars,
                false,
                departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV
        );

        // Route may be generated but marked infeasible
        if (route != null) {
            tinyShuttle.programItinerary(route);
            boolean launched = tinyShuttle.launch(system.getTimeStep());

            assertAll("Insufficient fuel mission",
                    () -> assertFalse(launched, "Launch should fail with insufficient fuel"),
                    () -> assertEquals(Spacecraft.SpacecraftState.DOCKED, tinyShuttle.getState()),
                    () -> assertTrue(platform.getHanger().containsKey("Tiny-1"), "Should remain docked")
            );
        }
    }

    @Test
    @DisplayName("Round trip mission - Earth to Mars and back")
    void testRoundTripMission() {
        // Create spacecraft with extra fuel for round trip
        Spacecraft explorer = new Spacecraft(
                "Explorer-2",
                10000.0,
                50000.0,  // Extra fuel for round trip
                50.0,
                3000.0,
                true,
                4,
                1,
                platform
        );

        double currentTime = system.getCurrentTime();

        // ===== OUTBOUND LEG: Earth to Mars =====
        double outboundDeparture = currentTime + 86400.0;
        Itinerary outbound = explorer.planRoute(
                mars,
                false,
                outboundDeparture,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV
        );

        assertNotNull(outbound, "Should plan outbound route");
        assertTrue(outbound.isFeasible(), "Outbound should be feasible");

        explorer.programItinerary(outbound);
        double initialFuel = explorer.getFuelMass();
        assertTrue(explorer.launch(system.getTimeStep()), "Outbound launch should succeed");

        // Simulate outbound journey
        int outboundSteps = 0;
        int maxSteps = 50000;
        while (!outbound.isComplete(system.getCurrentTime()) && outboundSteps < maxSteps) {
            system.stepVerlet();
            outboundSteps++;
        }

        assertTrue(outboundSteps < maxSteps, "Outbound should complete");
        assertEquals(Spacecraft.SpacecraftState.ORBITING, explorer.getState());
        assertEquals(mars, explorer.getOrbiting());

        double fuelAfterOutbound = explorer.getFuelMass();

        System.out.printf(
                "Outbound complete in %d steps. Fuel remaining: %.1f kg%n",
                outboundSteps, fuelAfterOutbound
        );

        // ===== RETURN LEG: Mars to Earth =====
        double returnDeparture = system.getCurrentTime() + 86400.0 * 30.0; // Wait 30 days
        Itinerary returnTrip = explorer.planRoute(
                earth,
                false,
                returnDeparture,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV
        );

        assertNotNull(returnTrip, "Should plan return route");

        if (returnTrip.isFeasible()) {
            explorer.programItinerary(returnTrip);
            assertTrue(explorer.launch(system.getTimeStep()), "Return launch should succeed");

            // Simulate return journey
            int returnSteps = 0;
            while (!returnTrip.isComplete(system.getCurrentTime()) && returnSteps < maxSteps) {
                system.stepVerlet();
                returnSteps++;
            }

            assertTrue(returnSteps < maxSteps, "Return should complete");
            assertEquals(Spacecraft.SpacecraftState.ORBITING, explorer.getState());
            assertEquals(earth, explorer.getOrbiting());

            double finalFuel = explorer.getFuelMass();
            double totalFuelUsed = initialFuel - finalFuel;

            System.out.println(String.format(
                    "Round trip complete. Total steps: %d. Total fuel used: %.1f kg (%.1f%% of capacity)",
                    outboundSteps + returnSteps, totalFuelUsed, (totalFuelUsed / 50000.0) * 100.0
            ));

            assertAll("Round trip completion",
                    () -> assertTrue(finalFuel > 0, "Should have fuel remaining"),
                    () -> assertTrue(totalFuelUsed < 50000.0, "Should not exceed fuel capacity")
            );
        } else {
            System.out.println("Return trip not feasible with remaining fuel: " +
                    returnTrip.getInfeasibilityReason());
            assertTrue(true, "Acceptable for return to be infeasible if fuel insufficient");
        }
    }

    // ==================== MULTI-SPACECRAFT COORDINATION TESTS ====================

    @Test
    @DisplayName("Multiple spacecraft can operate simultaneously")
    void testMultipleSpacecraftMissions() {
        // Create two spacecraft
        Spacecraft shuttle1 = VehicleFactory.createCargoShuttle("Alpha", platform);
        Spacecraft shuttle2 = VehicleFactory.createCargoShuttle("Beta", platform);

        double departureTime = system.getCurrentTime() + 86400.0;

        // Plan routes for both
        Itinerary route1 = shuttle1.planRoute(mars, false, departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);
        Itinerary route2 = shuttle2.planRoute(mars, false, departureTime + 86400.0 * 7.0,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);

        assertAll("Both routes planned",
                () -> assertNotNull(route1, "Alpha route should exist"),
                () -> assertNotNull(route2, "Beta route should exist"),
                () -> assertTrue(route1.isFeasible(), "Alpha route feasible"),
                () -> assertTrue(route2.isFeasible(), "Beta route feasible")
        );

        // Launch both spacecraft
        shuttle1.programItinerary(route1);
        shuttle2.programItinerary(route2);

        boolean launch1 = shuttle1.launch(system.getTimeStep());
        boolean launch2 = shuttle2.launch(system.getTimeStep());

        assertAll("Both launches succeed",
                () -> assertTrue(launch1, "Alpha should launch"),
                () -> assertTrue(launch2, "Beta should launch"),
                () -> assertEquals(Spacecraft.SpacecraftState.TRAVELING, shuttle1.getState()),
                () -> assertEquals(Spacecraft.SpacecraftState.TRAVELING, shuttle2.getState())
        );

        // Simulate until both complete
        int steps = 0;
        int maxSteps = 50000;

        while ((!route1.isComplete(system.getCurrentTime()) ||
                !route2.isComplete(system.getCurrentTime())) && steps < maxSteps) {
            system.stepVerlet();
            steps++;
        }

        assertAll("Both spacecraft arrive",
                () -> assertTrue(route1.isComplete(system.getCurrentTime()), "Alpha should complete"),
                () -> assertTrue(route2.isComplete(system.getCurrentTime()), "Beta should complete"),
                () -> assertEquals(Spacecraft.SpacecraftState.ORBITING, shuttle1.getState()),
                () -> assertEquals(Spacecraft.SpacecraftState.ORBITING, shuttle2.getState()),
                () -> assertEquals(mars, shuttle1.getOrbiting()),
                () -> assertEquals(mars, shuttle2.getOrbiting())
        );

        System.out.println(String.format(
                "Multi-spacecraft mission complete. Both arrived at Mars in %d steps (%.1f days)",
                steps, steps * TIME_STEP / 86400.0
        ));
    }

    // ==================== MISSION ABORT SCENARIOS ====================

    @Test
    @DisplayName("Mission continues correctly after simulation pause and resume")
    void testMissionPauseAndResume() {
        Spacecraft shuttle = VehicleFactory.createCargoShuttle("Resilient-1", platform);

        double departureTime = system.getCurrentTime() + 86400.0;
        Itinerary route = shuttle.planRoute(mars, true, departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);

        System.out.println(route.getSummary());
        shuttle.programItinerary(route);
        shuttle.launch(system.getTimeStep());

        System.out.println(route.getSummary());

        // Simulate partway through mission
        int halfwaySteps = 5000;
        for (int i = 0; i < halfwaySteps; i++) {
            system.stepVerlet();
        }

        assertEquals(Spacecraft.SpacecraftState.TRAVELING, shuttle.getState(),
                "Should still be traveling halfway through");

        // "Pause" by checking state
        double midMissionTime = system.getCurrentTime();
        double midMissionFuel = shuttle.getFuelMass();

        System.out.println("Fuel Mass: " + shuttle.getFuelMass());
        // "Resume" and complete mission
        int remainingSteps = 0;
        int maxSteps = (int)(PhysicsConstants.SECONDS_PER_DAY * 300/system.getTimeStep());

        System.out.println(maxSteps);

        while (remainingSteps < maxSteps) {
            system.stepVerlet();
            remainingSteps++;
        }

        System.out.println("Fuel Mass: " + shuttle.getFuelMass());

        assertAll("Mission completes after pause",
                () -> assertTrue(route.isComplete(system.getCurrentTime())),
                () -> assertEquals(Spacecraft.SpacecraftState.DOCKED, shuttle.getState()),
                () -> assertTrue(shuttle.getFuelMass() < midMissionFuel, "Should have consumed more fuel"),
                () -> assertTrue(system.getCurrentTime() > midMissionTime, "Time should have advanced")
        );

        System.out.printf(
                "Mission completed after pause. First leg: %d steps, Second leg: %d steps%n",
                halfwaySteps, remainingSteps
        );
    }

    // ==================== ORBITAL MECHANICS VALIDATION ====================

    @Test
    @DisplayName("Spacecraft follows predicted trajectory within tolerance")
    void testTrajectoryAccuracy() {
        Spacecraft shuttle = VehicleFactory.createCargoShuttle("Precise-1", platform);

        double departureTime = system.getCurrentTime() + 86400.0;
        Itinerary route = shuttle.planRoute(mars, false, departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);

        shuttle.programItinerary(route);

        // Record predicted values
        double predictedDeltaV = route.getTotalDeltaV();
        double predictedDuration = route.getEstimatedDuration();

        shuttle.launch(system.getTimeStep());
        double startTime = system.getCurrentTime();
        double startFuel = shuttle.getFuelMass();

        // Simulate mission
        int steps = 0;
        int maxSteps = 50000;
        while (!route.isComplete(system.getCurrentTime()) && steps < maxSteps) {
            system.stepVerlet();
            steps++;
        }

        double actualDuration = system.getCurrentTime() - startTime;
        double fuelConsumed = startFuel - shuttle.getFuelMass();

        // Validate predictions were reasonably accurate
        assertAll("Trajectory predictions",
                () -> assertTrue(Math.abs(actualDuration - predictedDuration) < predictedDuration * 0.1,
                        String.format("Duration within 10%% of prediction: actual=%.1f, predicted=%.1f days",
                                actualDuration / 86400.0, predictedDuration / 86400.0)),
                () -> assertTrue(fuelConsumed > 0, "Should consume fuel"),
                () -> assertTrue(predictedDeltaV > 0, "Should predict delta-V requirement")
        );

        System.out.println(String.format(
                "Trajectory validation: Predicted duration=%.1f days, Actual=%.1f days. Delta-V=%.1f m/s, Fuel=%.1f kg",
                predictedDuration / 86400.0, actualDuration / 86400.0, predictedDeltaV, fuelConsumed
        ));
    }

    // ==================== STRESS TESTS ====================

    @Test
    @DisplayName("System handles long-duration missions without numerical issues")
    void testLongDurationStability() {
        Spacecraft shuttle = VehicleFactory.createCargoShuttle("Endurance-1", platform);

        double departureTime = system.getCurrentTime() + 86400.0;
        Itinerary route = shuttle.planRoute(mars, false, departureTime,
                TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);

        shuttle.programItinerary(route);
        shuttle.launch(system.getTimeStep());

        double initialEnergy = calculateSystemEnergy();

        // Simulate mission
        int steps = 0;
        int maxSteps = 50000;
        while (!route.isComplete(system.getCurrentTime()) && steps < maxSteps) {
            system.stepVerlet();

            // Check for NaN or infinity
            assertAll("Numerical stability check",
                    () -> assertFalse(Double.isNaN(shuttle.getPosition().getX()), "Position should not be NaN"),
                    () -> assertFalse(Double.isInfinite(shuttle.getVelocity().magnitude()), "Velocity should not be infinite"),
                    () -> assertTrue(shuttle.getFuelMass() >= 0, "Fuel should not go negative")
            );

            steps++;
        }

        double finalEnergy = calculateSystemEnergy();

        // Energy should be roughly conserved (within reasonable tolerance for numerical integration)
        double energyChange = Math.abs(finalEnergy - initialEnergy) / Math.abs(initialEnergy);

        assertTrue(energyChange < 0.1,
                String.format("Energy conservation: change=%.2f%% (should be <10%%)", energyChange * 100.0));

        System.out.println(String.format(
                "Long-duration stability test passed. %d steps simulated. Energy drift: %.4f%%",
                steps, energyChange * 100.0
        ));
    }

    // ==================== HELPER METHODS ====================

    /**
     * Calculate total system energy (kinetic + potential) for validation.
     * This is a simplified calculation for testing purposes.
     */
    private double calculateSystemEnergy() {
        double totalEnergy = 0.0;

        // Add kinetic energy of orbiting bodies
        for (var orbiter : system.getOrbiters().values()) {
            double kineticEnergy = 0.5 * orbiter.getMass() *
                    Math.pow(orbiter.getVelocity().magnitude(), 2);
            totalEnergy += kineticEnergy;
        }

        return totalEnergy;
    }
}