package com.kaymlyn.planeteater.rendering;

import java.awt.Color;

/**
 * Configuration for the reference frame overlay rendered beneath solar system objects.
 *
 * Two independently toggleable layers:
 *
 *   Graduated axes  - Three number lines (X, Y, Z) intersecting at the origin.
 *                     Each axis is independently configured via AxisConfig.
 *                     Think of this as three perpendicular rulers.
 *
 *   Ecliptic grid   - A regular grid of lines parallel to the X and Y axes in
 *                     the Z=0 plane. Provides a visual floor for the ecliptic.
 *
 * gridOnTop controls Z-ordering. When false (default), the reference frame is
 * drawn before objects so objects appear on top. When true, the reference frame
 * is drawn after objects, overlaying them. Useful for debugging occlusion.
 *
 * gridExtentAU controls how far from the origin both the axes and the ecliptic
 * grid extend. Set to the maxAUVisible of the view at construction time by
 * the renderer if not overridden.
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class GridConfig {

    public static final double DEFAULT_GRID_INTERVAL_AU = 1.0;
    public static final int DEFAULT_GRID_LINE_WEIGHT = 1;
    public static final int DEFAULT_DASH_PERIOD = 12;

    private final boolean showGraduatedAxes;
    private final AxisConfig xAxisConfig;
    private final AxisConfig yAxisConfig;
    private final AxisConfig zAxisConfig;

    private final boolean showEclipticGrid;
    private final Color eclipticGridColor;
    private final int eclipticGridLineWeight;
    private final LineType eclipticGridLineType;
    private final int eclipticGridDashPeriod;
    private final double eclipticGridIntervalAU;

    private final boolean gridOnTop;

    private GridConfig(Builder builder) {
        this.showGraduatedAxes = builder.showGraduatedAxes;
        this.xAxisConfig = builder.xAxisConfig;
        this.yAxisConfig = builder.yAxisConfig;
        this.zAxisConfig = builder.zAxisConfig;
        this.showEclipticGrid = builder.showEclipticGrid;
        this.eclipticGridColor = builder.eclipticGridColor;
        this.eclipticGridLineWeight = builder.eclipticGridLineWeight;
        this.eclipticGridLineType = builder.eclipticGridLineType;
        this.eclipticGridDashPeriod = builder.eclipticGridDashPeriod;
        this.eclipticGridIntervalAU = builder.eclipticGridIntervalAU;
        this.gridOnTop = builder.gridOnTop;
    }

    public boolean isShowGraduatedAxes() { return showGraduatedAxes; }
    public AxisConfig getXAxisConfig() { return xAxisConfig; }
    public AxisConfig getYAxisConfig() { return yAxisConfig; }
    public AxisConfig getZAxisConfig() { return zAxisConfig; }
    public boolean isShowEclipticGrid() { return showEclipticGrid; }
    public Color getEclipticGridColor() { return eclipticGridColor; }
    public int getEclipticGridLineWeight() { return eclipticGridLineWeight; }
    public LineType getEclipticGridLineType() { return eclipticGridLineType; }
    public int getEclipticGridDashPeriod() { return eclipticGridDashPeriod; }
    public double getEclipticGridIntervalAU() { return eclipticGridIntervalAU; }
    public boolean isGridOnTop() { return gridOnTop; }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Convenience factory: graduated axes only, standard red/green/blue colors,
     * ecliptic grid disabled, grid behind objects.
     */
    public static GridConfig axesOnly() {
        return builder()
                .showGraduatedAxes(true)
                .xAxisConfig(AxisConfig.standard(new Color(160, 40, 40)))
                .yAxisConfig(AxisConfig.standard(new Color(40, 160, 40)))
                .zAxisConfig(AxisConfig.standard(new Color(40, 40, 160)))
                .showEclipticGrid(false)
                .eclipticGridColor(new Color(40, 40, 40))
                .eclipticGridLineWeight(DEFAULT_GRID_LINE_WEIGHT)
                .eclipticGridLineType(LineType.SOLID)
                .eclipticGridDashPeriod(DEFAULT_DASH_PERIOD)
                .eclipticGridIntervalAU(DEFAULT_GRID_INTERVAL_AU)
                .gridOnTop(false)
                .build();
    }

    /**
     * Convenience factory: both graduated axes and ecliptic grid enabled,
     * grid behind objects.
     */
    public static GridConfig full() {
        return builder()
                .showGraduatedAxes(true)
                .xAxisConfig(AxisConfig.standard(new Color(160, 40, 40)))
                .yAxisConfig(AxisConfig.standard(new Color(40, 160, 40)))
                .zAxisConfig(AxisConfig.standard(new Color(40, 40, 160)))
                .showEclipticGrid(true)
                .eclipticGridColor(new Color(40, 40, 40))
                .eclipticGridLineWeight(DEFAULT_GRID_LINE_WEIGHT)
                .eclipticGridLineType(LineType.SOLID)
                .eclipticGridDashPeriod(DEFAULT_DASH_PERIOD)
                .eclipticGridIntervalAU(DEFAULT_GRID_INTERVAL_AU)
                .gridOnTop(false)
                .build();
    }

    /**
     * Convenience factory: nothing rendered.
     */
    public static GridConfig disabled() {
        return builder()
                .showGraduatedAxes(false)
                .xAxisConfig(AxisConfig.disabled())
                .yAxisConfig(AxisConfig.disabled())
                .zAxisConfig(AxisConfig.disabled())
                .showEclipticGrid(false)
                .build();
    }

    public static class Builder {
        private boolean showGraduatedAxes = false;
        private AxisConfig xAxisConfig = AxisConfig.disabled();
        private AxisConfig yAxisConfig = AxisConfig.disabled();
        private AxisConfig zAxisConfig = AxisConfig.disabled();
        private boolean showEclipticGrid = false;
        private Color eclipticGridColor = new Color(40, 40, 40);
        private int eclipticGridLineWeight = DEFAULT_GRID_LINE_WEIGHT;
        private LineType eclipticGridLineType = LineType.SOLID;
        private int eclipticGridDashPeriod = DEFAULT_DASH_PERIOD;
        private double eclipticGridIntervalAU = DEFAULT_GRID_INTERVAL_AU;
        private boolean gridOnTop = false;

        public Builder showGraduatedAxes(boolean showGraduatedAxes) {
            this.showGraduatedAxes = showGraduatedAxes; return this;
        }
        public Builder xAxisConfig(AxisConfig xAxisConfig) {
            this.xAxisConfig = xAxisConfig; return this;
        }
        public Builder yAxisConfig(AxisConfig yAxisConfig) {
            this.yAxisConfig = yAxisConfig; return this;
        }
        public Builder zAxisConfig(AxisConfig zAxisConfig) {
            this.zAxisConfig = zAxisConfig; return this;
        }
        public Builder showEclipticGrid(boolean showEclipticGrid) {
            this.showEclipticGrid = showEclipticGrid; return this;
        }
        public Builder eclipticGridColor(Color eclipticGridColor) {
            this.eclipticGridColor = eclipticGridColor; return this;
        }
        public Builder eclipticGridLineWeight(int eclipticGridLineWeight) {
            this.eclipticGridLineWeight = eclipticGridLineWeight; return this;
        }
        public Builder eclipticGridLineType(LineType eclipticGridLineType) {
            this.eclipticGridLineType = eclipticGridLineType; return this;
        }
        public Builder eclipticGridDashPeriod(int eclipticGridDashPeriod) {
            this.eclipticGridDashPeriod = eclipticGridDashPeriod; return this;
        }
        public Builder eclipticGridIntervalAU(double eclipticGridIntervalAU) {
            this.eclipticGridIntervalAU = eclipticGridIntervalAU; return this;
        }
        public Builder gridOnTop(boolean gridOnTop) {
            this.gridOnTop = gridOnTop; return this;
        }

        public GridConfig build() {
            return new GridConfig(this);
        }
    }
}