package com.kaymlyn.planeteater.rendering;

/**
 * Controls which categories of labeled objects are shown in a given view.
 *
 * Five object categories map to the type hierarchy used in rendering:
 *
 *   star       - The central Star instance.
 *   planets    - Planet instances with a non-asteroid BodyType (BARREN, HABITABLE,
 *                GREENHOUSE, ICE_BALLS, ICE_GIANT, GAS_GIANT, ABERRANT).
 *   asteroids  - Planet instances with an asteroid BodyType (C_TYPE, S_TYPE, M_TYPE).
 *                Note: belt asteroids are already suppressed by the existing id-based
 *                filter. This flag controls named (non-belt) asteroids.
 *   satellites - CentralMind and any other Satellite implementations.
 *   spacecraft - Spacecraft instances not in DOCKED state.
 *
 * fontSize is applied globally to all rendered labels in this view.
 * The value is passed to Graphics2D Font construction. Default 11 matches
 * the Java AWT default sans-serif rendering.
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class LabelConfig {

    public static final int DEFAULT_FONT_SIZE = 11;

    private final boolean showStar;
    private final boolean showPlanets;
    private final boolean showAsteroids;
    private final boolean showSatellites;
    private final boolean showSpacecraft;
    private final int fontSize;

    private LabelConfig(Builder builder) {
        this.showStar = builder.showStar;
        this.showPlanets = builder.showPlanets;
        this.showAsteroids = builder.showAsteroids;
        this.showSatellites = builder.showSatellites;
        this.showSpacecraft = builder.showSpacecraft;
        this.fontSize = builder.fontSize;
    }

    public boolean isShowStar() { return showStar; }
    public boolean isShowPlanets() { return showPlanets; }
    public boolean isShowAsteroids() { return showAsteroids; }
    public boolean isShowSatellites() { return showSatellites; }
    public boolean isShowSpacecraft() { return showSpacecraft; }
    public int getFontSize() { return fontSize; }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * Convenience factory: all labels shown.
     */
    public static LabelConfig allEnabled() {
        return builder()
                .showStar(true)
                .showPlanets(true)
                .showAsteroids(true)
                .showSatellites(true)
                .showSpacecraft(true)
                .fontSize(DEFAULT_FONT_SIZE)
                .build();
    }

    /**
     * Convenience factory: only major bodies (star, planets, satellites).
     * Suitable for views where asteroid and spacecraft label density is noise.
     */
    public static LabelConfig majorBodiesOnly() {
        return builder()
                .showStar(true)
                .showPlanets(true)
                .showAsteroids(false)
                .showSatellites(true)
                .showSpacecraft(false)
                .fontSize(DEFAULT_FONT_SIZE)
                .build();
    }

    /**
     * Convenience factory: no labels rendered.
     */
    public static LabelConfig none() {
        return builder()
                .showStar(false)
                .showPlanets(false)
                .showAsteroids(false)
                .showSatellites(false)
                .showSpacecraft(false)
                .fontSize(DEFAULT_FONT_SIZE)
                .build();
    }

    public static class Builder {
        private boolean showStar = true;
        private boolean showPlanets = true;
        private boolean showAsteroids = false;
        private boolean showSatellites = true;
        private boolean showSpacecraft = true;
        private int fontSize = DEFAULT_FONT_SIZE;

        public Builder showStar(boolean showStar) { this.showStar = showStar; return this; }
        public Builder showPlanets(boolean showPlanets) { this.showPlanets = showPlanets; return this; }
        public Builder showAsteroids(boolean showAsteroids) { this.showAsteroids = showAsteroids; return this; }
        public Builder showSatellites(boolean showSatellites) { this.showSatellites = showSatellites; return this; }
        public Builder showSpacecraft(boolean showSpacecraft) { this.showSpacecraft = showSpacecraft; return this; }
        public Builder fontSize(int fontSize) { this.fontSize = fontSize; return this; }

        public LabelConfig build() {
            return new LabelConfig(this);
        }
    }
}