package com.kaymlyn.planeteater.rendering;

/**
 * Line rendering style for grid axes and ecliptic grid lines.
 *
 * SOLID renders every pixel of the line segment.
 * DASHED renders alternating filled and empty segments of equal length.
 * DOTTED renders single pixels with gaps of equal length.
 *
 * The gap length for DASHED and DOTTED is controlled by the dashPeriod
 * field in the enclosing axis or grid config.
 *
 * Generated by Claude (Sonnet 4.5)
 */
public enum LineType {
    SOLID,
    DASHED,
    DOTTED
}