package com.kaymlyn.planeteater.rendering;

import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import org.jcodec.api.SequenceEncoder;
import org.jcodec.common.io.NIOUtils;
import org.jcodec.common.model.ColorSpace;
import org.jcodec.common.model.Picture;
import org.jcodec.common.model.Rational;
import org.jcodec.scale.AWTUtil;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.Objects;
import java.util.Random;

import static java.awt.image.BufferedImage.TYPE_INT_RGB;

/**
 * Renders the orbital system to images and video.
 *
 * FIXED VERSION - Unified rendering logic for orbiters and spacecraft
 * - Consistent rotation method (rotateInto3spaceFrom3space)
 * - Extracted position determination logic
 * - Consistent color and size handling
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class OrbitalSystemRenderer {

    private final OrbitalSystem system;
    private int frameIndex;
    private final int scalar;

    private static final int IMAGE_TYPE = TYPE_INT_RGB;

    // Rendering constants
    private static final int HEIGHT_RATIO = 9;
    private static final int WIDTH_RATIO = 16;
    private static final double LARGE_BODY_THRESHOLD = 50000.0; // 50 km
    private static final int LARGE_BODY_SIZE = 3;
    private static final int SMALL_BODY_SIZE = 2;
    private static final int SPACECRAFT_SIZE = 1;

    public OrbitalSystemRenderer(OrbitalSystem system, double visibleAU) {
        this.scalar = 80;
        this.frameIndex = 0;
        this.system = system;

        File directory = new File("orbits");
        if(!directory.exists()) {
            directory.mkdir();
        }
        for(File file : Objects.requireNonNull(directory.listFiles())) {
            file.delete();
        }
    }

    public void render(boolean saveImage, double maxAUVisible, Vector3D rotate) throws IOException {
        BufferedImage frame = renderFrame(system, scalar, maxAUVisible, rotate);
        renderInfo(frame.createGraphics(),
                "Day " + (int)(system.getCurrentTime()/PhysicsConstants.SECONDS_PER_DAY) +
                        " Hour " + (int)((system.getCurrentTime()%PhysicsConstants.SECONDS_PER_DAY)/3600),
                0, 16);

        if(saveImage) {
            saveImage("Frame-" + frameIndex, frame);
        }
        frameIndex++;
    }

    private void renderInfo(Graphics2D canvas, String info, int x, int y) {
        canvas.setColor(Color.WHITE);
        canvas.drawString(info, x, y);
    }

    /**
     * UNIFIED rendering method - consistent logic for all objects
     */
    private BufferedImage renderFrame(OrbitalSystem system, int scalar, double maxAUVisible, Vector3D rotate) {
        BufferedImage image = new BufferedImage(
                WIDTH_RATIO * scalar,
                HEIGHT_RATIO * scalar,
                IMAGE_TYPE
        );
        Graphics2D canvas = image.createGraphics();
        canvas.setBackground(Color.BLACK);
        canvas.clearRect(0, 0, image.getWidth(), image.getHeight());

        double adjustedAU = scaleAUToCanvas(HEIGHT_RATIO, WIDTH_RATIO);
        double canvasScale = PhysicsConstants.AU * (maxAUVisible * 3.0 / 4.0);
        int centerX = WIDTH_RATIO * scalar / 2;
        int centerY = HEIGHT_RATIO * scalar / 2;

        // Draw central star
        canvas.setColor(Color.YELLOW);
        canvas.fillOval(centerX - 4, centerY - 4, 8, 8);

        // Draw all orbiters (unified rendering)
        Random colorRandom = new Random(scalar);
        for(Orbiter orbiter : system.getOrbiters().values()) {
            renderOrbiter(canvas, orbiter, rotate, canvasScale, adjustedAU,
                    centerX, centerY, colorRandom);
        }

        // Draw all spacecraft (unified rendering)
        for(Spacecraft spacecraft : system.getSpacecraftInTransit().values()) {
            // Only render if not docked
            if(spacecraft.getState() != Spacecraft.SpacecraftState.DOCKED) {
                renderSpacecraft(canvas, spacecraft, rotate, canvasScale,
                        adjustedAU, centerX, centerY);
            }
        }

        return image;
    }

    /**
     * Render a single orbiter with consistent rotation logic
     */
    private void renderOrbiter(Graphics2D canvas, Orbiter orbiter, Vector3D rotate,
                               double canvasScale, double adjustedAU,
                               int centerX, int centerY, Random colorRandom) {

        // Apply camera rotation around axes
        Vector3D position = orbiter.getPosition();
        Vector3D rotated = applyCameraRotation(position, rotate);
        double xRaw = rotated.getX() / canvasScale;
        double yRaw = rotated.getY() / canvasScale;

        int screenX = (int)(xRaw * adjustedAU + centerX);
        int screenY = (int)(yRaw * adjustedAU + centerY);

        // Determine color based on orbiter type
        Color color = determineOrbiterColor(orbiter, colorRandom);
        canvas.setColor(color);

        // Determine size based on radius
        int size = determineOrbiterSize(orbiter);

        // Draw the orbiter
        Rectangle rectangle = new Rectangle(screenX, screenY, size, size);
        canvas.fill(rectangle);

        // Draw label (skip for belt objects)
        if(!orbiter.getId().contains("Belt")) {
            renderInfo(canvas, orbiter.getId(), screenX + 3, screenY);
        }
    }

    /**
     * Render a single spacecraft with consistent rotation logic
     */
    private void renderSpacecraft(Graphics2D canvas, Spacecraft spacecraft, Vector3D rotate,
                                  double canvasScale, double adjustedAU,
                                  int centerX, int centerY) {

        // Get current position (telemetry, orbiting body, or direct)
        Vector3D position = getCurrentSpacecraftPosition(spacecraft);

        // Apply camera rotation around axes
        Vector3D rotated = applyCameraRotation(position, rotate);
        double xRaw = rotated.getX() / canvasScale;
        double yRaw = rotated.getY() / canvasScale;

        int screenX = (int)(xRaw * adjustedAU + centerX);
        int screenY = (int)(yRaw * adjustedAU + centerY);

        // Spacecraft always render in red
        canvas.setColor(Color.RED);

        // Draw the spacecraft
        Rectangle rectangle = new Rectangle(screenX, screenY, SPACECRAFT_SIZE, SPACECRAFT_SIZE);
        canvas.fill(rectangle);

        // Draw label with state
        String label = spacecraft.getId() + " " + spacecraft.getState();
        renderInfo(canvas, label, screenX, screenY + 10);
    }

    /**
     * Extract spacecraft position determination to separate method
     * Prioritizes: telemetry > orbiting body position > direct position
     */
    private Vector3D getCurrentSpacecraftPosition(Spacecraft spacecraft) {
        // First priority: telemetry data if in transit
        if(spacecraft.getTelemetry() != null &&
                spacecraft.getCurrentTravelCycle() < spacecraft.getTelemetry().size()) {
            return spacecraft.getTelemetry().get(spacecraft.getCurrentTravelCycle()).position();
        }

        // Second priority: orbiting body position if attached
        if(spacecraft.getOrbiting() != null) {
            return spacecraft.getOrbiting().getPosition();
        }

        // Fallback: spacecraft's own position
        return spacecraft.getPosition();
    }

    /**
     * Determine color for an orbiter based on its ID
     */
    private Color determineOrbiterColor(Orbiter orbiter, Random colorRandom) {
        String id = orbiter.getId();

        if(id.contains("Belt")) {
            return Color.WHITE;
        } else if(id.contains("KHI")) {
            // Purple-ish for KHI objects
            return new Color(colorRandom.nextInt(256), 0, 255);
        } else {
            // Green-ish for regular orbiters
            return new Color(colorRandom.nextInt(256), 255, 0);
        }
    }

    /**
     * Determine size for an orbiter based on its radius
     */
    private int determineOrbiterSize(Orbiter orbiter) {
        if(orbiter instanceof OrbitingBody) {
            OrbitingBody body = (OrbitingBody) orbiter;
            return body.getRadius() > LARGE_BODY_THRESHOLD ? LARGE_BODY_SIZE : SMALL_BODY_SIZE;
        }
        return SMALL_BODY_SIZE;
    }

    /**
     * Apply camera rotation to a 3D position vector
     *
     * Rotates around X, Y, Z axes in order using Euler angles
     * rotate.x = rotation around X axis (pitch)
     * rotate.y = rotation around Y axis (yaw)
     * rotate.z = rotation around Z axis (roll)
     */
    private Vector3D applyCameraRotation(Vector3D position, Vector3D rotate) {
        Vector3D result = position;

        // Rotate around X axis (pitch)
        if (Math.abs(rotate.getX()) > 1e-10) {
            result = result.rotateAroundVector(Vector3D.UNIT_X, rotate.getX());
        }

        // Rotate around Y axis (yaw)
        if (Math.abs(rotate.getY()) > 1e-10) {
            result = result.rotateAroundVector(Vector3D.UNIT_Y, rotate.getY());
        }

        // Rotate around Z axis (roll)
        if (Math.abs(rotate.getZ()) > 1e-10) {
            result = result.rotateAroundVector(Vector3D.UNIT_Z, rotate.getZ());
        }

        return result;
    }

    private double scaleAUToCanvas(int height, int width) {
        int min = Math.min(height, width);
        return scalar * (min / 4.0);
    }

    private void saveImage(String name, BufferedImage currentFrame) throws IOException {
        File output = new File("orbits/" + name + ".png");
        ImageIO.write(currentFrame, "PNG", output);
    }

    public void renderVideoFromImages(double scaleMultiplier) throws IOException {
        File output = new File("orbits/test.mp4");
        BufferedImage reference = ImageIO.read(new File("orbits/Frame-0.png"));
        int scaleWidth = (int)Math.round(reference.getWidth() * scaleMultiplier);
        int scaleHeight = (int)Math.round(reference.getHeight() * scaleMultiplier);

        SequenceEncoder encoder = SequenceEncoder.createWithFps(
                NIOUtils.writableChannel(output), Rational.R(30, 1));

        int currentFrame = 0;
        int totalFiles = Objects.requireNonNull(
                new File("orbits/").listFiles(pathname -> pathname.getName().endsWith(".png"))
        ).length;

        int logInterval = 20;
        Date start = new Date();
        File inputFrame = new File("orbits/Frame-" + currentFrame + ".png");

        while(inputFrame.exists()) {
            if(currentFrame % logInterval == 0) {
                double completed = (double)currentFrame / (double)totalFiles;
                int remainingSeconds = (int)((double)(totalFiles - currentFrame) *
                        (new Date().getTime() - start.getTime()) / (logInterval * 1000));
                System.out.printf("\rRendering Video Frame %4d - %3.1f%% complete : %3d minutes, %2d seconds remaining.",
                        currentFrame, completed * 100.0, remainingSeconds / 60, remainingSeconds % 60);
                start = new Date();
            }

            encoder.encodeNativeFrame(scaleImage(inputFrame, scaleWidth, scaleHeight));
            currentFrame++;
            inputFrame = new File("orbits/Frame-" + currentFrame + ".png");
        }

        encoder.finish();
        System.out.println("\nVideo rendering complete!");
    }

    private static Picture scaleImage(File source, int scaleWidth, int scaleHeight) throws IOException {
        Image scaledImage = ImageIO.read(source).getScaledInstance(
                scaleWidth, scaleHeight, Image.SCALE_SMOOTH);
        BufferedImage scaled = new BufferedImage(scaleWidth, scaleHeight, IMAGE_TYPE);
        Graphics2D g2d = scaled.createGraphics();
        g2d.drawImage(scaledImage, 0, 0, null);
        g2d.dispose();
        return AWTUtil.fromBufferedImage(scaled, ColorSpace.RGB);
    }

    public void renderVideo() throws IOException {
        File output = new File("orbits/test.mp4");
        SequenceEncoder encoder = SequenceEncoder.createWithFps(
                NIOUtils.writableChannel(output), Rational.R(30, 1));

        int currentFrame = 0;
        File input = new File("orbits/Frame-" + currentFrame + ".png");

        while(input.exists()) {
            BufferedImage image = ImageIO.read(input);
            encoder.encodeNativeFrame(AWTUtil.fromBufferedImage(image, ColorSpace.RGB));
            currentFrame++;
            input = new File("orbits/Frame-" + currentFrame + ".png");
        }

        encoder.finish();
    }
}