package com.kaymlyn.planeteater.rendering;

import com.kaymlyn.planeteater.simulation.celestial.Orbiter;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.PhysicsBody;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.celestial.BodyType;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.vehicles.Satellite;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import org.jcodec.api.SequenceEncoder;
import org.jcodec.common.io.NIOUtils;
import org.jcodec.common.model.ColorSpace;
import org.jcodec.common.model.Rational;
import org.jcodec.scale.AWTUtil;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferInt;
import java.io.File;
import java.io.IOException;
import java.util.*;

/**
 * HIGH-PERFORMANCE orbital system renderer
 *
 * OPTIMIZATIONS:
 * 1. Pre-compute rotation matrix (avoid 3 rotations per object)
 * 2. Direct pixel manipulation (avoid Graphics2D overhead)
 * 3. Batch similar operations (group by color)
 * 4. Skip disk I/O - render directly to video encoder
 * 5. Cache color objects and strings
 * 6. Pre-allocate data structures
 *
 * Multi-view rendering (render4View) uses a single-pass architecture:
 * all four rotation matrices are pre-computed, then each physics object
 * is projected into all four view buffers in one iteration. This avoids
 * 4x redundant traversal of the physics object map.
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class OrbitalSystemRendererOptimized {

    private final OrbitalSystem system;
    private final int width;
    private final int height;

    // Pre-computed constants
    private final int centerX;
    private final int centerY;
    private final double adjustedAU;

    // Cached objects (avoid allocations)
    private final Random colorRandom;
    private final Map<String, Color> colorCache;
    private final Map<String, Integer> sizeCache;
    private final Map<String, Boolean> shouldLabelCache;

    // Rendering mode
    private final boolean directToVideo;
    private SequenceEncoder videoEncoder;

    // Performance tracking
    private long frameCount = 0;
    private long totalRenderTime = 0;

    // Rendering constants
    private static final int IMAGE_TYPE = BufferedImage.TYPE_INT_RGB;
    private static final int HEIGHT_RATIO = 9;
    private static final int WIDTH_RATIO = 16;
    private static final double LARGE_BODY_THRESHOLD = 50000.0;
    private static final int LARGE_BODY_SIZE = 3;
    private static final int SMALL_BODY_SIZE = 2;
    private static final int SPACECRAFT_SIZE = 1;

    // Baseline minor dimension for proportional size scaling
    private static final int BASELINE_MINOR_DIMENSION = 720;

    // 4-view output dimensions: 1920x1080, each panel 960x540
    private static final int MULTIVIEW_TOTAL_WIDTH = 1920;
    private static final int MULTIVIEW_TOTAL_HEIGHT = 1080;
    private static final int MULTIVIEW_PANEL_WIDTH = MULTIVIEW_TOTAL_WIDTH / 2;
    private static final int MULTIVIEW_PANEL_HEIGHT = MULTIVIEW_TOTAL_HEIGHT / 2;

    // Panel offsets [panelIndex] = {xOffset, yOffset}
    private static final int[][] PANEL_OFFSETS = {
            {0, 0},                                           // top-left
            {MULTIVIEW_PANEL_WIDTH, 0},                       // top-right
            {0, MULTIVIEW_PANEL_HEIGHT},                      // bottom-left
            {MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT}   // bottom-right
    };

    // Colors (pre-allocated)
    private static final Color COLOR_STAR = Color.YELLOW;
    private static final Color COLOR_SPACECRAFT = Color.RED;
    private static final Color COLOR_BELT = Color.WHITE;
    private static final int BLACK_RGB = Color.BLACK.getRGB();

    /**
     * Create optimized renderer.
     *
     * @param system       the orbital system to render
     * @param visibleAU    radius of visible region in AU
     * @param directToVideo if true, skips PNG output and renders directly to MP4
     */
    public OrbitalSystemRendererOptimized(OrbitalSystem system, double visibleAU, boolean directToVideo) {
        this.system = system;
        int scalar = 80;
        this.width = WIDTH_RATIO * scalar;
        this.height = HEIGHT_RATIO * scalar;
        this.directToVideo = directToVideo;

        // Pre-compute constants
        this.centerX = width / 2;
        this.centerY = height / 2;
        this.adjustedAU = scalar * (Math.min(HEIGHT_RATIO, WIDTH_RATIO) / visibleAU);

        // Initialize caches
        this.colorRandom = new Random(scalar);
        this.colorCache = new HashMap<>();
        this.sizeCache = new HashMap<>();
        this.shouldLabelCache = new HashMap<>();

        // Pre-populate caches
        preCacheObjectProperties();

        // Setup output directory if needed
        if (!directToVideo) {
            File directory = new File("orbits");
            if (!directory.exists()) {
                directory.mkdir();
            }
            for (File file : Objects.requireNonNull(directory.listFiles())) {
                if (file.getName().endsWith(".png")) {
                    file.delete();
                }
            }
        }
    }

    // ==================== CACHE MANAGEMENT ====================

    /**
     * Pre-cache properties for all objects to avoid runtime lookups.
     */
    private void preCacheObjectProperties() {
        for (PhysicsBody body : system.getPhysicsObjects().values()) {
            String id = body.getId();

            if (id.contains("Belt")) {
                colorCache.put(id, COLOR_BELT);
            } else if (id.contains("KHI")) {
                colorCache.put(id, new Color(colorRandom.nextInt(256), 0, 255));
            } else {
                colorCache.put(id, new Color(colorRandom.nextInt(256), 255, 0));
            }

            int size = SMALL_BODY_SIZE;
            if (body instanceof OrbitingBody orbitingBody) {
                size = orbitingBody.getRadius() > LARGE_BODY_THRESHOLD ? LARGE_BODY_SIZE : SMALL_BODY_SIZE;
            }
            sizeCache.put(id, size);

            shouldLabelCache.put(id, !id.contains("Belt"));
        }
    }

    // ==================== VIDEO LIFECYCLE ====================

    /**
     * Initialize video encoder for direct rendering.
     */
    public void initializeVideoEncoder(String outputPath) throws IOException {
        File output = new File(outputPath);
        videoEncoder = SequenceEncoder.createWithFps(
                NIOUtils.writableChannel(output), Rational.R(30, 1));
    }

    /**
     * Finalize video encoding.
     */
    public void finalizeVideo() throws IOException {
        if (videoEncoder != null) {
            videoEncoder.finish();
            System.out.printf("%nVideo complete: %d frames, avg %.1f ms/frame%n",
                    frameCount, (double) totalRenderTime / frameCount);
        }
    }

    // ==================== SINGLE-VIEW RENDER ====================

    /**
     * Render a single frame at 1280x720 with the given camera rotation.
     * This is the backward-compatible entry point retained as a fallback.
     */
    public void render(double maxAUVisible, Vector3D rotate, int frameIndex) throws IOException {
        long startTime = System.nanoTime();

        RotationMatrix rotationMatrix = new RotationMatrix(rotate);
        BufferedImage image = new BufferedImage(width, height, IMAGE_TYPE);
        int[] pixels = ((DataBufferInt) image.getRaster().getDataBuffer()).getData();
        Arrays.fill(pixels, BLACK_RGB);

        double canvasScale = PhysicsConstants.AU * (maxAUVisible * 3.0 / 4.0);

        drawFilledCircle(pixels, centerX, centerY, 4, COLOR_STAR.getRGB());
        renderAllOrbiters(pixels, rotationMatrix, canvasScale);

        Graphics2D g2d = image.createGraphics();
        g2d.setColor(Color.WHITE);

        String timeInfo = String.format("Day %d Hour %d",
                (int) (system.getCurrentTime() / PhysicsConstants.SECONDS_PER_DAY),
                (int) ((system.getCurrentTime() % PhysicsConstants.SECONDS_PER_DAY) / 3600));
        g2d.drawString(timeInfo, 5, 16);

        for (PhysicsBody body : system.getPhysicsObjects().values()) {
            if (body instanceof Orbiter orbiter) {
                renderOrbiterLabel(orbiter, g2d, rotationMatrix, canvasScale);
            } else if (body instanceof Spacecraft spacecraft) {
                renderSpacecraftLabel(spacecraft, g2d, rotationMatrix, canvasScale);
            }
        }

        g2d.dispose();

        outputFrame(image, frameIndex);
        trackPerformance(startTime);
    }

    // ==================== FOUR-VIEW RENDER ====================

    /**
     * Render a 1920x1080 composite frame containing four view panels arranged in a 2x2 grid.
     *
     * Panel layout:
     *   [0] top-left     [1] top-right
     *   [2] bottom-left  [3] bottom-right
     *
     * The views array must have exactly 4 elements. A null element falls back to a
     * top-down view with no grid or labels.
     *
     * Single-pass: all physics objects are iterated once and projected into all four
     * panel buffers simultaneously.
     *
     * @param maxAUVisible visible radius in AU (matched to all four panels)
     * @param views        array of 4 ViewConfig instances
     * @param frameIndex   frame number for PNG output path
     */
    public void render4View(double maxAUVisible, ViewConfig[] views, int frameIndex) throws IOException {
        if (views == null || views.length != 4) {
            throw new IllegalArgumentException("views must be an array of exactly 4 ViewConfig instances");
        }

        long startTime = System.nanoTime();

        double canvasScale = PhysicsConstants.AU * (maxAUVisible * 3.0 / 4.0);


        // Panel geometry: 960x540, scalar derived from panel height
        int panelScalar = MULTIVIEW_PANEL_HEIGHT / HEIGHT_RATIO;
        double panelAdjustedAU = panelScalar * (Math.min(HEIGHT_RATIO, WIDTH_RATIO) / maxAUVisible);
        int panelCenterX = MULTIVIEW_PANEL_WIDTH / 2;
        int panelCenterY = MULTIVIEW_PANEL_HEIGHT / 2;

        // Pre-compute one RotationMatrix per panel
        RotationMatrix[] rotations = new RotationMatrix[4];
        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            ViewConfig view = views[panelIndex] != null ? views[panelIndex] : ViewConfig.topDown();
            rotations[panelIndex] = new RotationMatrix(view.getRotation());
        }

        // Allocate four independent pixel buffers
        int panelPixelCount = MULTIVIEW_PANEL_WIDTH * MULTIVIEW_PANEL_HEIGHT;
        int[][] panelPixels = new int[4][panelPixelCount];
        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            Arrays.fill(panelPixels[panelIndex], BLACK_RGB);
        }

        // Draw reference frame for panels where gridOnTop is false (before objects)
        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            ViewConfig view = views[panelIndex] != null ? views[panelIndex] : ViewConfig.topDown();
            GridConfig grid = view.getGridConfig();
            if (!grid.isGridOnTop()) {
                renderReferenceFrame(panelPixels[panelIndex], rotations[panelIndex],
                        canvasScale, panelAdjustedAU, panelCenterX, panelCenterY,
                        MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT,
                        maxAUVisible, grid);
            }
        }

        // Single pass over all physics objects: project into all four panels
        int panelStarRadius = 4;
        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            drawFilledCircle(panelPixels[panelIndex],
                    panelCenterX, panelCenterY, panelStarRadius, COLOR_STAR.getRGB(),
                    MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT);
        }

        for (PhysicsBody body : system.getPhysicsObjects().values()) {
            // Star is rendered separately as a filled circle at origin; skip it in the square pass
            if (body instanceof Star) {
                continue;
            }

            String id = body.getId();
            Vector3D position = body.getPosition();

            Color color = colorCache.getOrDefault(id, COLOR_SPACECRAFT);
            int baseSize = sizeCache.getOrDefault(id, SPACECRAFT_SIZE);

            for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
                ViewConfig view = views[panelIndex] != null ? views[panelIndex] : ViewConfig.topDown();
                int scaledSize = computeScaledSize(baseSize, body, view.getObjectSizeStrategy());

                Vector3D rotated = rotations[panelIndex].transform(position);
                int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
                int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);

                drawFilledSquare(panelPixels[panelIndex], screenX, screenY, scaledSize, color.getRGB(),
                        MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT);
            }
        }

        // Draw reference frame for panels where gridOnTop is true (after objects)
        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            ViewConfig view = views[panelIndex] != null ? views[panelIndex] : ViewConfig.topDown();
            GridConfig grid = view.getGridConfig();
            if (grid.isGridOnTop()) {
                renderReferenceFrame(panelPixels[panelIndex], rotations[panelIndex],
                        canvasScale, panelAdjustedAU, panelCenterX, panelCenterY,
                        MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT,
                        maxAUVisible, grid);
            }
        }

        // Composite four panels into the 1920x1080 output image
        BufferedImage composite = new BufferedImage(MULTIVIEW_TOTAL_WIDTH, MULTIVIEW_TOTAL_HEIGHT, IMAGE_TYPE);
        int[] compositePixels = ((DataBufferInt) composite.getRaster().getDataBuffer()).getData();

        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            int xOffset = PANEL_OFFSETS[panelIndex][0];
            int yOffset = PANEL_OFFSETS[panelIndex][1];
            blitPanel(panelPixels[panelIndex], compositePixels,
                    xOffset, yOffset,
                    MULTIVIEW_PANEL_WIDTH, MULTIVIEW_PANEL_HEIGHT,
                    MULTIVIEW_TOTAL_WIDTH);
        }

        // Labels and titles require Graphics2D; done once on the composite
        Graphics2D g2d = composite.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);

        for (int panelIndex = 0; panelIndex < 4; panelIndex++) {
            ViewConfig view = views[panelIndex] != null ? views[panelIndex] : ViewConfig.topDown();
            int xOffset = PANEL_OFFSETS[panelIndex][0];
            int yOffset = PANEL_OFFSETS[panelIndex][1];

            renderPanelOverlays(g2d, view, rotations[panelIndex], canvasScale,
                    panelAdjustedAU, panelCenterX, panelCenterY, xOffset, yOffset, maxAUVisible);
        }

        g2d.dispose();

        outputMultiviewFrame(composite, frameIndex);
        trackPerformance(startTime);
    }

    // ==================== REFERENCE FRAME RENDERING ====================

    /**
     * Render graduated axes and optional ecliptic grid into a panel pixel buffer.
     * The grid is aligned with the solar system (not the camera): axis world-space
     * endpoints are projected through the rotation matrix before rasterization.
     */
    private void renderReferenceFrame(int[] pixels, RotationMatrix rotation,
                                      double canvasScale, double panelAdjustedAU,
                                      int panelCenterX, int panelCenterY,
                                      int panelWidth, int panelHeight,
                                      double maxAUVisible, GridConfig grid) {
        if (grid.isShowEclipticGrid()) {
            renderEclipticGrid(pixels, rotation, canvasScale, panelAdjustedAU,
                    panelCenterX, panelCenterY, panelWidth, panelHeight,
                    maxAUVisible, grid);
        }
        if (grid.isShowGraduatedAxes()) {
            renderGraduatedAxes(pixels, rotation, canvasScale, panelAdjustedAU,
                    panelCenterX, panelCenterY, panelWidth, panelHeight,
                    maxAUVisible, grid);
        }
    }

    /**
     * Render three graduated number-line axes through the origin.
     * Each axis arm (positive and/or negative) is drawn from the origin out to
     * maxAUVisible, with tick marks at tickIntervalAU intervals.
     */
    private void renderGraduatedAxes(int[] pixels, RotationMatrix rotation,
                                     double canvasScale, double panelAdjustedAU,
                                     int panelCenterX, int panelCenterY,
                                     int panelWidth, int panelHeight,
                                     double maxAUVisible, GridConfig grid) {
        renderSingleAxis(pixels, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, panelWidth, panelHeight,
                maxAUVisible, grid.getXAxisConfig(),
                new Vector3D(1.0, 0.0, 0.0));

        renderSingleAxis(pixels, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, panelWidth, panelHeight,
                maxAUVisible, grid.getYAxisConfig(),
                new Vector3D(0.0, 1.0, 0.0));

        renderSingleAxis(pixels, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, panelWidth, panelHeight,
                maxAUVisible, grid.getZAxisConfig(),
                new Vector3D(0.0, 0.0, 1.0));
    }

    /**
     * Render one axis defined by a world-space unit direction vector.
     * Projects tick positions through the rotation matrix and draws line segments
     * between consecutive ticks using direct pixel manipulation.
     */
    private void renderSingleAxis(int[] pixels, RotationMatrix rotation,
                                  double canvasScale, double panelAdjustedAU,
                                  int panelCenterX, int panelCenterY,
                                  int panelWidth, int panelHeight,
                                  double maxAUVisible, AxisConfig axis,
                                  Vector3D axisDirection) {
        if (!axis.isEnabled()) {
            return;
        }

        int rgb = axis.getColor().getRGB();
        double tickIntervalMeters = axis.getTickIntervalAU() * PhysicsConstants.AU;
        int tickCount = (int) Math.ceil(maxAUVisible / axis.getTickIntervalAU());

        // Origin in screen space
        int originScreenX = panelCenterX;
        int originScreenY = panelCenterY;

        // Render positive arm
        if (axis.isShowPositive()) {
            int prevScreenX = originScreenX;
            int prevScreenY = originScreenY;
            for (int tick = 1; tick <= tickCount; tick++) {
                Vector3D worldPoint = axisDirection.multiply(tick * tickIntervalMeters);
                Vector3D rotated = rotation.transform(worldPoint);
                int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
                int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
                drawLine(pixels, prevScreenX, prevScreenY, screenX, screenY,
                        rgb, panelWidth, panelHeight,
                        axis.getLineType(), axis.getDashPeriod(), axis.getLineWeight());
                drawTickMark(pixels, screenX, screenY, rotated,
                        rgb, axis.getTickHeightPixels(), panelWidth, panelHeight);
                prevScreenX = screenX;
                prevScreenY = screenY;
            }
        }

        // Render negative arm
        if (axis.isShowNegative()) {
            int prevScreenX = originScreenX;
            int prevScreenY = originScreenY;
            for (int tick = 1; tick <= tickCount; tick++) {
                Vector3D worldPoint = axisDirection.multiply(-tick * tickIntervalMeters);
                Vector3D rotated = rotation.transform(worldPoint);
                int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
                int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
                drawLine(pixels, prevScreenX, prevScreenY, screenX, screenY,
                        rgb, panelWidth, panelHeight,
                        axis.getLineType(), axis.getDashPeriod(), axis.getLineWeight());
                drawTickMark(pixels, screenX, screenY, rotated,
                        rgb, axis.getTickHeightPixels(), panelWidth, panelHeight);
                prevScreenX = screenX;
                prevScreenY = screenY;
            }
        }
    }

    /**
     * Render the ecliptic grid: lines parallel to X and Y axes in the Z=0 plane,
     * spaced at eclipticGridIntervalAU intervals from -maxAUVisible to +maxAUVisible.
     */
    private void renderEclipticGrid(int[] pixels, RotationMatrix rotation,
                                    double canvasScale, double panelAdjustedAU,
                                    int panelCenterX, int panelCenterY,
                                    int panelWidth, int panelHeight,
                                    double maxAUVisible, GridConfig grid) {
        int rgb = grid.getEclipticGridColor().getRGB();
        double intervalMeters = grid.getEclipticGridIntervalAU() * PhysicsConstants.AU;
        double extentMeters = maxAUVisible * PhysicsConstants.AU;
        int lineCount = (int) Math.ceil(maxAUVisible / grid.getEclipticGridIntervalAU());

        // Lines parallel to Y axis (constant X)
        for (int lineIndex = -lineCount; lineIndex <= lineCount; lineIndex++) {
            double xWorld = lineIndex * intervalMeters;

            Vector3D startWorld = new Vector3D(xWorld, -extentMeters, 0.0);
            Vector3D endWorld = new Vector3D(xWorld, extentMeters, 0.0);
            Vector3D startRotated = rotation.transform(startWorld);
            Vector3D endRotated = rotation.transform(endWorld);

            int startScreenX = (int) (startRotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
            int startScreenY = (int) (startRotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
            int endScreenX = (int) (endRotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
            int endScreenY = (int) (endRotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);

            drawLine(pixels, startScreenX, startScreenY, endScreenX, endScreenY,
                    rgb, panelWidth, panelHeight,
                    grid.getEclipticGridLineType(), grid.getEclipticGridDashPeriod(),
                    grid.getEclipticGridLineWeight());
        }

        // Lines parallel to X axis (constant Y)
        for (int lineIndex = -lineCount; lineIndex <= lineCount; lineIndex++) {
            double yWorld = lineIndex * intervalMeters;

            Vector3D startWorld = new Vector3D(-extentMeters, yWorld, 0.0);
            Vector3D endWorld = new Vector3D(extentMeters, yWorld, 0.0);
            Vector3D startRotated = rotation.transform(startWorld);
            Vector3D endRotated = rotation.transform(endWorld);

            int startScreenX = (int) (startRotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
            int startScreenY = (int) (startRotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
            int endScreenX = (int) (endRotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
            int endScreenY = (int) (endRotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);

            drawLine(pixels, startScreenX, startScreenY, endScreenX, endScreenY,
                    rgb, panelWidth, panelHeight,
                    grid.getEclipticGridLineType(), grid.getEclipticGridDashPeriod(),
                    grid.getEclipticGridLineWeight());
        }
    }

    // ==================== LABEL AND OVERLAY RENDERING ====================

    /**
     * Render all text overlays for one panel onto the composite Graphics2D context.
     * Handles view title, timestamp, and per-object-type labels with panel offset applied.
     */
    private void renderPanelOverlays(Graphics2D g2d, ViewConfig view,
                                     RotationMatrix rotation, double canvasScale,
                                     double panelAdjustedAU, int panelCenterX, int panelCenterY,
                                     int xOffset, int yOffset, double maxAUVisible) {
        LabelConfig labelConfig = view.getLabelConfig();
        g2d.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, labelConfig.getFontSize()));
        g2d.setColor(Color.WHITE);

        // View title
        if (!view.getViewTitle().isEmpty()) {
            g2d.drawString(view.getViewTitle(), xOffset + 5, yOffset + 14);
        }

        // Timestamp
        if (view.isShowTimestamp()) {
            String timeInfo = String.format("Day %d Hour %d",
                    (int) (system.getCurrentTime() / PhysicsConstants.SECONDS_PER_DAY),
                    (int) ((system.getCurrentTime() % PhysicsConstants.SECONDS_PER_DAY) / 3600));
            g2d.drawString(timeInfo, xOffset + 5, yOffset + 28);
        }

        if (labelConfig.isShowStar()) {
            FontMetrics metrics = g2d.getFontMetrics();
            String starId = system.getCentralStar().getId();
            int stringCenter = metrics.stringWidth(starId)/2;
            g2d.drawString(starId, xOffset + panelCenterX - stringCenter, yOffset + panelCenterY + metrics.getMaxAscent() + 3);
        }

        // Object labels
        for (PhysicsBody body : system.getPhysicsObjects().values()) {
            if (!shouldRenderLabel(body, labelConfig)) {
                continue;
            }

            Vector3D position = body.getPosition();
            Vector3D rotated = rotation.transform(position);
            int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
            int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);

            String label = buildLabel(body);
            g2d.drawString(label, xOffset + screenX + 3, yOffset + screenY);
        }

        // Axis tick labels (AU values)
        renderAxisTickLabels(g2d, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, xOffset, yOffset,
                maxAUVisible, view.getGridConfig());
    }

    /**
     * Render AU value labels for axis ticks onto the composite context.
     * Called once per panel per axis that has showTickLabels enabled.
     */
    private void renderAxisTickLabels(Graphics2D g2d, RotationMatrix rotation,
                                      double canvasScale, double panelAdjustedAU,
                                      int panelCenterX, int panelCenterY,
                                      int xOffset, int yOffset,
                                      double maxAUVisible, GridConfig grid) {
        if (!grid.isShowGraduatedAxes()) {
            return;
        }

        renderAxisTickLabelsForAxis(g2d, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, xOffset, yOffset,
                maxAUVisible, grid.getXAxisConfig(), new Vector3D(1.0, 0.0, 0.0));

        renderAxisTickLabelsForAxis(g2d, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, xOffset, yOffset,
                maxAUVisible, grid.getYAxisConfig(), new Vector3D(0.0, 1.0, 0.0));

        renderAxisTickLabelsForAxis(g2d, rotation, canvasScale, panelAdjustedAU,
                panelCenterX, panelCenterY, xOffset, yOffset,
                maxAUVisible, grid.getZAxisConfig(), new Vector3D(0.0, 0.0, 1.0));
    }

    private void renderAxisTickLabelsForAxis(Graphics2D g2d, RotationMatrix rotation,
                                             double canvasScale, double panelAdjustedAU,
                                             int panelCenterX, int panelCenterY,
                                             int xOffset, int yOffset,
                                             double maxAUVisible, AxisConfig axis,
                                             Vector3D axisDirection) {
        if (!axis.isEnabled() || !axis.isShowTickLabels()) {
            return;
        }

        g2d.setColor(axis.getColor());
        double tickIntervalMeters = axis.getTickIntervalAU() * PhysicsConstants.AU;
        int tickCount = (int) Math.ceil(maxAUVisible / axis.getTickIntervalAU());

        for (int tick = 1; tick <= tickCount; tick++) {
            if (axis.isShowPositive()) {
                Vector3D worldPoint = axisDirection.multiply(tick * tickIntervalMeters);
                Vector3D rotated = rotation.transform(worldPoint);
                int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
                int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
                g2d.drawString(tick + " AU", xOffset + screenX + 3, yOffset + screenY - 3);
            }
            if (axis.isShowNegative()) {
                Vector3D worldPoint = axisDirection.multiply(-tick * tickIntervalMeters);
                Vector3D rotated = rotation.transform(worldPoint);
                int screenX = (int) (rotated.getX() / canvasScale * panelAdjustedAU + panelCenterX);
                int screenY = (int) (rotated.getY() / canvasScale * panelAdjustedAU + panelCenterY);
                g2d.drawString("-" + tick + " AU", xOffset + screenX + 3, yOffset + screenY - 3);
            }
        }
    }

    // ==================== OBJECT CLASSIFICATION ====================

    /**
     * Determine whether a label should be rendered for this body given the config.
     * Belt objects are always suppressed regardless of config (id-based filter
     * consistent with existing single-view behaviour).
     */
    private boolean shouldRenderLabel(PhysicsBody body, LabelConfig labelConfig) {
        String id = body.getId();
        if (id.contains("Belt")) {
            return false;
        }

        if (body instanceof Spacecraft spacecraft) {
            if (spacecraft.getState() == Spacecraft.SpacecraftState.DOCKED) {
                return false;
            }
            return labelConfig.isShowSpacecraft();
        }
        if (body instanceof Satellite) {
            return labelConfig.isShowSatellites();
        }
        if (body instanceof Planet planet) {
            BodyType type = planet.getType();
            boolean isAsteroid = type == BodyType.C_TYPE
                    || type == BodyType.S_TYPE
                    || type == BodyType.M_TYPE;
            return isAsteroid ? labelConfig.isShowAsteroids() : labelConfig.isShowPlanets();
        }

        // Unknown type: show by default
        return true;
    }

    /**
     * Build the display label string for a body.
     */
    private String buildLabel(PhysicsBody body) {
        if (body instanceof Spacecraft spacecraft) {
            return spacecraft.getId() + " " + spacecraft.getState();
        }
        return body.getId();
    }

    // ==================== OBJECT SIZE SCALING ====================

    /**
     * Compute the pixel size for an object in a panel given the size strategy.
     * The baseline for PROPORTIONAL and SMART scaling is BASELINE_MINOR_DIMENSION (720).
     * The panel minor dimension is MULTIVIEW_PANEL_HEIGHT (540).
     */
    private int computeScaledSize(int baseSize, PhysicsBody body, ObjectSizeStrategy strategy) {
        return switch (strategy) {
            case CONSTANT -> Math.max(1, baseSize);
            case PROPORTIONAL -> Math.max(1,
                    (int) Math.round(baseSize * ((double) MULTIVIEW_PANEL_HEIGHT / BASELINE_MINOR_DIMENSION)));
            case SMART -> {
                boolean isLargeBody = (body instanceof OrbitingBody orbitingBody)
                        && orbitingBody.getRadius() > LARGE_BODY_THRESHOLD;
                if (isLargeBody) {
                    yield Math.max(1,
                            (int) Math.round(baseSize * ((double) MULTIVIEW_PANEL_HEIGHT / BASELINE_MINOR_DIMENSION)));
                }
                yield 1;
            }
        };
    }

    // ==================== PIXEL PRIMITIVE OPERATIONS ====================

    /**
     * Copy one panel pixel buffer into the composite pixel buffer at the given offset.
     */
    private void blitPanel(int[] source, int[] destination,
                           int xOffset, int yOffset,
                           int panelWidth, int panelHeight,
                           int destinationWidth) {
        for (int row = 0; row < panelHeight; row++) {
            int sourceRowStart = row * panelWidth;
            int destinationRowStart = (yOffset + row) * destinationWidth + xOffset;
            System.arraycopy(source, sourceRowStart, destination, destinationRowStart, panelWidth);
        }
    }

    /**
     * Draw filled circle to an explicitly dimensioned pixel buffer.
     * Bounds-checks against the provided width and height.
     */
    private void drawFilledCircle(int[] pixels, int cx, int cy, int radius, int rgb,
                                  int bufferWidth, int bufferHeight) {
        int radiusSquared = radius * radius;
        for (int dy = -radius; dy <= radius; dy++) {
            for (int dx = -radius; dx <= radius; dx++) {
                if (dx * dx + dy * dy <= radiusSquared) {
                    int x = cx + dx;
                    int y = cy + dy;
                    if (x >= 0 && x < bufferWidth && y >= 0 && y < bufferHeight) {
                        pixels[y * bufferWidth + x] = rgb;
                    }
                }
            }
        }
    }

    /**
     * Draw filled circle to the class-level pixel buffer (single-view path).
     */
    private void drawFilledCircle(int[] pixels, int cx, int cy, int radius, int rgb) {
        drawFilledCircle(pixels, cx, cy, radius, rgb, width, height);
    }

    /**
     * Draw filled square to an explicitly dimensioned pixel buffer.
     */
    private void drawFilledSquare(int[] pixels, int x, int y, int size, int rgb,
                                  int bufferWidth, int bufferHeight) {
        for (int dy = 0; dy < size; dy++) {
            for (int dx = 0; dx < size; dx++) {
                int px = x + dx;
                int py = y + dy;
                if (px >= 0 && px < bufferWidth && py >= 0 && py < bufferHeight) {
                    pixels[py * bufferWidth + px] = rgb;
                }
            }
        }
    }

    /**
     * Draw filled square to the class-level pixel buffer (single-view path).
     */
    private void drawFilledSquare(int[] pixels, int x, int y, int size, int rgb) {
        drawFilledSquare(pixels, x, y, size, rgb, width, height);
    }

    /**
     * Bresenham's line algorithm with line type support.
     * lineWeight >= 2 draws perpendicular thick lines (simple square brush).
     */
    private void drawLine(int[] pixels, int x0, int y0, int x1, int y1, int rgb,
                          int bufferWidth, int bufferHeight,
                          LineType lineType, int dashPeriod, int lineWeight) {
        int dx = Math.abs(x1 - x0);
        int dy = Math.abs(y1 - y0);
        int stepX = x0 < x1 ? 1 : -1;
        int stepY = y0 < y1 ? 1 : -1;
        int error = dx - dy;
        int pixelIndex = 0;

        int currentX = x0;
        int currentY = y0;

        while (true) {
            boolean shouldDraw = switch (lineType) {
                case SOLID -> true;
                case DASHED -> (pixelIndex % dashPeriod) < (dashPeriod / 2);
                case DOTTED -> (pixelIndex % dashPeriod) == 0;
            };

            if (shouldDraw) {
                for (int dy2 = 0; dy2 < lineWeight; dy2++) {
                    for (int dx2 = 0; dx2 < lineWeight; dx2++) {
                        int px = currentX + dx2;
                        int py = currentY + dy2;
                        if (px >= 0 && px < bufferWidth && py >= 0 && py < bufferHeight) {
                            pixels[py * bufferWidth + px] = rgb;
                        }
                    }
                }
            }

            if (currentX == x1 && currentY == y1) {
                break;
            }

            int doubleError = 2 * error;
            if (doubleError > -dy) {
                error -= dy;
                currentX += stepX;
            }
            if (doubleError < dx) {
                error += dx;
                currentY += stepY;
            }

            pixelIndex++;
        }
    }

    /**
     * Draw a tick mark perpendicular to the axis direction at the given screen position.
     * The perpendicular is derived by rotating the projected axis direction 90 degrees
     * in screen space.
     *
     * rotatedAxisPoint is the projected world position at this tick; the perpendicular
     * direction is computed from it relative to the projected origin.
     */
    private void drawTickMark(int[] pixels, int screenX, int screenY,
                              Vector3D rotatedAxisPoint,
                              int rgb, int tickHeightPixels,
                              int bufferWidth, int bufferHeight) {
        // Perpendicular to the axis in screen space: rotate 90 degrees
        // The axis direction at this point is (rotatedAxisPoint.x, rotatedAxisPoint.y) normalized
        double axisScreenX = rotatedAxisPoint.getX();
        double axisScreenY = rotatedAxisPoint.getY();
        double magnitude = Math.sqrt(axisScreenX * axisScreenX + axisScreenY * axisScreenY);

        if (magnitude < 1e-9) {
            return;
        }

        double perpX = -axisScreenY / magnitude;
        double perpY = axisScreenX / magnitude;

        int halfTick = tickHeightPixels / 2;
        for (int step = -halfTick; step <= halfTick; step++) {
            int px = (int) Math.round(screenX + step * perpX);
            int py = (int) Math.round(screenY + step * perpY);
            if (px >= 0 && px < bufferWidth && py >= 0 && py < bufferHeight) {
                pixels[py * bufferWidth + px] = rgb;
            }
        }
    }

    // ==================== SINGLE-VIEW INTERNALS (backward compat) ====================

    private void renderAllOrbiters(int[] pixels, RotationMatrix rotation, double canvasScale) {
        for (PhysicsBody body : system.getPhysicsObjects().values()) {
            String id = body.getId();
            Vector3D position = body.getPosition();
            Vector3D rotated = rotation.transform(position);

            int screenX = (int) (rotated.getX() / canvasScale * adjustedAU + centerX);
            int screenY = (int) (rotated.getY() / canvasScale * adjustedAU + centerY);

            Color color = colorCache.get(id);
            int size;
            try {
                size = sizeCache.get(id);
            } catch (NullPointerException npe) {
                size = 1;
                color = COLOR_SPACECRAFT;
            }

            drawFilledSquare(pixels, screenX, screenY, size, color.getRGB());
        }
    }

    private void renderOrbiterLabel(Orbiter orbiter, Graphics2D g2d,
                                    RotationMatrix rotation, double canvasScale) {
        String id = orbiter.getId();
        if (!shouldLabelCache.get(id)) {
            return;
        }

        Vector3D position = orbiter.getPosition();
        Vector3D rotated = rotation.transform(position);

        int screenX = (int) (rotated.getX() / canvasScale * adjustedAU + centerX);
        int screenY = (int) (rotated.getY() / canvasScale * adjustedAU + centerY);

        g2d.drawString(id, screenX + 3, screenY);
    }

    private void renderSpacecraftLabel(Spacecraft spacecraft, Graphics2D g2d,
                                       RotationMatrix rotationMatrix, double canvasScale) {
        if (spacecraft.getState() == Spacecraft.SpacecraftState.DOCKED) {
            return;
        }

        Vector3D position = getCurrentSpacecraftPosition(spacecraft);
        Vector3D rotated = rotationMatrix.transform(position);

        int screenX = (int) (rotated.getX() / canvasScale * adjustedAU + centerX);
        int screenY = (int) (rotated.getY() / canvasScale * adjustedAU + centerY);

        String label = spacecraft.getId() + " " + spacecraft.getState();
        g2d.drawString(label, screenX, screenY + 10);
    }

    private Vector3D getCurrentSpacecraftPosition(Spacecraft spacecraft) {
        return spacecraft.getPosition();
    }

    // ==================== OUTPUT ====================

    private void outputFrame(BufferedImage image, int frameIndex) throws IOException {
        if (directToVideo && videoEncoder != null) {
            videoEncoder.encodeNativeFrame(AWTUtil.fromBufferedImage(image, ColorSpace.RGB));
        } else {
            File output = new File(String.format("orbits/Frame-%d.png", frameIndex));
            ImageIO.write(image, "PNG", output);
        }
    }

    private void outputMultiviewFrame(BufferedImage image, int frameIndex) throws IOException {
        if (directToVideo && videoEncoder != null) {
            videoEncoder.encodeNativeFrame(AWTUtil.fromBufferedImage(image, ColorSpace.RGB));
        } else {
            File output = new File(String.format("orbits/Frame4v-%d.png", frameIndex));
            ImageIO.write(image, "PNG", output);
        }
    }

    private void trackPerformance(long startTimeNanos) {
        long renderTime = (System.nanoTime() - startTimeNanos) / 1_000_000;
        totalRenderTime += renderTime;
        frameCount++;

        if (frameCount % 100 == 0) {
            System.out.printf("\rRendered %d frames, avg %.1f ms/frame",
                    frameCount, (double) totalRenderTime / frameCount);
        }
    }

    // ==================== ROTATION MATRIX ====================

    /**
     * Pre-computed rotation matrix for camera transformation.
     * Avoids 3 separate rotateAroundVector calls per object.
     * Convention: Rz * Ry * Rx applied to world-space position vectors.
     */
    private static class RotationMatrix {
        private final double[][] matrix = new double[3][3];

        public RotationMatrix(Vector3D eulerAngles) {
            double cosX = Math.cos(eulerAngles.getX());
            double sinX = Math.sin(eulerAngles.getX());
            double cosY = Math.cos(eulerAngles.getY());
            double sinY = Math.sin(eulerAngles.getY());
            double cosZ = Math.cos(eulerAngles.getZ());
            double sinZ = Math.sin(eulerAngles.getZ());

            matrix[0][0] = cosY * cosZ;
            matrix[0][1] = -cosY * sinZ;
            matrix[0][2] = sinY;

            matrix[1][0] = sinX * sinY * cosZ + cosX * sinZ;
            matrix[1][1] = -sinX * sinY * sinZ + cosX * cosZ;
            matrix[1][2] = -sinX * cosY;

            matrix[2][0] = -cosX * sinY * cosZ + sinX * sinZ;
            matrix[2][1] = cosX * sinY * sinZ + sinX * cosZ;
            matrix[2][2] = cosX * cosY;
        }

        public Vector3D transform(Vector3D v) {
            double x = matrix[0][0] * v.getX() + matrix[0][1] * v.getY() + matrix[0][2] * v.getZ();
            double y = matrix[1][0] * v.getX() + matrix[1][1] * v.getY() + matrix[1][2] * v.getZ();
            double z = matrix[2][0] * v.getX() + matrix[2][1] * v.getY() + matrix[2][2] * v.getZ();
            return new Vector3D(x, y, z);
        }
    }
}