package com.kaymlyn.planeteater.simulation.celestial;

import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;

import lombok.Getter;

/**
 * Represents a star (central body in the system)
 * Can be mined using advanced stellar lifting technology
 * Uses mass-radius relationship for main sequence stars
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Star implements CelestialBody {

    protected String id;
    protected OrbitalSystem system;
    protected Vector3D position; // meters
    protected Vector3D velocity;
    private final Composition atmosphereComposition;  // Extractable materials from corona/photosphere
    private final Composition totalComposition;               // Natural mass loss rate (kg/s)
    private boolean initialized;

    public Star(String id, Vector3D position, Vector3D velocity) {
        this(id, null, position, velocity);
    }

    protected  Star(String id, OrbitalSystem system, Vector3D position, Vector3D velocity) {
        this.id = id;
        this.system = system;
        this.position = position;
        this.velocity = velocity;
        this.totalComposition = new Composition();
        this.atmosphereComposition = new Composition();
        initialized = false;
    }

    protected void initialize() {
        if(!initialized) {
            initializeAtmosphere();
            initialized = true;
        }
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public Vector3D getPosition() {
        return Vector3D.ZERO;
    }

    /**
     * Calculate stellar radius using the main sequence mass-radius relationship
     * For main sequence stars:
     * - M < 1 M_sun: R scales as M^0.8
     * - M >= 1 M_sun: R scales as M^0.57
     * This accounts for gravitational compression balanced by fusion pressure
     */
    private double calculateMainSequenceRadius() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8; // meters

        if (massRatio < 1.0) {
            // Low mass stars: stronger gravity compression relative to pressure
            return solarRadius * Math.pow(massRatio, 0.8);
        } else {
            // Higher mass stars: radiation pressure becomes more significant
            return solarRadius * Math.pow(massRatio, 0.57);
        }
    }

    /**
     * Calculate surface temperature using main sequence mass-luminosity-temperature relationship
     * L scales as M^3.5 for main sequence stars
     * L = 4πR²σT^4 (Stefan-Boltzmann)
     * Combining: T scales as (M^3.5 / R²)^0.25
     */
    public double calculateMainSequenceTemperature() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8;
        double solarTemp = 5778.0; // Kelvin

        // Luminosity scales as M^3.5
        double luminosityRatio = Math.pow(massRatio, 3.5);

        // Radius ratio
        double radiusRatio = calculateMainSequenceRadius() / solarRadius;

        // Temperature from Stefan-Boltzmann: T^4 scales as L/R²
        double tempRatio = Math.pow(luminosityRatio / (radiusRatio * radiusRatio), 0.25);

        return solarTemp * tempRatio;
    }

    /**
     * Calculate mass loss rate (solar wind)
     * Scales roughly with luminosity and surface area
     * Higher mass stars lose mass faster
     */
    public double calculateMassLossRate() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarMassLoss = 2e9; // kg/s for Sun

        // Mass loss roughly scales with M^2 (combination of wind speed and density)
        return solarMassLoss * Math.pow(massRatio, 2.0);
    }

    /**
     * Calculate average density of the star
     * This accounts for compression - stars are much denser than their constituent materials
     */
    @Override
    public double getDensity() {
        return getMass() / getVolume();
    }

    @Override
    public double getVolume() {
        return (4.0 / 3.0) * Math.PI * Math.pow(calculateMainSequenceRadius(), 3);
    }

    @Override
    public double getMass() {
        return getAggregatedMass();
    }

    /**
     * Override getRadius to return the calculated stellar radius
     * Not based on composition volume
     */
    @Override
    public double getRadius() {
        return calculateMainSequenceRadius();
    }

    @Override
    public double getAggregatedMass() {
        return totalComposition.getTotalMass();
    }


    /**
     * Calculate orbital velocity for a circular orbit at given radius
     * v = sqrt(G * M / r)
     */
    @Override
    public double getCircularOrbitVelocity(double radius) {
        return Math.sqrt(PhysicsConstants.G * this.getMass() / radius);
    }

    /**
     * Extract type from the star's corona/photosphere
     * This represents stellar lifting or mass stream capture
     */
    public double extractStellarMaterial(Material material, double requestedMass,
                                         double extractionRate, double duration) {
        double maxByRate = extractionRate * duration;
        double toExtract = Math.min(requestedMass, maxByRate);

        double extracted = atmosphereComposition.removeMaterial(material, toExtract);
        replenishAtmosphere(duration);

        return extracted;
    }

    /**
     * Replenish the extractable atmosphere based on natural mass loss
     */
    private void replenishAtmosphere(double duration) {
        final double massAdded = calculateMassLossRate() * duration;

        totalComposition.getMaterials().forEach(
                (m,a) -> {
                    if (m.isGas())
                        atmosphereComposition.addMaterialAsRawMass(m, totalComposition.removeMaterial(m, massAdded * totalComposition.getFraction(m)));
                });

    }

    /**
     * Check if star has a specific type available for extraction
     */
    public boolean hasExtractableMaterial(Material material) {
        return atmosphereComposition.contains(material);
    }

    /**
     * Get amount of extractable type
     */
    public double getExtractableAmount(Material material) {
        return atmosphereComposition.getMass(material);
    }

    /**
     * Calculate the minimum safe distance for mining operations
     * Corona extends to about 2-3 stellar radii
     */
    public double getMinimumMiningDistance() {
        return 3.0 * calculateMainSequenceRadius();
    }

    /**
     * Get the spectral class based on temperature
     * O > 30000K, B 10000-30000K, A 7500-10000K, F 6000-7500K,
     * G 5200-6000K, K 3700-5200K, M < 3700K
     */
    public String getSpectralClass() {
        double surfaceTemperature = calculateMainSequenceTemperature();
        if (surfaceTemperature > 30000) return "O";
        if (surfaceTemperature > 10000) return "B";
        if (surfaceTemperature > 7500) return "A";
        if (surfaceTemperature > 6000) return "F";
        if (surfaceTemperature > 5200) return "G";
        if (surfaceTemperature > 3700) return "K";
        return "M";
    }

    /**
     * Calculate luminosity relative to Sun
     * L scales as M^3.5 for main sequence stars
     */
    public double getLuminosity() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        return Math.pow(massRatio, 3.5);
    }

    private void initializeAtmosphere() {
        replenishAtmosphere(1e10);
    }

    /**
     * Stars are stationary at the center of the system
     */
    public void update(double dt) {
        replenishAtmosphere(dt);
    }


    @Override
    public String toString() {
        return String.format("Star[id=%s, mass=%.3e kg (%.2f M☉), radius=%.3e m (%.2f R☉), " +
                        "temp=%.0f K, class=%s, density=%.1f kg/m³]",
                id, getMass(), getMass() / PhysicsConstants.SOLAR_MASS,
                calculateMainSequenceRadius(), calculateMainSequenceRadius() / 6.96e8,
                calculateMainSequenceTemperature(), getSpectralClass(), getDensity());
    }
}