package com.kaymlyn.planeteater.simulation.celestial;

import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;

import lombok.Getter;

/**
 * Represents a star (central body in the system).
 *
 * Can be mined using advanced stellar lifting technology. The extractable
 * atmosphere (corona/photosphere pool) is seeded once at initialization
 * from a fixed fraction of total gas mass. It does not replenish on its
 * own. At gameplay timescales (tens to thousands of years) stellar mass
 * loss is completely negligible; continuous replenishment would introduce
 * spurious mass accounting errors without any physical justification at
 * those scales.
 *
 * If a harvesting operation depletes the atmosphere pool, the player must
 * transfer additional mass from totalComposition directly using
 * transferToAtmosphere().
 *
 * Uses the main sequence mass-radius relationship for structural properties.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Star implements CelestialBody {

    // Fraction of total gas mass placed in the extractable atmosphere pool at init.
    // Large enough for meaningful harvesting; small enough to avoid gravitational error.
    private static final double ATMOSPHERE_SEED_FRACTION = 0.01;

    protected String id;
    protected OrbitalSystem system;
    protected Vector3D position;
    protected Vector3D velocity;

    // Extractable materials from corona/photosphere available for stellar lifting.
    private final Composition atmosphereComposition;

    // Full body composition. getMass() reads from here. Defines gravity and structure.
    private final Composition totalComposition;

    private boolean initialized;

    public Star(String id, Vector3D position, Vector3D velocity) {
        this(id, null, position, velocity);
    }

    protected Star(String id, OrbitalSystem system, Vector3D position, Vector3D velocity) {
        this.id = id;
        this.system = system;
        this.position = position;
        this.velocity = velocity;
        this.totalComposition = new Composition();
        this.atmosphereComposition = new Composition();
        this.initialized = false;
    }

    /**
     * Seed the extractable atmosphere from total composition.
     * Called once by CelestialBodyFactory after mass has been added.
     * Safe to call multiple times; subsequent calls are no-ops.
     */
    protected void initialize() {
        if (!initialized) {
            seedAtmosphere();
            initialized = true;
        }
    }

    /**
     * Transfer ATMOSPHERE_SEED_FRACTION of each gas material from
     * totalComposition into atmosphereComposition.
     *
     * totalComposition mass decreases by exactly the amount added to
     * atmosphereComposition, so getMass() accurately reflects the
     * gravitationally active body mass.
     */
    private void seedAtmosphere() {
        totalComposition.getMaterials().forEach((material, mass) -> {
            if (material.isGas()) {
                double toTransfer = mass * ATMOSPHERE_SEED_FRACTION;
                double transferred = totalComposition.removeMaterial(material, toTransfer);
                atmosphereComposition.addMaterialAsRawMass(material, transferred);
            }
        });
    }

    /**
     * Manually transfer a mass of a gas material from the body into the
     * atmosphere pool, making it available for extraction.
     *
     * Use this when the atmosphere pool has been significantly depleted by
     * harvesting and the player wants to expose more material for extraction.
     *
     * @param material the gas material to expose
     * @param mass     the mass in kg to transfer
     * @return the mass actually transferred (may be less if insufficient stock)
     */
    public double transferToAtmosphere(Material material, double mass) {
        double transferred = totalComposition.removeMaterial(material, mass);
        atmosphereComposition.addMaterialAsRawMass(material, transferred);
        return transferred;
    }

    @Override
    public String getId() {
        return id;
    }

    /**
     * Stars are fixed at the coordinate origin.
     */
    @Override
    public Vector3D getPosition() {
        return Vector3D.ZERO;
    }

    @Override
    public void setPosition(Vector3D position) {

    }

    @Override
    public void setVelocity(Vector3D velocity) {

    }

    /**
     * Stars do not move. No-op to satisfy PhysicsBody contract.
     */
    public void update(double timeStep) {
        // Stars are stationary. No per-step update required.
    }

    /**
     * Calculate stellar radius using the main sequence mass-radius relationship.
     *
     * M < 1 M_sun: R = R_sun * (M/M_sun)^0.8
     * M >= 1 M_sun: R = R_sun * (M/M_sun)^0.57
     */
    private double calculateMainSequenceRadius() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8; // meters

        if (massRatio < 1.0) {
            return solarRadius * Math.pow(massRatio, 0.8);
        } else {
            return solarRadius * Math.pow(massRatio, 0.57);
        }
    }

    /**
     * Calculate surface temperature from the Stefan-Boltzmann relation.
     *
     * L scales as M^3.5; L = 4*pi*R^2*sigma*T^4; combining:
     * T = T_sun * ((M/M_sun)^3.5 / (R/R_sun)^2)^0.25
     */
    public double calculateMainSequenceTemperature() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        double solarRadius = 6.96e8;
        double solarTemp = 5778.0; // Kelvin

        double luminosityRatio = Math.pow(massRatio, 3.5);
        double radiusRatio = calculateMainSequenceRadius() / solarRadius;
        double tempRatio = Math.pow(luminosityRatio / (radiusRatio * radiusRatio), 0.25);

        return solarTemp * tempRatio;
    }

    /**
     * Luminosity relative to the Sun. L/L_sun = (M/M_sun)^3.5.
     *
     * @return dimensionless luminosity ratio
     */
    public double getLuminosity() {
        double massRatio = getMass() / PhysicsConstants.SOLAR_MASS;
        return Math.pow(massRatio, 3.5);
    }

    /**
     * Spectral classification from surface temperature.
     *
     * O > 30000 K, B 10000-30000 K, A 7500-10000 K, F 6000-7500 K,
     * G 5200-6000 K, K 3700-5200 K, M < 3700 K
     */
    public String getSpectralClass() {
        double temperature = calculateMainSequenceTemperature();
        if (temperature > 30000) return "O";
        if (temperature > 10000) return "B";
        if (temperature > 7500)  return "A";
        if (temperature > 6000)  return "F";
        if (temperature > 5200)  return "G";
        if (temperature > 3700)  return "K";
        return "M";
    }

    /**
     * Minimum safe approach distance for harvesting operations.
     * Corona extends to approximately 3 stellar radii.
     *
     * @return minimum distance in meters
     */
    public double getMinimumMiningDistance() {
        return 3.0 * calculateMainSequenceRadius();
    }

    /**
     * Mass available for extraction of a specific material from the atmosphere pool.
     *
     * @param material the material to query
     * @return available mass in kg
     */
    public double getExtractableAmount(Material material) {
        return atmosphereComposition.getMass(material);
    }

    /**
     * Check if a material is available for extraction from the atmosphere pool.
     *
     * @param material the material to check
     * @return true if mass > 0 in the atmosphere pool
     */
    public boolean hasExtractableMaterial(Material material) {
        return atmosphereComposition.contains(material);
    }

    /**
     * Extract material from the star's corona/photosphere pool.
     *
     * Extraction is limited by the rate-duration product and by what is
     * available in the atmosphere pool. The pool does not replenish
     * automatically. Use transferToAtmosphere() to expose more material
     * when the pool is depleted.
     *
     * @param material      the material to extract
     * @param requestedMass total mass requested in kg
     * @param extractionRate extraction rate in kg/s
     * @param duration       operation duration in seconds
     * @return actual mass extracted in kg
     */
    public double extractStellarMaterial(Material material, double requestedMass,
                                         double extractionRate, double duration) {
        double rateLimitedMax = extractionRate * duration;
        double toExtract = Math.min(requestedMass, rateLimitedMax);
        return atmosphereComposition.removeMaterial(material, toExtract);
    }

    @Override
    public double getDensity() {
        return getMass() / getVolume();
    }

    @Override
    public double getVolume() {
        return (4.0 / 3.0) * Math.PI * Math.pow(calculateMainSequenceRadius(), 3);
    }

    @Override
    public double getMass() {
        return getAggregatedMass();
    }

    @Override
    public void update(Vector3D acceleration, double timeStep) {

    }

    @Override
    public Orbit snapshotOrbit() {
        return null;
    }

    @Override
    public double getRadius() {
        return calculateMainSequenceRadius();
    }

    @Override
    public double getAggregatedMass() {
        return totalComposition.getTotalMass();
    }

    @Override
    public String toString() {
        return String.format("Star[id=%s, mass=%.3e kg (%.2f M_sun), radius=%.3e m (%.2f R_sun), "
                        + "temp=%.0f K, class=%s, density=%.1f kg/m^3]",
                id,
                getMass(), getMass() / PhysicsConstants.SOLAR_MASS,
                calculateMainSequenceRadius(), calculateMainSequenceRadius() / 6.96e8,
                calculateMainSequenceTemperature(), getSpectralClass(),
                getDensity());
    }
}