package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.simulation.physics.ManeuverDetails;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;

/**
 * Diagnostic tool to understand the maneuver chain and telemetry generation
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class ManeuverChainDiagnostic {

    /**
     * Walk through the maneuver chain and print detailed information
     */
    public static void diagnoseManeuverChain(ManeuverDetails initial) {
        System.out.println("=======================================================");
        System.out.println("MANEUVER CHAIN DIAGNOSTIC");
        System.out.println("=======================================================\n");

        ManeuverDetails current = initial;
        int index = 0;

        while (current != null) {
            System.out.println("-----------------------------------------------------");
            System.out.printf("Maneuver %d: %s\n", index, current.getId());
            System.out.println("-----------------------------------------------------");

            // Timing
            System.out.printf("  Start Time: %.2f s (%.2f days)\n",
                    current.getStartTime(),
                    current.getStartTime() / 86400.0);
            System.out.printf("  Duration: %.2f s (%.2f days)\n",
                    current.getTimeToExecute(),
                    current.getTimeToExecute() / 86400.0);
            System.out.printf("  End Time: %.2f s (%.2f days)\n",
                    current.getEndTime(),
                    current.getEndTime() / 86400.0);

            // Position
            System.out.printf("  Start Position: %s\n", formatVector(current.getStartingPosition()));
            System.out.printf("  End Position: %s\n", formatVector(current.getEndingPosition()));
            double positionChange = current.getEndingPosition()
                    .subtract(current.getStartingPosition()).magnitude();
            System.out.printf("  Position Change: %.2e m (%.2e km)\n",
                    positionChange, positionChange / 1000.0);

            // Velocity
            System.out.printf("  Start Velocity: %s\n", formatVector(current.getStartingVelocity()));
            System.out.printf("  End Velocity: %s\n", formatVector(current.getEndingVelocity()));
            double velocityChange = current.getEndingVelocity()
                    .subtract(current.getStartingVelocity()).magnitude();
            System.out.printf("  Velocity Change (ΔV): %.2f m/s\n", velocityChange);
            System.out.printf("  Reported ΔV: %.2f m/s\n", current.getDeltaV());

            // Orbit info
            if (current.getOrbit() != null) {
                System.out.printf("  Orbit Epoch: %.2f s (%.2f days)\n",
                        current.getOrbit().epoch(),
                        current.getOrbit().epoch() / 86400.0);
                System.out.printf("  Orbit SMA: %.3e m (%.3f AU)\n",
                        current.getOrbit().semiMajorAxis(),
                        current.getOrbit().semiMajorAxis() / 1.496e11);
                System.out.printf("  Orbit Eccentricity: %.6f\n",
                        current.getOrbit().eccentricity());

                // Check if orbit epoch matches expected time
                double expectedEpoch = index == 0 ? current.getStartTime() : current.getStartTime();
                double epochDiff = Math.abs(current.getOrbit().epoch() - expectedEpoch);
                if (epochDiff > 0.01) {
                    System.out.printf("    WARNING: Orbit epoch differs from start time by %.2f s\n", epochDiff);
                }
            } else {
                System.out.println("  No orbit (terminus maneuver)");
            }

            // Type identification
            boolean isBurn = current.getId().contains("Burn") ||
                    current.getId().contains("Launch") ||
                    current.getId().contains("Detach") ||
                    current.getId().contains("Take off") ||
                    current.getId().contains("Landing");
            System.out.printf("  Type: %s\n", isBurn ? "BURN" : "COAST");

            if (isBurn && current.getTimeToExecute() == 0.0) {
                System.out.println("  ✓ Instant burn (expected duration = 0)");
            }

            System.out.println();

            current = current.getNext();
            index++;
        }

        System.out.println("=======================================================");
    }

    /**
     * Diagnose a specific position jump between two states
     */
    public static void diagnosePositionJump(
            String firstName,
            Vector3D firstPos,
            String secondName,
            Vector3D secondPos) {

        System.out.println("\n=======================================================");
        System.out.println("POSITION JUMP DIAGNOSTIC");
        System.out.println("=======================================================");

        System.out.printf("From: %s\n", firstName);
        System.out.printf("  Position: %s\n", formatVector(firstPos));

        System.out.printf("\nTo: %s\n", secondName);
        System.out.printf("  Position: %s\n", formatVector(secondPos));

        Vector3D diff = secondPos.subtract(firstPos);
        double distance = diff.magnitude();

        System.out.printf("\nDifference:\n");
        System.out.printf("  Vector: %s\n", formatVector(diff));
        System.out.printf("  Distance: %.2e m (%.2e km)\n", distance, distance / 1000.0);
        System.out.printf("  Distance: %.2f AU\n", distance / 1.496e11);

        System.out.println("\n=======================================================");
    }

    /**
     * Check if telemetry generation is using the right time calculations
     */
    public static void diagnoseCoastTelemetryGeneration(
            ManeuverDetails coast,
            double systemTimeStep,
            int stepsToCheck) {

        System.out.println("\n=======================================================");
        System.out.println("COAST TELEMETRY GENERATION DIAGNOSTIC");
        System.out.println("=======================================================");

        System.out.printf("Coast: %s\n", coast.getId());
        System.out.printf("Duration: %.2f s (%.2f days)\n",
                coast.getTimeToExecute(), coast.getTimeToExecute() / 86400.0);
        System.out.printf("Start Time: %.2f s\n", coast.getStartTime());
        System.out.printf("Orbit Epoch: %.2f s\n", coast.getOrbit().epoch());
        System.out.printf("Time Step: %.2f s\n", systemTimeStep);

        double epochDiff = coast.getStartTime() - coast.getOrbit().epoch();
        System.out.printf("\nEpoch Difference: %.2f s (%.2f days)\n",
                epochDiff, epochDiff / 86400.0);

        if (Math.abs(epochDiff) > 0.01) {
            System.out.println("   WARNING: Coast start time != orbit epoch");
            System.out.println("   This means the orbit was created before the coast started");
            System.out.println("   (which is correct - it was created at the burn)");
        }

        System.out.println("\nFirst few telemetry calculations:");

        int steps = (int) Math.ceil(coast.getTimeToExecute() / systemTimeStep);
        stepsToCheck = Math.min(stepsToCheck, steps);

        for (int step = 0; step < stepsToCheck; step++) {
            double timeInCoast = step * systemTimeStep;

            // What the OLD code would do (WRONG):
            double oldTimeSinceEpoch = timeInCoast;

            // What the NEW code should do (CORRECT):
            double cumulativeTime = coast.getStartTime() + timeInCoast;
            double newTimeSinceEpoch = cumulativeTime - coast.getOrbit().epoch();

            System.out.printf("\n  Step %d (t_coast = %.2f s):\n", step, timeInCoast);
            System.out.printf("    OLD: time since epoch = %.2f s\n", oldTimeSinceEpoch);
            System.out.printf("    NEW: time since epoch = %.2f s\n", newTimeSinceEpoch);
            System.out.printf("    Difference: %.2f s\n",
                    Math.abs(newTimeSinceEpoch - oldTimeSinceEpoch));
        }

        System.out.println("\n=======================================================");
    }

    private static String formatVector(Vector3D v) {
        return String.format("(%.3e, %.3e, %.3e)", v.getX(), v.getY(), v.getZ());
    }
}