package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.simulation.physics.*;

/**
 * Diagnostic for analyzing maneuver chain structure
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class ManeuverChainDiagnostic {

    public static void analyzeChain(ManeuverDetails first) {
        System.out.println("=== MANEUVER CHAIN STRUCTURE ===\n");

        ManeuverDetails current = first;
        int index = 0;

        while (current != null) {
            System.out.printf("Maneuver %d: %s\n", index, current.getId());
            System.out.printf("  Start time: %.1f\n", current.getStartTime());
            System.out.printf("  Duration:   %.1f\n", current.getTimeToExecute());
            System.out.printf("  End time:   %.1f\n", current.getEndTime());
            System.out.printf("  Delta-V:    %.1f m/s\n", current.getDeltaV());

            System.out.printf("  Start pos:  %s\n", formatVector(current.getStartingPosition()));
            System.out.printf("  Start vel:  %s\n", formatVector(current.getStartingVelocity()));
            System.out.printf("  End pos:    %s\n", formatVector(current.getEndingPosition()));
            System.out.printf("  End vel:    %s\n", formatVector(current.getEndingVelocity()));

            if (current.getOrbit() != null) {
                System.out.printf("  Orbit epoch: %.1f\n", current.getOrbit().epoch());
                System.out.printf("  Orbit a:     %.3e m\n", current.getOrbit().semiMajorAxis());
                System.out.printf("  Orbit e:     %.6f\n", current.getOrbit().eccentricity());
            }

            // Check for issues
            if (Math.abs(current.getTimeToExecute()) < 1e-6 && current.getDeltaV() < 1e-3) {
                System.out.println("  WARNING: Zero-duration, zero-deltaV maneuver");
            }

            if (current.getStartingPosition().equals(current.getEndingPosition())
                    && current.getTimeToExecute() > 1.0) {
                System.out.println("  WARNING: Long duration but no position change");
            }

            if (current.getNext() != null) {
                Vector3D gap = current.getNext().getStartingPosition()
                        .subtract(current.getEndingPosition());
                if (gap.magnitude() > 1000) {
                    System.out.printf("  ERROR: Gap to next maneuver: %.0f m\n",
                            gap.magnitude());
                }
            }

            System.out.println();
            current = current.getNext();
            index++;
        }
    }

    public static void analyzeTelemetryGeneration(ManeuverDetails first, double timeStep) {
        System.out.println("=== TELEMETRY GENERATION ANALYSIS ===\n");

        ManeuverDetails current = first;
        int index = 0;
        int totalStates = 0;

        while (current != null) {
            int stepsInManeuver = (int) (current.getTimeToExecute() / timeStep);
            totalStates += stepsInManeuver;

            System.out.printf("Maneuver %d: %s\n", index, current.getId());
            System.out.printf("  Duration: %.1f s\n", current.getTimeToExecute());
            System.out.printf("  Timestep: %.1f s\n", timeStep);
            System.out.printf("  States:   %d\n", stepsInManeuver);

            if (stepsInManeuver == 0 && current.getTimeToExecute() > 0) {
                System.out.printf("  WARNING: Duration %.1f < timestep %.1f, no states generated\n",
                        current.getTimeToExecute(), timeStep);
            }

            System.out.println();
            current = current.getNext();
            index++;
        }

        System.out.printf("Total states across all maneuvers: %d\n", totalStates);
    }

    private static String formatVector(Vector3D v) {
        return String.format("(%.3e, %.3e, %.3e)", v.getX(), v.getY(), v.getZ());
    }
}