package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import lombok.Getter;
import lombok.AllArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * Calculates orbital elements from state vectors (position and velocity)
 * Can predict the resulting orbit after applying a thrust vector
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class OrbitFromStateVectors {

    /**
     * Calculate orbital elements from current position and velocity vectors
     *
     * @param position Position vector (m)
     * @param velocity Velocity vector (m/s)
     * @param centralMass Mass of central body (kg)
     * @return Orbital elements
     */
    public static Orbit calculateOrbitFromStateVectors(Vector3D position,
                                                                  Vector3D velocity,
                                                                  Gravitational centralMass) {
        double mu = centralMass.getGravitationalParameter();

        Vector3D r = position;
        Vector3D v = velocity;
        double rMag = r.magnitude();
        double vMag = v.magnitude();

        // Specific orbital energy: ε = v²/2 - μ/r
        double energy = (vMag * vMag) / 2.0 - mu / rMag;

        // Semi-major axis: a = -μ/(2ε)
        double a = -mu / (2.0 * energy);

        // Angular momentum vector: h = r × v
        Vector3D h = r.cross(v);
        double hMag = h.magnitude();

        // Eccentricity vector: e = (v × h)/μ - r/|r|
        Vector3D eVec = v.cross(h).divide(mu).subtract(r.divide(rMag));
        double e = eVec.magnitude();

        // Inclination: i = arccos(h_z / |h|)
        double i = Math.acos(h.getZ() / hMag);

        // Node vector: n = k × h (where k is unit z vector)
        Vector3D n = Vector3D.UNIT_Z.cross(h);
        double nMag = n.magnitude();

        // Longitude of ascending node: Ω
        double omega;
        if (nMag > 1e-10) {
            omega = Math.acos(n.getX() / nMag);
            if (n.getY() < 0) {
                omega = 2 * Math.PI - omega;
            }
        } else {
            // Non-inclined orbit - Ω is undefined, set to 0
            omega = 0.0;
        }

        // Argument of periapsis: ω
        double w;
        if (nMag > 1e-10 && e > 1e-10) {
            w = Math.acos(n.dot(eVec) / (nMag * e));
            if (eVec.getZ() < 0) {
                w = 2 * Math.PI - w;
            }
        } else {
            w = 0.0;
        }

        // True anomaly: ν
        double nu;
        if (e > 1e-10) {
            nu = Math.acos(eVec.dot(r) / (e * rMag));
            if (r.dot(v) < 0) {
                nu = 2 * Math.PI - nu;
            }
        } else {
            // Circular orbit - measure from ascending node
            if (nMag > 1e-10) {
                nu = Math.acos(n.dot(r) / (nMag * rMag));
                if (r.getZ() < 0) {
                    nu = 2 * Math.PI - nu;
                }
            } else {
                // Circular equatorial - use longitude
                nu = Math.atan2(r.getY(), r.getX());
                if (nu < 0) nu += 2 * Math.PI;
            }
        }

        return new Orbit(a, e, i, omega, w, nu,  centralMass, 0.0);
    }

    /**
     * Calculate the resulting orbit after applying a delta-v vector
     *
     * @param currentPosition Current position vector (m)
     * @param currentVelocity Current velocity vector (m/s)
     * @param deltaV Delta-v vector to apply (m/s) - can be in any 3D direction
     * @param centralMass Mass of central body (kg)
     * @return New orbital elements after burn
     */
    public static Orbit calculateOrbitAfterBurn(Vector3D currentPosition,
                                                           Vector3D currentVelocity,
                                                           Vector3D deltaV,
                                                           Gravitational centralMass) {
        // New velocity is current velocity plus delta-v
        Vector3D newVelocity = currentVelocity.add(deltaV);

        // Calculate orbital elements with new velocity
        return calculateOrbitFromStateVectors(currentPosition, newVelocity, centralMass);
    }

    /**
     * Create a delta-v vector from magnitude and direction angles
     *
     * @param magnitude Delta-v magnitude (m/s)
     * @param azimuth Angle in the horizontal plane from prograde (radians)
     *                0 = prograde, π/2 = normal, π = retrograde, 3π/2 = anti-normal
     * @param elevation Angle above/below orbital plane (radians)
     *                  0 = in plane, π/2 = radial out, -π/2 = radial in
     * @param currentPosition Current position vector (for reference frame)
     * @param currentVelocity Current velocity vector (for reference frame)
     * @return Delta-v vector in 3D space
     */
    public static Vector3D createDeltaVFromAngles(double magnitude,
                                                  double azimuth,
                                                  double elevation,
                                                  Vector3D currentPosition,
                                                  Vector3D currentVelocity) {
        // Create local reference frame
        // Prograde direction (along velocity)
        Vector3D prograde = currentVelocity.normalize();

        // Normal direction (perpendicular to orbital plane)
        Vector3D normal = currentPosition.cross(currentVelocity).normalize();

        // Radial direction (away from central body)
        Vector3D radial = currentPosition.normalize();

        // Build delta-v in local frame
        // Component along prograde direction
        double progradeComponent = magnitude * Math.cos(elevation) * Math.cos(azimuth);

        // Component along normal direction
        double normalComponent = magnitude * Math.cos(elevation) * Math.sin(azimuth);

        // Component along radial direction
        double radialComponent = magnitude * Math.sin(elevation);

        // Combine components
        Vector3D deltaV = prograde.multiply(progradeComponent)
                .add(normal.multiply(normalComponent))
                .add(radial.multiply(radialComponent));

        return deltaV;
    }

    /**
     * Represents a comparison between two orbits
     */
    @Getter
    @AllArgsConstructor
    public static class OrbitComparison {
        private Orbit beforeOrbit;
        private Orbit afterOrbit;
        private Vector3D deltaVApplied;
        private double deltaVMagnitude;

        private double semiMajorAxisChange;
        private double eccentricityChange;
        private double inclinationChange;
        private double periapsisAltitudeChange;
        private double apoapsisAltitudeChange;

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("=== ORBIT CHANGE ANALYSIS ===\n");
            sb.append(String.format("Delta-v Applied: %.1f m/s\n", deltaVMagnitude));
            sb.append(String.format("Direction: %s\n\n", deltaVApplied));

            sb.append("BEFORE:\n");
            sb.append(String.format("  Semi-major axis: %.3e m\n", beforeOrbit.semiMajorAxis()));
            sb.append(String.format("  Eccentricity: %.6f\n", beforeOrbit.eccentricity()));
            sb.append(String.format("  Inclination: %.3f°\n", Math.toDegrees(beforeOrbit.inclination())));

            double r_peri_before = beforeOrbit.semiMajorAxis() * (1 - beforeOrbit.eccentricity());
            double r_apo_before = beforeOrbit.semiMajorAxis() * (1 + beforeOrbit.eccentricity());
            sb.append(String.format("  Periapsis: %.3e m\n", r_peri_before));
            sb.append(String.format("  Apoapsis: %.3e m\n\n", r_apo_before));

            sb.append("AFTER:\n");
            sb.append(String.format("  Semi-major axis: %.3e m (Δ: %+.3e m)\n",
                    afterOrbit.semiMajorAxis(), semiMajorAxisChange));
            sb.append(String.format("  Eccentricity: %.6f (Δ: %+.6f)\n",
                    afterOrbit.eccentricity(), eccentricityChange));
            sb.append(String.format("  Inclination: %.3f° (Δ: %+.3f°)\n",
                    Math.toDegrees(afterOrbit.inclination()), Math.toDegrees(inclinationChange)));

            double r_peri_after = afterOrbit.semiMajorAxis() * (1 - afterOrbit.eccentricity());
            double r_apo_after = afterOrbit.semiMajorAxis() * (1 + afterOrbit.eccentricity());
            sb.append(String.format("  Periapsis: %.3e m (Δ: %+.3e m)\n",
                    r_peri_after, periapsisAltitudeChange));
            sb.append(String.format("  Apoapsis: %.3e m (Δ: %+.3e m)\n",
                    r_apo_after, apoapsisAltitudeChange));

            return sb.toString();
        }
    }

    /**
     * Compare orbits before and after a burn
     * Provides detailed analysis of what changed
     */
    public static OrbitComparison compareOrbits(Vector3D position,
                                                Vector3D velocityBefore,
                                                Vector3D deltaV,
                                                Gravitational centralMass) {
        Orbit beforeOrbit = calculateOrbitFromStateVectors(
                position, velocityBefore, centralMass);

        Orbit afterOrbit = calculateOrbitAfterBurn(
                position, velocityBefore, deltaV, centralMass);

        double semiMajorAxisChange = afterOrbit.semiMajorAxis() - beforeOrbit.semiMajorAxis();
        double eccentricityChange = afterOrbit.eccentricity() - beforeOrbit.eccentricity();
        double inclinationChange = afterOrbit.inclination() - beforeOrbit.inclination();

        double periapsisBefore = beforeOrbit.semiMajorAxis() * (1 - beforeOrbit.eccentricity());
        double periapsisAfter = afterOrbit.semiMajorAxis() * (1 - afterOrbit.eccentricity());
        double periapsisChange = periapsisAfter - periapsisBefore;

        double apoapsisBefore = beforeOrbit.semiMajorAxis() * (1 + beforeOrbit.eccentricity());
        double apoapsisAfter = afterOrbit.semiMajorAxis() * (1 + afterOrbit.eccentricity());
        double apoapsisChange = apoapsisAfter - apoapsisBefore;

        return new OrbitComparison(
                beforeOrbit, afterOrbit, deltaV, deltaV.magnitude(),
                semiMajorAxisChange, eccentricityChange, inclinationChange,
                periapsisChange, apoapsisChange
        );
    }

    /**
     * Calculate the delta-v needed to achieve a target orbit from current state
     * This finds the optimal burn direction and magnitude
     *
     * @param currentPosition Current position
     * @param currentVelocity Current velocity
     * @param targetOrbit Desired orbital elements
     * @param centralMass Central body mass
     * @return Delta-v vector needed (approximate)
     */
    public static Vector3D calculateDeltaVToOrbit(Vector3D currentPosition,
                                                  Vector3D currentVelocity,
                                                  Orbit targetOrbit,
                                                  double centralMass) {
        // This is a complex problem - we'll use an iterative approach
        // For now, provide a simplified version

        double mu = PhysicsConstants.G * centralMass;

        // Calculate target velocity at current position
        // Using vis-viva equation: v² = μ(2/r - 1/a)
        double r = currentPosition.magnitude();
        double a_target = targetOrbit.semiMajorAxis();
        double v_target_mag = Math.sqrt(mu * (2.0/r - 1.0/a_target));

        // Direction: perpendicular to radius for circular orbit approximation
        Vector3D radial = currentPosition.normalize();
        Vector3D targetDirection = currentVelocity.normalize(); // Simplified

        Vector3D targetVelocity = targetDirection.multiply(v_target_mag);

        // Delta-v is the difference
        return targetVelocity.subtract(currentVelocity);
    }

    /**
     * Calculate the exact delta-v vector required to transfer from one orbit to another
     * at their intersection point. Both orbits must share the same focus (central body)
     * and intersect at the current position.
     *
     * This calculates the velocity on the target orbit at the intersection point,
     * then returns the delta-v needed to match it.
     *
     * @param currentPosition Position at the intersection point (m)
     * @param currentOrbit Current orbital elements
     * @param targetOrbit Target orbital elements
     * @param centralMass Mass of central body (kg)
     * @return Delta-v vector required for the transfer
     */
    public static Vector3D calculateDeltaVBetweenOrbits(Vector3D currentPosition,
                                                        Orbit currentOrbit,
                                                        Orbit targetOrbit,
                                                        Gravitational centralMass) {
        double mu = centralMass.getGravitationalParameter();

        // Calculate current velocity vector from current orbit at this position
        Vector3D currentVelocity = calculateVelocityVector(
                currentPosition, currentOrbit, centralMass
        );

        // Calculate target velocity vector from target orbit at this position
        Vector3D targetVelocity = calculateVelocityVector(
                currentPosition, targetOrbit, centralMass
        );

        // Delta-v is simply the difference
        return targetVelocity.subtract(currentVelocity);
    }

    /**
     * Calculate the velocity vector for a given orbit at a specific position
     * Uses orbital elements to determine velocity magnitude and direction
     *
     * @param position    Position vector (m)
     * @param orbit       Orbital elements
     * @param centralBody Mass of central body (kg)
     * @return Velocity vector at this position
     */
    public static Vector3D calculateVelocityVector(Vector3D position,
                                                   Orbit orbit,
                                                   Gravitational centralBody) {
        double mu = centralBody.getGravitationalParameter();
        double a = orbit.semiMajorAxis();
        double e = orbit.eccentricity();
        double i = orbit.inclination();
        double omega = orbit.ascendingNode();
        double w = orbit.periapsis();

        double r = position.magnitude();

        // Velocity magnitude from vis-viva equation
        double v_mag = Math.sqrt(mu * (2.0/r - 1.0/a));

        // Find true anomaly at this position
        double nu = findTrueAnomalyAtPosition(position, orbit);

        // Velocity in orbital plane (perpendicular to radius, in direction of motion)
        // In orbital plane coordinates:
        // v_r = (μ/h) * e * sin(ν)  (radial component)
        // v_θ = (μ/h) * (1 + e*cos(ν))  (tangential component)

        double h = Math.sqrt(mu * a * (1 - e*e)); // Specific angular momentum


        double v_r = (mu / h) * e * Math.sin(nu);           // Radial velocity
        double v_theta = (mu / h) * (1 + e * Math.cos(nu)); // Tangential velocity

        // Convert to orbital plane cartesian coordinates

        return new Vector3D(
                v_r * Math.cos(nu) - v_theta * Math.sin(nu),
                v_r * Math.sin(nu) + v_theta * Math.cos(nu)
                ).rotateInto3spaceFrom2space(omega,i,w);
    }

    /**
     * Find the true anomaly at a given position on an orbit
     *
     * @param position Position vector
     * @param orbit Orbital elements
     * @return True anomaly (radians)
     */
    private static double findTrueAnomalyAtPosition(Vector3D position, Orbit orbit) {
        double a = orbit.semiMajorAxis();
        double e = orbit.eccentricity();
        double i = orbit.inclination();
        double omega = orbit.ascendingNode();
        double w = orbit.periapsis();

        // Transform position from 3D inertial to orbital plane
        double x = position.getX();
        double y = position.getY();
        double z = position.getZ();

        double cosO = Math.cos(omega);
        double sinO = Math.sin(omega);
        double cosi = Math.cos(i);
        double sini = Math.sin(i);
        double cosw = Math.cos(w);
        double sinw = Math.sin(w);

        // Inverse rotation (transpose of rotation matrix)
        double x_orbital = x * (cosO * cosw - sinO * sinw * cosi) +
                y * (sinO * cosw + cosO * sinw * cosi) +
                z * (sinw * sini);
        double y_orbital = -x * (cosO * sinw + sinO * cosw * cosi) -
                y * (sinO * sinw - cosO * cosw * cosi) +
                z * (cosw * sini);

        // True anomaly from position in orbital plane
        double nu = Math.atan2(y_orbital, x_orbital);

        // Normalize to [0, 2π]
        while (nu < 0) nu += 2 * Math.PI;

        return nu;
    }

    /**
     * Check if two orbits intersect and find their intersection points
     *
     * @param orbit1 First orbit
     * @param orbit2 Second orbit
     * @param centralMass Mass of central body
     * @return OrbitIntersection containing intersection information
     */
    public static OrbitIntersection findOrbitIntersections(Orbit orbit1,
                                                           Orbit orbit2,
                                                           double centralMass) {
        // Two orbits can intersect at up to 2 points
        // This is a complex calculation involving solving for intersection of two ellipses
        // in 3D space with different orbital planes

        // For simplicity, we'll check if they intersect at the ascending/descending nodes
        // or at specific true anomalies

        List<Vector3D> intersections = new ArrayList<>();
        List<Double> trueAnomalies1 = new ArrayList<>();
        List<Double> trueAnomalies2 = new ArrayList<>();

        // Sample points along both orbits and find closest approaches
        // This is an approximation - exact solution requires solving complex equations

        int numSamples = 360;
        double minDistance = Double.POSITIVE_INFINITY;

        for (int i = 0; i < numSamples; i++) {
            double nu1 = (2 * Math.PI * i) / numSamples;
            Vector3D pos1 = calculatePositionAtTrueAnomaly(orbit1, nu1);

            for (int j = 0; j < numSamples; j++) {
                double nu2 = (2 * Math.PI * j) / numSamples;
                Vector3D pos2 = calculatePositionAtTrueAnomaly(orbit2, nu2);

                double distance = pos1.distanceTo(pos2);

                // If very close (within 1 km), consider it an intersection
                if (distance < 1000.0) {
                    // Check if we already have this intersection
                    boolean duplicate = false;
                    for (Vector3D existing : intersections) {
                        if (existing.distanceTo(pos1) < 10000.0) {
                            duplicate = true;
                            break;
                        }
                    }

                    if (!duplicate) {
                        intersections.add(pos1);
                        trueAnomalies1.add(nu1);
                        trueAnomalies2.add(nu2);
                    }
                }
            }
        }

        return new OrbitIntersection(
                intersections.isEmpty() ? null : intersections,
                trueAnomalies1,
                trueAnomalies2
        );
    }

    /**
     * Calculate position at a specific true anomaly for an orbit
     */
    private static Vector3D calculatePositionAtTrueAnomaly(Orbit orbit, double nu) {
        double a = orbit.semiMajorAxis();
        double e = orbit.eccentricity();
        double i = orbit.inclination();
        double omega = orbit.ascendingNode();
        double w = orbit.periapsis();

        // Radius at this true anomaly
        double r = a * (1 - e * e) / (1 + e * Math.cos(nu));

        // Position in orbital plane
        double x_orbital = r * Math.cos(nu);
        double y_orbital = r * Math.sin(nu);

        // Rotate to 3D
        double cosO = Math.cos(omega);
        double sinO = Math.sin(omega);
        double cosi = Math.cos(i);
        double sini = Math.sin(i);
        double cosw = Math.cos(w);
        double sinw = Math.sin(w);

        double x = x_orbital * (cosO * cosw - sinO * sinw * cosi) -
                y_orbital * (cosO * sinw + sinO * cosw * cosi);
        double y = x_orbital * (sinO * cosw + cosO * sinw * cosi) -
                y_orbital * (sinO * sinw - cosO * cosw * cosi);
        double z = x_orbital * (sinw * sini) + y_orbital * (cosw * sini);

        return new Vector3D(x, y, z);
    }

    /**
     * Represents intersection information between two orbits
     */
    @Getter
    @AllArgsConstructor
    public static class OrbitIntersection {
        private List<Vector3D> intersectionPoints;      // Positions where orbits cross
        private List<Double> trueAnomaliesOrbit1;       // True anomalies on orbit 1
        private List<Double> trueAnomaliesOrbit2;       // True anomalies on orbit 2

        public boolean hasIntersections() {
            return intersectionPoints != null && !intersectionPoints.isEmpty();
        }

        public int getNumberOfIntersections() {
            return intersectionPoints == null ? 0 : intersectionPoints.size();
        }

        @Override
        public String toString() {
            if (!hasIntersections()) {
                return "No intersections found";
            }

            StringBuilder sb = new StringBuilder();
            sb.append(String.format("Found %d intersection(s):\n", getNumberOfIntersections()));
            for (int i = 0; i < intersectionPoints.size(); i++) {
                sb.append(String.format("  Intersection %d:\n", i + 1));
                sb.append(String.format("    Position: %s\n", intersectionPoints.get(i)));
                sb.append(String.format("    True anomaly (orbit 1): %.3f° (%.3f rad)\n",
                        Math.toDegrees(trueAnomaliesOrbit1.get(i)), trueAnomaliesOrbit1.get(i)));
                sb.append(String.format("    True anomaly (orbit 2): %.3f° (%.3f rad)\n",
                        Math.toDegrees(trueAnomaliesOrbit2.get(i)), trueAnomaliesOrbit2.get(i)));
            }
            return sb.toString();
        }
    }


    /**
     * Check if an orbit is escape trajectory (hyperbolic)
     */
    public static boolean isEscapeTrajectory(Vector3D position, Vector3D velocity,
                                             double centralMass) {
        double mu = PhysicsConstants.G * centralMass;
        double r = position.magnitude();
        double v = velocity.magnitude();

        // Escape velocity at this distance
        double v_escape = Math.sqrt(2 * mu / r);

        return v >= v_escape;
    }

    /**
     * Calculate orbital period from state vectors
     */
    public static double calculateOrbitalPeriod(Vector3D position, Vector3D velocity,
                                                Gravitational centralMass) {
        Orbit orbit = calculateOrbitFromStateVectors(position, velocity, centralMass);

        if (orbit.eccentricity() >= 1.0) {
            return Double.POSITIVE_INFINITY; // Hyperbolic/parabolic - no period
        }

        double mu = centralMass.getGravitationalParameter();
        double a = orbit.semiMajorAxis();

        return 2 * Math.PI * Math.sqrt(Math.pow(a, 3) / mu);
    }
}