package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.physics.Orbit;

/**
 * Clean-room implementation of OrbitalState
 *
 * Represents the instantaneous state of an orbiting body:
 * - Position vector (3D)
 * - Velocity vector (3D)
 * - Orbital elements that describe the orbit
 *
 * This is a simple data container (record) with one helper method
 * for calculating angular momentum.
 *
 * Generated by Claude (Sonnet 4.5) - Clean Room Implementation
 */
public record OrbitalStateCleanRoom(
        Vector3D position,
        Vector3D velocity,
        Orbit orbitalElements
) {
    /**
     * Calculate specific angular momentum magnitude
     * h = r × v
     *
     * @return Angular momentum magnitude (m²/s)
     */
    public double angularMomentum() {
        return position.cross(velocity).magnitude();
    }
}
