package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.simulation.physics.*;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;

import java.util.List;

/**
 * Diagnostic tool to verify telemetry continuity
 *
 * Checks for position jumps between consecutive telemetry states
 * that would indicate bugs in time handling.
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class TelemetryDiagnostics {

    private static final double POSITION_JUMP_THRESHOLD = 1e9; // 1000 km
    private static final double VELOCITY_JUMP_THRESHOLD = 1e4; // 10 km/s

    /**
     * Analyze telemetry for discontinuities
     */
    public static TelemetryReport analyzeTelemetry(Spacecraft spacecraft, Itinerary itinerary) {
        TelemetryReport report = new TelemetryReport();

        List<PiecewiseState> telemetry = itinerary.generateTelemetry(
                spacecraft.getSystem());

        if (telemetry.isEmpty()) {
            report.addWarning("No telemetry generated - itinerary may be infeasible");
            return report;
        }

        report.totalStates = telemetry.size();
        report.addInfo("Total telemetry states: " + telemetry.size());

        // Check for position/velocity continuity
        for (int i = 1; i < telemetry.size(); i++) {
            PiecewiseState prev = telemetry.get(i - 1);
            PiecewiseState curr = telemetry.get(i);

            // Position jump check
            double positionDelta = curr.position().subtract(prev.position()).magnitude();
            if (positionDelta > POSITION_JUMP_THRESHOLD) {
                report.positionJumps++;
                report.addError(String.format(
                        "Position jump at state %d: %.0f km\n  From: %s\n  To: %s\n   First: %s\n   Second: %s",
                        i, positionDelta / 1000, prev.position(), curr.position(), prev.id(), curr.id()
                ));
            }

            // Velocity jump check
            double velocityDelta = curr.velocity().subtract(prev.velocity()).magnitude();
            if (velocityDelta > VELOCITY_JUMP_THRESHOLD) {
                report.velocityJumps++;
                report.addWarning(String.format(
                        "Velocity jump at state %d: %.0f m/s (may be legitimate burn)",
                        i, velocityDelta
                ));
            }

            // Time check
            double timeDelta = curr.timeElapsed() - prev.timeElapsed();
            if (timeDelta < 0) {
                report.addError(String.format(
                        "Time goes backward at state %d: %.1f → %.1f\n%s -> %s",
                        i, prev.timeElapsed(), curr.timeElapsed(), prev.id(), curr.id()
                ));
            }
        }

        // Check maneuver boundaries
        report.addInfo("\nManeuver boundary analysis:");
        ManeuverDetails maneuver = itinerary.getInitialManeuver();
        int stateIndex = 0;
        int maneuverIndex = 0;

        while (maneuver != null) {
            int stepsInManeuver = (int) (maneuver.getTimeToExecute() /
                    spacecraft.getSystem().getTimeStep());

            if (stateIndex < telemetry.size()) {
                PiecewiseState firstState = telemetry.get(stateIndex);
                report.addInfo(String.format(
                        "  Maneuver %d (%s): %d states, starts at %s",
                        maneuverIndex, maneuver.getId(), stepsInManeuver,
                        firstState.position()
                ));

                // Check first state matches maneuver start
                double startPosDelta = firstState.position()
                        .subtract(maneuver.getStartingPosition()).magnitude();
                if (startPosDelta > 1000) { // 1 km tolerance
                    report.addError(String.format(
                            "  First state doesn't match maneuver start: %.0f m gap",
                            startPosDelta
                    ));
                }
            }

            stateIndex += stepsInManeuver;
            maneuverIndex++;
            maneuver = maneuver.getNext();
        }

        return report;
    }

    /**
     * Diagnostic report
     */
    public static class TelemetryReport {
        int totalStates = 0;
        int positionJumps = 0;
        int velocityJumps = 0;
        StringBuilder messages = new StringBuilder();

        void addError(String msg) {
            messages.append(" ERROR: ").append(msg).append("\n");
        }

        void addWarning(String msg) {
            messages.append("  WARNING: ").append(msg).append("\n");
        }

        void addInfo(String msg) {
            messages.append("  ").append(msg).append("\n");
        }

        public boolean isHealthy() {
            return positionJumps == 0;
        }

        @Override
        public String toString() {
            return "=== TELEMETRY DIAGNOSTIC REPORT ===\n\n" +
                    messages +
                    "\n=== SUMMARY ===\n" +
                    String.format("Total states: %d\n", totalStates) +
                    String.format("Position jumps: %d\n", positionJumps) +
                    String.format("Velocity jumps: %d\n", velocityJumps) +
                    String.format("Health: %s\n",
                            isHealthy() ? "✓ HEALTHY" : "✗ ISSUES FOUND");
        }
    }

    /**
     * Visualization helper - shows trajectory path
     */
    public static void printTrajectoryPath(List<PiecewiseState> telemetry, int stride) {
        System.out.println("\n=== TRAJECTORY PATH (every " + stride + " states) ===");
        for (int i = 0; i < telemetry.size(); i += stride) {
            PiecewiseState state = telemetry.get(i);
            System.out.printf("t=%.1fd pos=%s (%.0f%% complete)\n",
                    state.timeElapsed() / PhysicsConstants.SECONDS_PER_DAY,
                    formatVector(state.position()),
                    state.fractionComplete() * 100
            );
        }
    }

    private static String formatVector(Vector3D v) {
        return String.format("(%.2e, %.2e, %.2e)", v.getX(), v.getY(), v.getZ());
    }
}