package com.kaymlyn.planeteater.claude;

import com.kaymlyn.planeteater.RenderingThread;
import com.kaymlyn.planeteater.simulation.celestial.*;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.PlanetPattern;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.physics.*;
import com.kaymlyn.planeteater.simulation.vehicles.*;

/**
 * Example demonstrating the telemetry generation fix
 *
 * Shows how proper time handling eliminates position jumps
 *
 * BEFORE FIX: Spacecraft jumps around because time was calculated globally
 * AFTER FIX: Smooth trajectory because time is per-maneuver
 *
 * Generated by Claude (Sonnet 4.5)
 */
public class TelemetryFixExample {

    public static void main(String[] args) {
        System.out.println("=== TELEMETRY FIX DEMONSTRATION ===\n");

        // Create simple system
        CelestialBodyFactory factory = new CelestialBodyFactory(
                CelestialBodyFactory.createMainSequenceStar("Sun", 1.0),
                3600.0  // 1 hour timestep
        );
        OrbitalSystem system = factory.getSystem();

        // Create orbital platform
        CentralMind platform = factory.createCentralMind(PhysicsConstants.AU);

        // Create destination planet
        Planet destination = factory.createPlanetFromPattern(
                "Earf",
                factory.getCentralStar(),
                new Orbit(1.5 * PhysicsConstants.AU, 0.0, 0.0, 0.0, 0.0, 0.0,
                        system.getCentralStar(), 0.0),
                PlanetPattern.EARTH,
                1
        );

        // Create spacecraft
        Spacecraft spacecraft = VehicleFactory.createCargoShuttle("TestShip", platform);
        platform.dock(spacecraft);

        // Plan route
        Itinerary itinerary = spacecraft.planRoute(
                destination, false, system.getCurrentTime(),
                TransferOptimizer.OptimizationGoal.MINIMUM_DELTAV
        );

        if (!itinerary.isFeasible()) {
            System.out.println(" Route infeasible: " + itinerary.getInfeasibilityReason());
            return;
        }

        System.out.println(itinerary.getSummary());
        System.out.println("\n" + "=".repeat(50));

        // Generate telemetry and analyze
        System.out.println("\nGenerating telemetry...");
        spacecraft.programItinerary(itinerary);

        TelemetryDiagnostics.TelemetryReport report =
                TelemetryDiagnostics.analyzeTelemetry(spacecraft, itinerary);

        System.out.println(report);

        // Show trajectory path
        TelemetryDiagnostics.printTrajectoryPath(
                itinerary.generateTelemetry(system),
                24  // Show every 24 hours
        );

        // Explain the fix
        System.out.println("\n" + "=".repeat(50));
        System.out.println("=== WHAT WAS FIXED ===\n");
        System.out.println("BEFORE:");
        System.out.println("  • Telemetry used GLOBAL elapsed time across all maneuvers");
        System.out.println("  • calculateTrajectoryState received absolute time");
        System.out.println("  • Orbit propagation used wrong time reference");
        System.out.println("  • Result: Spacecraft jumped between maneuvers\n");

        System.out.println("AFTER:");
        System.out.println("  • Telemetry tracks time PER-MANEUVER");
        System.out.println("  • calculateTrajectoryState receives time-since-maneuver-start");
        System.out.println("  • Orbit propagation uses correct epoch reference");
        System.out.println("  • Result: Smooth, continuous trajectory\n");

        if (report.isHealthy()) {
            System.out.println("✓ Fix successful - no position jumps detected!");
        } else {
            System.out.println("✗ Issues remain - further investigation needed");
        }

        EpochMismatchDiagnostic.diagnoseManeuverChain(itinerary.getInitialManeuver());

        ManeuverChainDiagnostic.analyzeChain(itinerary.getInitialManeuver());
        RenderingThread thread = new RenderingThread(spacecraft.getSystem(),
                (int)(260 * PhysicsConstants.SECONDS_PER_DAY/3600), 1,3,Vector3D.ZERO);
        thread.run();
    }
}