package com.kaymlyn.planeteater.simulation.celestial.planetoid;

import com.kaymlyn.planeteater.simulation.celestial.BodyType;
import com.kaymlyn.planeteater.simulation.celestial.CelestialBody;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import lombok.Getter;

import java.util.Set;

/**
 * Represents an asteroid with minable resources
 * 
 * Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Asteroid extends CelestialBody {

    private final Composition crustComposition;
    
    private final BodyType type;
    
    public Asteroid(String id, OrbitalSystem system, Vector3D position, Vector3D velocity,
                    Composition composition, BodyType type) {
        super(id, system, position, velocity);
        this.type = type;
        this.crustComposition = composition;
    }

    /**
     * Mine a specific type from this asteroid
     * Returns the actual amount mined (amount may be less than requested)
     */
    public double mineMaterial(Material material, double requestedMass) {
        return crustComposition.removeMaterial(material, requestedMass);
    }
    
    /**
     * Check if this asteroid has a specific type available
     */
    public boolean hasMaterial(Material material) {
        return crustComposition.contains(material);
    }
    
    /**
     * Get the amount of a specific type available
     */
    public double getAvailableMaterial(Material material) {
        return crustComposition.getMass(material);
    }

    public Set<Material> getAvailableMaterials() {
        return crustComposition.getMaterials().keySet();
    }

    @Override
    protected double getAggregatedMass() {
        return crustComposition.getTotalMass();
    }

    @Override
    public double getRadius() {
        double volume = crustComposition.getTotalVolume();
        return Math.cbrt((3.0 * volume) / (4.0 * Math.PI));
    }

    @Override
    public double getDensity() {
        return crustComposition.getBulkDensity();
    }

    @Override
    public double getVolume() {
        return crustComposition.getTotalVolume();
    }

    @Override
    public String toString() {
        return String.format("Asteroid[id=%s, type=%s, pos=%s, mass=%.3e kg, radius=%.1f m]",
            id, type, position, getMass(), getRadius());
    }
}