package com.kaymlyn.planeteater.simulation.celestial.planetoid;

import com.kaymlyn.planeteater.simulation.celestial.BodyType;
import com.kaymlyn.planeteater.simulation.celestial.CelestialBody;
import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.Gravitational;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.operations.Operation;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;
import lombok.Setter;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents a planet with differentiated layers.
 * Position and velocity are the ground truth - orbital elements calculated on demand.
 *
 * Generated by Claude (Sonnet 4.5) - Architecture Refactor
 */
@Getter
public class Planet extends OrbitingBody implements CelestialBody, Differentiated, Dockable {

    @Setter
    private Gravitational parentBody;
    private final BodyType type;
    private final Composition coreComposition;
    private final Composition mantleComposition;
    private final Composition crustComposition;
    private final Composition atmosphereComposition;

    private final HashMap<String, Spacecraft> hanger;
    private final HashMap<String, Operation> operations;

    public Planet(String id, Gravitational parentBody, Vector3D position, Vector3D velocity, BodyType type) {
        super(id, position, velocity, parentBody);
        this.type = type;
        this.coreComposition = new Composition();
        this.mantleComposition = new Composition();
        this.crustComposition = new Composition();
        this.atmosphereComposition = new Composition();
        this.parentBody = parentBody;
        this.hanger = new HashMap<>();
        this.operations = new HashMap<>();
    }

    @Override
    public double getAggregatedMass() {
        return coreComposition.getTotalMass() +
                mantleComposition.getTotalMass() +
                crustComposition.getTotalMass() +
                atmosphereComposition.getTotalMass();
    }

    @Override
    public double getRadius() {
        return Math.cbrt((3.0 * totalVolume()) / (4.0 * Math.PI));
    }

    @Override
    public double getDensity() {
        return getAggregatedMass() / getRadius();
    }

    @Override
    public double getVolume() {
        return coreComposition.getTotalVolume() +
                mantleComposition.getTotalVolume() +
                crustComposition.getTotalVolume() +
                atmosphereComposition.getTotalVolume();
    }

    @Override
    public OrbitalSystem getSystem() {
        return parentBody.getSystem();
    }

    @Override
    public Vector3D getPosition(double tPlus) {
        return super.getPosition(tPlus);
    }

    @Override
    public boolean canMineCrust() {
        return crustComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canHarvestAtmosphere() {
        return atmosphereComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canMineMantle() {
        return crustComposition.getTotalMass() == 0.0 && mantleComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canMineCore() {
        return mantleComposition.getTotalMass() == 0.0 && coreComposition.getTotalMass() > 0.0;
    }

    @Override
    public double mineCrustMaterial(Material material, double requestedMass) {
        if (!canMineCrust()) {
            return 0.0;
        }
        return crustComposition.removeMaterial(material, requestedMass);
    }

    @Override
    public double harvestAtmosphere(Material material, double requestedMass) {
        if (!canHarvestAtmosphere()) {
            return 0.0;
        }
        return atmosphereComposition.removeMaterial(material, requestedMass);
    }

    public boolean canHaveSubSatellites() {
        double hillRadius = calculateHillSphereRadius();
        return hillRadius > (10.0 * getRadius());
    }

    public boolean isTidallyLocked() {
        double hillRadius = calculateHillSphereRadius();
        return hillRadius < (50.0 * getRadius());
    }

    public double getSurfaceGravity() {
        return PhysicsConstants.G * this.getMass() / Math.pow(getRadius(), 2);
    }

    private double totalVolume() {
        return coreComposition.getTotalVolume() +
                mantleComposition.getTotalVolume() +
                crustComposition.getTotalVolume() +
                atmosphereComposition.getTotalVolume();
    }

    public double calculateHillSphereRadius() {
        return this.getPosition().distanceTo(parentBody.getPosition()) *
                Math.pow(getMass() / (3.0 * parentBody.getMass()), 1.0 / 3.0);
    }

    @Override
    public Map<String, Spacecraft> getHanger() {
        return hanger;
    }

    @Override
    public void dock(Spacecraft spacecraft) {
        hanger.put(spacecraft.getId(), spacecraft);
        spacecraft.setState(Spacecraft.SpacecraftState.DOCKED);
    }

    @Override
    public void updateDocked() {
        hanger.forEach((id,ship) -> {
            ship.setPosition(this.getPosition());
            ship.setVelocity(this.getVelocity());
        });
    }
}