package com.kaymlyn.planeteater.simulation.celestial.planetoid;

import com.kaymlyn.planeteater.simulation.celestial.BodyType;
import com.kaymlyn.planeteater.simulation.celestial.CelestialBody;
import com.kaymlyn.planeteater.simulation.celestial.Dockable;
import com.kaymlyn.planeteater.simulation.celestial.OrbitingBody;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.operations.Operation;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.physics.Vector3D;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import lombok.Getter;

import java.util.HashMap;

/**
 * Represents a planet with differentiated layers.
 * These layers in order of depth are: Core (solid center), Mantle (liquid rock), Crust (solid rock),
 * Atmosphere (Gaseous layer also representing Hydrosphere, or the topmost layer). There are no rules on composition of
 * these layers. Atmosphere is always harvestable. The other layers require the removal of the layer above them with the
 * crust being available first. (in order: Crust, Mantle, Core). Planets are objects to be exploited and thermodynamics
 * of the internals are not modeled, nor is heat a concern. It is assumed outposts attached to a given Planet are
 * updated and adjusted to facilitate changes to the realities of the planet's external environment.
 * <p>
 * Asteroids are planets with only crust. <br/>
 * Gas Giants are planets without crust. <br/>
 * Terrestrial are planets with all four layers. <br/>
 * Terrestrial Vacuum worlds would have no atmosphere layer. <br/>
 * Exotic worlds can be modeled by the contents of each layer e.g. a world that rains molten iron would have
 * the Material.IRON in its atmospheric composition.
 * </p>
 * Initially Generated by Claude (Sonnet 4.5)
 */
@Getter
public class Planet extends OrbitingBody implements CelestialBody, Differentiated, Dockable {

    @Getter
    private final CelestialBody parentBody;
    private final BodyType type;
    private final Composition coreComposition;
    private final Composition mantleComposition;
    private final Composition crustComposition;
    private final Composition atmosphereComposition;

    private final HashMap<String, Spacecraft> hanger;
    private final HashMap<String, Operation> operations;
    
    public Planet(String id, CelestialBody parentBody, OrbitalSystem system, Vector3D position, Vector3D velocity, BodyType type) {
        super(id, system, position, velocity);
        this.type = type;
        this.coreComposition = new Composition();
        this.mantleComposition = new Composition();
        this.crustComposition = new Composition();
        this.atmosphereComposition = new Composition();
        this.parentBody = parentBody;
        this.hanger = new HashMap<>();
        this.operations = new HashMap<>();
    }

    /**
     * Override to calculate total mass from all layers
     */
    @Override
    public double getAggregatedMass() {
        return coreComposition.getTotalMass() +
               mantleComposition.getTotalMass() +
               crustComposition.getTotalMass() +
               atmosphereComposition.getTotalMass();
    }
//
//    /**
//     * Calculate gravitational force this body exerts on another body
//     * F = G * m1 * m2 / r²
//     * Returns force vector pointing from other body toward this body
//     */
//    public Vector3D gravitationalForceOn(Orbiter other) {
//        Vector3D displacement = this.position.subtract(other.getPosition());
//        double distanceSquared = displacement.magnitudeSquared();
//
//        if (distanceSquared < 1e-10) {
//            return Vector3D.ZERO;
//        }
//
//        double forceMagnitude = PhysicsConstants.G * this.getMass() * other.getMass() / distanceSquared;
//        return displacement.normalize().multiply(forceMagnitude);
//    }

    /**
     * For planets, radius should be set explicitly based on layer volumes
     */
    @Override
    public double getRadius() {
        // Sum volumes of all layers and calculate radius
        return Math.cbrt((3.0 * totalVolume()) / (4.0 * Math.PI));
    }

    /**
     *
     * @return
     */
    @Override
    public double getDensity() {
        return coreComposition.getTotalMass()
                + mantleComposition.getTotalMass()
                + crustComposition.getTotalMass()
                + atmosphereComposition.getTotalMass()/getRadius();
    }

    @Override
    public double getVolume() {
        return coreComposition.getTotalVolume()
                + mantleComposition.getTotalVolume()
                + crustComposition.getTotalVolume()
                + atmosphereComposition.getTotalVolume();
    }
    /**
     * For planets, only the crust and atmosphere are accessible for mining
     * Deep mining could theoretically access mantle materials
     */
    @Override
    public boolean canMineCrust() {
        return crustComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canHarvestAtmosphere() {
        return atmosphereComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canMineMantle() {
        return crustComposition.getTotalMass() == 0.0 && mantleComposition.getTotalMass() > 0.0;
    }

    @Override
    public boolean canMineCore() {
        return mantleComposition.getTotalMass() == 0.0 && coreComposition.getTotalMass() > 0.0;
    }

    /**
     * Mine from the crust (surface mining)
     */
    @Override
    public double mineCrustMaterial(Material material, double requestedMass) {
        if (!canMineCrust()) {
            return 0.0;
        }
        return crustComposition.removeMaterial(material, requestedMass);
    }

    /**
     * Extract from atmosphere (gas harvesting)
     */
    @Override
    public double harvestAtmosphere(Material material, double requestedMass) {
        if (!canHarvestAtmosphere()) {
            return 0.0;
        }
        return atmosphereComposition.removeMaterial(material, requestedMass);
    }

    /**
     * Check if this satellite can have stable sub-satellites (moons of moons)
     * Generally requires Hill sphere radius >> sub-satellite radius
     */
    public boolean canHaveSubSatellites() {
        double hillRadius = calculateHillSphereRadius();
        // Need Hill sphere at least 10x the satellite's radius for stability
        return hillRadius > (10.0 * getRadius());
    }

    /**
     * Check if this satellite is tidally locked to its parent
     */
    public boolean isTidallyLocked() {
        // Large moons close to their parent tend to be tidally locked
        // Simplified check: if Hill sphere ratio is small, likely locked
        double hillRadius = calculateHillSphereRadius();
        return hillRadius < (50.0 * getRadius());
    }

    /**
     * Gravitational pull at the surface
     * @return Small g for the planet in m*s^-2
     */
    public double getSurfaceGravity() {
        return PhysicsConstants.G * this.getMass()/Math.pow(getRadius(),2);
    }

    private double totalVolume() {
        return coreComposition.getTotalVolume() +
                mantleComposition.getTotalVolume() +
                crustComposition.getTotalVolume() +
                atmosphereComposition.getTotalVolume();
    }

    /**
     * Calculate Hill sphere radius - region where satellite can have stable sub-satellites
     * r_Hill = a * (m_satellite / (3 * m_parent))^(1/3)
     */
    public double calculateHillSphereRadius() {

        return this.getPosition().distanceTo(parentBody.getPosition()) * Math.pow(getMass() / (3.0 * parentBody.getMass()), 1.0/3.0);
    }

    @Override
    public void land(Spacecraft spacecraft) {

    }

    @Override
    public void launch(Spacecraft spacecraft) {

    }
}