package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.CelestialBodyFactory;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.PlanetPattern;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import com.kaymlyn.planeteater.simulation.vehicles.VehicleFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for Itinerary.
 *
 * Tests cover:
 * - Construction and initialization
 * - Burn scheduling and automatic sorting
 * - Completion detection
 * - Delta-V calculations
 * - Burn management (add, remove, retrieve)
 * - Feasibility tracking
 * - Edge cases (empty burns, overlapping times, negative times)
 * - Summary and diagnostic output
 *
 * Note: Full spacecraft integration tests (Earth-Venus transfers, etc.) are in
 * SpacecraftTest.java and belong in a separate integration test suite.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("Itinerary Tests")
public class ItineraryTest {

    private static final double TOLERANCE = 1e-6;

    private CelestialBodyFactory factory;
    private OrbitalSystem spark;
    private Planet earth;
    private Planet venus;
    private Spacecraft shuttle;

    @BeforeEach
    public void setup() {
        factory = new CelestialBodyFactory(
                CelestialBodyFactory.createMainSequenceStar("Sol", 1), 3600
        );
        spark = factory.getSystem();
        earth = factory.createPlanetFromPattern(
                "Earf",
                factory.getCentralStar(),
                new Orbit(PhysicsConstants.AU, 0.0, 0.0, 0.0, 0.0, 0.0, factory.getCentralStar()),
                PlanetPattern.EARTH,
                1
        );
        venus = factory.createPlanetFromPattern(
                "Venas",
                factory.getCentralStar(),
                new Orbit(PhysicsConstants.AU * 0.723, 0.0, 0.0, 0.0, 0.0, 0.0, factory.getCentralStar()),
                PlanetPattern.VENUS,
                1
        );

        shuttle = VehicleFactory.createCubeSat("Test-1", earth);
    }

    // ==================== CONSTRUCTION TESTS ====================

    @Test
    @DisplayName("Create itinerary with valid start time")
    void testConstruction() {
        double startTime = 1000.0;
        Itinerary itinerary = new Itinerary(startTime);

        assertAll("Itinerary construction",
                () -> assertNotNull(itinerary, "Itinerary should not be null"),
                () -> assertEquals(startTime, itinerary.getStartTime(), TOLERANCE, "Start time should match"),
                () -> assertTrue(itinerary.getBurns().isEmpty(), "Burns list should be empty initially"),
                () -> assertTrue(itinerary.isFeasible(), "Should be feasible by default"),
                () -> assertNull(itinerary.getDestination(), "Destination should be null initially"),
                () -> assertNull(itinerary.getFinalState(), "Final state should be null initially")
        );
    }

    @Test
    @DisplayName("Create itinerary with zero start time")
    void testConstructionZeroTime() {
        Itinerary itinerary = new Itinerary(0.0);

        assertEquals(0.0, itinerary.getStartTime(), TOLERANCE, "Start time should be zero");
    }

    // ==================== BURN SCHEDULING TESTS ====================

    @Test
    @DisplayName("Add single burn to itinerary")
    void testAddSingleBurn() {
        Itinerary itinerary = new Itinerary(0.0);
        ScheduledBurn burn = new ScheduledBurn(
                "burn-1",
                1000.0,
                new Vector3D(100.0, 0.0, 0.0),
                "Test burn"
        );

        itinerary.addBurn(burn);

        assertAll("Single burn addition",
                () -> assertEquals(1, itinerary.getBurns().size(), "Should have one burn"),
                () -> assertEquals(burn, itinerary.getBurns().get(0), "Burn should match")
        );
    }

    @Test
    @DisplayName("Burns are automatically sorted by execution time")
    void testBurnAutoSorting() {
        Itinerary itinerary = new Itinerary(0.0);

        // Add burns out of chronological order
        ScheduledBurn burn3 = new ScheduledBurn("burn-3", 3000.0, new Vector3D(10.0, 0.0, 0.0), "Third");
        ScheduledBurn burn1 = new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "First");
        ScheduledBurn burn2 = new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Second");

        itinerary.addBurn(burn3);
        itinerary.addBurn(burn1);
        itinerary.addBurn(burn2);

        List<ScheduledBurn> burns = itinerary.getBurns();

        assertAll("Burns sorted chronologically",
                () -> assertEquals(3, burns.size(), "Should have three burns"),
                () -> assertEquals(burn1, burns.get(0), "First burn should be at T=1000"),
                () -> assertEquals(burn2, burns.get(1), "Second burn should be at T=2000"),
                () -> assertEquals(burn3, burns.get(2), "Third burn should be at T=3000")
        );
    }

    @Test
    @DisplayName("Multiple burns with same execution time maintain insertion order")
    void testSimultaneousBurns() {
        Itinerary itinerary = new Itinerary(0.0);

        // Add multiple burns at same time
        ScheduledBurn burnA = new ScheduledBurn("burn-A", 1000.0, new Vector3D(10.0, 0.0, 0.0), "A");
        ScheduledBurn burnB = new ScheduledBurn("burn-B", 1000.0, new Vector3D(20.0, 0.0, 0.0), "B");
        ScheduledBurn burnC = new ScheduledBurn("burn-C", 1000.0, new Vector3D(30.0, 0.0, 0.0), "C");

        itinerary.addBurn(burnA);
        itinerary.addBurn(burnB);
        itinerary.addBurn(burnC);

        List<ScheduledBurn> burns = itinerary.getBurns();

        assertAll("Simultaneous burns",
                () -> assertEquals(3, burns.size(), "Should have three burns"),
                () -> assertEquals(1000.0, burns.get(0).executionTime(), TOLERANCE, "All at same time"),
                () -> assertEquals(1000.0, burns.get(1).executionTime(), TOLERANCE, "All at same time"),
                () -> assertEquals(1000.0, burns.get(2).executionTime(), TOLERANCE, "All at same time")
        );
    }

    @Test
    @DisplayName("Burns list is unmodifiable")
    void testBurnsListUnmodifiable() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "Test"));

        List<ScheduledBurn> burns = itinerary.getBurns();

        assertThrows(UnsupportedOperationException.class,
                () -> burns.add(new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Invalid")),
                "Should not allow direct modification of burns list"
        );
    }

    // ==================== BURN RETRIEVAL TESTS ====================

    @Test
    @DisplayName("Get next burn returns correct burn")
    void testGetNextBurn() {
        Itinerary itinerary = new Itinerary(0.0);

        ScheduledBurn burn1 = new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "First");
        ScheduledBurn burn2 = new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Second");
        ScheduledBurn burn3 = new ScheduledBurn("burn-3", 3000.0, new Vector3D(10.0, 0.0, 0.0), "Third");

        itinerary.addBurn(burn1);
        itinerary.addBurn(burn2);
        itinerary.addBurn(burn3);

        assertAll("Get next burn at different times",
                () -> assertEquals(burn1, itinerary.getNextBurn(500.0), "At T=500, next is burn1"),
                () -> assertEquals(burn1, itinerary.getNextBurn(1000.0), "At T=1000, next is burn1"),
                () -> assertEquals(burn2, itinerary.getNextBurn(1500.0), "At T=1500, next is burn2"),
                () -> assertEquals(burn3, itinerary.getNextBurn(2500.0), "At T=2500, next is burn3"),
                () -> assertNull(itinerary.getNextBurn(3500.0), "At T=3500, no next burn")
        );
    }

    @Test
    @DisplayName("Get next burn from empty itinerary returns null")
    void testGetNextBurnEmpty() {
        Itinerary itinerary = new Itinerary(0.0);

        assertNull(itinerary.getNextBurn(1000.0), "Empty itinerary should return null");
    }

    // ==================== BURN REMOVAL TESTS ====================

    @Test
    @DisplayName("Remove burn from itinerary")
    void testRemoveBurn() {
        Itinerary itinerary = new Itinerary(0.0);

        ScheduledBurn burn1 = new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "First");
        ScheduledBurn burn2 = new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Second");

        itinerary.addBurn(burn1);
        itinerary.addBurn(burn2);

        assertEquals(2, itinerary.getBurns().size(), "Should start with 2 burns");

        itinerary.removeBurn(burn1);

        assertAll("After removing first burn",
                () -> assertEquals(1, itinerary.getBurns().size(), "Should have 1 burn"),
                () -> assertEquals(burn2, itinerary.getBurns().get(0), "Remaining burn should be burn2")
        );
    }

    @Test
    @DisplayName("Remove non-existent burn does not throw")
    void testRemoveNonExistentBurn() {
        Itinerary itinerary = new Itinerary(0.0);
        ScheduledBurn burn = new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "Test");

        assertDoesNotThrow(() -> itinerary.removeBurn(burn), "Removing non-existent burn should not throw");
    }

    // ==================== COMPLETION DETECTION TESTS ====================

    @Test
    @DisplayName("Empty itinerary is complete")
    void testEmptyItineraryComplete() {
        Itinerary itinerary = new Itinerary(0.0);

        assertTrue(itinerary.isComplete(1000.0), "Empty itinerary should be complete at any time");
    }

    @Test
    @DisplayName("Itinerary is not complete before last burn")
    void testNotCompleteBeforeLastBurn() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "Test"));

        assertFalse(itinerary.isComplete(500.0), "Should not be complete before burn");
    }

    @Test
    @DisplayName("Itinerary is complete after last burn")
    void testCompleteAfterLastBurn() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "Test"));

        assertTrue(itinerary.isComplete(1500.0), "Should be complete after last burn");
    }

    @Test
    @DisplayName("Itinerary completion with multiple burns")
    void testCompletionMultipleBurns() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "First"));
        itinerary.addBurn(new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Second"));
        itinerary.addBurn(new ScheduledBurn("burn-3", 3000.0, new Vector3D(10.0, 0.0, 0.0), "Third"));

        assertAll("Completion at different times",
                () -> assertFalse(itinerary.isComplete(500.0), "Not complete at T=500"),
                () -> assertFalse(itinerary.isComplete(1500.0), "Not complete at T=1500"),
                () -> assertFalse(itinerary.isComplete(2500.0), "Not complete at T=2500"),
                () -> assertTrue(itinerary.isComplete(3500.0), "Complete at T=3500")
        );
    }

    // ==================== DELTA-V CALCULATION TESTS ====================

    @Test
    @DisplayName("Calculate total delta-V for single burn")
    void testTotalDeltaVSingleBurn() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn(
                "burn-1",
                1000.0,
                new Vector3D(100.0, 0.0, 0.0),
                "Test"
        ));

        assertEquals(100.0, itinerary.getTotalDeltaV(), TOLERANCE, "Total delta-V should be 100 m/s");
    }

    @Test
    @DisplayName("Calculate total delta-V for multiple burns")
    void testTotalDeltaVMultipleBurns() {
        Itinerary itinerary = new Itinerary(0.0);
        // Pythagorean triple: 3-4-5, magnitude = 5
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(3.0, 4.0, 0.0), "First"));
        // Another Pythagorean triple: 5-12-13, magnitude = 13
        itinerary.addBurn(new ScheduledBurn("burn-2", 2000.0, new Vector3D(5.0, 12.0, 0.0), "Second"));
        // Simple scalar: magnitude = 20
        itinerary.addBurn(new ScheduledBurn("burn-3", 3000.0, new Vector3D(20.0, 0.0, 0.0), "Third"));

        // Total = 5 + 13 + 20 = 38
        assertEquals(38.0, itinerary.getTotalDeltaV(), TOLERANCE, "Total delta-V should be sum of magnitudes");
    }

    @Test
    @DisplayName("Total delta-V for empty itinerary is zero")
    void testTotalDeltaVEmpty() {
        Itinerary itinerary = new Itinerary(0.0);

        assertEquals(0.0, itinerary.getTotalDeltaV(), TOLERANCE, "Empty itinerary should have zero delta-V");
    }

    // ==================== ESTIMATED COMPLETION TIME TESTS ====================

    @Test
    @DisplayName("Get estimated completion time")
    void testEstimatedCompletionTime() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(10.0, 0.0, 0.0), "First"));
        itinerary.addBurn(new ScheduledBurn("burn-2", 2000.0, new Vector3D(10.0, 0.0, 0.0), "Second"));
        itinerary.addBurn(new ScheduledBurn("burn-3", 3000.0, new Vector3D(10.0, 0.0, 0.0), "Third"));

        assertEquals(3000.0, itinerary.getEstimatedCompletionTime(), TOLERANCE,
                "Completion time should be time of last burn");
    }

    @Test
    @DisplayName("Estimated completion time for empty itinerary is start time")
    void testEstimatedCompletionTimeEmpty() {
        double startTime = 500.0;
        Itinerary itinerary = new Itinerary(startTime);

        assertEquals(startTime, itinerary.getEstimatedCompletionTime(), TOLERANCE,
                "Empty itinerary completion time should be start time");
    }

    // ==================== FEASIBILITY TESTS ====================

    @Test
    @DisplayName("Mark itinerary as infeasible")
    void testMarkInfeasible() {
        Itinerary itinerary = new Itinerary(0.0);
        String reason = "Insufficient fuel";

        itinerary.setInfeasible(reason);

        assertAll("Infeasible itinerary",
                () -> assertFalse(itinerary.isFeasible(), "Should be marked infeasible"),
                () -> assertEquals(reason, itinerary.getInfeasibilityReason(), "Reason should match")
        );
    }

    @Test
    @DisplayName("Feasible itinerary has no infeasibility reason initially")
    void testFeasibleNoReason() {
        Itinerary itinerary = new Itinerary(0.0);

        assertAll("Feasible itinerary",
                () -> assertTrue(itinerary.isFeasible(), "Should be feasible"),
                () -> assertNull(itinerary.getInfeasibilityReason(), "Should have no reason")
        );
    }

    // ==================== DESTINATION AND STATE TESTS ====================

    @Test
    @DisplayName("Set and get destination")
    void testDestination() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.setDestination(venus);

        assertEquals(venus, itinerary.getDestination(), "Destination should match");
    }

    @Test
    @DisplayName("Set and get final state")
    void testFinalState() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.setFinalState(Spacecraft.SpacecraftState.ORBITING);

        assertEquals(Spacecraft.SpacecraftState.ORBITING, itinerary.getFinalState(), "Final state should match");
    }

    // ==================== EDGE CASE TESTS ====================

    @Test
    @DisplayName("Handle burns with negative execution times")
    void testNegativeExecutionTime() {
        Itinerary itinerary = new Itinerary(0.0);

        ScheduledBurn burnNegative = new ScheduledBurn("burn-neg", -1000.0, new Vector3D(10.0, 0.0, 0.0), "Past");
        ScheduledBurn burnPositive = new ScheduledBurn("burn-pos", 1000.0, new Vector3D(10.0, 0.0, 0.0), "Future");

        itinerary.addBurn(burnPositive);
        itinerary.addBurn(burnNegative);

        List<ScheduledBurn> burns = itinerary.getBurns();

        assertAll("Negative time handling",
                () -> assertEquals(2, burns.size(), "Should have both burns"),
                () -> assertEquals(burnNegative, burns.get(0), "Negative time burn should sort first"),
                () -> assertEquals(burnPositive, burns.get(1), "Positive time burn should sort second")
        );
    }

    @Test
    @DisplayName("Handle very large delta-V values")
    void testLargeDeltaV() {
        Itinerary itinerary = new Itinerary(0.0);

        // Speed of light is ~3e8 m/s, use 1e7 m/s as "large"
        Vector3D largeDeltaV = new Vector3D(1e7, 0.0, 0.0);
        itinerary.addBurn(new ScheduledBurn("large-burn", 1000.0, largeDeltaV, "Large"));

        assertEquals(1e7, itinerary.getTotalDeltaV(), 1.0, "Should handle large delta-V values");
    }

    @Test
    @DisplayName("Handle itinerary with many burns")
    void testManyBurns() {
        Itinerary itinerary = new Itinerary(0.0);

        // Add 100 burns
        for (int i = 0; i < 100; i++) {
            itinerary.addBurn(new ScheduledBurn(
                    "burn-" + i,
                    i * 100.0,  // Every 100 seconds
                    new Vector3D(10.0, 0.0, 0.0),
                    "Burn " + i
            ));
        }

        assertAll("Many burns handling",
                () -> assertEquals(100, itinerary.getBurns().size(), "Should have 100 burns"),
                () -> assertEquals(1000.0, itinerary.getTotalDeltaV(), TOLERANCE, "Total delta-V should be 100 * 10"),
                () -> assertEquals(9900.0, itinerary.getEstimatedCompletionTime(), TOLERANCE, "Last burn at T=9900")
        );
    }

    // ==================== INTEGRATION TESTS ====================
    // NOTE: Full spacecraft integration tests (Earth-Venus transfers, etc.) are in
    // SpacecraftTest.java and belong in a separate integration test suite.
    // These tests focus on Itinerary behavior with minimal spacecraft interaction.

    @Test
    @DisplayName("Itinerary summary contains expected information")
    void testGetSummary() {
        Itinerary itinerary = new Itinerary(1000.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 2000.0, new Vector3D(100.0, 0.0, 0.0), "First burn"));
        itinerary.addBurn(new ScheduledBurn("burn-2", 3000.0, new Vector3D(50.0, 0.0, 0.0), "Second burn"));
        itinerary.setDestination(venus);
        itinerary.setFinalState(Spacecraft.SpacecraftState.ORBITING);

        String summary = itinerary.getSummary();

        assertAll("Summary content",
                () -> assertTrue(summary.contains("ITINERARY"), "Should have header"),
                () -> assertTrue(summary.contains("Start Time"), "Should show start time"),
                () -> assertTrue(summary.contains("Estimated Completion"), "Should show completion time"),
                () -> assertTrue(summary.contains("Feasible: YES"), "Should show feasibility"),
                () -> assertTrue(summary.contains("Total Δv"), "Should show total delta-V"),
                () -> assertTrue(summary.contains("Number of Burns: 2"), "Should show burn count"),
                () -> assertTrue(summary.contains("Venas"), "Should show destination name"),
                () -> assertTrue(summary.contains("ORBITING"), "Should show final state"),
                () -> assertTrue(summary.contains("First burn"), "Should list first burn"),
                () -> assertTrue(summary.contains("Second burn"), "Should list second burn")
        );
    }

    @Test
    @DisplayName("Infeasible itinerary summary shows reason")
    void testGetSummaryInfeasible() {
        Itinerary itinerary = new Itinerary(1000.0);
        itinerary.setInfeasible("Insufficient fuel for transfer");

        String summary = itinerary.getSummary();

        assertAll("Infeasible summary",
                () -> assertTrue(summary.contains("Feasible: NO"), "Should show infeasible"),
                () -> assertTrue(summary.contains("Insufficient fuel"), "Should show reason")
        );
    }

    @Test
    @DisplayName("toString provides compact representation")
    void testToString() {
        Itinerary itinerary = new Itinerary(0.0);
        itinerary.addBurn(new ScheduledBurn("burn-1", 1000.0, new Vector3D(100.0, 0.0, 0.0), "Test"));
        itinerary.addBurn(new ScheduledBurn("burn-2", 2000.0, new Vector3D(50.0, 0.0, 0.0), "Test"));

        String str = itinerary.toString();

        assertAll("toString content",
                () -> assertTrue(str.contains("Itinerary"), "Should have class name"),
                () -> assertTrue(str.contains("burns=2"), "Should show burn count"),
                () -> assertTrue(str.contains("Δv=150.0"), "Should show total delta-V"),
                () -> assertTrue(str.contains("feasible=true"), "Should show feasibility")
        );
    }
}