package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.celestial.CelestialBodyFactory;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for Orbit class
 *
 * Tests all major functionality:
 * - Orbit creation from position/velocity
 * - Orbital state calculation
 * - Coordinate transformations
 * - Anomaly conversions
 * - Orbital geometry
 * - Edge cases
 *
 * Generated by Claude (Sonnet 4.5)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class OrbitTest {

    private static Star sun;

    // Test tolerances
    private static final double POSITION_TOLERANCE = 1000.0;    // 1 km
    private static final double VELOCITY_TOLERANCE = 10.0;      // 10 m/s
    private static final double ANGLE_TOLERANCE = 1e-6;         // ~0.00006 degrees
    private static final double DISTANCE_TOLERANCE = 1000.0;    // 1 km
    private static final double ENERGY_TOLERANCE = 1e3;         // 1 kJ/kg

    @BeforeAll
    static void setup() {
        CelestialBodyFactory factory = new CelestialBodyFactory(
                CelestialBodyFactory.createMainSequenceStar("TestStar", 1.0),
                3600.0
        );
        sun = factory.getCentralStar();
    }

    // ==================== ORBIT CREATION TESTS ====================

    @Test
    @Order(1)
    @DisplayName("Create circular orbit from position/velocity")
    void testCreateCircularOrbit() {
        Vector3D position = new Vector3D(PhysicsConstants.AU, 0, 0);
        double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / PhysicsConstants.AU);
        Vector3D velocity = new Vector3D(0, orbitalVel, 0);

        Orbit orbit = Orbit.fromState(sun, position, velocity);

        assertEquals(PhysicsConstants.AU, orbit.semiMajorAxis(), DISTANCE_TOLERANCE,
                "Semi-major axis should equal orbital radius");
        assertTrue(orbit.eccentricity() < 0.01,
                "Eccentricity should be near zero for circular orbit");
        assertTrue(orbit.inclination() < ANGLE_TOLERANCE,
                "Inclination should be near zero for ecliptic orbit");
    }

    @Test
    @Order(2)
    @DisplayName("Create elliptical orbit from position/velocity")
    void testCreateEllipticalOrbit() {
        double periapsis = 0.7 * PhysicsConstants.AU;
        Vector3D position = new Vector3D(periapsis, 0, 0);

        // Velocity for ellipse with apoapsis at 1.3 AU
        double semiMajorAxis = PhysicsConstants.AU;
        double vPeriapsis = Math.sqrt(sun.getGravitationalParameter() *
                (2.0/periapsis - 1.0/semiMajorAxis));
        Vector3D velocity = new Vector3D(0, vPeriapsis, 0);

        Orbit orbit = Orbit.fromState(sun, position, velocity);

        assertEquals(semiMajorAxis, orbit.semiMajorAxis(), DISTANCE_TOLERANCE,
                "Semi-major axis incorrect");
        assertTrue(orbit.eccentricity() > 0.25 && orbit.eccentricity() < 0.35,
                "Eccentricity should be ~0.3");
        assertEquals(0.0, orbit.trueAnomaly(), ANGLE_TOLERANCE,
                "Should be at periapsis (true anomaly = 0)");
    }

    @Test
    @Order(3)
    @DisplayName("Create inclined orbit")
    void testCreateInclinedOrbit() {
        double inclination = Math.toRadians(30);
        double radius = PhysicsConstants.AU;

        Vector3D position = new Vector3D(
                radius * Math.cos(inclination),
                0,
                radius * Math.sin(inclination)
        );

        double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / radius);
        Vector3D velocity = new Vector3D(0, orbitalVel, 0);

        Orbit orbit = Orbit.fromState(sun, position, velocity);

        assertEquals(inclination, orbit.inclination(), Math.toRadians(1),
                "Inclination should be ~30 degrees");
    }

    // ==================== ROUND-TRIP CONSISTENCY TESTS ====================

    @Test
    @Order(10)
    @DisplayName("Round-trip: circular orbit")
    void testRoundTripCircular() {
        Vector3D position = new Vector3D(PhysicsConstants.AU, 0, 0);
        double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / PhysicsConstants.AU);
        Vector3D velocity = new Vector3D(0, orbitalVel, 0);

        testRoundTrip(position, velocity, "Circular");
    }

    @Test
    @Order(11)
    @DisplayName("Round-trip: elliptical orbit at periapsis")
    void testRoundTripEllipticalPeriapsis() {
        double periapsis = 0.5 * PhysicsConstants.AU;
        Vector3D position = new Vector3D(periapsis, 0, 0);

        double semiMajorAxis = PhysicsConstants.AU;
        double vPeriapsis = Math.sqrt(sun.getGravitationalParameter() *
                (2.0/periapsis - 1.0/semiMajorAxis));
        Vector3D velocity = new Vector3D(0, vPeriapsis, 0);

        testRoundTrip(position, velocity, "Elliptical periapsis");
    }

    @Test
    @Order(12)
    @DisplayName("Round-trip: elliptical orbit at apoapsis")
    void testRoundTripEllipticalApoapsis() {
        double apoapsis = 1.5 * PhysicsConstants.AU;
        Vector3D position = new Vector3D(apoapsis, 0, 0);

        double semiMajorAxis = PhysicsConstants.AU;
        double vApoapsis = Math.sqrt(sun.getGravitationalParameter() *
                (2.0/apoapsis - 1.0/semiMajorAxis));
        Vector3D velocity = new Vector3D(0, -vApoapsis, 0);  // Negative for apoapsis

        testRoundTrip(position, velocity, "Elliptical apoapsis");
    }

    @Test
    @Order(13)
    @DisplayName("Round-trip: various true anomaly positions")
    void testRoundTripVariousAngles() {
        for (int angle = 0; angle < 360; angle += 45) {
            double theta = Math.toRadians(angle);
            double radius = PhysicsConstants.AU;

            Vector3D position = new Vector3D(
                    radius * Math.cos(theta),
                    radius * Math.sin(theta),
                    0
            );

            double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / radius);
            Vector3D velocity = new Vector3D(
                    -orbitalVel * Math.sin(theta),
                    orbitalVel * Math.cos(theta),
                    0
            );

            testRoundTrip(position, velocity, "Angle " + angle + "°");
        }
    }

    @Test
    @Order(14)
    @DisplayName("Round-trip: 3D inclined elliptical orbit")
    void testRoundTrip3DElliptical() {
        Vector3D position = new Vector3D(1.496e11, 4.488e10, 2.992e10);
        Vector3D velocity = new Vector3D(-15000, 25000, 5000);

        testRoundTrip(position, velocity, "3D elliptical");
    }

    // ==================== ORBITAL GEOMETRY TESTS ====================

    @Test
    @Order(20)
    @DisplayName("Calculate periapsis and apoapsis distances")
    void testPeriapsisApoapsis() {
        double semiMajorAxis = PhysicsConstants.AU;
        double eccentricity = 0.3;

        Orbit orbit = new Orbit(
                semiMajorAxis, eccentricity, 0, 0, 0, 0,
                sun
        );

        double expectedPeriapsis = semiMajorAxis * (1 - eccentricity);
        double expectedApoapsis = semiMajorAxis * (1 + eccentricity);

        assertEquals(expectedPeriapsis, orbit.calculateRadiusAtTrueAnomaly(0.0),
                DISTANCE_TOLERANCE, "Periapsis distance incorrect");
        assertEquals(expectedApoapsis, orbit.calculateRadiusAtTrueAnomaly(Math.PI),
                DISTANCE_TOLERANCE, "Apoapsis distance incorrect");
    }

    @Test
    @Order(21)
    @DisplayName("Semi-minor axis calculation")
    void testSemiMinorAxis() {
        double semiMajorAxis = PhysicsConstants.AU;
        double eccentricity = 0.6;

        Orbit orbit = new Orbit(
                semiMajorAxis, eccentricity, 0, 0, 0, 0,
                sun
        );

        double expectedSemiMinor = semiMajorAxis * Math.sqrt(1 - eccentricity * eccentricity);
        assertEquals(expectedSemiMinor, orbit.semiMinorAxis(),
                DISTANCE_TOLERANCE, "Semi-minor axis incorrect");
    }

    @Test
    @Order(22)
    @DisplayName("Orbital period calculation")
    void testOrbitalPeriod() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.0, 0, 0, 0, 0,
                sun
        );

        double expectedPeriod = 2 * Math.PI * Math.sqrt(
                Math.pow(PhysicsConstants.AU, 3) / sun.getGravitationalParameter()
        );

        assertEquals(expectedPeriod, orbit.orbitalPeriod(),
                100.0, "Orbital period incorrect");

        // Should be approximately 1 year
        double periodInDays = orbit.orbitalPeriod() / PhysicsConstants.SECONDS_PER_DAY;
        assertEquals(365.25, periodInDays, 1.25,
                "Period should be ~365 days for 1 AU orbit");
    }

    // ==================== ANOMALY CONVERSION TESTS ====================

    @Test
    @Order(30)
    @DisplayName("True to eccentric anomaly conversion")
    void testTrueToEccentricAnomaly() {
        double eccentricity = 0.5;
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, eccentricity, 0, 0, 0, 0,
                sun
        );

        // At periapsis: true = 0, eccentric = 0
        assertEquals(0.0, orbit.trueToEccentricAnomaly(0.0),
                ANGLE_TOLERANCE, "Eccentric anomaly at periapsis should be 0");

        // At apoapsis: true = π, eccentric = π
        assertEquals(Math.PI, orbit.trueToEccentricAnomaly(Math.PI),
                ANGLE_TOLERANCE, "Eccentric anomaly at apoapsis should be π");

        // At 90 degrees: verify relationship
        double trueAnomaly90 = Math.PI / 2;
        double eccentricAnomaly = orbit.trueToEccentricAnomaly(trueAnomaly90);

        // Verify using the relationship: tan(ν/2) = sqrt((1+e)/(1-e)) * tan(E/2)
        double leftSide = Math.tan(trueAnomaly90 / 2);
        double rightSide = Math.sqrt((1 + eccentricity) / (1 - eccentricity)) *
                Math.tan(eccentricAnomaly / 2);
        assertEquals(leftSide, rightSide, 1e-6,
                "True/eccentric anomaly relationship incorrect");
    }

    @Test
    @Order(31)
    @DisplayName("Mean anomaly calculation")
    void testMeanAnomaly() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.5, 0, 0, 0, 0,
                sun
        );

        // At periapsis: mean anomaly = 0
        Orbit periapsisOrbit = new Orbit(
                PhysicsConstants.AU, 0.5, 0, 0, 0, 0.0,
                sun
        );
        assertEquals(0.0, periapsisOrbit.meanAnomaly(), ANGLE_TOLERANCE,
                "Mean anomaly at periapsis should be 0");

        // At apoapsis: mean anomaly = π
        Orbit apoapsisOrbit = new Orbit(
                PhysicsConstants.AU, 0.5, 0, 0, 0, Math.PI,
                sun
        );
        assertEquals(Math.PI, apoapsisOrbit.meanAnomaly(), ANGLE_TOLERANCE,
                "Mean anomaly at apoapsis should be π");
    }

    // ==================== TIME PROPAGATION TESTS ====================

    @Test
    @Order(40)
    @DisplayName("Propagate orbit forward in time")
    void testOrbitPropagation() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.0, 0, 0, 0, 0,
                sun
        );

        // Propagate for 1/4 period (should be at 90 degrees)
        double quarterPeriod = orbit.orbitalPeriod() / 4.0;
        OrbitalState state = orbit.stateAt(sun.getSystem().getCurrentTime(), sun.getSystem().getCurrentTime() + quarterPeriod);

        // Should be at approximately 90 degrees
        double expectedAngle = Math.PI / 2;
        assertEquals(expectedAngle, state.toOrbit(sun).trueAnomaly(),
                Math.toRadians(1), "After 1/4 period should be at 90°");
    }

    @Test
    @Order(41)
    @DisplayName("Full orbit period returns to start")
    void testFullOrbitPeriod() {
        Vector3D initialPos = new Vector3D(PhysicsConstants.AU, 0, 0);
        double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / PhysicsConstants.AU);
        Vector3D initialVel = new Vector3D(0, orbitalVel, 0);

        Orbit orbit = Orbit.fromState(sun, initialPos, initialVel);

        // Propagate for full period
        OrbitalState state = orbit.stateAt(sun.getSystem().getCurrentTime(), orbit.orbitalPeriod());

        // Should return to approximately same position
        double positionError = state.position().subtract(initialPos).magnitude();
        assertTrue(positionError < 10000.0,  // 10 km tolerance
                "After full period, should return to start position");
    }

    // ==================== COORDINATE SYSTEM TESTS ====================

    @Test
    @Order(50)
    @DisplayName("Orbital plane nodes")
    void testOrbitalNodes() {
        double inclination = Math.toRadians(30);
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.1, inclination,
                Math.toRadians(45), Math.toRadians(60), 0,
                sun
        );

        Vector3D ascendingNode = orbit.getAscendingNode();
        Vector3D descendingNode = orbit.getDescendingNode();

        // Nodes should be in the ecliptic plane (z ≈ 0)
        assertEquals(0.0, ascendingNode.getZ(), DISTANCE_TOLERANCE,
                "Ascending node should be in ecliptic plane");
        assertEquals(0.0, descendingNode.getZ(), DISTANCE_TOLERANCE,
                "Descending node should be in ecliptic plane");

        // Nodes should be opposite each other
        double dotProduct = ascendingNode.normalize().dot(descendingNode.normalize());
        assertEquals(-1.0, dotProduct, 1e-6,
                "Nodes should be 180° apart");
    }

    @Test
    @Order(51)
    @DisplayName("Periapsis and apoapsis positions")
    void testPeriapsisApoapsisPositions() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.3, 0, 0, 0, 0,
                sun
        );

        Vector3D periapsis = orbit.periapsisPoint();
        Vector3D apoapsis = orbit.apoapsisPoint();

        // Check distances
        double expectedPeriDist = orbit.semiMajorAxis() * (1 - orbit.eccentricity());
        double expectedApoDist = orbit.semiMajorAxis() * (1 + orbit.eccentricity());

        assertEquals(expectedPeriDist, periapsis.magnitude(),
                DISTANCE_TOLERANCE, "Periapsis distance incorrect");
        assertEquals(expectedApoDist, apoapsis.magnitude(),
                DISTANCE_TOLERANCE, "Apoapsis distance incorrect");

        // Should be opposite directions
        double dotProduct = periapsis.normalize().dot(apoapsis.normalize());
        assertEquals(-1.0, dotProduct, 1e-6,
                "Periapsis and apoapsis should be 180° apart");
    }

    // ==================== ENERGY CONSERVATION TESTS ====================

    @Test
    @Order(60)
    @DisplayName("Specific orbital energy conservation")
    void testEnergyConservation() {
        Vector3D position = new Vector3D(PhysicsConstants.AU, 0, 0);
        double orbitalVel = Math.sqrt(sun.getGravitationalParameter() / PhysicsConstants.AU);
        Vector3D velocity = new Vector3D(0, orbitalVel, 0);

        Orbit orbit = Orbit.fromState(sun, position, velocity);

        // Calculate initial energy
        double initialEnergy = velocity.magnitudeSquared() / 2.0 -
                sun.getGravitationalParameter() / position.magnitude();

        // Propagate to various points
        for (double timeFraction : new double[]{0.25, 0.5, 0.75, 1.0}) {
            OrbitalState state = orbit.stateAt(sun.getSystem().getCurrentTime(), orbit.orbitalPeriod() * timeFraction);

            double energy = state.velocity().magnitudeSquared() / 2.0 -
                    sun.getGravitationalParameter() / state.position().magnitude();

            assertEquals(initialEnergy, energy, ENERGY_TOLERANCE,
                    "Energy should be conserved at t=" + timeFraction);
        }
    }

    // ==================== EDGE CASE TESTS ====================

    @Test
    @Order(70)
    @DisplayName("Nearly circular orbit (e ≈ 0)")
    void testNearlyCircular() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 1e-10, 0, 0, 0, 0,
                sun
        );

        // Should behave like circular orbit
        double periapsis = orbit.calculateRadiusAtTrueAnomaly(0);
        double apoapsis = orbit.calculateRadiusAtTrueAnomaly(Math.PI);

        assertEquals(periapsis/apoapsis, apoapsis/periapsis, 1.0e-8,
                "Near-circular orbit should have equal periapsis/apoapsis");
    }

    @Test
    @Order(71)
    @DisplayName("Highly eccentric orbit (e ≈ 0.99)")
    void testHighlyEccentric() {
        Orbit orbit = new Orbit(
                PhysicsConstants.AU, 0.99, 0, 0, 0, 0,
                sun
        );

        double periapsis = orbit.calculateRadiusAtTrueAnomaly(0);
        double apoapsis = orbit.calculateRadiusAtTrueAnomaly(Math.PI);

        // Ratio should be very large
        double ratio = apoapsis / periapsis;
        assertTrue(ratio > 100,
                "Highly eccentric orbit should have large peri/apo ratio");
    }

    // ==================== HELPER METHODS ====================

    private void testRoundTrip(Vector3D originalPos, Vector3D originalVel, String testName) {
        Orbit orbit = Orbit.fromState(sun, originalPos, originalVel);
        OrbitalState state = orbit.stateAt(sun.getSystem().getCurrentTime(),sun.getSystem().getCurrentTime());

        double posError = state.position().subtract(originalPos).magnitude();
        double velError = state.velocity().subtract(originalVel).magnitude();

        assertTrue(posError < POSITION_TOLERANCE,
                String.format("%s: Position error %.1f m exceeds tolerance",
                        testName, posError));
        assertTrue(velError < VELOCITY_TOLERANCE,
                String.format("%s: Velocity error %.1f m/s exceeds tolerance",
                        testName, velError));
    }
}