package com.kaymlyn.planeteater.simulation.physics;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for ScheduledBurn class.
 *
 * Tests cover:
 * - Record construction and field access
 * - Delta-V magnitude calculations
 * - Fuel requirement calculations (Tsiolkovsky equation)
 * - Execution timing logic
 * - Natural ordering (Comparable implementation)
 * - Edge cases and boundary conditions
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("ScheduledBurn Tests")
public class ScheduledBurnTest {

    // Test constants
    private static final double TOLERANCE = 1e-6;
    private static final String TEST_BURN_ID = "test-burn-1";
    private static final String TEST_DESCRIPTION = "Test Burn Description";

    // Standard test values
    private double standardExecutionTime;
    private double standardSpacecraftMass;
    private double standardExhaustVelocity;

    // Standard burn for most tests
    private ScheduledBurn standardBurn;

    @BeforeEach
    void setUp() {
        standardExecutionTime = 1000.0; // Execute at T+1000 seconds
        Vector3D standardDeltaVelocity = new Vector3D(100.0, 50.0, 25.0); // m/s in each axis
        standardSpacecraftMass = 5000.0; // kg
        standardExhaustVelocity = 3000.0; // m/s (typical chemical rocket)

        standardBurn = new ScheduledBurn(
                TEST_BURN_ID,
                standardExecutionTime,
                standardDeltaVelocity,
                TEST_DESCRIPTION
        );
    }

    // ==================== CONSTRUCTION TESTS ====================

    @Test
    @DisplayName("Create burn with all parameters")
    void testBurnConstruction() {
        ScheduledBurn burn = new ScheduledBurn(
                "burn-1",
                500.0,
                new Vector3D(10.0, 20.0, 30.0),
                "Departure burn"
        );

        assertAll("Burn construction",
                () -> assertEquals("burn-1", burn.id(), "ID should match"),
                () -> assertEquals(500.0, burn.executionTime(), TOLERANCE, "Execution time should match"),
                () -> assertEquals(new Vector3D(10.0, 20.0, 30.0), burn.deltaVelocity(), "Delta-V vector should match"),
                () -> assertEquals("Departure burn", burn.description(), "Description should match")
        );
    }

    @Test
    @DisplayName("Create burn with zero delta-V")
    void testZeroDeltaVBurn() {
        ScheduledBurn burn = new ScheduledBurn(
                "zero-burn",
                100.0,
                Vector3D.ZERO,
                "Zero delta-V burn"
        );

        assertAll("Zero delta-V burn",
                () -> assertEquals(Vector3D.ZERO, burn.deltaVelocity(), "Should accept zero delta-V"),
                () -> assertEquals(0.0, burn.deltaVMagnitude(), TOLERANCE, "Magnitude should be zero")
        );
    }

    @Test
    @DisplayName("Create burn with negative execution time")
    void testNegativeExecutionTime() {
        ScheduledBurn burn = new ScheduledBurn(
                "negative-time",
                -100.0,
                new Vector3D(10.0, 0.0, 0.0),
                "Past burn"
        );

        // Should allow negative times (for historical burns or validation)
        assertEquals(-100.0, burn.executionTime(), TOLERANCE,
                "Should allow negative execution times");
    }

    // ==================== DELTA-V MAGNITUDE TESTS ====================

    @Test
    @DisplayName("Calculate delta-V magnitude for standard burn")
    void testDeltaVMagnitude() {
        // Delta-V magnitude = sqrt(100^2 + 50^2 + 25^2) = sqrt(11875) ≈ 108.97 m/s
        double expectedMagnitude = Math.sqrt(100.0*100.0 + 50.0*50.0 + 25.0*25.0);

        assertEquals(expectedMagnitude, standardBurn.deltaVMagnitude(), TOLERANCE,
                "Delta-V magnitude should match vector magnitude");
    }

    @Test
    @DisplayName("Delta-V magnitude for single-axis burn")
    void testSingleAxisDeltaV() {
        ScheduledBurn burnX = new ScheduledBurn("x-burn", 100.0, new Vector3D(500.0, 0.0, 0.0), "X-axis");
        ScheduledBurn burnY = new ScheduledBurn("y-burn", 100.0, new Vector3D(0.0, 500.0, 0.0), "Y-axis");
        ScheduledBurn burnZ = new ScheduledBurn("z-burn", 100.0, new Vector3D(0.0, 0.0, 500.0), "Z-axis");

        assertAll("Single-axis burns",
                () -> assertEquals(500.0, burnX.deltaVMagnitude(), TOLERANCE, "X-axis magnitude"),
                () -> assertEquals(500.0, burnY.deltaVMagnitude(), TOLERANCE, "Y-axis magnitude"),
                () -> assertEquals(500.0, burnZ.deltaVMagnitude(), TOLERANCE, "Z-axis magnitude")
        );
    }

    @Test
    @DisplayName("Delta-V magnitude for negative components")
    void testNegativeDeltaVComponents() {
        ScheduledBurn burn = new ScheduledBurn(
                "negative-burn",
                100.0,
                new Vector3D(-100.0, -50.0, -25.0),
                "Retrograde burn"
        );

        // Magnitude should be same as positive version (direction doesn't affect magnitude)
        double expectedMagnitude = Math.sqrt(100.0*100.0 + 50.0*50.0 + 25.0*25.0);

        assertEquals(expectedMagnitude, burn.deltaVMagnitude(), TOLERANCE,
                "Negative components should not affect magnitude");
    }

    // ==================== FUEL CALCULATION TESTS ====================

    @Test
    @DisplayName("Calculate fuel required using Tsiolkovsky equation")
    void testFuelRequiredStandardCase() {
        // Tsiolkovsky: m_fuel = m_initial * (1 - e^(-Δv/v_e))
        double deltaV = standardBurn.deltaVMagnitude();
        double ratio = Math.exp(-deltaV / standardExhaustVelocity);
        double expectedFuel = standardSpacecraftMass * (1.0 - ratio);

        double actualFuel = standardBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);

        assertEquals(expectedFuel, actualFuel, TOLERANCE,
                "Fuel calculation should match Tsiolkovsky equation");
    }

    @Test
    @DisplayName("Fuel required increases with delta-V")
    void testFuelRequiredIncreaseWithDeltaV() {
        ScheduledBurn smallBurn = new ScheduledBurn(
                "small", 100.0, new Vector3D(10.0, 0.0, 0.0), "Small"
        );
        ScheduledBurn mediumBurn = new ScheduledBurn(
                "medium", 100.0, new Vector3D(100.0, 0.0, 0.0), "Medium"
        );
        ScheduledBurn largeBurn = new ScheduledBurn(
                "large", 100.0, new Vector3D(1000.0, 0.0, 0.0), "Large"
        );

        double fuelSmall = smallBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);
        double fuelMedium = mediumBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);
        double fuelLarge = largeBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);

        assertAll("Fuel increases with delta-V",
                () -> assertTrue(fuelMedium > fuelSmall, "Medium burn should require more fuel than small"),
                () -> assertTrue(fuelLarge > fuelMedium, "Large burn should require more fuel than medium"),
                () -> assertTrue(fuelLarge < standardSpacecraftMass, "Large burn should not require more fuel than total mass")
        );
    }

    @Test
    @DisplayName("Fuel required with zero delta-V")
    void testFuelRequiredZeroDeltaV() {
        ScheduledBurn zeroBurn = new ScheduledBurn(
                "zero", 100.0, Vector3D.ZERO, "Zero"
        );

        double fuel = zeroBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);

        assertEquals(0.0, fuel, TOLERANCE,
                "Zero delta-V should require zero fuel");
    }

    @Test
    @DisplayName("Fuel required with very high delta-V approaches spacecraft mass")
    void testFuelRequiredHighDeltaV() {
        // Extreme delta-V that would require most of the spacecraft to be fuel
        ScheduledBurn extremeBurn = new ScheduledBurn(
                "extreme", 100.0, new Vector3D(30000.0, 0.0, 0.0), "Extreme"
        );

        double fuel = extremeBurn.fuelRequired(standardSpacecraftMass, standardExhaustVelocity);

        assertAll("Extreme delta-V fuel requirements",
                () -> assertTrue(fuel < standardSpacecraftMass, "Cannot require more fuel than total mass"),
                () -> assertTrue(fuel > standardSpacecraftMass * 0.99, "Should require >99% of mass for extreme delta-V")
        );
    }

    @Test
    @DisplayName("Fuel required with different exhaust velocities")
    void testFuelRequiredDifferentExhaustVelocities() {
        double lowExhaustVel = 2000.0;  // Chemical rocket
        double highExhaustVel = 10000.0; // Ion drive

        double fuelLowEfficiency = standardBurn.fuelRequired(standardSpacecraftMass, lowExhaustVel);
        double fuelHighEfficiency = standardBurn.fuelRequired(standardSpacecraftMass, highExhaustVel);

        assertTrue(fuelHighEfficiency < fuelLowEfficiency,
                "Higher exhaust velocity (more efficient) should require less fuel");
    }

    @Test
    @DisplayName("Fuel required with different spacecraft masses")
    void testFuelRequiredDifferentMasses() {
        double smallMass = 1000.0;
        double largeMass = 10000.0;

        double fuelSmallCraft = standardBurn.fuelRequired(smallMass, standardExhaustVelocity);
        double fuelLargeCraft = standardBurn.fuelRequired(largeMass, standardExhaustVelocity);

        assertAll("Fuel scales with spacecraft mass",
                () -> assertTrue(fuelLargeCraft > fuelSmallCraft, "Larger spacecraft requires more fuel"),
                () -> assertEquals(10.0, fuelLargeCraft / fuelSmallCraft, 0.01,
                        "Fuel should scale linearly with mass for same delta-V")
        );
    }

    // ==================== EXECUTION TIMING TESTS ====================

    @Test
    @DisplayName("Should execute when current time matches execution time")
    void testShouldExecuteExactMatch() {
        double currentTime = standardExecutionTime;

        assertTrue(standardBurn.shouldExecute(currentTime),
                "Burn should execute when current time exactly matches");
    }

    @Test
    @DisplayName("Should execute within default tolerance (1 second)")
    void testShouldExecuteWithinTolerance() {
        double timeBefore = standardExecutionTime - 0.5;
        double timeAfter = standardExecutionTime + 0.5;

        assertAll("Should execute within default tolerance",
                () -> assertTrue(standardBurn.shouldExecute(timeBefore), "Should execute 0.5s before"),
                () -> assertTrue(standardBurn.shouldExecute(timeAfter), "Should execute 0.5s after")
        );
    }

    @Test
    @DisplayName("Should not execute outside default tolerance")
    void testShouldNotExecuteOutsideTolerance() {
        double timeTooEarly = standardExecutionTime - 1.1;
        double timeTooLate = standardExecutionTime + 1.1;

        assertAll("Should not execute outside default tolerance",
                () -> assertFalse(standardBurn.shouldExecute(timeTooEarly), "Should not execute 1.1s early"),
                () -> assertFalse(standardBurn.shouldExecute(timeTooLate), "Should not execute 1.1s late")
        );
    }

    @Test
    @DisplayName("Should execute with custom tolerance")
    void testShouldExecuteCustomTolerance() {
        double customTolerance = 10.0;
        double timeWithinCustom = standardExecutionTime + 9.0;
        double timeOutsideCustom = standardExecutionTime + 11.0;

        assertAll("Custom tolerance",
                () -> assertTrue(standardBurn.shouldExecute(timeWithinCustom, customTolerance),
                        "Should execute within custom tolerance"),
                () -> assertFalse(standardBurn.shouldExecute(timeOutsideCustom, customTolerance),
                        "Should not execute outside custom tolerance")
        );
    }

    @Test
    @DisplayName("Should execute with very tight tolerance")
    void testShouldExecuteTightTolerance() {
        double tightTolerance = 0.001; // 1 millisecond
        double exactTime = standardExecutionTime;
        double slightlyOff = standardExecutionTime + 0.002;

        assertAll("Tight tolerance",
                () -> assertTrue(standardBurn.shouldExecute(exactTime, tightTolerance),
                        "Should execute at exact time even with tight tolerance"),
                () -> assertFalse(standardBurn.shouldExecute(slightlyOff, tightTolerance),
                        "Should not execute 2ms off with 1ms tolerance")
        );
    }

    // ==================== COMPARABLE/ORDERING TESTS ====================

    @Test
    @DisplayName("Burns should order by execution time (earliest first)")
    void testNaturalOrdering() {
        ScheduledBurn earlyBurn = new ScheduledBurn("early", 100.0, Vector3D.ZERO, "Early");
        ScheduledBurn middleBurn = new ScheduledBurn("middle", 500.0, Vector3D.ZERO, "Middle");
        ScheduledBurn lateBurn = new ScheduledBurn("late", 1000.0, Vector3D.ZERO, "Late");

        assertAll("Natural ordering by execution time",
                () -> assertTrue(earlyBurn.compareTo(middleBurn) < 0, "Early < Middle"),
                () -> assertTrue(middleBurn.compareTo(lateBurn) < 0, "Middle < Late"),
                () -> assertTrue(earlyBurn.compareTo(lateBurn) < 0, "Early < Late"),
                () -> assertTrue(lateBurn.compareTo(earlyBurn) > 0, "Late > Early"),
                () -> assertEquals(0, earlyBurn.compareTo(earlyBurn), "Burn should equal itself")
        );
    }

    @Test
    @DisplayName("Burns with same execution time should compare equal")
    void testSameExecutionTimeOrdering() {
        ScheduledBurn burn1 = new ScheduledBurn("burn1", 500.0, new Vector3D(100.0, 0.0, 0.0), "Burn 1");
        ScheduledBurn burn2 = new ScheduledBurn("burn2", 500.0, new Vector3D(0.0, 100.0, 0.0), "Burn 2");

        assertEquals(0, burn1.compareTo(burn2),
                "Burns with same execution time should compare equal (regardless of delta-V)");
    }

    @Test
    @DisplayName("Ordering should handle negative execution times")
    void testNegativeTimeOrdering() {
        ScheduledBurn negativeBurn = new ScheduledBurn("neg", -100.0, Vector3D.ZERO, "Negative");
        ScheduledBurn zeroBurn = new ScheduledBurn("zero", 0.0, Vector3D.ZERO, "Zero");
        ScheduledBurn positiveBurn = new ScheduledBurn("pos", 100.0, Vector3D.ZERO, "Positive");

        assertAll("Ordering with negative times",
                () -> assertTrue(negativeBurn.compareTo(zeroBurn) < 0, "Negative < Zero"),
                () -> assertTrue(zeroBurn.compareTo(positiveBurn) < 0, "Zero < Positive"),
                () -> assertTrue(negativeBurn.compareTo(positiveBurn) < 0, "Negative < Positive")
        );
    }

    // ==================== EDGE CASES AND VALIDATION ====================

    @Test
    @DisplayName("ToString should include key information")
    void testToString() {
        String result = standardBurn.toString();

        assertAll("ToString contains key info",
                () -> assertTrue(result.contains(TEST_BURN_ID), "Should contain burn ID"),
                () -> assertTrue(result.contains("1000.0"), "Should contain execution time"),
                () -> assertTrue(result.contains(TEST_DESCRIPTION), "Should contain description")
        );
    }

    @Test
    @DisplayName("Fuel calculation should handle very small masses")
    void testFuelRequiredSmallMass() {
        double tinyMass = 0.1; // 100 grams
        double fuel = standardBurn.fuelRequired(tinyMass, standardExhaustVelocity);

        assertAll("Small mass fuel calculation",
                () -> assertTrue(fuel >= 0.0, "Fuel should be non-negative"),
                () -> assertTrue(fuel < tinyMass, "Fuel should be less than total mass"),
                () -> assertTrue(fuel > 0.0, "Should require some fuel for non-zero delta-V")
        );
    }

    @Test
    @DisplayName("Fuel calculation should handle very large masses")
    void testFuelRequiredLargeMass() {
        double hugeMass = 1e9; // 1 million metric tons
        double fuel = standardBurn.fuelRequired(hugeMass, standardExhaustVelocity);

        assertAll("Large mass fuel calculation",
                () -> assertTrue(fuel >= 0.0, "Fuel should be non-negative"),
                () -> assertTrue(fuel < hugeMass, "Fuel should be less than total mass"),
                () -> assertFalse(Double.isInfinite(fuel), "Should not overflow to infinity"),
                () -> assertFalse(Double.isNaN(fuel), "Should not be NaN")
        );
    }

    @Test
    @DisplayName("Burns should be independent (no shared state)")
    void testBurnIndependence() {
        ScheduledBurn burn1 = new ScheduledBurn("burn1", 100.0, new Vector3D(10.0, 0.0, 0.0), "Burn 1");
        ScheduledBurn burn2 = new ScheduledBurn("burn2", 200.0, new Vector3D(20.0, 0.0, 0.0), "Burn 2");

        // Calculate fuel for both
        double fuel1 = burn1.fuelRequired(1000.0, 2000.0);
        double fuel2 = burn2.fuelRequired(1000.0, 2000.0);

        // Recalculate fuel for burn1 to ensure it hasn't changed
        double fuel1Again = burn1.fuelRequired(1000.0, 2000.0);

        assertEquals(fuel1, fuel1Again, TOLERANCE,
                "Burn calculations should be independent (immutable records)");
    }
}