package com.kaymlyn.planeteater.simulation.physics;

import com.kaymlyn.planeteater.simulation.celestial.CelestialBodyFactory;
import com.kaymlyn.planeteater.simulation.vehicles.CentralMind;
import com.kaymlyn.planeteater.simulation.celestial.OrbitalSystem;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.PlanetPattern;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.celestial.planetoid.Planet;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import com.kaymlyn.planeteater.simulation.vehicles.VehicleFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for TransferPlanner.
 *
 * Tests cover:
 * - Lambert universal variable solver correctness
 * - Stumpff function stability across trajectory types
 * - Transfer option generation (all four Lambert strategies)
 * - Selection logic for optimization goals
 * - Feasibility validation against spacecraft constraints
 * - Degenerate geometry handling
 * - Max delta-V search and multiplier configuration
 *
 * All assertions are prescriptive: each is derived from a physical law,
 * mathematical definition, or explicit API contract - not from observed output.
 * See TEST_WRITING_GUIDELINES.md for the prescriptive/descriptive distinction.
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("TransferPlanner Tests")
public class TransferPlannerTest {

    // Tolerances - all prescriptive
    private static final double TIME_TOLERANCE = 1.0;        // 1 second - burn scheduling contract
    private static final double PHYSICS_TOLERANCE = 1e-6;    // dimensionless ratios, exact math
    private static final double DELTA_V_MIN_BOUND = 3000.0;  // m/s - physically impossible to do less
    private static final double DELTA_V_MAX_BOUND = 15000.0; // m/s - impractically high trajectory

    private CelestialBodyFactory factory;
    private OrbitalSystem system;
    private Star sun;
    private Planet earth;
    private Planet mars;
    private Planet venus;
    private Spacecraft probe;
    private CentralMind platform;

    @BeforeEach
    void setUp() {
        sun = CelestialBodyFactory.createMainSequenceStar("Sol", 1.0);
        factory = new CelestialBodyFactory(sun, 3600.0);
        system = factory.getSystem();

        earth = factory.createPlanetFromPattern(
                "Earth", sun,
                new Orbit(PhysicsConstants.AU, 0.0, 0.0, 0.0, 0.0, 0.0, sun),
                PlanetPattern.EARTH, 1.0);

        mars = factory.createPlanetFromPattern(
                "Mars", sun,
                new Orbit(PhysicsConstants.AU * 1.524, 0.0, 0.0, 0.0, 0.0, 0.0, sun),
                PlanetPattern.MARS, 1.0);

        venus = factory.createPlanetFromPattern(
                "Venus", sun,
                new Orbit(PhysicsConstants.AU * 0.723, 0.0, 0.0, 0.0, 0.0, 0.0, sun),
                PlanetPattern.VENUS, 1.0);

        platform = factory.createCentralMind(PhysicsConstants.AU);

        // createInterplanetaryProbe: ~1000 kg dry, 8000 kg fuel, 4500 m/s exhaust
        // Available delta-V ~9592 m/s - sufficient for Earth-Mars-Earth round trip
        probe = VehicleFactory.createInterplanetaryProbe("Test-Probe", platform);
    }

    // ==================== LAMBERT SOLVER - STRUCTURAL TESTS ====================

    @Test
    @DisplayName("Lambert transfer produces exactly two burns for orbit transfer")
    void testLambertTransferBurnCount() {
        // Contract: buildLambertTransfer for a non-landing orbit transfer produces
        // exactly two burns: departure and arrival. No more, no less.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertAll("Lambert orbit transfer burn count",
                () -> assertNotNull(itinerary, "Itinerary must not be null"),
                () -> assertEquals(2, itinerary.getBurns().size(),
                        "Non-landing transfer must have exactly 2 burns: departure and arrival")
        );
    }

    @Test
    @DisplayName("Lambert transfer with landing produces at least three burns")
    void testLambertLandingBurnCount() {
        // Contract: a landing transfer adds a third descent burn after orbit insertion.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, true,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertTrue(itinerary.getBurns().size() >= 3,
                "Landing transfer must have at least 3 burns: departure, arrival, landing");
    }

    @Test
    @DisplayName("Departure burn fires at specified departure time")
    void testDepartureBurnTiming() {
        // Contract: first burn executes at departureTime.
        double departure = departureTime();
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departure, 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertEquals(departure, itinerary.getBurns().get(0).executionTime(), TIME_TOLERANCE,
                "Departure burn must fire at the specified departure time");
    }

    @Test
    @DisplayName("Arrival burn is separated from departure by transfer time")
    void testArrivalBurnTiming() {
        // Contract: arrival burn fires exactly transferTime seconds after departure.
        double departure = departureTime();
        double transferTime = 200.0 * PhysicsConstants.SECONDS_PER_DAY;
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departure, transferTime);

        double separation = itinerary.getBurns().get(1).executionTime()
                - itinerary.getBurns().get(0).executionTime();

        assertEquals(transferTime, separation, TIME_TOLERANCE,
                "Burn separation must equal the specified transfer time");
    }

    @Test
    @DisplayName("Departure delta-V is non-zero for any physical transfer")
    void testDepartureDeltaVNonZero() {
        // Physical law: any transfer between non-identical orbits requires non-zero delta-V.
        // A zero departure burn would mean the spacecraft is already on the transfer arc.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertTrue(itinerary.getBurns().get(0).deltaVelocity().magnitude() > 0,
                "Departure delta-V must be non-zero for any physical transfer");
    }

    @Test
    @DisplayName("Earth-Mars departure burn is prograde")
    void testOutwardTransferPrograde() {
        // Physical law: to raise apoapsis from Earth orbit (1 AU) to Mars orbit (1.524 AU),
        // the departure burn must have a positive component along Earth's velocity vector.
        // Traceable to vis-viva equation: raising apoapsis requires prograde burn at periapsis.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        if (!itinerary.isFeasible()) return; // skip if geometry infeasible

        Vector3D departureDeltaV = itinerary.getBurns().get(0).deltaVelocity();
        double progradeComponent = departureDeltaV.dot(earth.getVelocity().normalize());

        assertTrue(progradeComponent > 0,
                String.format("Earth-Mars departure must be prograde (positive dot with Earth velocity). "
                        + "Got %.1f m/s prograde component.", progradeComponent));
    }

    @Test
    @DisplayName("Earth-Venus departure burn is retrograde")
    void testInwardTransferRetrograde() {
        // Physical law: to lower apoapsis from Earth orbit (1 AU) to Venus orbit (0.723 AU),
        // the departure burn must decelerate (retrograde).
        // Traceable to vis-viva equation: lowering periapsis requires retrograde burn.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe, venus.snapshotOrbit(), venus, false,
                departureTime(), 150.0 * PhysicsConstants.SECONDS_PER_DAY);

        if (!itinerary.isFeasible()) return;

        Vector3D departureDeltaV = itinerary.getBurns().get(0).deltaVelocity();
        double progradeComponent = departureDeltaV.dot(earth.getVelocity().normalize());

        assertTrue(progradeComponent < 0,
                String.format("Earth-Venus departure must be retrograde (negative dot with Earth velocity). "
                        + "Got %.1f m/s prograde component.", progradeComponent));
    }

    @Test
    @DisplayName("Earth-Mars total delta-V is within physically realistic bounds")
    void testEarthMarsDeltaVBounds() {
        // Physical law: Earth-Mars Hohmann-equivalent requires ~5940 m/s total
        // (departure ~2945 + heliocentric capture ~910 + orbit insertion ~2085).
        // Any valid trajectory must lie within the bounds below.
        // Lower bound 3000 m/s: physically impossible to do less for this transfer.
        // Upper bound 15000 m/s: impractically high, indicates solver error.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 259.0 * PhysicsConstants.SECONDS_PER_DAY);

        if (!itinerary.isFeasible()) return;

        double totalDeltaV = itinerary.getTotalDeltaV();
        assertAll("Earth-Mars delta-V physical bounds",
                () -> assertTrue(totalDeltaV > DELTA_V_MIN_BOUND,
                        String.format("Total delta-V %.0f m/s is below physical minimum for Earth-Mars", totalDeltaV)),
                () -> assertTrue(totalDeltaV < DELTA_V_MAX_BOUND,
                        String.format("Total delta-V %.0f m/s exceeds physical maximum for Earth-Mars", totalDeltaV))
        );
    }

    @Test
    @DisplayName("Itinerary destination is set to the destination body")
    void testDestinationTracking() {
        // Contract: buildLambertTransfer sets itinerary.destination to the destination body.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertEquals(mars, itinerary.getDestination(),
                "Itinerary destination must be set to the destination body");
    }

    @Test
    @DisplayName("Non-landing transfer sets final state to ORBITING")
    void testFinalStateOrbiting() {
        // Contract: state machine - non-landing transfer terminates in ORBITING.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertEquals(Spacecraft.SpacecraftState.ORBITING, itinerary.getFinalState(),
                "Non-landing transfer must set final state to ORBITING");
    }

    @Test
    @DisplayName("Landing transfer sets final state to DOCKED")
    void testFinalStateDocked() {
        // Contract: state machine - landing transfer terminates in DOCKED.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, true,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertEquals(Spacecraft.SpacecraftState.DOCKED, itinerary.getFinalState(),
                "Landing transfer must set final state to DOCKED");
    }

    // ==================== SOLVER STABILITY TESTS ====================

    @Test
    @DisplayName("Solver converges without throwing across a range of transfer times")
    void testSolverStabilityAcrossTransferTimes() {
        // Contract: solveLambert must not throw for any well-posed geometry.
        // Stability is required for the max delta-V binary search (84 solves per call).
        double[] transferDays = {150.0, 200.0, 259.0, 350.0, 500.0, 700.0};

        for (double days : transferDays) {
            double transferTime = days * PhysicsConstants.SECONDS_PER_DAY;
            Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                    probe,mars.snapshotOrbit(), mars, false,
                    departureTime(), transferTime);

            assertNotNull(itinerary,
                    String.format("Solver must not throw for %.0f day Earth-Mars transfer", days));
        }
    }

    @Test
    @DisplayName("Near-parabolic geometry (very long transfer) does not throw")
    void testNearParabolicStability() {
        // Mathematical property: very long transfer times push the universal variable z
        // toward zero (parabolic limit). The Stumpff series expansion must handle this
        // without numerical overflow or division by zero.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 900.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertNotNull(itinerary,
                "Solver must not throw for near-parabolic geometry (900 day transfer)");
    }

    @Test
    @DisplayName("Degenerate geometry (near-zero transfer time) returns infeasible, not exception")
    void testDegenerateGeometryHandled() {
        // Contract: collinear or near-collinear position vectors have no defined orbital plane.
        // The solver must return infeasible (null LambertSolution) rather than throwing
        // or returning a wrong answer.
        // Near-zero transfer time: arrival position almost identical to departure position.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe, earth.snapshotOrbit(), earth, false,
                departureTime(), 1.0); // 1 second: planet barely moves

        assertNotNull(itinerary,
                "Must return itinerary (not throw) for degenerate near-zero transfer time");
    }

    // ==================== TRANSFER OPTION GENERATION TESTS ====================

    @Test
    @DisplayName("generateTransferOptions returns non-empty list for feasible mission")
    void testGenerateTransferOptionsNonEmpty() {
        // Contract: probe has ~9592 m/s, Earth-Mars requires ~5940 m/s.
        // At least one strategy must succeed.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        assertFalse(options.isEmpty(),
                "Must generate at least one feasible option when spacecraft has sufficient delta-V");
    }

    @Test
    @DisplayName("generateTransferOptions includes all three fixed Lambert strategies")
    void testGenerateTransferOptionsAllStrategies() {
        // Contract: generateTransferOptions attempts FAST, BALANCED, EFFICIENT multipliers.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        assertAll("All fixed Lambert strategies present",
                () -> assertTrue(options.stream().anyMatch(
                                o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_FAST),
                        "Must include LAMBERT_FAST (1.0x min transfer time)"),
                () -> assertTrue(options.stream().anyMatch(
                                o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_BALANCED),
                        "Must include LAMBERT_BALANCED (1.5x min transfer time)"),
                () -> assertTrue(options.stream().anyMatch(
                                o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_EFFICIENT),
                        "Must include LAMBERT_EFFICIENT (2.5x min transfer time)")
        );
    }

    @Test
    @DisplayName("Options are sorted by efficiency score ascending")
    void testOptionsSortedByEfficiencyScore() {
        // Contract: generateTransferOptions sorts by efficiency score (duration / delta-V) ascending.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        for (int i = 0; i < options.size() - 1; i++) {
            double current = options.get(i).getEfficiencyScore();
            double next = options.get(i + 1).getEfficiencyScore();
            assertTrue(current <= next,
                    String.format("Options must be sorted ascending: index %d (%.4f) > index %d (%.4f)",
                            i, current, i + 1, next));
        }
    }

    @Test
    @DisplayName("All generated options have positive delta-V")
    void testAllOptionsPositiveDeltaV() {
        // Physical law: any real transfer requires energy expenditure. delta-V = 0 violates
        // conservation of energy for a transfer between different orbital states.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        options.forEach(option ->
                assertTrue(option.getItinerary().getTotalDeltaV() > 0,
                        String.format("Strategy %s must require positive delta-V, got %.2f m/s",
                                option.getStrategy(), option.getItinerary().getTotalDeltaV()))
        );
    }

    @Test
    @DisplayName("Efficiency score equals duration divided by delta-V")
    void testEfficiencyScoreFormula() {
        // Contract: TransferOption.efficiencyScore = duration / deltaV.
        // Traceable to TransferOption constructor implementation.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        options.forEach(option -> {
            double duration = option.getItinerary().getEstimatedDuration();
            double deltaV = option.getItinerary().getTotalDeltaV();
            double expectedScore = deltaV > 0 ? duration / deltaV : Double.POSITIVE_INFINITY;
            assertEquals(expectedScore, option.getEfficiencyScore(), PHYSICS_TOLERANCE,
                    String.format("Efficiency score for %s must equal duration/delta-V",
                            option.getStrategy()));
        });
    }

    // ==================== MAX DELTA-V TRANSFER TESTS ====================

    @Test
    @DisplayName("LAMBERT_MAX_DELTAV option generated when spacecraft has fuel")
    void testMaxDeltaVOptionGenerated() {
        // Contract: probe delta-V budget > Earth-Mars requirement.
        // The binary search must find a feasible trajectory and add LAMBERT_MAX_DELTAV.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        assertTrue(options.stream().anyMatch(
                        o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_MAX_DELTAV),
                "LAMBERT_MAX_DELTAV must be present when spacecraft has sufficient fuel");
    }

    @Test
    @DisplayName("LAMBERT_MAX_DELTAV uses no more than available delta-V")
    void testMaxDeltaVWithinBudget() {
        // Contract: the search finds the shortest time within the budget.
        // Result must not exceed the budget or the search found the wrong root.
        double availableDeltaV = probe.getAvailableDeltaV();
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        options.stream()
                .filter(o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_MAX_DELTAV)
                .forEach(option ->
                        assertTrue(option.getItinerary().getTotalDeltaV() <= availableDeltaV,
                                String.format("Max delta-V option (%.0f m/s) must not exceed available (%.0f m/s)",
                                        option.getItinerary().getTotalDeltaV(), availableDeltaV))
                );
    }

    @Test
    @DisplayName("LAMBERT_MAX_DELTAV not generated when spacecraft has no fuel")
    void testMaxDeltaVAbsentWithNoFuel() {
        // Contract: zero fuel means zero delta-V. No transfer can be feasible.
        // The binary search must return null. No LAMBERT_MAX_DELTAV option in list.
        Spacecraft emptyProbe = new Spacecraft(
                "Empty-Probe",
                new Composition().addMaterialAsRawMass(Material.TITANIUM, 600.0),
                0.0, 2.0, 4500.0, false, 0, 0, platform);

        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                emptyProbe, earth, mars, false, departureTime());

        assertFalse(options.stream().anyMatch(
                        o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_MAX_DELTAV),
                "LAMBERT_MAX_DELTAV must not be present when spacecraft has no fuel");
    }

    @Test
    @DisplayName("maxTransferTimeMultiplier limits the search window upper bound")
    void testMaxTransferTimeMultiplierRespected() {
        // Contract: max delta-V search range upper bound = minTransferTime * maxTransferTimeMultiplier.
        // Setting multiplier to 1.05 restricts valid trajectories to near-minimum time only.
        double originalMultiplier = TransferPlanner.maxTransferTimeMultiplier;
        try {
            TransferPlanner.maxTransferTimeMultiplier = 1.05;

            Orbit earthOrbit = earth.snapshotOrbit();
            Orbit marsOrbit = mars.snapshotOrbit();
            double transferSMA = (earthOrbit.semiMajorAxis() + marsOrbit.semiMajorAxis()) / 2.0;
            double minTime = Math.PI * Math.sqrt(Math.pow(transferSMA, 3) / sun.getGravitationalParameter());
            double upperBound = minTime * 1.05;

            List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                    probe, earth, mars, false, departureTime());

            options.stream()
                    .filter(o -> o.getStrategy() == TransferPlanner.TransferStrategy.LAMBERT_MAX_DELTAV)
                    .forEach(option ->
                            assertTrue(option.getItinerary().getEstimatedDuration() <= upperBound * 1.01,
                                    "Max delta-V option must not exceed the configured multiplier upper bound")
                    );
        } finally {
            TransferPlanner.maxTransferTimeMultiplier = originalMultiplier;
        }
    }

    // ==================== SELECTION TESTS ====================

    @Test
    @DisplayName("MINIMUM_TIME selects option with shortest duration")
    void testSelectMinimumTime() {
        // Contract: MINIMUM_TIME returns min(estimatedDuration) from options.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        TransferPlanner.TransferOption selected = TransferPlanner.selectBestTransfer(
                options, TransferPlanner.OptimizationGoal.MINIMUM_TIME);

        assertNotNull(selected, "MINIMUM_TIME selection must return a result");
        double selectedDuration = selected.getItinerary().getEstimatedDuration();
        options.forEach(option ->
                assertTrue(selectedDuration <= option.getItinerary().getEstimatedDuration(),
                        "MINIMUM_TIME result must have duration <= all other options")
        );
    }

    @Test
    @DisplayName("MINIMUM_DELTAV selects option with least fuel consumption")
    void testSelectMinimumDeltaV() {
        // Contract: MINIMUM_DELTAV returns min(totalDeltaV) from options.
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        TransferPlanner.TransferOption selected = TransferPlanner.selectBestTransfer(
                options, TransferPlanner.OptimizationGoal.MINIMUM_DELTAV);

        assertNotNull(selected, "MINIMUM_DELTAV selection must return a result");
        double selectedDeltaV = selected.getItinerary().getTotalDeltaV();
        options.forEach(option ->
                assertTrue(selectedDeltaV <= option.getItinerary().getTotalDeltaV(),
                        "MINIMUM_DELTAV result must have delta-V <= all other options")
        );
    }

    @Test
    @DisplayName("BALANCED selects option with lowest efficiency score")
    void testSelectBalanced() {
        // Contract: BALANCED returns min(efficiencyScore) from options.
        // Since options are already sorted ascending by efficiency score, result is options.get(0).
        List<TransferPlanner.TransferOption> options = TransferPlanner.generateTransferOptions(
                probe, earth, mars, false, departureTime());

        TransferPlanner.TransferOption selected = TransferPlanner.selectBestTransfer(
                options, TransferPlanner.OptimizationGoal.BALANCED);

        assertNotNull(selected, "BALANCED selection must return a result");
        double selectedScore = selected.getEfficiencyScore();
        options.forEach(option ->
                assertTrue(selectedScore <= option.getEfficiencyScore(),
                        "BALANCED result must have efficiency score <= all other options")
        );
    }

    @Test
    @DisplayName("selectBestTransfer returns null for empty list")
    void testSelectFromEmptyList() {
        // Contract: no options means no selection possible. Null is the correct sentinel.
        assertAll("Empty list returns null for all goals",
                () -> assertNull(TransferPlanner.selectBestTransfer(
                                List.of(), TransferPlanner.OptimizationGoal.MINIMUM_TIME),
                        "MINIMUM_TIME on empty list must return null"),
                () -> assertNull(TransferPlanner.selectBestTransfer(
                                List.of(), TransferPlanner.OptimizationGoal.MINIMUM_DELTAV),
                        "MINIMUM_DELTAV on empty list must return null"),
                () -> assertNull(TransferPlanner.selectBestTransfer(
                                List.of(), TransferPlanner.OptimizationGoal.BALANCED),
                        "BALANCED on empty list must return null")
        );
    }

    // ==================== FEASIBILITY TESTS ====================

    @Test
    @DisplayName("Transfer is feasible for well-fuelled spacecraft")
    void testFeasibleWithSufficientFuel() {
        // Contract: probe has ~9592 m/s, Earth-Mars requires ~5940 m/s.
        // validateAgainstSpacecraft must pass.
        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                probe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertTrue(itinerary.isFeasible(),
                "Earth-Mars transfer must be feasible for probe with ~9592 m/s budget. "
                        + "Infeasibility reason: " + itinerary.getInfeasibilityReason());
    }

    @Test
    @DisplayName("Transfer is infeasible when fuel is insufficient")
    void testInfeasibleWithInsufficientFuel() {
        // Contract: validateAgainstSpacecraft sets infeasible when requiredFuel > fuelMass.
        // 1 kg fuel is orders of magnitude below the ~4000 kg required for Earth-Mars.
        Spacecraft tinyProbe = new Spacecraft(
                "Tiny-Probe",
                new Composition().addMaterialAsRawMass(Material.TITANIUM, 600.0),
                1.0, 2.0, 4500.0, false, 0, 0, platform);

        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                tinyProbe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertFalse(itinerary.isFeasible(),
                "Earth-Mars transfer must be infeasible for spacecraft with 1 kg fuel");
    }

    @Test
    @DisplayName("Infeasible itinerary provides a reason")
    void testInfeasibleItineraryHasReason() {
        // Contract: setInfeasible always stores a non-null, non-empty reason string.
        Spacecraft tinyProbe = new Spacecraft(
                "Tiny-Probe",
                new Composition().addMaterialAsRawMass(Material.TITANIUM, 600.0),
                1.0, 2.0, 4500.0, false, 0, 0, platform);

        Itinerary itinerary = TransferPlanner.buildLambertTransfer(
                tinyProbe,mars.snapshotOrbit(), mars, false,
                departureTime(), 200.0 * PhysicsConstants.SECONDS_PER_DAY);

        assertAll("Infeasible itinerary has reason",
                () -> assertFalse(itinerary.isFeasible(), "Must be infeasible"),
                () -> assertNotNull(itinerary.getInfeasibilityReason(), "Must have reason string"),
                () -> assertFalse(itinerary.getInfeasibilityReason().isBlank(), "Reason must not be blank")
        );
    }

    // ==================== HELPER ====================

    private double departureTime() {
        return system.getCurrentTime() + PhysicsConstants.SECONDS_PER_DAY;
    }
}