package com.kaymlyn.planeteater.simulation.celestial.planetoid;

import com.kaymlyn.planeteater.simulation.celestial.CelestialBodyFactory;
import com.kaymlyn.planeteater.simulation.celestial.Star;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.LayerProfile;
import com.kaymlyn.planeteater.simulation.celestial.planetconfig.Materials;
import com.kaymlyn.planeteater.simulation.physics.Orbit;
import com.kaymlyn.planeteater.simulation.physics.PhysicsConstants;
import com.kaymlyn.planeteater.simulation.resources.Material;
import com.kaymlyn.planeteater.simulation.vehicles.Spacecraft;
import com.kaymlyn.planeteater.simulation.resources.Composition;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive test suite for Planet.
 *
 * Tests cover:
 * - Construction and layer composition for core-only and full-layer planets
 * - Mass and radius derivation from composition
 * - Surface gravity (Newton: g = G*M/r^2)
 * - Mineable layer flags and sequential depletion gating
 * - Resource extraction: correct layer, correct quantity, exhaustion
 * - Hill sphere: r_Hill = d * (m / (3 * M))^(1/3)
 * - Sub-satellite and tidal-lock thresholds
 * - Docking contract: state, hanger, updateDocked position propagation
 * - System delegation
 *
 * getDensity() is deferred pending a bug review (Planet returns mass/radius,
 * not mass/volume; see BACKLOG.md).
 *
 * Generated by Claude (Sonnet 4.5)
 */
@DisplayName("Planet Tests")
public class PlanetTest {

    // Tolerances
    private static final double TOLERANCE = 1e-6;
    private static final double PHYSICS_TOLERANCE = 1e-3;

    // Orbital parameters
    private static final double ONE_AU = PhysicsConstants.AU;

    // Layer radii for earthLikePlanet (meters, additive)
    private static final double CORE_RADIUS = 3.476e6;
    private static final double MANTLE_OUTER_RADIUS = CORE_RADIUS + 2.885e6;
    private static final double CRUST_OUTER_RADIUS = MANTLE_OUTER_RADIUS + 6.5e4;
    private static final double ATMOSPHERE_OUTER_RADIUS = CRUST_OUTER_RADIUS + 1.0e4;

    // Layer radius for coreOnlyPlanet (meters)
    private static final double CORE_ONLY_RADIUS = 5.0e5;

    private CelestialBodyFactory factory;
    private Star star;

    // Test fixtures
    private Planet earthLikePlanet;  // full-layer (core + mantle + crust + atmosphere)
    private Planet coreOnlyPlanet;   // single layer, no crust or atmosphere

    @BeforeEach
    void setUp() {
        star = CelestialBodyFactory.createMainSequenceStar("TestStar", 1.0);
        factory = new CelestialBodyFactory(star, 3600.0);

        Map<String, LayerProfile> profiles = factory.getProfiles();

        earthLikePlanet = factory.createArbitraryPlanet(
                "earth-like",
                new Orbit(ONE_AU, 0.0, 0.0, 0.0, 0.0, 0.0, null),
                profiles.get("IRON_NICKEL_CORE"),          CORE_RADIUS,
                profiles.get("MG_FE_SILICATE_MANTLE"),     MANTLE_OUTER_RADIUS,
                profiles.get("ALUMINA_SILICA_CRUST"),      CRUST_OUTER_RADIUS,
                profiles.get("NITROGEN_OXYGEN_ATMOSPHERE"), ATMOSPHERE_OUTER_RADIUS
        );

        // Core-only: null for mantle, crust, atmosphere layers
        LayerProfile ironNickelCore = new LayerProfile(
                "IRON_NICKEL",
                Zone.CORE,
                List.of(new Materials(Material.IRON, 85), new Materials(Material.NICKEL, 10))
        );

        coreOnlyPlanet = factory.createArbitraryPlanet(
                "core-only",
                earthLikePlanet,
                new Orbit(1.0e7, 0.0, 0.0, 0.0, 0.0, 0.0, null),
                ironNickelCore, CORE_ONLY_RADIUS,
                null, 0.0,
                null, 0.0,
                null, 0.0
        );
    }

    // ==================== CONSTRUCTION - FULL-LAYER PLANET ====================

    @Test
    @DisplayName("Full-layer planet has mass in all four compositions")
    void testFullLayerCompositionsHaveMass() {
        assertAll("All layers populated",
                () -> assertTrue(earthLikePlanet.getCoreComposition().getTotalMass() > 0.0,
                        "Core must have mass"),
                () -> assertTrue(earthLikePlanet.getMantleComposition().getTotalMass() > 0.0,
                        "Mantle must have mass"),
                () -> assertTrue(earthLikePlanet.getCrustComposition().getTotalMass() > 0.0,
                        "Crust must have mass"),
                () -> assertTrue(earthLikePlanet.getAtmosphereComposition().getTotalMass() > 0.0,
                        "Atmosphere must have mass")
        );
    }

    @Test
    @DisplayName("Planet mass equals sum of all layer masses")
    void testMassEqualsLayerSum() {
        // Contract: Planet.getAggregatedMass() sums all four layer compositions
        double expectedMass = earthLikePlanet.getCoreComposition().getTotalMass()
                + earthLikePlanet.getMantleComposition().getTotalMass()
                + earthLikePlanet.getCrustComposition().getTotalMass()
                + earthLikePlanet.getAtmosphereComposition().getTotalMass();

        assertEquals(expectedMass, earthLikePlanet.getMass(), TOLERANCE,
                "getMass() must equal sum of all layer masses");
    }

    @Test
    @DisplayName("Planet radius derived from total volume (sphere formula)")
    void testRadiusFromVolume() {
        // Contract: Planet.getRadius() = cbrt(3 * totalVolume / (4 * PI))
        double totalVolume = earthLikePlanet.getCoreComposition().getTotalVolume()
                + earthLikePlanet.getMantleComposition().getTotalVolume()
                + earthLikePlanet.getCrustComposition().getTotalVolume()
                + earthLikePlanet.getAtmosphereComposition().getTotalVolume();
        double expectedRadius = Math.cbrt((3.0 * totalVolume) / (4.0 * Math.PI));

        assertEquals(expectedRadius, earthLikePlanet.getRadius(), TOLERANCE,
                "Radius must satisfy sphere volume formula r = cbrt(3V/4PI)");
    }

    @Test
    @DisplayName("Surface gravity satisfies Newton: g = G*M / r^2")
    void testSurfaceGravity() {
        // Law: Newtonian surface gravity
        double mass = earthLikePlanet.getMass();
        double radius = earthLikePlanet.getRadius();
        double expectedGravity = PhysicsConstants.G * mass / (radius * radius);

        assertEquals(expectedGravity, earthLikePlanet.getSurfaceGravity(), PHYSICS_TOLERANCE,
                "Surface gravity must satisfy g = G*M/r^2");
    }

    // ==================== CONSTRUCTION - CORE-ONLY PLANET ====================

    @Test
    @DisplayName("Core-only planet has mass only in core; other layers are empty")
    void testCoreOnlyLayerDistribution() {
        assertAll("Layer distribution for core-only planet",
                () -> assertTrue(coreOnlyPlanet.getCoreComposition().getTotalMass() > 0.0,
                        "Core must have mass"),
                () -> assertEquals(0.0, coreOnlyPlanet.getMantleComposition().getTotalMass(), TOLERANCE,
                        "Mantle must be empty (null layer at construction)"),
                () -> assertEquals(0.0, coreOnlyPlanet.getCrustComposition().getTotalMass(), TOLERANCE,
                        "Crust must be empty (null layer at construction)"),
                () -> assertEquals(0.0, coreOnlyPlanet.getAtmosphereComposition().getTotalMass(), TOLERANCE,
                        "Atmosphere must be empty (null layer at construction)")
        );
    }

    @Test
    @DisplayName("Core-only planet contains expected materials")
    void testCoreOnlyMaterials() {
        assertAll("Core-only planet materials",
                () -> assertTrue(coreOnlyPlanet.getCoreComposition().contains(Material.IRON),
                        "Iron must be present in iron-nickel core"),
                () -> assertTrue(coreOnlyPlanet.getCoreComposition().contains(Material.NICKEL),
                        "Nickel must be present in iron-nickel core"),
                () -> assertFalse(coreOnlyPlanet.getCoreComposition().contains(Material.SILICA),
                        "Silica must not be present in iron-nickel core")
        );
    }

    // ==================== DIFFERENTIATED LAYER FLAGS ====================

    @Test
    @DisplayName("Full-layer planet: canMineCrust and canHarvestAtmosphere are true")
    void testFullLayerMineabilityFlags() {
        assertAll("Full-layer planet flags",
                () -> assertTrue(earthLikePlanet.canMineCrust(),
                        "Planet with crust mass > 0 must be crust-minable"),
                () -> assertTrue(earthLikePlanet.canHarvestAtmosphere(),
                        "Planet with atmosphere mass > 0 must be atmosphere-harvestable"),
                () -> assertFalse(earthLikePlanet.canMineMantle(),
                        "canMineMantle requires crust fully exhausted first"),
                () -> assertFalse(earthLikePlanet.canMineCore(),
                        "canMineCore requires mantle fully exhausted first")
        );
    }

    @Test
    @DisplayName("Core-only planet: only canMineMantle is true initially")
    void testCoreOnlyMineabilityFlags() {
        // Contract: canMineMantle = (crust mass == 0 AND mantle mass > 0)
        // Core-only has neither crust nor mantle; canMineMantle checks mantle mass > 0 which is false.
        // canMineCore checks mantle mass == 0 AND core mass > 0 - both are true here.
        assertAll("Core-only planet flags",
                () -> assertFalse(coreOnlyPlanet.canMineCrust(),
                        "No crust - cannot mine crust"),
                () -> assertFalse(coreOnlyPlanet.canHarvestAtmosphere(),
                        "No atmosphere - cannot harvest atmosphere"),
                () -> assertFalse(coreOnlyPlanet.canMineMantle(),
                        "canMineMantle requires mantle mass > 0"),
                () -> assertTrue(coreOnlyPlanet.canMineCore(),
                        "canMineCore: mantle is 0 and core has mass")
        );
    }

    @Test
    @DisplayName("Sequential depletion: exhausting crust unlocks mantle access")
    void testSequentialDepletionUnlocksMantle() {
        // Exhaust all crust materials
        double crustMass = earthLikePlanet.getCrustComposition().getTotalMass();
        // Remove all materials that are present in the crust
        for (Material mat : Material.values()) {
            earthLikePlanet.getCrustComposition().removeMaterial(mat, crustMass);
        }

        // After crust exhaustion, canMineMantle should flip to true
        // Contract: canMineMantle = (crust total mass == 0) AND (mantle total mass > 0)
        assertAll("Post-crust-exhaustion state",
                () -> assertEquals(0.0, earthLikePlanet.getCrustComposition().getTotalMass(), TOLERANCE,
                        "Crust must be fully exhausted"),
                () -> assertFalse(earthLikePlanet.canMineCrust(),
                        "canMineCrust must be false when crust mass is 0"),
                () -> assertTrue(earthLikePlanet.canMineMantle(),
                        "canMineMantle must be true once crust is exhausted and mantle has mass")
        );
    }

    @Test
    @DisplayName("Sequential depletion: exhausting mantle unlocks core access")
    void testSequentialDepletionUnlocksCore() {
        // Exhaust crust then mantle
        double largeAmount = 1.0e40;
        for (Material mat : Material.values()) {
            earthLikePlanet.getCrustComposition().removeMaterial(mat, largeAmount);
            earthLikePlanet.getMantleComposition().removeMaterial(mat, largeAmount);
        }

        // Contract: canMineCore = (mantle total mass == 0) AND (core total mass > 0)
        assertAll("Post-mantle-exhaustion state",
                () -> assertEquals(0.0, earthLikePlanet.getCrustComposition().getTotalMass(), TOLERANCE,
                        "Crust must be zero"),
                () -> assertEquals(0.0, earthLikePlanet.getMantleComposition().getTotalMass(), TOLERANCE,
                        "Mantle must be zero"),
                () -> assertFalse(earthLikePlanet.canMineMantle(),
                        "canMineMantle must be false once mantle is exhausted"),
                () -> assertTrue(earthLikePlanet.canMineCore(),
                        "canMineCore must be true once mantle is exhausted and core has mass")
        );
    }

    // ==================== RESOURCE EXTRACTION ====================

    @Test
    @DisplayName("mineCrustMaterial removes correct amount from crust")
    void testMineCrustRemovesFromCrust() {
        // Sanity check: crust must have iron oxide to mine it
        assertTrue(earthLikePlanet.getCrustComposition().contains(Material.IRON_OXIDE),
                "Test fixture must have iron oxide in crust");

        double preMineIronOxide = earthLikePlanet.getCrustComposition().getMass(Material.IRON_OXIDE);
        double requestedMass = preMineIronOxide * 0.1; // request 10% of available

        double actuallyMined = earthLikePlanet.mineCrustMaterial(Material.IRON_OXIDE, requestedMass);
        double postMineIronOxide = earthLikePlanet.getCrustComposition().getMass(Material.IRON_OXIDE);

        assertAll("Crust extraction correctness",
                () -> assertEquals(requestedMass, actuallyMined, TOLERANCE,
                        "When requested <= available, return exactly requested amount"),
                () -> assertEquals(preMineIronOxide - requestedMass, postMineIronOxide, TOLERANCE,
                        "Crust mass decreases by exactly the mined amount")
        );
    }

    @Test
    @DisplayName("Mining reduces planet mass and surface gravity")
    void testMiningReducesMassAndGravity() {
        double preMass = earthLikePlanet.getMass();
        double preGravity = earthLikePlanet.getSurfaceGravity();

        double ironOxideAvailable = earthLikePlanet.getCrustComposition().getMass(Material.IRON_OXIDE);
        earthLikePlanet.mineCrustMaterial(Material.IRON_OXIDE, ironOxideAvailable * 0.5);

        double postMass = earthLikePlanet.getMass();
        double postGravity = earthLikePlanet.getSurfaceGravity();

        assertAll("Mass and gravity change after mining",
                () -> assertTrue(postMass < preMass,
                        "Planet mass must decrease after extraction"),
                () -> assertTrue(postGravity < preGravity,
                        "Surface gravity must decrease as mass decreases (g = G*M/r^2)")
        );
    }

    @Test
    @DisplayName("Over-mining returns available amount, not requested amount")
    void testOverMiningClampsToAvailable() {
        double available = earthLikePlanet.getCrustComposition().getMass(Material.IRON_OXIDE);
        double oversizedRequest = available * 1000.0;

        double actuallyMined = earthLikePlanet.mineCrustMaterial(Material.IRON_OXIDE, oversizedRequest);

        assertAll("Over-mining behavior",
                () -> assertEquals(available, actuallyMined, TOLERANCE,
                        "Returned amount must equal what was actually available, not what was requested"),
                () -> assertFalse(earthLikePlanet.getCrustComposition().contains(Material.IRON_OXIDE),
                        "Exhausted material must be removed from composition"),
                () -> assertEquals(0.0, earthLikePlanet.getCrustComposition().getMass(Material.IRON_OXIDE), TOLERANCE,
                        "getMass on exhausted material returns 0.0")
        );
    }

    @Test
    @DisplayName("harvestAtmosphere removes correct amount from atmosphere")
    void testHarvestAtmosphereRemovesFromAtmosphere() {
        assertTrue(earthLikePlanet.getAtmosphereComposition().contains(Material.NITROGEN_GAS),
                "Test fixture must have nitrogen in atmosphere");

        double preHarvestNitrogen = earthLikePlanet.getAtmosphereComposition().getMass(Material.NITROGEN_GAS);
        double preHarvestOxygen = earthLikePlanet.getAtmosphereComposition().getMass(Material.OXYGEN_GAS);
        double requestedMass = preHarvestNitrogen * 0.01;

        double actuallyHarvested = earthLikePlanet.harvestAtmosphere(Material.NITROGEN_GAS, requestedMass);

        assertAll("Atmosphere harvest correctness",
                () -> assertEquals(requestedMass, actuallyHarvested, TOLERANCE,
                        "When requested <= available, return exactly requested amount"),
                () -> assertEquals(preHarvestNitrogen - requestedMass,
                        earthLikePlanet.getAtmosphereComposition().getMass(Material.NITROGEN_GAS), TOLERANCE,
                        "Nitrogen decreases by harvested amount"),
                () -> assertEquals(preHarvestOxygen,
                        earthLikePlanet.getAtmosphereComposition().getMass(Material.OXYGEN_GAS), TOLERANCE,
                        "Oxygen is not affected by nitrogen harvest")
        );
    }

    @Test
    @DisplayName("Mining and harvesting return 0.0 when the required layer is absent")
    void testExtractionGuardsWhenLayerAbsent() {
        // coreOnlyPlanet has no crust and no atmosphere
        assertAll("Extraction guards",
                () -> assertEquals(0.0,
                        coreOnlyPlanet.mineCrustMaterial(Material.IRON, 1.0e10), TOLERANCE,
                        "mineCrustMaterial returns 0.0 when canMineCrust is false"),
                () -> assertEquals(0.0,
                        coreOnlyPlanet.harvestAtmosphere(Material.NITROGEN_GAS, 1.0e10), TOLERANCE,
                        "harvestAtmosphere returns 0.0 when canHarvestAtmosphere is false")
        );
    }

    // ==================== HILL SPHERE ====================

    @Test
    @DisplayName("Hill sphere radius satisfies r_Hill = d * (m / (3 * M))^(1/3)")
    void testHillSphereFormula() {
        // Law: Hill sphere approximation for secondary body in circular orbit
        // r_Hill = semi-major axis * (mass / (3 * parent_mass))^(1/3)
        double distanceToParent = earthLikePlanet.getPosition()
                .distanceTo(star.getPosition());
        double expectedHillRadius = distanceToParent
                * Math.pow(earthLikePlanet.getMass() / (3.0 * star.getMass()), 1.0 / 3.0);

        assertEquals(expectedHillRadius, earthLikePlanet.calculateHillSphereRadius(), PHYSICS_TOLERANCE,
                "Hill sphere must satisfy r_Hill = d * (m/3M)^(1/3)");
    }

    @Test
    @DisplayName("canHaveSubSatellites: true when Hill sphere > 10 * planet radius")
    void testCanHaveSubSatellitesThreshold() {
        // Contract: canHaveSubSatellites = (hillRadius > 10 * radius)
        double hillRadius = earthLikePlanet.calculateHillSphereRadius();
        double tenRadii = 10.0 * earthLikePlanet.getRadius();

        if (hillRadius > tenRadii) {
            assertTrue(earthLikePlanet.canHaveSubSatellites(),
                    "Planet with Hill sphere > 10 radii must return true for canHaveSubSatellites");
        } else {
            assertFalse(earthLikePlanet.canHaveSubSatellites(),
                    "Planet with Hill sphere <= 10 radii must return false for canHaveSubSatellites");
        }
    }

    @Test
    @DisplayName("isTidallyLocked: true when Hill sphere < 50 * planet radius")
    void testIsTidallyLockedThreshold() {
        // Contract: isTidallyLocked = (hillRadius < 50 * radius)
        // earthLikePlanet at 1 AU has a very large Hill sphere; should NOT be tidally locked.
        double hillRadius = earthLikePlanet.calculateHillSphereRadius();
        double fiftyRadii = 50.0 * earthLikePlanet.getRadius();

        assertFalse(earthLikePlanet.isTidallyLocked(),
                "Planet at 1 AU must not be tidally locked (Hill sphere >> 50 * radius)");

        // Verify the formula drives the result
        assertTrue(hillRadius > fiftyRadii,
                "At 1 AU, Hill sphere must exceed 50 planet radii, confirming no tidal lock");
    }

    @Test
    @DisplayName("isTidallyLocked: true for planet with very small Hill sphere")
    void testTidallyLockedCloseOrbit() {
        // Construct a planet with very small orbit so Hill sphere < 50 * radius
        // coreOnlyPlanet orbits earthLikePlanet at SMALL_ORBIT (1e7 m) with low mass.
        // Evaluate against contract directly.
        double hillRadius = coreOnlyPlanet.calculateHillSphereRadius();
        double planetRadius = coreOnlyPlanet.getRadius();

        if (hillRadius < 50.0 * planetRadius) {
            assertTrue(coreOnlyPlanet.isTidallyLocked(),
                    "Planet whose Hill sphere < 50 radii must be tidally locked");
        } else {
            // If the fixture happens not to satisfy the condition, assert the contract
            // is consistent: isTidallyLocked must be false
            assertFalse(coreOnlyPlanet.isTidallyLocked(),
                    "Planet whose Hill sphere >= 50 radii must not be tidally locked");
        }
    }

    // ==================== DOCKING ====================

    @Test
    @DisplayName("dock: spacecraft enters hanger and state becomes DOCKED")
    void testDockPlacesSpacecraftInHangerAndSetsState() {
        // Construct a minimal spacecraft using a CentralMind as shipyard
        // (Planet.dock requires a Spacecraft; state is set by dock())
        Spacecraft probe = buildMinimalSpacecraft("probe-1");

        // Dock with planet directly
        earthLikePlanet.dock(probe);

        assertAll("dock() contract",
                () -> assertTrue(earthLikePlanet.getHanger().containsKey("probe-1"),
                        "Spacecraft must appear in planet hanger after dock()"),
                () -> assertEquals(Spacecraft.SpacecraftState.DOCKED, probe.getState(),
                        "dock() must set spacecraft state to DOCKED")
        );
    }

    @Test
    @DisplayName("updateDocked: docked spacecraft position and velocity match planet")
    void testUpdateDockedPropagatesPosition() {
        Spacecraft probe = buildMinimalSpacecraft("probe-2");
        earthLikePlanet.dock(probe);

        // Advance simulation one step so planet position changes
        factory.getSystem().stepVerlet();

        assertAll("updateDocked() propagates motion",
                () -> assertEquals(earthLikePlanet.getPosition(), probe.getPosition(),
                        "After updateDocked(), spacecraft position must equal planet position"),
                () -> assertEquals(earthLikePlanet.getVelocity(), probe.getVelocity(),
                        "After updateDocked(), spacecraft velocity must equal planet velocity")
        );
    }

    // ==================== SYSTEM DELEGATION ====================

    @Test
    @DisplayName("getSystem() returns the owning OrbitalSystem (non-null)")
    void testGetSystemDelegation() {
        assertAll("getSystem() delegation",
                () -> assertNotNull(earthLikePlanet.getSystem(),
                        "getSystem() must not return null"),
                () -> assertNotNull(coreOnlyPlanet.getSystem(),
                        "getSystem() must not return null for satellite planet")
        );
    }

    // ==================== HELPERS ====================

    /**
     * Builds a minimal probe spacecraft docked at the factory's CentralMind
     * for use in docking tests. Uses factory.createCentralMind() as shipyard
     * so the Spacecraft constructor receives a valid Orbiter.
     */
    private Spacecraft buildMinimalSpacecraft(String id) {
        Composition construction = new Composition();
        construction.addMaterialAsRawMass(Material.ALUMINUM, 100.0);

        // Use a new CentralMind as shipyard so the Spacecraft constructor receives a valid Orbiter
        com.kaymlyn.planeteater.simulation.vehicles.CentralMind platform =
                factory.createCentralMind(PhysicsConstants.AU * 2.0);

        Spacecraft craft = new Spacecraft(
                id,
                construction,
                100.0,   // fuel mass kg
                1.0,     // cargo capacity m^3
                2200.0,  // exhaust velocity m/s
                false,
                0,
                0,
                platform
        );
        platform.dock(craft);
        return craft;
    }
}